### ISSUE TITLE
CSP compatibility

### ISSUE THREAD

**Issue by elrido** [PrivateBin/PrivateBin#10]
@rugk:

It would be nice if I could use [Content Security Policy](http://content-security-policy.com/) with ZeroBin.
It is actually possible, but to use such [a policy](https://scotthelme.co.uk/content-security-policy-an-introduction/) without weak settings (`unsafe-...`) the source code has to meet [some criterias](https://scotthelme.co.uk/content-security-policy-an-introduction/#realworldlimitations):

* no inline JavaScript (also no `OnClick` or similar things)
* no `eval`used in JS
* no inline CSS

So if you have CSP compatibility you of course could also send a strong header via PHP.

A CSP would also mitigate https://github.com/elrido/ZeroBin/issues/8 a bit as the website with such a CSP (which can easily be checked in a browsers console) cannot load arbitrary scripts.

BTW for PHP there is also this framework: https://github.com/paragonie/csp-builder

**Comment by elrido** [comment]
Question: I started looking into CSP and added a header I think proper for our app to [my test site](http://zerobin-test.dssr.ch). Everything works, but I still get an error message in the console of my Firefox:

> Content Security Policy: Die Einstellungen der Seite haben das Laden einer Ressource auf self blockiert ("script-src http://zerobin-test.dssr.ch").

Does anybody have an idea if this is an issue and if yes, how to solve it?

I did set this header:

  Content-Security-Policy: default-src 'none'; connect-src *; script-src 'self'; style-src 'self'; font-src 'self'; img-src 'self';

**Comment by rugk** [comment]
Quite likely it is an add-on. Try restarting Firefox with all add-ons disabled (over the ? menu) and 

BTW you can use https://report-uri.io/ to collect reports.

**Comment by rugk** [comment]
You can set `connect-src *;` to self too BTW. It just restricts AJAX and similar requests, so these requests should only go to the same domain.

**Comment by rugk** [comment]
Also an issue I discovered recently: You have to set `manifest-src 'self';` for Chrome browsers as we [use such a manifest file](https://github.com/PrivateBin/PrivateBin/blob/master/manifest.json).

**Comment by rugk** [comment]
Actually I also tested my installation again and it indeed seems to be working without any "unsafe-eval" and "unsafe-inline" for CSS. Only the [IE 10 fallback](https://github.com/PrivateBin/PrivateBin/blob/9bde729cb590d1c1aa65ada3e2bea8a90ea99fb1/tpl/bootstrap-dark-page.php#L32) might - theoretically - cause problems, but as IE10 does not support CSP anyway, practically it works.

Only the [onclick values](https://github.com/PrivateBin/PrivateBin/search?utf8=%E2%9C%93&q=onclick) in the HTML code cause warnings.

**Comment by elrido** [comment]
The `connect-src *;` is intentional to allow a local PrivateBin install to access remote ones (for #2).

Ok, so we would only need to get rid of the onclick values. Probably need to set the values as data-attributes and parse and set the onclick from the JS-side.

Thanks for the help.

**Comment by rugk** [comment]
> Probably need to set the values as data-attributes and parse and set the onclick from the JS-side.

This would be a good idea.

**Comment by rugk** [comment]
> The connect-src *; is intentional to allow a local PrivateBin install to access remote ones (for #2).

But as #2 was not implemented yet, we can change it to `'self'` for now, right?
And when #2 is finally implemented, we could even serve the `connect-src *;` only when the feature is actually enabled. (This means a reload is needed after activating/disabling this feature, but I think this is okay.)

**Comment by elrido** [comment]
I do not see any risk in keeping it as is.

**Comment by rugk** [comment]
Well I think using self for it may prevent js from sending arbitrary ajax requests to this party sever, so this does make sure your data is not exposed in this way...

**Comment by nitmir** [comment]
The URL shortener option (`urlshortener = "https://…?url="`) is using inline javascript `onclick="window.location.href = 'https://…` and so is not working anymore with the default CSP params.

**Comment by elrido** [comment]
Right... Thanks for reminding me!
