### ISSUE TITLE
PrivateBin Doesn't Work in Chrome on Android

### ISSUE THREAD

**Issue by revnode** [PrivateBin/PrivateBin#100]
## Steps to reproduce

1. Open in Chrome on Android. My version is 52.0.2743.98 on Nexus 5X on Android 7.0

### What happens

1. Hamburger menu doesn't work.
2. Secret isn't shown.
3. Any notifications aren't shown.

### What should happen

1. It should work same as on mobile Firefox. Works on mobile Firefox.

**Comment by rugk** [comment]
Have you tested it on Chrome on Desktop?
Do you get any error message?
What server do you use?

**Comment by revnode** [comment]
> Have you tested it on Chrome on Desktop?

Works perfectly on the desktop version of Chrome.

> Do you get any error message?

None that I can see, but no console on mobile Chrome.

> What server do you use?

I don't think it's the server, everything works as it should on desktop and on mobile Firefox.

**Comment by rugk** [comment]
Okay, so it may be that the JS files are not loaded or broken as 1. and 2. are both done by JS, but as you get no error message Chrome is supposed to execute them correctly.
Maybe there is some SRI verification issue or so, but you do not use Cloudflare or any other CDN, do you?

Just to be sure: Have you tried the "desktop view" of Chrome on mobile? (if there is such a thing)

**Comment by revnode** [comment]
Ok, I fixed this. It was a combination of factors.

I'm not running the server off of HTTPS yet and I had Data Saver on in Android for Chrome. Data Saver pumps all static files through Google when using HTTP and compresses them. This was breaking things.

To resolve, either use HTTPS or turn Data Saver off. Thanks for your help! Closing.

**Comment by rugk** [comment]
Yes, data saver does crappy things there. And using HTTPS is a good idea...
