### ISSUE TITLE
URL Shortner issue "Your paste is https://www.opera.com/"

### ISSUE THREAD

**Issue by BlackWolfWoof** [PrivateBin/PrivateBin#1002]
## Steps to reproduce

1. Install YOURLS & PrivateBin
2. Set both up (YOURLS with default config), PrivateBin with the config from (see at end of post)
3. Create a paste and hit shorten url.

### What happens
It gives me https://www.opera.com/ as url instead of the actual shortened url

### What should happen
Giving me a shortened url

## Additional information

Here a video of this happening
https://user-images.githubusercontent.com/29355595/198081817-16bf930f-e5f6-405d-8f5e-2bc85cd604ed.mp4

## Basic information

**Server address**: https://pastebin.blackwolfwoof.com/

**Server OS:**
Debian GNU/Linux 11 (bullseye) x86_64

**Webserver:**
Apache/2.4.54 (Debian) Server

**Browser:**
Firefox 106.0.1 (64-bit)

**PrivateBin version:**
The currently latest (nightly) from https://hub.docker.com/r/privatebin/nginx-fpm-alpine (should be 1.4.0)

I can reproduce this issue on <https://privatebin.net>: Yes / No
No (since it doesn't use https://url.blackwolfwoof.com/ as url shortner which is YOURLS)

**Config:**
```
; The full URL, with the domain name and directories that point to the PrivateBin files
; This URL is essential to allow Opengraph images to be displayed on social networks
basepath = "https://pastebin.blackwolfwoof.com"
```
...
```
; (optional) URL shortener address to offer after a new paste is created
; it is suggested to only use this with self-hosted shorteners as this will leak
; the pastes encryption key
urlshortener = "$basepath/shortenviayourls?link="
```
...
```
[yourls]
; don't mix this up with "urlshortener" config item:
; - when using a standard configuration, "urlshortener" will point to the YOURLS
;   API, including access credentials, and will be part of the PrivateBin public
;   web page (insecure!)
; - when using the parameters in this section ("signature" and "apiurl"),
;   "urlshortener" will point to a fixed PrivateBin page
;   ("$basepath/shortenviayourls?link=") and that URL will in turn call YOURLS
;   server-side, using the URL from "apiurl" and the "access signature" from the
;   "signature" parameters below.

; (optional) the "signature" (access key) issued by YOURLS for the using account
signature = "[REDACTED]"

; (optional) the URL of the YOURLS API, called to shorten a PrivateBin URL
apiurl = "https://url.blackwolfwoof.com/yourls-api.php?action=shorturl&format=json&url="
```

**Comment by elrido** [comment]
Pretty obviously the documentation needs to be improved. There are several issues:

1. The `urlshortener` needs to be set to "https://pastebin.blackwolfwoof.com/shortenviayourls?link="  - it may be possible to use `${basepath}` according to https://www.php.net/manual/en/function.parse-ini-file.php#example-2257 - let me know if you can find such a variable expansion to work, so I can add that to the doc.
2. The `apiurl` needs to be just the base URL of the api, no GET parameters (instead we [send a POST request and encode these in the body of the message](https://github.com/PrivateBin/PrivateBin/blob/d5104a1d636ee7eaac2a3e0cb481216360afb304/lib/YourlsProxy.php#L62-L79)), i.e. `apiurl = "https://url.blackwolfwoof.com/yourls-api.php"`
3. When I manually try to send a GET request to `https://pastebin.blackwolfwoof.com/shortenviayourls?link=<inserting a pastebin.blackwolfwoof.com paste URL in URLencoded form here> the main view gets executed instead of the new proxy. If you are using php-fpm and for example the opcache PHP module, this may require that you reload that service or even restart it, to enforce it reads in the updated PHP files from disk and executes the new code path.

If anyone has suggestions how that wording in the configuration file could be improved, please share it here, too, so I can get it into a PR by next weekend. Here is an attempt at rephrasing it:

```
; (optional) URL shortener address to offer after a new paste is created
; it is suggested to only use this with self-hosted shorteners as this will leak
; the pastes encryption key
; urlshortener = "https://shortener.example.com/api?link="
[...]
[yourls]
; When using YOURLS as a "urlshortener" config item:
; - When using a standard configuration, "urlshortener" will point to the YOURLS
;   API, with or without credentials, and will be visible on the PrivateBin public
;   web page (insecure!). Only use this if you allow short URL creation without
;   credentials.
; - When using the parameters in this section ("signature" and "apiurl"),
;   "urlshortener" needs to point to the base URL of your PrivateBin instance
;   with "shortenviayourls?link=" appended. For example:
;   urlshortener = "https://privatebin.example.com/shortenviayourls?link="
;   This URL will in turn call YOURLS on the server side, using the URL from
;   "apiurl" and the "access signature" from the "signature" parameters below.

; (optional) the "signature" (access key) issued by YOURLS for the using account
; signature = ""
; (optional) the URL of the YOURLS API, called to shorten a PrivateBin URL
; apiurl = "https://yourls.example.com/yourls-api.php"
```

**Comment by JantsoP** [comment]
Issues began after PR #997

**Comment by BlackWolfWoof** [comment]
@elrido Thanks for your fast reply.
Yea, i noticed the baseurl thing and also thought of maybe using { } which i haven't tried out yet and instead went for what you suggested.

About the apiurl, i also used the base url (without any parameters in the url) which didn't succeed, thats why i switched to the parameters again because i thought i got it wrong after reading the docs. 

> the main view gets executed instead of the new proxy
Yea, i noticed that too. Dunno why tho. Whenever i change the config i hit the container with a restart anyways, so that shouldn't be the problem then. 
![Awooo JGE34hEvCt](https://user-images.githubusercontent.com/29355595/198100257-66a96bae-9678-4450-a918-4af858d758d5.gif)

**Comment by jmozd** [comment]
I can confirm that 
    urlshortener = "${basepath}/shortenviayourls?link="
works in the intended way. Additionally, I can also confirm that apiurls needs to be just the URL, no params.

**Comment by BlackWolfWoof** [comment]
> I can confirm that urlshortener = "${basepath}/..." works in the intended way. Additionally, I can also confirm that apiurls needs to be just the URL, no params.
> 
> EDIT: the urlshortener URL needs to be modified to reflect @elrido 's change regarding MVC routing.

On another note
(ignore the error, focus on the url)
`Content Security Policy: The page’s settings blocked the loading of a resource at https://pastebin.local.blackwolfwoof.comimg/apple-touch-icon.png (“img-src”).`
**comimg** hmm... if we use "${basepath}/" then it will end in example.com//test.php

**Comment by jmozd** [comment]
> **comimg** hmm... if we use "${basepath}/" then it will end in example.com//test.php.
> The wrong formatted url should disapear if i use a / at the end in basepath = https://example.com/

not sure I follow - I have in my config
basepath = "https://example.com"
urlshortener = "${basepath}/yourlsproxy.php.php?link="

and I have no double slashes in the URL inserted into the web page? (It doesn't work, though, as I've yet to get the proper URL to access the shortening MVC functionality, if that's possible at all.)

**Comment by BlackWolfWoof** [comment]
> and I have no double slashes in the URL

Because you used the basepath = https://example.com with no / at the end. 
If you don't add a slash you'll get issues with it doing something like `blackwolfwoof.comimg` instead of `blackwolfwoof.com/img`

**Comment by jmozd** [comment]
> and I have no double slashes in the URL
...and my debugging-fu was failing me. If I properly bypass the browser cache, I do see the 404s. And had I looked more closely, I'd have seen the debug error counters even without reloading...

Sorry for the noise.

**Comment by elrido** [comment]
I'll prepare a branch with the documentation change and the change reg. the slash and we can review and discuss it in the merge request. I had tested this change with a very old instance of YOURLS that was still installed on one of my internal test systems and it had worked end-to-end, but I may have to check it again with a later YOURLS version.

**Comment by niksek11** [comment]
Surprise wolf

**Comment by BlackWolfWoof** [comment]
@elrido got a lil question 😅
I am still unable to get the url shortner working with privatebin.

```
; (optional) the "signature" (access key) issued by YOURLS for the using account
signature = "[REDATCED]"

; (optional) the URL of the YOURLS API, called to shorten a PrivateBin URL
apiurl = "https://url.blackwolfwoof.com/yourls-api.php"
```
Is both set, but whenever I create a paste it does not show me the shorten url button for whatever reason.

Another question about CORS...
I am using nginx proxy manager as reverse proxy. That means adding 
```
location ~ \.php$ {
    add_header Access-Control-Allow-Origin "https://pastebin.blackwolfwoof.com" always;
}
```
to url.blackwolfwoof.com should work right?
This gives me issues on https://url.blackwolfwoof.com/admin/index.php as example then and i can no longer access that site anymore (404).
I added this via the gui
![Awooo BHmPwHgu6r](https://user-images.githubusercontent.com/29355595/200135366-35629571-c142-41d6-a64a-41f9a9389c0f.png)

**Comment by r4sas** [comment]
> Is both set, but whenever I create a paste it does not show me the shorten url button for whatever reason.

PHP logs?

**Comment by BlackWolfWoof** [comment]
> PHP logs?

What are you trying to ask me?

**Comment by elrido** [comment]
> Is both set, but whenever I create a paste it does not show me the shorten url button for whatever reason.

And I assume that the `urlshortener = "${basepath}/yourlsproxy.php.php?link=" is also set, to actually enable the url shortener?

> Another question about CORS... I am using nginx proxy manager as reverse proxy. That means adding

Because you are (trying to) use the YOURLS proxy, there is no CORS in play. The request to the URL shortener will be sent from privatebin server side, not the client. The client will instead fetch the HTML containing the URL from privatebin itself, so there is no cross-origin requests involved, unlike with the "classic" URL shortener mechanism.

**Comment by BlackWolfWoof** [comment]
> And I assume that the `urlshortener = "${basepath}/yourlsproxy.php.php?link="` is also set, to actually enable the url shortener?

`urlshortener = "${basepath}/yourlsproxy.php.php?link="`?
Are you sure you mean php.php?
Wasn't it `"${basepath}/shortenviayourls?link="` before?

I tried both now but without any success.


> Because you are (trying to) use the YOURLS proxy [...]

True that...

**Comment by elrido** [comment]
> Are you sure you mean php.php?
> Wasn't it "${basepath}/shortenviayourls?link=" before?

You are correct. Please check if you get a shortened URL displayed, if you manually call that URL with a link to a paste to your own instance appended. If that works, you have confirmed the setup of the proxy and it should get used, if not, you should find a reason for the error displayed or in the logs.

**Comment by BlackWolfWoof** [comment]
Well this is what happens if i use https://pastebin.blackwolfwoof.com/shortenviayourls.php?link=https://pastebin.blackwolfwoof.com/?28d3e55f91ace4a0#DtoPJs1ayWBawAzmaL9BxtkQM32Jx6SXcBZzurTNWfWH as example
![Awooo Lft2FJENCF](https://user-images.githubusercontent.com/29355595/200137363-217bfd23-9af6-4e2c-a1ac-5f4492f9147b.gif)

```
172.17.0.1 - - [05/Nov/2022:20:22:15 +0100] "GET /shortenviayourls?link=https://pastebin.blackwolfwoof.com/?28d3e55f91ace4a0 HTTP/1.1" 200 5208 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:106.0) Gecko/20100101 Firefox/106.0" "[REDACED]"
```

Am i messing up the format somehow or...

**Comment by BlackWolfWoof** [comment]
Adding to this, i can confirm YOURLS is working. So the issue should not be on the side of YOURLS.
![Awooo yPSg6B9zqn](https://user-images.githubusercontent.com/29355595/200137692-f8b84cec-2ae2-4b07-8328-adab3d94fec2.png)
![Awooo XSCbLv7MSL](https://user-images.githubusercontent.com/29355595/200137699-db169bc8-65e7-427d-bd16-f8495d8ef712.png)

**Comment by elrido** [comment]
So service isn't routing this request to the new endpoint and instead returning the main content? Do you need to restart the service so it reloads the new code path or something?

**Comment by BlackWolfWoof** [comment]
> So service isn't routing this request to the new endpoint and instead returning the main content? Do you need to restart the service so it reloads the new code path or something?

I restart the privatebin container whenever i make a change in the config.

**Comment by elrido** [comment]
I'm sorry, but I'm out of ideas. You will have to debug this on your own setup, stepping through the Controller.php to see where it goes pear shaped. I can confirm that I did test this end to end and it was working - I'm using the docker image locally to validate the code:

```
docker run -d --rm --name pb-janitor -p 127.0.0.1:8080:8080 -u $(id -u) -v /absolute/path/to/your/git/repo:/var/www:rw privatebin/nginx-fpm-alpine
```
This lets you replicate the setup if you place your configuration file into the cfg folder.

**Comment by BlackWolfWoof** [comment]
> I'm sorry, but I'm out of ideas. You will have to debug this on your own setup, stepping through the Controller.php to see where it goes pear shaped. I can confirm that I did test this end to end and it was working - I'm using the docker image locally to validate the code:
> 
> ```
> docker run -d --rm --name pb-janitor -p 127.0.0.1:8080:8080 -u $(id -u) -v /absolute/path/to/your/git/repo:/var/www:rw privatebin/nginx-fpm-alpine
> ```
> 
> This lets you replicate the setup if you place your configuration file into the cfg folder.

Thanks for trying your best to help me. Really appreachiate it 🖤.

**Comment by BlackWolfWoof** [comment]
Welp, nothing has worked for me yet and i am giving up on this note.
**To anyone seeing this in the future, here is how you can replicate this issue with opera.com instead of the shortned url**.
I am using the example config and ONLY changing apiurl, signature, urlshortener and basepath.

If anyone else is having this issue then let me know i guess
[Video of me spinning up the instance](https://blackwolfwoof.com/s/mgfP4XrS8pZypYG) (video link expires in 1 year)


And here is my full config

```
;<?php http_response_code(403); /*
; config file for PrivateBin
;
; An explanation of each setting can be find online at https://github.com/PrivateBin/PrivateBin/wiki/Configuration.

[main]
; (optional) set a project name to be displayed on the website
; name = "PrivateBin"

; The full URL, with the domain name and directories that point to the
; PrivateBin files, including an ending slash (/). This URL is essential to
; allow Opengraph images to be displayed on social networks.
basepath = "https://pastebin1.blackwolfwoof.com/"

; enable or disable the discussion feature, defaults to true
discussion = true

; preselect the discussion feature, defaults to false
opendiscussion = false

; enable or disable the password feature, defaults to true
password = true

; enable or disable the file upload feature, defaults to false
fileupload = false

; preselect the burn-after-reading feature, defaults to false
burnafterreadingselected = false

; which display mode to preselect by default, defaults to "plaintext"
; make sure the value exists in [formatter_options]
defaultformatter = "plaintext"

; (optional) set a syntax highlighting theme, as found in css/prettify/
; syntaxhighlightingtheme = "sons-of-obsidian"

; size limit per paste or comment in bytes, defaults to 10 Mebibytes
sizelimit = 10485760

; template to include, default is "bootstrap" (tpl/bootstrap.php)
template = "bootstrap"

; (optional) info text to display
; use single, instead of double quotes for HTML attributes
;info = "More information on the <a href='https://privatebin.info/'>project page</a>."

; (optional) notice to display
; notice = "Note: This is a test service: Data may be deleted anytime. Kittens will die if you abuse this service."

; by default PrivateBin will guess the visitors language based on the browsers
; settings. Optionally you can enable the language selection menu, which uses
; a session cookie to store the choice until the browser is closed.
languageselection = false

; set the language your installs defaults to, defaults to English
; if this is set and language selection is disabled, this will be the only language
; languagedefault = "en"

; (optional) URL shortener address to offer after a new paste is created.
; It is suggested to only use this with self-hosted shorteners as this will leak
; the pastes encryption key.
urlshortener = "${basepath}shortenviayourls?link="

; (optional) Let users create a QR code for sharing the paste URL with one click.
; It works both when a new paste is created and when you view a paste.
; qrcode = true

; (optional) IP based icons are a weak mechanism to detect if a comment was from
; a different user when the same username was used in a comment. It might get
; used to get the IP of a comment poster if the server salt is leaked and a
; SHA512 HMAC rainbow table is generated for all (relevant) IPs.
; Can be set to one these values:
; "none" / "vizhash" / "identicon" / "jdenticon" (default).
; icon = "none"

; Content Security Policy headers allow a website to restrict what sources are
; allowed to be accessed in its context. You need to change this if you added
; custom scripts from third-party domains to your templates, e.g. tracking
; scripts or run your site behind certain DDoS-protection services.
; Check the documentation at https://content-security-policy.com/
; Notes:
; - If you use a bootstrap theme, you can remove the allow-popups from the
;   sandbox restrictions.
; - By default this disallows to load images from third-party servers, e.g. when
;   they are embedded in pastes. If you wish to allow that, you can adjust the
;   policy here. See https://github.com/PrivateBin/PrivateBin/wiki/FAQ#why-does-not-it-load-embedded-images
;   for details.
; - The 'unsafe-eval' is used in two cases; to check if the browser supports
;   async functions and display an error if not and for Chrome to enable
;   webassembly support (used for zlib compression). You can remove it if Chrome
;   doesn't need to be supported and old browsers don't need to be warned.
; cspheader = "default-src 'none'; base-uri 'self'; form-action 'none'; manifest-src 'self'; connect-src * blob:; script-src 'self' 'unsafe-eval'; style-src 'self'; font-src 'self'; frame-ancestors 'none'; img-src 'self' data: blob:; media-src blob:; object-src blob:; sandbox allow-same-origin allow-scripts allow-forms allow-popups allow-modals allow-downloads"

; stay compatible with PrivateBin Alpha 0.19, less secure
; if enabled will use base64.js version 1.7 instead of 2.1.9 and sha1 instead of
; sha256 in HMAC for the deletion token
; zerobincompatibility = false

; Enable or disable the warning message when the site is served over an insecure
; connection (insecure HTTP instead of HTTPS), defaults to true.
; Secure transport methods like Tor and I2P domains are automatically whitelisted.
; It is **strongly discouraged** to disable this.
; See https://github.com/PrivateBin/PrivateBin/wiki/FAQ#why-does-it-show-me-an-error-about-an-insecure-connection for more information.
; httpwarning = true

; Pick compression algorithm or disable it. Only applies to pastes/comments
; created after changing the setting.
; Can be set to one these values: "none" / "zlib" (default).
; compression = "zlib"

[expire]
; expire value that is selected per default
; make sure the value exists in [expire_options]
default = "1week"

[expire_options]
; Set each one of these to the number of seconds in the expiration period,
; or 0 if it should never expire
5min = 300
10min = 600
1hour = 3600
1day = 86400
1week = 604800
; Well this is not *exactly* one month, it's 30 days:
1month = 2592000
1year = 31536000
never = 0

[formatter_options]
; Set available formatters, their order and their labels
plaintext = "Plain Text"
syntaxhighlighting = "Source Code"
markdown = "Markdown"

[traffic]
; time limit between calls from the same IP address in seconds
; Set this to 0 to disable rate limiting.
limit = 10

; (optional) Set IPs addresses (v4 or v6) or subnets (CIDR) which are exempted
; from the rate-limit. Invalid IPs will be ignored. If multiple values are to
; be exempted, the list needs to be comma separated. Leave unset to disable
; exemptions.
; exempted = "1.2.3.4,10.10.10/24"

; (optional) If you want only some source IP addresses (v4 or v6) or subnets
; (CIDR) to be allowed to create pastes, set these here. Invalid IPs will be
; ignored. If multiple values are to be exempted, the list needs to be comma
; separated. Leave unset to allow anyone to create pastes.
; creators = "1.2.3.4,10.10.10/24"

; (optional) if your website runs behind a reverse proxy or load balancer,
; set the HTTP header containing the visitors IP address, i.e. X_FORWARDED_FOR
; header = "X_FORWARDED_FOR"

[purge]
; minimum time limit between two purgings of expired pastes, it is only
; triggered when pastes are created
; Set this to 0 to run a purge every time a paste is created.
limit = 300

; maximum amount of expired pastes to delete in one purge
; Set this to 0 to disable purging. Set it higher, if you are running a large
; site
batchsize = 10

[model]
; name of data model class to load and directory for storage
; the default model "Filesystem" stores everything in the filesystem
class = Filesystem
[model_options]
dir = PATH "data"

;[model]
; example of a Google Cloud Storage configuration
;class = GoogleCloudStorage
;[model_options]
;bucket = "my-private-bin"
;prefix = "pastes"
;uniformacl = false

;[model]
; example of DB configuration for MySQL
;class = Database
;[model_options]
;dsn = "mysql:host=localhost;dbname=privatebin;charset=UTF8"
;tbl = "privatebin_"    ; table prefix
;usr = "privatebin"
;pwd = "Z3r0P4ss"
;opt[12] = true   ; PDO::ATTR_PERSISTENT

;[model]
; example of DB configuration for SQLite
;class = Database
;[model_options]
;dsn = "sqlite:" PATH "data/db.sq3"
;usr = null
;pwd = null
;opt[12] = true ; PDO::ATTR_PERSISTENT

;[model]
; example of DB configuration for PostgreSQL
;class = Database
;[model_options]
;dsn = "pgsql:host=localhost;dbname=privatebin"
;tbl = "privatebin_"     ; table prefix
;usr = "privatebin"
;pwd = "Z3r0P4ss"
;opt[12] = true    ; PDO::ATTR_PERSISTENT

;[model]
; example of S3 configuration for Rados gateway / CEPH
;class = S3Storage
;[model_options]
;region = ""
;version = "2006-03-01"
;endpoint = "https://s3.my-ceph.invalid"
;use_path_style_endpoint = true
;bucket = "my-bucket"
;accesskey = "my-rados-user"
;secretkey = "my-rados-pass"

;[model]
; example of S3 configuration for AWS
;class = S3Storage
;[model_options]
;region = "eu-central-1"
;version = "latest"
;bucket = "my-bucket"
;accesskey = "access key id"
;secretkey = "secret access key"

[yourls]
; When using YOURLS as a "urlshortener" config item:
; - By default, "urlshortener" will point to the YOURLS API URL, with or without
;   credentials, and will be visible in public on the PrivateBin web page.
;   Only use this if you allow short URL creation without credentials.
; - Alternatively, using the parameters in this section ("signature" and
;   "apiurl"), "urlshortener" needs to point to the base URL of your PrivateBin
;   instance with "shortenviayourls?link=" appended. For example:
;   urlshortener = "${basepath}shortenviayourls?link="
;   This URL will in turn call YOURLS on the server side, using the URL from
;   "apiurl" and the "access signature" from the "signature" parameters below.

; (optional) the "signature" (access key) issued by YOURLS for the using account
signature = "[REDACTED]"
; (optional) the URL of the YOURLS API, called to shorten a PrivateBin URL
apiurl = "https://url.blackwolfwoof.com/yourls-api.php"
```

**Comment by elrido** [comment]
Uhm, sorry, but the video actually seems to show that it is working? When you hit the shorten button, isn't the displayed URL getting shortened? Is this maybe more a UX issue?

**Comment by BlackWolfWoof** [comment]
> Edit: disregard - when zooming in the replacement URL is opera.com - really no clue where that would be coming from. Maybe cached in the browser somehow? Did you try on a different device, user session or different browser?

Yes, no luck there too.
The only thing where the opera link can come from is from the "use a supported browser" popup that privatebin has... 
But what is that doing in the url shortner field? No clue...

**Comment by Showfom** [comment]
Same issue here, I give up and wait for fix :D

**Comment by VijendraMalhotra** [comment]
I just upgraded to 1.5.1  and i can't get the /sortenviayourls" method to work.
my configuration is something like this
basepath = "https://bin.malhotra.me/paste/"
urlshortener = "${basepath}shortenviayourls?link="

[yourls]
 signature = "blahblahblah "
; (optional) the URL of the YOURLS API, called to shorten a PrivateBin URL
 apiurl = "https://vru.me/yourls-api.php"

however each time i click the shorten URL button i get an 404 error saying that shortenviayours is not present

**Comment by asherber** [comment]
I'm seeing the same thing as @VijendraMalhotra with 1.7.1. My conf is set up essentially the same, and I get a 404 when I click the Shorten URL button. I'm running Apache on Ubuntu.

Is there maybe an `.htaccess` redirect needed here? Otherwise I'm not sure how `${basepath}shortenviayourls` will make it into the pipeline at `${basepath}index.php` -- I think the request is actually looking for a `/shortenviayourls` resource that doesn't exist.

**Comment by elrido** [comment]
> Is there maybe an `.htaccess` redirect needed here? Otherwise I'm not sure how `${basepath}shortenviayourls` will make it into the pipeline at `${basepath}index.php` -- I think the request is actually looking for a `/shortenviayourls` resource that doesn't exist.

Not a redirect, but a rewrite - All requests that don't resolve to a static file should get handled by index.php. I'd expect a config similar to this snippet:

```
RewriteEngine on
RewriteCond %{REQUEST_FILENAME} !-f
RewriteRule . index.php [L]
```

**Comment by asherber** [comment]
1. After some testing, I think the rule should be `RewriteRule (.*) index.php/$1 [L]`, but I haven't actually done this on my server.
2. It's simpler just to set `urlshortener` directly to `${basepath}index.php/shortenviayourls?link=`, rather than mucking around with mod_rewrite. Should this be updated in the docs? I can't speak for other web servers, but the current suggestion of `${basepath}shortenviayourls?link=` does not work on Apache.
3. What do you think about adding code to `Request.php` that would allow something like `${basepath}?shortenviayourls=` or `${basepath}?shortenviayourls=true&link=`? The solution in # 2 would continue to work, so as not to break anything. If this is something you're interested in, I'm happy to work on a PR.

**Comment by elrido** [comment]
As we do currently support the `${basepath}shortenviayourls?link=` variant, we would need to keep that support for backwards compatibility, but I see the benefit for allowing an additional variant of the URL that is simpler to setup on some servers or doesn't require configuration changes. I would recommend documenting # 2 and/or the following one: `?shortenviayourls&link=`. Yes, not a proper get parameter, but it will show up as a key with empty string in the $_GET array.

Codewise, I don't think a large change would be necessary to allow for this. It should be this area:
https://github.com/PrivateBin/PrivateBin/blob/e1e0e8399c5ed94cc8ac7f8da1d732a7346b8c17/lib/Request.php#L145-L149
Reducing the `strpos` search pattern to just `'shortenviayourls'` should probably do the trick.

**Comment by rzippert** [comment]
Can't say if this solves the issue for everyone, but here is how I fixed this behavior on my setup. I did not have my instance public on the internet, and ended up taking a few years to update it. I have updated from probably 1.2.3 to the latest version in a single pass. This issue did not happen with the ancient version.

Here are my (working) relevant cfg parameters:

```
[main]
basepath = "https://bin.hidden.site/"
urlshortener = "${basepath}shortenviayourls?link="

[yourls]
signature = "46597fabdf0"
apiurl = "https://yourls.hidden.site/yourls-api.php"
```

I use apache and have a rewrite rule for the shortenviayourls route:
```
	<Directory /var/www/privatebin>
		Options -MultiViews -Indexes
		<IfModule mod_rewrite.c>
			# Redirect /shortenviayourls to /index.php with query string parameters
			RewriteEngine On
			RewriteRule ^shortenviayourls$ /index.php [L,QSA]

			# Serve other requests with try_files directive
			RewriteCond %{REQUEST_FILENAME} !-f
			RewriteCond %{REQUEST_FILENAME} !-d
			RewriteRule ^(.*)$ /index.php/$1 [L]
		</IfModule>
	</Directory>
```


In case you're wondering where did opera.com com from, it is from the bootstrap files from privatebin itself (tpl folder). If you have something wrong with your rewrite, the main privatebin html may get loaded instead of making the API call, and that URL ends up getting parsed and returned as if it was from yourls (at least that's my best guess).

I must also add that I have cloudflare in front of this service (and always had). For some reason the new version started getting blocked by it (detected as a bot maybe?). After managing to allow privatebin to actually get to my yourls instance, it started working again. If you're not sure if that's your case, check your webserver logs and locate the requests from privatebin. If there are no logs, it means that the block is happening before it reaches your server (likely, in your waf/cdn). Your waf/cdn may also provide logs to you, but not always.

My PHP errors were like this:
```
[Sun Sep 29 22:46:45.641272 2024] [proxy_fcgi:error] [pid 996632] [client xxx.xxx.xxx.xxx:0] AH01071: Got error 'PHP message: PHP Warning:  file_get_contents(https://yourls.hidden.site/yourls-api.php): Failed to open stream: HTTP request failed! HTTP/1.1 403 Forbidden\r\n in /var/www/privatebin/lib/YourlsProxy.php on line 72PHP message: PHP Fatal error:  Uncaught TypeError: json_decode(): Argument #1 ($json) must be of type string, bool given in /var/www/privatebin/lib/Json.php:50\nStack trace:\n#0 /var/www/privatebin/lib/Json.php(50): json_decode()\n#1 /var/www/privatebin/lib/YourlsProxy.php(80): PrivateBin\\Json::decode()\n#2 /var/www/privatebin/lib/Controller.php(490): PrivateBin\\YourlsProxy->__construct()\n#3 /var/www/privatebin/lib/Controller.php(141): PrivateBin\\Controller->_yourlsproxy()\n#4 /var/www/privatebin/index.php(17): PrivateBin\\Controller->__construct()\n#5 {main}\n  thrown in /var/www/privatebin/lib/Json.php on line 50'
```

I hope this helps someone. While I love privatebin, even working as a sysadmin for a few years I must say that this configuration was still not straightforward the first, or this time. May I suggest leaving a complete example (with fake URLs), like mine, in the wiki for reference? The webserver configuration should be included as not many people can make these by themselves. The yourls section in the configuration docs could link to the wiki page.

I can try making a PR if that's desirable.

**Comment by rugk** [comment]
The wiki is not PR-able, but the doc can certainly be improved, sure. The configurations part of the wiki probably or the FAQ(?).
