### ISSUE TITLE
PrivateBin Installed but unusable

### ISSUE THREAD

**Issue by FuckingToasters** [PrivateBin/PrivateBin#1023]
## Steps to reproduce
1. I've downloaded the sourcecode.zip from the releases
2. I've added all files in a subfolder called "paste"
3. I then visited the pastebin on https://my.domain/paste
4. I see following site: (Screenshot in Additional Info Section below)

### What happens
It don't show the normal paste site correctly so i can't view pastes, make new ones etc.

### What should happen
It should show the main paste with a create paste button etc. like all other sites do (pastebin, ghostbin etc.)

## Additional information
![grafik](https://user-images.githubusercontent.com/94435104/205517421-3b15ecc0-2374-48bb-9c19-834e19352e3d.png)
Note that i'm using a modern browser (firefox)

### If you use a public server enter the address of it here.
**Server address**: http://infinimonster.bplaced.net/paste/

### The Operation System of your server
Linux

### The webserver running on your server, preferrably including the version
Not sure, i don't think https://bplaced.net provide that Info

### The version of your browser (when it is a client-side issue)
Firefox 107.0 64 bit

### The version of PrivateBin, if you use an unstable version paste the commit hash or the GitHub link to the commit here (you can get it by running `git rev-parse HEAD`)
I don't have terminal access on my hosting provider

I can reproduce this issue on <http://infinimonster.bplaced.net/paste/>: Yes

**Comment by r4sas** [comment]
To run PrivateBin you must use HTTPS connection to your site.

**Comment by FuckingToasters** [comment]
solved after adding letsencrypt, thx for your reply i thought https were optional.

**Comment by rugk** [comment]
It's not optional, see https://github.com/PrivateBin/PrivateBin/wiki/FAQ#why-does-it-show-me-an-error-about-an-insecure-connection for more information.

**Comment by imTHAI** [comment]
Sorry but I have the same problem. I understand about the secure connection but what about the "modern browser" error ?
I tried with Safari 17.5 and Edge 127.0.2651.86

**Comment by rugk** [comment]
An insecure connection will usually automatically also cause a "modern browser" error in the sense that the required Web Crypto API cannot be accessed over insecure HTTP connections in most browsers.

Again, here the relevant FAQ quote:
> However, even in these cases, you may have technical difficulties and PrivateBin may not work as expected, because some browsers limit [some features](https://developer.mozilla.org/docs/Web/Security/Secure_Contexts/features_restricted_to_secure_contexts) such as the Web Crypto API (which PrivateBin makes use of) to a [secure context](https://developer.mozilla.org/docs/Web/Security/Secure_Contexts). A browser known to do this [is Chrome/all Chromium-based browsers](https://github.com/PrivateBin/PrivateBin/issues/441) (since v60). This is a deliberate decision of the browser makers (for their reasoning, also see the previous links) and the inclusion of the WebCrypto API is based on [this decision by the W3C](https://github.com/w3c/webcrypto/issues/28). There is nothing PrivateBin can do about this. Either your browser trusts that is a secure connection and PrivateBin can use the features it needs, or it cannot.

https://github.com/PrivateBin/PrivateBin/wiki/FAQ#why-does-it-show-me-an-error-about-an-insecure-connection

**Comment by rugk** [comment]
And here is the FAQ that is also actually linked directly in the error message: https://github.com/PrivateBin/PrivateBin/wiki/FAQ#why-does-it-show-me-the-error-privatebin-requires-a-modern-browser-to-work

**Comment by imTHAI** [comment]
@rugk Thank you. Indeed, both errors disappeared after I've setup a cert for https.
