### ISSUE TITLE
Custom Theme

### ISSUE THREAD

**Issue by FuckingToasters** [PrivateBin/PrivateBin#1024]
I'd like to edit the css so it looks like this paste site: https://paste.fo with custom advertisement banners too.
I never really worked as webdev so i don't know how html, css, js and php works.
I basically like to copy paste the Theme from https://paste.fo and making some major changes afterwards so it's not copied 1:1

**Comment by IIPoliII** [comment]
I don't think they are using privatebin.

**Comment by elrido** [comment]
You won't need PHP skills, and JS ones only if your theme makes use of that, but HTML and CSS know how will likely be required.

See the [wiki page on creating templates](https://github.com/PrivateBin/PrivateBin/wiki/Templates#creating-templates) for a starting point. It's probably easiest to start with a copy of an existing template and and tweak the colors, etc. to approximate what you want to go for.

**Comment by FuckingToasters** [comment]
> I don't think they are using privatebin.

yes that's correct but there need to be a way to format privatebin to match the theme and button, navbar layout as the site i mentioned.

**Comment by elrido** [comment]
> [...] there need to be a way to format privatebin to match the theme and button, navbar layout as the site i mentioned.

There is and you can find the link to get you started above. Note that while you can change the looks and navbar layout, most of the elements in it do need to remain present for privatebin to function. They need to keep the same id's, though you may be able to use CSS to hide some of them permanently.

Simple changes (background color, font type, size and color) won't require much indepth know how. Pixel-perfect look-alike will, tough. :-) In any case, it should be a good learning experience - modding website templates is how I got my start in web development, 20-something years ago. You can do it!

**Comment by FuckingToasters** [comment]
> > [...] there need to be a way to format privatebin to match the theme and button, navbar layout as the site i mentioned.
> 
> There is and you can find the link to get you started above. Note that while you can change the looks and navbar layout, most of the elements in it do need to remain present for privatebin to function. They need to keep the same id's, though you may be able to use CSS to hide some of them permanently.
> 
> Simple changes (background color, font type, size and color) won't require much indepth know how. Pixel-perfect look-alike will, tough. :-) In any case, it should be a good learning experience - modding website templates is how I got my start in web development, 20-something years ago. You can do it!

I don't really understand the css, i opend it in notepad++ but i'm Overwhelmed with it....
I took a look at the page src from https://paste.fo and it seem to be totally different.

**Comment by FuckingToasters** [comment]
Hey, i now opend css/privatebin.css and on line 29 i edited the font:
```css
body {
	font-family: Source Code Pro, monospace;
	font-size: 0.9em;
	margin-bottom: 15px;
	padding-left: 60px;
	padding-right: 60px;
}
```
However, the new font and every nwe change somehow don't become applied to it and it keep the default theme.

**Comment by elrido** [comment]
> Hey, i now opend css/privatebin.css and on line 29 i edited the font:

Which template are you editing? css/privatebin.css is used in the "classic" page template:

https://github.com/PrivateBin/PrivateBin/blob/910675c74b3a4c63eb0dc963a714d4041cf0eb66/tpl/page.php#L11

And the different bootstrap templates use css/_bootstrap_/privatebin.css:
https://github.com/PrivateBin/PrivateBin/blob/910675c74b3a4c63eb0dc963a714d4041cf0eb66/tpl/bootstrap.php#L31

**Comment by FuckingToasters** [comment]
> > Hey, i now opend css/privatebin.css and on line 29 i edited the font:
> 
> Which template are you editing? css/privatebin.css is used in the "classic" page template:
> 
> https://github.com/PrivateBin/PrivateBin/blob/910675c74b3a4c63eb0dc963a714d4041cf0eb66/tpl/page.php#L11
> 
> And the different bootstrap templates use css/_bootstrap_/privatebin.css:
> https://github.com/PrivateBin/PrivateBin/blob/910675c74b3a4c63eb0dc963a714d4041cf0eb66/tpl/bootstrap.php#L31

I've copied darkstrep, saved under a different name and in config set the template to new name and then i noticed that everything was dark except the navbse and when i tried to change stuff no change occurred.
