### ISSUE TITLE
Issues with I18n.php (not able to work)

### ISSUE THREAD

**Issue by IIPoliII** [PrivateBin/PrivateBin#1025]
## Steps to reproduce

1. Create an privatebin instance and move all the files except the index.php file outside of this directory.
2. Grant all access to  the folder described in the path
3. Try to go on the page
4. Check error logs

### What happens

Whenever I try to visit the website I get a blank page and the following error in my error.log file. 
`[Mon Dec 05 20:02:08.819616 2022] [php7:error] [pid 3020569] [client 162.158.86.161:21018] PHP Fatal error:  Uncaught Error: Call to a member function read() on bool in /var/www/privatebin-data/lib/I18n.php:197\nStack trace:\n#0 /var/www/privatebin-data/lib/I18n.php(284): PrivateBin\\I18n::getAvailableLanguages()\n#1 /var/www/privatebin-data/lib/Controller.php(168): PrivateBin\\I18n::setLanguageFallback()\n#2 /var/www/privatebin-data/lib/Controller.php(121): PrivateBin\\Controller->_init()\n#3 /var/www/privatebin/index.php(18): PrivateBin\\Controller->__construct()\n#4 {main}\n  thrown in /var/www/privatebin-data/lib/I18n.php on line 197
`

### What should happen

It should correctly, and automatically find the path in the l18n.php lib file. Like that the instance would surely work.

## Additional information

The instance is fresh and just installed. So there is nothing custom **yet**.

## Basic information

**Server OS:** Ubuntu Server 20.04.5 LTS

**Webserver:** Apache 2.4

**Browser:** Firefox 107

**PrivateBin version:** Latest

I can reproduce this issue on <https://privatebin.net>: No

**Comment by elrido** [comment]
Have you updated the `PATH` or the `PUBLIC_PATH` in your index.php to fit your environment?
https://github.com/PrivateBin/PrivateBin/blob/910675c74b3a4c63eb0dc963a714d4041cf0eb66/index.php#L13-L16

See also the [INSTALL.md section on changing the PATH](https://github.com/PrivateBin/PrivateBin/blob/master/INSTALL.md#changing-the-path).

**Comment by IIPoliII** [comment]
> Have you updated the `PATH` or the `PUBLIC_PATH` in your index.php to fit your environment?
> 
> https://github.com/PrivateBin/PrivateBin/blob/910675c74b3a4c63eb0dc963a714d4041cf0eb66/index.php#L13-L16
> 
> See also the [INSTALL.md section on changing the PATH](https://github.com/PrivateBin/PrivateBin/blob/master/INSTALL.md#changing-the-path).

I only changed the path the public path is the same. 
I don't see anything in the doc about it, should I set it in another way?

**Comment by elrido** [comment]
The doc states that:

> You can move [...] (directories bin, cfg, doc, data, lib, tpl, tst and vendor) outside of your document root. [...] (see also [open_basedir setting](https://secure.php.net/manual/en/ini.core.php#ini.open-basedir)).

So the i18n directory that fails to open, as per your error, needs to stay in the public folder (as it gets shared with the client as well) and you may have to check the open_basedir setting to ensure your php process is allowed to access it.

For further evidence/reference that such a setup is possible and currrently supported, see also the [setup done in our docker image](https://github.com/PrivateBin/docker-nginx-fpm-alpine/blob/master/Dockerfile#L68).
