### ISSUE TITLE
Add "JS not working" error message

### ISSUE THREAD

**Issue by rugk** [PrivateBin/PrivateBin#103]
After https://github.com/PrivateBin/PrivateBin/issues/100 I think it is a good idea to add an error message:
- which is _not_ shown when no JS is supported (so it must be hidden)
- which is shown when JS could not load correctly (is not executed (so there might just be a JS line hiding this error message directly after loading/DOM creation)

Or we could adjust the usual "No JS" error message to cover these aspects...

**Comment by elrido** [comment]
To do this (so that it works under any circumstances) you would need inline JS in the HTML. Which would break our CSP protection.

IMHO this is an extreme corner case: JS works, but the files are not loaded due to something (proxy) messing with the files.

**Comment by rugk** [comment]
Okay, just wanting to say it is possible: With CSP v2 we could use inline-JS and use nounces or hashes to add an exception for them.

**Comment by rugk** [comment]
Actually the case here is bigger than we thought, because when the SRI is wrong (maybe because the admin modified it or so), then the second case in some way applies (JS is activated/loaded, but could not get executed). (I know the initial case is described differently.) That's why we should probably [show an error in this case](https://github.com/PrivateBin/PrivateBin/issues/118#issuecomment-256115602).
 
And I've got an idea, just let me tinkle around a bit.
