### ISSUE TITLE
phpdoc errors / missing documentation

### ISSUE THREAD

**Issue by elrido** [PrivateBin/PrivateBin#1036]
We've been getting a bit sloppy 😳 and not all of the phpdoc blocks in our code are still up to date, as evidenced by the increase in errors in the report at https://privatebin.info/codedoc/reports/errors.html

Apart from the obvious missing summaries or incorrect arguments:
- for I18n.php, the issues is that we accept a dynamic number of arguments - maybe recent phpdoc has a solution how to document this without causing an error?
- add the new bin folder to the included folders, so the new scripts also get picked up

**Comment by rugk** [comment]
> for I18n.php, the issues is that we accept a dynamic number of arguments - maybe recent phpdoc has a solution how to document this without causing an error?

Similar to JSDoc and others, `...` should be the solution possible here too, see:
https://stackoverflow.com/questions/14513356/phpdoc-documenting-a-function-with-a-variable-number-of-arguments#38275992
