### ISSUE TITLE
German message overlapping

### ISSUE THREAD

**Issue by un99known99** [PrivateBin/PrivateBin#1039]
please see attached the formatting for "The recipient could get to know your timezone, would you like to convert the time to UTC?

![grafik](https://user-images.githubusercontent.com/1615207/209980140-6721bc02-8db0-48c0-b0c5-ec9bf30f35b7.png)

**Comment by rugk** [comment]
Thanks for the report, however please mind to fill out the issue template you choose, when you open an issue the next time. This makes it easier to troubleshoot issues or understand feature requests etc.

What system were you using, especially the browser? And could you please tell us your screen resolution you had when you took the screenshot?

**Comment by elrido** [comment]
For what is worth, I can reproduce this on our demo instance, where we do have the language drop-down enabled, using Firefox 108.0.1 (64-Bit) without zoom on full HD, but also on any other browser or screen size:

![screenshot 2022-12-31 13-44-16](https://user-images.githubusercontent.com/1017622/210137235-a2d0718f-20ba-41f0-b226-5dbae4ed81ac.png) - AFAIK we are not using anything special here, so this seems to be the default settings of buttons in bootstrap CSS 3.4?

**Comment by un99known99** [comment]
sry, will keep that in mind.
Error occurs while using option "Send by email", W10 lastest patch level, Browser is FF, latest 108.0.1, screen resolution is 

![grafik](https://user-images.githubusercontent.com/1615207/210153785-70ead41f-de13-405c-9785-bcd29bcb080d.png)
