### ISSUE TITLE
Delete Button "burn after reading"

### ISSUE THREAD

**Issue by Zitronella** [PrivateBin/PrivateBin#104]
Hi, thanks for the fork PrivateBin. Can you tell me a possibility to delete Button "Burn after reading"? I use tpl/page.html

**Comment by rugk** [comment]
You have to edit [this part](https://github.com/PrivateBin/PrivateBin/blob/master/tpl/page.php#L117-L124).

**Comment by Zitronella** [comment]
Thank you very much.
