### ISSUE TITLE
types.jsonld: actually return it and update the servers configured expiration dates in it

### ISSUE THREAD

**Issue by elrido** [PrivateBin/PrivateBin#1045]
## Steps to reproduce
1. request the JSON-LD for the supported types of an instance, i.e. https://privatebin.net/?jsonld=types

### What happens
a blank JSON document is returned.

### What should happen
something like https://raw.githubusercontent.com/PrivateBin/PrivateBin/master/js/types.jsonld should get returned, but ideally the "Expiration" enum options should be based on the actual configured values and not static.

## Additional information
Need to add "types" to the allowed list in:
https://github.com/PrivateBin/PrivateBin/blob/e84a8694e4f4ca6ff7dd745aa985e27388d3dad0/lib/Controller.php#L428-L431

## Basic information

**Server address**: https://privatebin.net/

**Server OS:** Alpine Linux 3.17

**Webserver:** [nginx 1.22.1](https://pkgs.alpinelinux.org/package/v3.17/main/x86_64/nginx) / [php-fpm 8.1.14](https://pkgs.alpinelinux.org/package/v3.17/community/x86_64/php81-fpm)

**Browser:** Firefox 108.0.2

**PrivateBin version:** 1.5.1

I can reproduce this issue on <https://privatebin.net>: Yes, see https://privatebin.net/?jsonld=types

**Comment by r4sas** [comment]
btw, what about including supported compression, paste types too?

**Comment by elrido** [comment]
The compression and paste types don't matter to the API - or rather: even if compression is disabled, formats limited or file upload disabled, the API would still accept compressed pastes with a disabled format and an attached file sent by a third party client.

These settings only affect the creation of new pastes within the web interface. Existing pastes created before the setting got restricted, or new pastes created by other means, can still be displayed.
