### ISSUE TITLE
Is it possible that basePath is used in the Paste link?

### ISSUE THREAD

**Issue by dwydler** [PrivateBin/PrivateBin#1051]
## Steps to reproduce

1. Setuped multiple instances of PrivateBin in our LAN. 
2. All instances are reachable via one FQDN (DNS round robin).
3. The users distributed to the instances randomly.

### What happens
First of all my dns scheme for the instances:
```
FQDN for DNS round robin: pb.cl1033.web.domain.com
FQDN for the docker host 1:  pb.h1.cl1033.web.domain.com
FQDN for the docker host 2:  pb.h2.cl1033.web.domain.com
FQDN for the docker host 3:  pb.h3.cl1033.web.domain.com
```

The FQDN of each docker host was configured in his conf.php.

If a user/guest try to open an existing PrivateBin Link, it can be failed. Depending on which instance the user lands on. Due to DNS round robin this cannot be controlled.

### What should happen
The URL of the variable basePath of conf.php should be used to generate the paste link.

## Additional information

Is there an option to use the basepath for the paste link?

## Basic information

**Server address**: LAN Instances

**Server OS:** Ubuntu Server 22.04 LTS

**Webserver:** Docker

**Browser:** Microsoft Edge

**PrivateBin version:** 1.5.1

I can reproduce this issue on <https://privatebin.net>: No

**Comment by elrido** [comment]
In a setup like this, you would need to configure the public FQDN address as the basePath, not the internal, per-instance ones. Your reverse proxi(es) or per-instance webservers would all respond to that single public FQDN and forward the requests to the nginx server in the containers with that same URL. Since privatebin doesn't use sessions it would not matter if several requests of the same user go to different instances in the background, though with DNS-round-robin, the clients will usually just pick one IP and cache that response.

**Comment by dwydler** [comment]
Hi @elrido,

> In a setup like this, you would need to configure the public FQDN address as the basePath, not the internal, per-instance ones.
I did/try that already (e.g. pb.h1.cl1033.web.domain.com). But PrivateBin still not use the configured FQDN for the paste url, it use the FQDN of the DNS round robin address (e.g. pb.cl1033.web.domain.com). This one i used in the browser.

**Comment by elrido** [comment]
So I looked it up and the URL displayed in the web interface is not generated on the server side and based on that configuration, but instead is derived from the actual URL used to access the web client via JS:

https://github.com/PrivateBin/PrivateBin/blob/e84a8694e4f4ca6ff7dd745aa985e27388d3dad0/js/privatebin.js#L515

So if you access the instance via the shared domain, it would pick up that one and not the one configured. So if you access the instance via pb.cl1033.web.domain.com than that is what should get used - which I understand is what you want to achieve, right?

**Comment by dwydler** [comment]
> So if you access the instance via the shared domain, it would pick up that one and not the one configured. So if you access the instance via pb.cl1033.web.domain.com than that is what should get used - which I understand is what you want to achieve, right?

Not quite... I'll try to explain it differently. The user only knows the FQDN pb.cl1033.web.domain.com. In this way, failures and maintenance work should be invisible to our end users.

In order for the recipient of an Paste, the link should not contain the FQDN pb.cl1033.web.domain.com instead the FQDN of the conneted host (e.g. pb.h1.cl1033.web.domain.com). Otherwise the recipient will almost receive the message that the paste does not exist. Which depending on which host the browser will be directed.

**Comment by r4sas** [comment]
Really strange idea to use 4 not identical, and without single storage, service accessible via one domain.

In that case you can help only sending somehow to your backend (PHP) domain from your webserver (nginx, apache2, etc.) via fastcgi options as example.

**Comment by elrido** [comment]
Ok, that is not how it is designed to work. You need to set up some shared data storage between all of the instances, i.e. an NFS share, OCFS2, GlusterFS, iSCSI, Fiberchannel volume or similar when using the Filesystem backend or a shared database, S3 or GCS storage. Then it doesn't matter which instance the visitor hits, they will always get the paste displayed. And then you can simply publish the one public domain on all instances.

**Comment by dwydler** [comment]
Ok, Thanks.
