### ISSUE TITLE
add comment - not working

### ISSUE THREAD

**Issue by un99known99** [PrivateBin/PrivateBin#1052]
Hi,

I am using 1.5.1 and was trying to use the “_add comment_” functionality.
Unfortunately, it is giving me the following error:

“Could not send comment: GD does not appear to be available in your PHP installation. Please try another generator”
⇒ I would think that all dependencies should have been initially installed?

Also, this is a mixed error message EN/DE which should be translated to DE as well I guess?

Any help welcome – thanks.

![grafik](https://user-images.githubusercontent.com/1615207/215476055-db8b8edc-a966-4168-9659-a62cb873f102.png)

**Comment by elrido** [comment]
If you use the default configuration of ["identicon" style icons](https://github.com/PrivateBin/PrivateBin/wiki/Configuration#icon) for the comments, you will need to have the GD PHP module installed. You can:
- install the GD PHP module
- or change the configuration to use "jdenticon" or "none", both of which do not require the GD PHP module - "jdenticon" is a pure PHP implementation and therefore slower than the others. With "none" it will skip generating these icons entirely, which does save some space as well. Practically speaking neither the size nor speed should matter much to pick one over the other.

**Comment by un99known99** [comment]
@elrido thx for your answer, setting to jedenticon fixed it, comment from my side, seems this an "undocumented feature" as in the php.config only thoses are "available":

; Can be set to one these values: "none" / "vizhash" / "identicon" (default).

"jedenticon" is not described there as a valid option

**Comment by elrido** [comment]
At least as of 1.5.0, the new option should be mentioned in the conf.sample.php:
https://github.com/PrivateBin/PrivateBin/blob/b5602dd1ae0df9d84409bb5c604d9bdb50de72ac/cfg/conf.sample.php#L73

**Comment by un99known99** [comment]
Ah, okie, haven't seen it there – many thanks for pointing towards it
