### ISSUE TITLE
burn after read should not burn if no password was entered

### ISSUE THREAD

**Issue by wzrdtales** [PrivateBin/PrivateBin#1055]
when a paste is password protected, it shouldn't get deleted without actually having entered the password.

This is especially relevant if you want to really make use of them in the age of every stupid service scanning URLs send, which could be at least made more secure by adding a password which will then delete it immediately and still make sure that an actual access only deleted it.

**Comment by wzrdtales** [comment]
a stateless implementation could look like the following:

a URL gets generated that contains an encrypted payload which contains the real paste URL instead. when the user enters the password the real URL gets decrypted in the users browser and they get redirected to the actual paste URL which then uses the default action.

**Comment by elrido** [comment]
This topic is tracked in #245 and we had attempted to develop a solution, but abandoned it as introducing too great a risk to the pastes security. The approach described here seems much simpler - would require a slight protocol / paste format change, but not as complex as the one of the prior approach. Would you want to collaborate on this in a branch?

I'll close this issue as a duplicate, but please do continue the conversation over in #245.
