### ISSUE TITLE
[Q] How to use privatebin.js generate the form data "adata"

### ISSUE THREAD

**Issue by finalcreator** [PrivateBin/PrivateBin#1057]
### What happens
I just want to use privatebin.js to generate the "adata" , which generate the form data and send to backend.

### What should happen

I just want to integrate this logic in my application without access the privatebin instance directly.

**Comment by elrido** [comment]
If your application isn't written in JavaScript, may I recommend looking at the encryption logic of a [third party client](https://github.com/PrivateBin/PrivateBin/wiki/Third-party-clients) written in your preferred language?

In the document on the [encyption format](https://github.com/PrivateBin/PrivateBin/wiki/Encryption-format), the contents of the authenticated data (adata) are described in the `paste_meta_json` structure. In the JSON-LD schema, the `AuthenticatedData` is documented in [pastemeta.jsonld](https://raw.githubusercontent.com/PrivateBin/PrivateBin/master/js/pastemeta.jsonld) and the inner `CipherParameters` in [types.jsonld](https://raw.githubusercontent.com/PrivateBin/PrivateBin/master/js/types.jsonld). The format depends if you are creating a paste or a comment. Comments use the `CipherParameters` as their adata, while paste use the nested `AuthenticatedData` type that also contains other paste meta data.

You can see this in the privatebin.js in the section here below:
https://github.com/PrivateBin/PrivateBin/blob/fa8cc59ec03f7c26b4cd9f27b902f2e279507048/js/privatebin.js#L1202-L1221

**Comment by finalcreator** [comment]
Actually the privatebin.js is not straightforward to me , but the thrid party https://github.com/pixelfactoryio/privatebin-cli is very useful, and I can use it right out of the box.
I thought at first, it would have a public endpoint for requests without care about encryption as we already use https。

Thanks a lot.
