### ISSUE TITLE
API usage not clear

### ISSUE THREAD

**Issue by Nhoya** [PrivateBin/PrivateBin#106]
https://github.com/PrivateBin/PrivateBin/wiki/API 

`cipherdata` is defined as `cipherdata: JSON string containing format and base64 encoded data, output of the encryption function` actually not clear at all..

can i have an example please?

**Comment by rugk** [comment]
Unless I am mistaken you can find this on your server in the `data` dir. (or when using MySQL in the database)

You have to do the encryption by yourself of course, but the JS for doing so is in this repo. :smiley:

**Comment by elrido** [comment]
You can find samples in the [unit tests](https://github.com/PrivateBin/PrivateBin/blob/master/tst/Bootstrap.php#L33-L47).

The JSON in question is simply the object that the SJCL library outputs. The easiest way of replicating its output is to use the library in a CLI JS environment like Rhino. @ziirish had done that in his [ZeroCli client](https://github.com/ziirish/zerocli).

If you want to replicate valid JSONs without using SJCL, you can found out valid ranges and values by looking at how that JSON is [validated](https://github.com/PrivateBin/PrivateBin/blob/master/lib/Sjcl.php#L32).

The contents of all these fields should be relatively clear to anybody that has worked with a low level cryptographic function. There are values for the initialisation vector (iv), the version number of the SJCL data fomat (v), the number of iterations (iter), the key size in bits (ks), the authentication strength in bits (ts), the encryption mode (mode), optional clear text authentication data (adata), the cipher algorithm (cipher), the salt (salt) and the cipher test of course (ct).

Note that you actually need to encrypt the cipher text and can't simply store any kind of base64 encoded data as the server checks if it is compressible. Well encrypted data is indistinguishable from random noise, hence it should not compress well.

**Comment by Nhoya** [comment]
Problem solved, thank for the reply :+1:
