### ISSUE TITLE
There is child porn being hosted on your platform. 

### ISSUE THREAD

**Issue by Anon12345awsefrt** [PrivateBin/PrivateBin#1064]
There is child porn being hosted on your platform. Please remove it and ban the user:

https://support-tools.com/?`redacted`

**Comment by Lewis8379** [comment]
It looks like that's a site that is simply powered by this script, but isn't affiliated or controlled by the PrivateBin project at all, so there's nothing they can do. The best you could do is try to find who hosts them through WHOIS data and contact their hosting company.

**Comment by r4sas** [comment]
Link removed, answer given.
