### ISSUE TITLE
Needs documentation on the new "administration" features

### ISSUE THREAD

**Issue by Lewis8379** [PrivateBin/PrivateBin#1065]
As of 1.5.1, there's a new "administration" feature, which is quoted as: "PrivateBin now adds another script to help perform administrative tasks. The new script, called administration, helps with deleting pastes, removing empty directories, when using the filesystem backend, purging all expired pastes at once and gathering statistics on an instance."

However, despite checking the FAQ and Wiki, I cannot find any documentation on how to actually use these features. I do not do programming but I was expecting a GUI of some kind, like changing the page to .php and being able to visit it, like a tiny Wordpress dashboard, but instead I'm scratching my head on how to make use of the administration features.

Some documentation on this would be appreciated :)

**Comment by elrido** [comment]
I know, not where you looked for it, but the script does come with a `--help` / `-h` option. We did add it's output to the [container images' read-me document](https://github.com/PrivateBin/docker-nginx-fpm-alpine#running-administrative-scripts) as well. In short, it is this:

```
administration --help
Usage:
  administration [--delete <paste id> | --empty-dirs | --help | --purge | --statistics]

Options:
  -d, --delete      deletes the requested paste ID
  -e, --empty-dirs  removes empty directories (only if Filesystem storage is
                    configured)
  -h, --help        displays this help message
  -p, --purge       purge all expired pastes
  -s, --statistics  reads all stored pastes and comments and reports statistics
```

**Comment by Lewis8379** [comment]
Couldn't it be made a file that has to be renamed with a .php extension which then shows the options or something? It wouldn't have to be locked behind anything other than maybe an admin password in the config file

I use cPanel/WHM on my server and only touch the command line for cPanel/server tasks like whmlogin or reboot. As a noob who put the files in the public directory, I don't understand how to actually make use of these admin functions. In the case of cPanel would it be the CLI for the server, i.e. when I connect to the server using "root" in Mobaxterm?

**Comment by elrido** [comment]
You should run the script as the same user that your PHP process runs as (it will work when running as root, but one should avoid using root when possible). In most share-host scenarios, including cPanel, the user you used to upload files to the server via sftp normally is the same one that your PHP process runs as and that you, hopefully, are allowed to login as, via ssh, too. You could then change into the directory you have privatebin installed into (to the directory above the `data` one, to be precise) and then can run the script like so:

```
./bin/administration --help
# or
./bin/administration --statistics
# or
./bin/administration --delete <some paste ID here>
# or
./bin/administration --purge
# or
./bin/administration --empty-dirs
```

Similarly, you can set up a cron job in your cPanel to run an automatic purge every so-and-so hours. Or you could create a cron job that pipes the output of the statistics into the `sendmail` command (with appropriate recipient and parameters as required by your mail server) to create an email report once per day or week. A command line tool is more flexible and robust for these scenarios, compared to a dynamic website that you'd have to call via curl or wget to be triggered in a cron job.
