### ISSUE TITLE
Feature: Allow AWS SDK to use default credential provider chain for S3Storage

### ISSUE THREAD

**Issue by fenak** [PrivateBin/PrivateBin#1069]
The `S3Storage` constructor currently expects the AWS access keys to be passed via config file.

There are some security downsides with this being the only approach:
1. We have to use IAM user long-living keys to use S3
2. The credentials need to be recorded in plaintext in the config file

It would be good if we could alternatively leverage AWS SDK default credential provider chain instead of passing keys via config file. This way, the access keys could be passed via environment variables, which solves the second issue, or if PrivateBin is also being deployed in AWS, it could also leverage IAM roles instead of user keys, solving points 1 and 2.

PR: #1070 

_edit: PR reference updated_

## References
- https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/guide_credentials.html#default-credential-chain

**Comment by elrido** [comment]
FYI: Raised https://github.com/PrivateBin/docker-nginx-fpm-alpine/pull/142 to expose these in the container image as well.

**Comment by rugk** [comment]
BTW next time @fenak, you can (automatically) [let issues close](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue) when a PR is merged by adding some "magic" text to your PR _body_. 

Closing this here as completed.

**Comment by fenak** [comment]
Thanks for the tip @rugk will keep in mind 🙌
