### ISSUE TITLE
The source code formatting is awful on dark theme.

### ISSUE THREAD

**Issue by nolsen42** [PrivateBin/PrivateBin#107]
I noticed on the dark bootstrap theme, using the source code format, you can't really see the formatting, it is blended in a bit into the theme.

**Comment by elrido** [comment]
Make sure to use the `sons-of-obsidian` [syntax highlighting theme](https://github.com/PrivateBin/PrivateBin/wiki/Configuration#syntaxhighlightingtheme) when using the `bootstrap-dark` template.

**Comment by nolsen42** [comment]
@elrido Much better now, thanks.
