### ISSUE TITLE
Migration fails with "Source and destination storage configurations are identical"

### ISSUE THREAD

**Issue by AllieQpzm** [PrivateBin/PrivateBin#1074]
## Steps to reproduce

1. Run the new migration tool, specifying both a src and dest config file
2. Fails with the above error

### What happens
I run the migration tool with `./migrate /srv/cfg/conf.php /srv/new/conf.php` and when I do I receive the error "Source and destination storage configurations are identical". Having added some debug output to the migration file, I can see that it's picked up the model that's in the cfg folder for both the source and the destination. The configuration files are different - the one in the cfg has a FileSystem model, and the one in the new folder has a Database model. It's like the destination argument is completely ignored.

### What should happen

The source and destination arguments should result in different configurations loaded.

## Basic information

**Server address**: N/A

**Server OS:** Ubuntu Server 20.04 lts

**Webserver:** Nginx

**Browser:** N/A

**PrivateBin version:** 1.5.1

I can reproduce this issue on <https://privatebin.net>:  No

**Comment by elrido** [comment]
The two arguments are the configuration _directories_, not the files themselves. From the tools usage information (`--help`):

>       <srcconfdir>     use storage backend configration from conf.php found in
>                        this directory as source
>       <dstconfdir>     optionally, use storage backend configration from conf.php
>                        found in this directory as destination; 

When parsing these parameters, the tool will set these as the CONFIG_PATH environment variable before instantiating `Configuration` to parse the file found in there:
https://github.com/PrivateBin/PrivateBin/blob/b23e781b5b5501335d97527c5f7dc50a59cf1601/bin/migrate#L156-L158

If there is no file found (by appending `conf.php` to the path given), `Configuration` will fall back to the default configuration.

For future reference, we did add a unit test that migrates from files into a (SQLite) database and back again:
https://github.com/PrivateBin/PrivateBin/blob/b23e781b5b5501335d97527c5f7dc50a59cf1601/tst/MigrateTest.php#L68-L83

**Comment by elrido** [comment]
I believe this question has been answered and we can therefore close the issue.
