### ISSUE TITLE
modify paste url

### ISSUE THREAD

**Issue by pppaapp** [PrivateBin/PrivateBin#1078]
## Steps to reproduce

1. Installed with docker
2. I set the basepath value to "https://privatebin.example.com/paste/" in the conf.php file. But nothing changed.

### What happens

hello

I create a paste url from `https://privatebin.example.com/`.

The output is `Your paste is https://privatebin.example.com/?5ad7fdfc02a06280#Ce9jzHrPGDrQVqM7cVV4hdqZddA8LNet21eeHnnGLBf5 (Hit [Ctrl]+[c] to copy)`.

Is it possible to change this to output `Your paste is https://privatebin.example.com/paste?5ad7fdfc02a06280#Ce9jzHrPGDrQVqM7cVV4hdqZddA8LNet21eeHnnGLBf5 (Hit [Ctrl]+[c] to copy)`?

I don't want to create a paste url from `https://privatebin.example.com/paste`.

I want to create it from `https://privatebin.example.com/`.

## Basic information

**Server address**:

**Server OS:**

**Webserver:**

**Browser:**

**PrivateBin version:**

I can reproduce this issue on <https://privatebin.net>: Yes / No

**Comment by elrido** [comment]
You would have to do two things:
1. When a visitor arrives at https://privatebin.example.com/ have your webserver redirect them (permanently -> http status 301) to https://privatebin.example.com/paste (or https://privatebin.example.com/paste/ - which ever you prefer).
2. Set up your webserver to have requests to https://privatebin.example.com/paste (or https://privatebin.example.com/paste/ ) get proxied to your privatebin container

The output of privatebin will pick up the URL it currently runs under. With the above setup you can hand out the shorter URL and visitors will automatically land on the one that ends up getting used for the paste creation.

The basepath setting is used for generating the twitter and social media image URLs in the HTML header and for a check when the yourls integration is used - it isn't used for the generated URL (the setting is for the server side code, but the URL gets generated by the end user in the browser).

**Comment by pppaapp** [comment]
Thank you for your response

I created two privatebin containers

The first container has the url `privatebin.example.com` and is for writing posts
And I set up login authentication

The second container has the url `privatebin.example.com/paste` and is used for sharing url

Two containers use the same volume

So a url created in `privatebin.example.com` can also be used in `privatebin.example.com/paste`


![CleanShot 2023-03-11 at 20 30 25](https://user-images.githubusercontent.com/31263588/224481822-57ec66db-6d17-416c-b626-914644d4135f.png)

This screen shows `https://privatebin.example.com/?014c1cb9f81715b5#6enQZCG4CGg7BzhiNjWtFYFfBfhBhzfQoZ2v14k5QgXT`

I want to see `https://privatebin.example.com/paste/?014c1cb9f81715b5#6enQZCG4CGg7BzhiNjWtFYFfBfhBhzfQoZ2v14k5QgXT` on the screen instead of that url

The first method is not possible because it's not what I intended

I don't know how to do the second method

My English is very bad and I am worried that you will not be able to understand my writing.....

**Comment by ruderl** [comment]
I have encountered a related use case which I think exposes a limitation not covered by the current `basepath` behaviour.

I run PrivateBin in a split-access configuration:

* paste creation is restricted using `[traffic] creators`
* the client IP is taken from `X_FORWARDED_FOR`
* only my private Tailscale devices are allowed to create pastes
* recipients access shared pastes through a separate public reverse-proxy hostname

For example:

* authoring URL: `https://privatebin.internal.example`
* public recipient URL: `https://privatebin.example.com`

This works well from an access-control perspective, but when I create a paste through the private hostname, PrivateBin generates a link such as:

`https://privatebin.internal.example/?<paste-id>#<key>`

What I would like it to generate instead is:

`https://privatebin.example.com/?<paste-id>#<key>`

while still allowing creation to take place through the private hostname.

I tried using `basepath`, but this does not appear to control the hostname used for newly generated paste links.

This is particularly useful in combination with the existing `creators` IP/CIDR restriction. It allows a deployment model where:

* private/VPN/Tailscale endpoint → create pastes and upload files
* public reverse-proxy endpoint → recipients retrieve pastes and files

A configuration option such as:

`publicurl = "https://privatebin.example.com/"`

or

`shareurl = "https://privatebin.example.com/"`

would solve this cleanly.

The important distinction is that this would not change where PrivateBin itself is accessed for authoring. It would only define the canonical hostname used when generating share links.

At present the workaround is to manually replace the hostname in every generated URL, which is easy to get wrong and rather cumbersome in normal use.

I think this would complement the existing creator restriction nicely and make split private-authoring/public-sharing deployments much easier to operate.
