### ISSUE TITLE
fix StyleCI formatting recommendations

### ISSUE THREAD

**Issue by elrido** [PrivateBin/PrivateBin#1084]
In the latest two pull requests, StyleCI complained about code that hasn't been changed. It recommends to remove brackets around ternary expressions. IMHO this would make those pieces less readable.

Arguably, we could store the result of the expression in another variable and use it in those function calls, making brackets unnecessary.

Example report: https://github.styleci.io/analyses/7WQjlb

**Comment by rugk** [comment]
Yeah, sounds good, this suggestion is rather odd- especially when other stuff is around there.
