### ISSUE TITLE
URL shorting API key gets exposed

### ISSUE THREAD

**Issue by XNonymous-N2** [PrivateBin/PrivateBin#1087]
## Steps to reproduce

1. Enable url shorting in configuration
2. Create a paste
3.  Click on Short link

### What happens
The API key gets exposed because the user itself requests a shorten link and not the server

### What should happen
A shorted link should be generated without exposing the API key itself

## Additional information

Example configuration for shlink:
urlshortener = "https://domain.de/rest/v1/short-urls/shorten?apiKey=key&format=txt&longUrl="

Shlink: https://shlink.io/

## Basic information

**Server address**: private server

**Server OS:** debian 10

**Webserver:** nginx

**Browser:** Brave v1.50.121 (But it is not a client-side issue)

**PrivateBin version:**
privatebin/fs:latest image on docker

I can reproduce this issue on <https://privatebin.net>: Yes / No
No

**Comment by elrido** [comment]
That is correct and depends on the used configuration. As the [wiki on that option](https://github.com/PrivateBin/PrivateBin/wiki/Configuration#urlshortener) explains:

> It is strongly suggested to only ever use this with self-hosted shortener services as this will leak the pastes encryption key to the service entered here.

If you use YOURLS as the shortener service, we do now offer a [server side API creation](https://github.com/PrivateBin/PrivateBin/wiki/Configuration#yourls) to allow using a key without leaking it. If using another shortener service, you would have to use it without key (i.e. allow only users with referer set to your PrivateBin URL to create the short URLs).

Please note that we do not recommend using a shortener, as it undermines your users privacy, storing their keys on another service when used.

Out of curiosity, what is your use case and motivation to use PrivateBin with a URL shortener? Given that it is a popular feature, I'd like to understand why it is (still) used. Maybe we can address that need in some safer way?

**Comment by XNonymous-N2** [comment]
The main reason to use a shortener is because the generated links of PrivateBin are very long, when I want to share pastes with friends without sending them the pastes directly, I have to dictate them the whole link which is very long.

My shortener is self-hosted but as I said afaik the user still has to have access on the shortener because, the user makes the request.

I also tried to use YOURLS but firstly the installation didn't work as expected and secondly PrivateBin gave me everytime the notification that, either the signature is invalid or the provided host.

**Comment by XNonymous-N2** [comment]
Is it now planned to solve this problem? There should never be the possibility of exposing the API key

**Comment by elrido** [comment]
Yes, you can totally solve this problem, by changing your setup. Let me re-iterate your options to address this:
1. using your existing URL-shortener software:
   1. disable the API key requirement, allowing your users to create short-links without a key
   2. optionally, if you don't want the shortener to be used for anything but your own privatebin instance, set up a rule in your webserver to restrict access to the shortener to referers from privatebin
2. alternatively, switch to the yourls shortener, which can be used with the server side proxy feature

The thing is that there do not seem generic solutions to this as different shorteners have their own APIs, and we would likely have to develop special proxies for every shortener software - if anyone is willing to contribute to such code and it suffices our quality requirements I wont stand in the way of merging it. But that is all for a feature that undermines the core tenet of privatebin, that the server should have zero knowledge of the key (that long pseudorandom string at the end of the URL, which you wish to shorten). By using a shortener, your server now collects these keys and privatebin is not much different than any server-side pastebin service.

**Comment by XNonymous-N2** [comment]
👍
