### ISSUE TITLE
DNS DoS

### ISSUE THREAD

**Issue by cryptolok** [PrivateBin/PrivateBin#109]
Greetings,
I saw that PrivateBin has a BIND DNS server, which is OK.
However, your current version is vulnerable to DoS attack that could crash the server, just by sending a specially crafted packet. For obvious reason, I didn't test it.
As mitigation, you should update to newer BIND version.
Great project by the way.

**Comment by elrido** [comment]
Thanks for the hint. Did update both systems.

For anybody wondering how to check this (where the FQDN after the @ is the DNS server in question):

    dig @ns.example.com version.bind txt chaos
