### ISSUE TITLE
Issues With /var/www/zerobin/cfg

### ISSUE THREAD

**Issue by gawlinski-com** [PrivateBin/PrivateBin#1094]
Hello,

First of all, thank you for all the devs and contributors who made this tool.  Appreciate everyone's time and labor.  I tried installing this on my instance, and am running into issues updating my config theme and settings.

Installed PrivateBin on a new yunohost setup.  Working okay, but when I edit the config figure, seems as if changes don't take affect.

My ultimate goal is to change the theme and remove the "forever" option for expiration.

**Server address**:  paste.gawlinski.com

**PrivateBin version:**
1.3.5

Here is a link to my config file:
https://paste.debian.net/1281599/

I tried to restart my server, but the settings don't seem to apply.

And here is my neofetch/setup:
https://paste.gawlinski.com/?80d4d44ab1cde1bd#6XiJtc7pcE33n7NPTdMuDeZnht6xZWMdRv1L4687zBkQ

I tried restarting my server to see if that would restart the process, but seems as if no changes take place.  Any help would be appreciated.

**Comment by elrido** [comment]
PrivateBin looks for the configuration file in the directory defined in the environment variable `CONFIG_PATH` (if set) as well as under `PATH . 'cfg'` and the file has to be named `conf.php` and must be readable to the PHP process and user:
https://github.com/PrivateBin/PrivateBin/blob/5b458a17c2470a44ec241fc1791e28d1e2a81dc6/lib/Configuration.php#L111-L115

The PATH is defined in your `index.php`, so if you have changed that to have the data outside of the web root, you need to have the cfg directory live next to it:
https://github.com/PrivateBin/PrivateBin/blob/5b458a17c2470a44ec241fc1791e28d1e2a81dc6/index.php#L13-L14

Assuming all of these points can be ruled out, I'd bet on PHP not being able to read the file, skipping it and going to default settings.

**Comment by elrido** [comment]
With the shell's ls command or filebrowser of your choice, simply compare the ownership and group of the conf.php file as well as the mode bits with the other php files. Your PHP process can read the other scripts, so those must have the right permission. If you suspect the PATH to have been set (which you can lookup in the index.php file), simply look for the data directory - the cfg folder needs to be next to (on the same level as) the data directory.

**Comment by gawlinski-com** [comment]
Thank you for the help and feedback.  I ran a couple commands to check permissions.  on the config file (cfg.php), and a test file zerobin/index.php

This is what came up:

https://paste.gawlinski.com/?f2c6a85cf66258b0#FQX6nPBMYVbawF9tu4PQBdcD4ARaFUjc1fPjNqT4aVzf

Should I change permissions so it can read my configuration?  Or let me know if I should try anything else.

Thank you!!

**Comment by elrido** [comment]
If I read your stat output right, the conf.php is owned by root, group root and has rw-,r--,--- mode bits set, while the php script is owned by zerobin, group www-data and mode bits rw-,rw-,---. If we can assume that your php process runs as either user zerobin or is in the group www-data, it won't be able to read the root owned conf.php. I would therefore try and change the group ownership of conf.php to www-data (keep it read-only for the group) using chgrp and if that is not sufficient also change the owner to zerobin using chown.

To remove the guesswork, you would need to look up as what user the php processes run as (php-fpm, apache mod_php, etc.), either by looking at the configuration files or using ps or top to spot the running processes.

**Comment by gawlinski-com** [comment]
Okay.  So thank you for all your support.

Is there a way to restart the privatebin serivce without having to restart my entire server?

I am tinkering around with my permissions, and tried to search for the privbin service - but nothing is coming up.  Feel bad asking because I know your time is important.  But can't seem to find a way to restart this specific app.

**Comment by ppfeufer** [comment]
> Is there a way to restart the privatebin serivce without having to restart my entire server?

Restart the webserver.

**Comment by gawlinski-com** [comment]
Great news - I ran chgrp & chown and looks like all the settings were applied!

Thank you for all the help, I really appreciate it
🍻
