### ISSUE TITLE
UX: Discussion/One time buttons

### ISSUE THREAD

**Issue by elrido** [PrivateBin/PrivateBin#11]
@rugk:

Although I have set `discussion = true` the discussion button in the UI is always disabled.

Even if I set `opendiscussion = true` it stays the same.

Version: latest from git

---

@rugk:

Ah I found it out: (Obviously) when I select "one time text" it cannot have a discussion.
So as you just found out the current behaviour is bad UX.

It has two problems:

1. I only see that the button is disabled when clicking on it *or* when hovering over the check box (the text is still displayed with a linked button in my case, Firefox here)
2. You might even just leave this button enabled every time and let a user click on it. When they click on it you can automatically deselected the other button. 
This is the way it is currently already done when I have discussion selected and click the other button. However it is not done the other way around.

**Comment by rugk** [comment]
Actually the buttons still behave differently:
![buttons](https://cloud.githubusercontent.com/assets/11966684/17565652/95b5e310-5f38-11e6-88b2-7de894199980.gif)

**Comment by elrido** [comment]
I don't think that is such a good idea. A user might not notice that ticking another option disables a previously set one. By locking the other option it is explicit.

Actually, thinking about it, as the two options are mutually exclusive, radiobuttons would be the better choice then checkboxes. That would also make it visually clear how they are dependent and no JS is required to do the switching.

What do you think?

**Comment by rugk** [comment]
Mhh, radio buttons might be a way to go, but I think it is a bit strange to have a list of (only) two radio buttons in a vertical list. Also the "options" you choose are really something completely different and don't belong to the same "group" of settings (which is implied by radio buttons).

In this case I think locking the other option (but for *both* buttons) might be a better decision. You might then use JS to attach a click event to the disabled button, which toggles the state of both buttons (meaning the current one gets activated and enabled and the other one gets disabled.)

**Comment by elrido** [comment]
Ok, then lets just treat them the same.

**Comment by rugk** [comment]
Yeah this souls be done in and case. The way how they should be threaded is another question.
