### ISSUE TITLE
PrivateBin instance for personal use, with public read access?

### ISSUE THREAD

**Issue by ivanskodje** [PrivateBin/PrivateBin#1105]
Hello,

I am looking into running a PrivateBin instance for **personal use** only for myself and family, and was wondering if there is a way to restrict note creation, but to allow anyone to read the notes (unless it is password protected, of course). 

Do PrivateBin currently support this, or something like this to achieve what I want? :smiley_cat: 

Thank you for your time.

**Comment by r4sas** [comment]
https://github.com/PrivateBin/PrivateBin/wiki/Restrict-upload-using-NGINX
