### ISSUE TITLE
License changes: Add © for @ElRido

### ISSUE THREAD

**Issue by rugk** [PrivateBin/PrivateBin#112]
I think given your substantial work, @elrido, you should add yourself to the license. At least for an MIT license [you can easily do this](https://opensource.stackexchange.com/questions/2391/how-should-i-assert-copyright-when-im-forking-an-mit-project?rq=1). It should be similar with the zlib license. :smiley:

**Comment by elrido** [comment]
[IANAL](https://en.wikipedia.org/wiki/IANAL) so I would avoid to touch that license file with even a 10 foot pole. :open_mouth: My name doesn't need to be all over the place, you know. :wink:
