### ISSUE TITLE
Can I get the url that could show simple words page?

### ISSUE THREAD

**Issue by lategege** [PrivateBin/PrivateBin#1124]
I want to get the url like github's  or  pasteBin's  https://xxxxx/raw/xxxxxx , so i can see the pasted content directly by request the url, and i will use it in my linux shell if the content is cmd or others.

**Comment by r4sas** [comment]
Directly - no. Such functional means that server must know what stored on paste. This is out of project scope.
You can use [third party clinets](https://github.com/PrivateBin/PrivateBin/wiki/Third-party-clients) for receiving paste contents and use it later.

**Comment by rugk** [comment]
Please see the following FAQ questions:
* https://github.com/PrivateBin/PrivateBin/wiki/FAQ#can-i-uploaddownload-the-pastes-with-curlwget
* https://github.com/PrivateBin/PrivateBin/wiki/FAQ#how-can-i-link-to-raw-pastes-instead-of-taking-users-to-a-web-page

So as it seems this question has been answered and I thus close this issue. If anyone has further questions on that topic, feel free to comment here, again.
