### ISSUE TITLE
Feature: Edit previous pastes 

### ISSUE THREAD

**Issue by ajvsol** [PrivateBin/PrivateBin#114]
It would be nice to have the ability to edit previous pastes using a separate admin password.

**Comment by KaKi87** [comment]
Hello,
Any news on this ?
Thanks !

**Comment by rugk** [comment]
Hmm, do you think this is useful @elrido?

IMHO, we should stay true to being a simple past service – like pastebin. There you also cannot edit the paste.

This is really complex to implement with the encryption and then users cannot be sure they have the same content behind an URL.

Also, who should have the permission to update the paste? Only the paste author can be identified. (I doubt _everyone_ who has the paste link should be able to edit it.)

Thus, I'm inclined to decline this feature.

**Comment by r4sas** [comment]
I'm against such functionality, because that is pasting service, not a "memory" or notepad-like service.

**Comment by KaKi87** [comment]
Some proprietary paste services allows the author to edit his pastes using a cookie/localStorage token or using a password he'd set at creation.
I'm okay with both but this is absolutely necessary to me.
Thanks

**Comment by KaKi87** [comment]
@r4sas Notepad-like services are either offline or authenticated.
Paste services are neither.

**Comment by rugk** [comment]
Hmm, not really. The most similar service that requires no login (authentication) and is e2e-encrypted (and FLOSS) like PrivateBin is probably https://cryptpad.fr/. Maybe you should try this, if that solves your use case.
It's like Etherpad though, i.e. anyone can edit it.

Of course, you need authentication if you want only some users to edit it or so. (okay possibly cryptopad can do it with links too, dunno)

**Comment by KaKi87** [comment]
- [textup.fr](https://textup.fr/) allows edit by password
- [justpaste.it](https://justpaste.it/) allows edit by secret URL
- [justpaste.me](https://justpaste.me/) allows edit by cookie
- [nopaste.me](https://nopaste.me/) allows edit by localStorage

Etc...

**Comment by rugk** [comment]
…and I guess nobodey of these e2e-encrypts the data…

**Comment by KaKi87** [comment]
That's why I'm requesting PrivateBin to support one of these editing techniques. Thanks

**Comment by elrido** [comment]
My opinion: As long as it does not involve the introduction of a user authentication system, I would not be against such a merge request.

The challenge: Currently the API and data storage is very heavily designed around the assumption that pastes (and comments) are immutable. Implementing such a feature would therefore require a very deep redesign of both file and databased storage, the API and the client code. Doing this in a way that won't break backwards client compatibility could be pretty challenging, bordering on a rewrite of the solution.

@KaKi87 if you intend to develop such a feature, I am happy to help you with code reviews, support you writing the unit tests to prove backwards compatibility, etc. But to me this is pretty much out of scope for this project and I will focus my time on other features as I don't regard this to be an must have feature.

Workaround, within the current scope of the project: You can simply clone the paste, change what you need, save it again. In the original paste you can attach a link to the new paste in the discussion section of the paste. That in mind, I would be more in favour of the "versioned pastes" #255 feature, then allow editing a paste.

**Comment by KaKi87** [comment]
> My opinion: As long as it does not involve the introduction of a user authentication system, I would not be against such a merge request.

Agreed.

> @KaKi87 if you intend to develop such a feature, I am happy to help you with code reviews, support you writing the unit tests to prove backwards compatibility, etc. But to me this is pretty much out of scope for this project and I will focus my time on other features as I don't regard this to be an must have feature.

Would it involve PHP or JS ?
I'm more into JS.

> Workaround, within the current scope of the project: You can simply clone the paste, change what you need, save it again. In the original paste you can attach a link to the new paste in the discussion section of the paste. That in mind, I would be more in favour of the "versioned pastes" #255 feature, then allow editing a paste.

Cloning poses two problems for me :
1. **Data duplication.** I know it's just text after all, but I wouldn't be very proud to participate in exponentially increasing the size of the database you're hosting for free for everyone.
2. **Discussion.** I'd prefer to be the only one to be able to post content.

Thanks

**Comment by rugk** [comment]
> Would it involve PHP or JS ?

Both, heavily.

> Data duplication. I know it's just text after all, but I wouldn't be very proud to participate in exponentially increasing the size of the database you're hosting for free for everyone.

All pastes have an expiration date, so that will work without problems.

> Discussion. I'd prefer to be the only one to be able to post content.

Hmm, yet again this _would_ require authentication, at least via a link.

**Comment by rugk** [comment]
So, if there would be a proper PR, maybe. But it would be a lot of work…
Though I also like the "create-only" feature of PrivateBin, it assures you the same content can be found via a link. For additions, comments can be used. So IMHO it should at least be stated in the UI that it has been edited/is editable, and you should have to tick that (just like another option) when creating a paste.

So for now, let's say I'd close this as wontfix, because it's clearly against the concept of PrivateBin so far and not intended to be implemented anytime soon.

**Comment by KaKi87** [comment]
> Hmm, yet again this would require authentication, at least via a link.
Why is a link, a password, a cookie/localStorage a problem ?

**Comment by Fhiss** [comment]
Sometimes it takes a joint editing with other people. Secret URL [justpaste.it](https://justpaste.it/) lets do it.

**Comment by rugk** [comment]
This won't be (end-to-end)encrypted then. Personally I'd suggest you using a service from cryptpad.fr then if you have this use case, multiple users can edit it and it's e2e encrypted.
