### ISSUE TITLE
Feature request: Allow disable encryption

### ISSUE THREAD

**Issue by cuixiping** [PrivateBin/PrivateBin#1146]
## The problem

I want to use `PrivateBin` in internal network and small team. I do not need encryption. The advantage without encryption is that the link url is much shorter and no urlshortener is needed.

## The solution
Allow disable encryption

**Comment by elrido** [comment]
Given that the unique selling point of PrivateBin over other pastebin clones is the encryption, this is way out of scope for this project. Just ask yourself, when you remove the encryption, how is this project any different from any of the other self-hosted pastebin clones? Sorry, I'll close this ticket, for said reasons.
