### ISSUE TITLE
jQuery outdated?

### ISSUE THREAD

**Issue by nolsen42** [PrivateBin/PrivateBin#115]
The version jQuery uses on PrivateBin is 1.11.3, But the latest jQuery version is 3.1.1, should PrivateBin update to the latest?

**Comment by rugk** [comment]
Well... many online services use a jQuery version, which they are known to work with. Why should we update jQuery to a newer version?

**Comment by nolsen42** [comment]
@rugk I have no idea how jQuery works, but could it have new improvements and optimizations?

**Comment by rugk** [comment]
You can create a PR for that. I'll think at least it won't have any disadvantages, so if everything works I think we would merge that PR.

**Comment by nolsen42** [comment]
#117

**Comment by nolsen42** [comment]
I will, later on today.
