### ISSUE TITLE
After deleting a paste redirect to the home page aka "basepath" URL

### ISSUE THREAD

**Issue by TehPeGaSuS** [PrivateBin/PrivateBin#1156]
## The problem

Currently when we delete a paste we need to click in the Pastebin icon to be able to paste again.

## The solution

When deleting a paste we could be redirected to the `basepath` URL. This would improve user experience and spare us of an additional click.

## Alternatives

N/A

## Additional context

N/A

**Comment by PeGaSuS-Coder** [comment]
Having that banner for a bit and then redirecting to the homepage would be sensible as well.

That way we'd have the confirmation that the paste was actually deleted before being redirected. 5s between the deletion confirmation and the redirect would probably cover everyone.

Unfortunately I can't code, so I can't be of much help when comes to provide a patch. 😅
