### ISSUE TITLE
Add Ansible Role Installation Method - Rootless Podman

### ISSUE THREAD

**Issue by voidquark** [PrivateBin/PrivateBin#1159]
**Suggestion:** Add Ansible Role Installation Method - Rootless Podman

**Description:**
I would like to suggest the addition of an Ansible role as an installation method for PrivateBin in the documentation. I have developed an Ansible role that simplifies the deployment process of PrivateBin within a rootless container using Podman. 

**Role Details:**
- Role Name: PrivateBin - Ansible Role
- Role GitHub Repository: https://github.com/voidquark/privatebin
- Ansible Galaxy: https://galaxy.ansible.com/voidquark/privatebin

**Benefits:**
- The role ensures a secure and efficient deployment by running PrivateBin within the user namespace.
- It utilizes systemd to manage the container, promoting reliability.
- The role is designed to be user-friendly and can accommodate both beginners and advanced users.

**Proposal:**
I propose adding a section in [installation.md](https://github.com/PrivateBin/PrivateBin/blob/master/doc/Installation.md)  documentation that highlights the use of this Ansible role for installation. This would provide users with an alternative method for deploying PrivateBin.

I look forward to hearing your thoughts on this suggestion and would be happy to provide any further information or assistance needed to make this integration happen. Thank you for your consideration.

**Comment by elrido** [comment]
Right, it would make sense to extend the current ansible section to include this role as well:
https://github.com/PrivateBin/PrivateBin/blob/9b8bee82cf73d9a2a56f11bcbef20714080dcb84/doc/Installation.md?plain=1#L16-L19

We could extend it into a list with both roles linked and briefly mention their use cases. e1mo's one uses git to deploy privatebin to disk and creates a custom configuration file, where yours sets up podman, etc. but targets EL9 distros.

**Comment by voidquark** [comment]
I agree, creating a list is a good idea.

**Comment by elrido** [comment]
Oki, then go for it and raise a PR, so we can get that sorted. (If I raise one, we need to find a third person to approve it, but if you raise it, I can get it merged)

**Comment by voidquark** [comment]
The Pull request #1163 includes my suggestion. Feel free to adjust it, but I believe it's clean and consistent.
