### ISSUE TITLE
Grafana dashboard tailored for PrivateBin NGINX access log

### ISSUE THREAD

**Issue by voidquark** [PrivateBin/PrivateBin#1167]
### Feature Request Documentation:
PrivateBin is an excellent tool for securely sharing text-based information. However, monitoring and analyzing the usage of PrivateBin instances can be challenging since the application lacks a built-in audit log feature. To address this challenge, I've created a Grafana dashboard capable of extracting valuable insights from NGINX Access Logs related to PrivateBin usage.
It enables administrators to monitor who accessed/created which paste and provides essential total statistics.

- Github Repository for [dashboard source code](https://github.com/voidquark/grafana-dashboards)
- Grafana [Dashboard ID 19507](https://grafana.com/grafana/dashboards/19507-privatebin-access-log/)
- More details in my [blog post](https://voidquark.com/privatebin-nginx-access-log-dashboard/).

I would like to propose integrating a link to my  Grafana dashboard ID into the documentation (I'm not sure where it should go).

Please let me know if you require additional information or if you have any questions about the proposed integration.

**Comment by rugk** [comment]
Thanks, it would be great if you could put that information into [our wiki](https://github.com/PrivateBin/PrivateBin/wiki).

**Comment by voidquark** [comment]
I’d appreciate more details on its exact placement:

**Two potential solutions:**
 **1.** Adding it to the `Home` page, extending the `I am a server administrator wanting to set up PrivateBin` section.
 **2.** Incorporating it into the `FAQ` under the `General` category by creating new entries.

**Comment by elrido** [comment]
Further options:
3. Adding a link to your blog post to [Other installation methods](https://github.com/PrivateBin/PrivateBin/wiki/Other-installation-methods) under a new subtitle 
4. Creating a new page called "Installation of Grafana Dashboard for NGINX Access Log" or "Installation of Grafana Dashboard" with the details from the blog article and link it on the Home or Other methods

**Comment by elrido** [comment]
> Yeah I guess [a new wiki page](https://github.com/PrivateBin/PrivateBin/wiki/_new) "Monitoring PrivateBin" could be created mentioning different (future) ways. So you may create a headline "Using Graphana reading log file via promtail" or so?
> 
> You could then extend/link to that page in the home page IMHO.

Agreed, new page then and link on the home page. "Monitoring PrivateBin" sounds good, I can already think of other points I could extend that topic with, beyond Grafana, later on.

**Comment by voidquark** [comment]
I have created a new wiki page dedicated to [monitoring PrivateBin](https://github.com/PrivateBin/PrivateBin/wiki/Monitoring-PrivateBin).

Additionally, I have made adjustments to the [home page](https://github.com/PrivateBin/PrivateBin/wiki#i-am-a-server-administrator-wanting-to-setup-privatebin) in server administrators section.

**Comment by rugk** [comment]
Thanks a llot! This issue is thus likely solved.
