### ISSUE TITLE
Update Ansible Galaxy Role Links in Installation Documentation

### ISSUE THREAD

**Issue by voidquark** [PrivateBin/PrivateBin#1180]
I would like to create a Pull Request to update the installation instructions at https://github.com/PrivateBin/PrivateBin/blob/master/doc/Installation.md#installation. The Ansible Galaxy portal has been changed, and it would be beneficial to update the links to the Ansible roles as well.

**Here are the old links:**
- https://galaxy.ansible.com/voidquark/privatebin
- https://galaxy.ansible.com/e1mo/privatebin

**And here are the new links:**
- https://galaxy.ansible.com/ui/standalone/roles/voidquark/privatebin/
- https://galaxy.ansible.com/ui/standalone/roles/e1mo/privatebin/

**Comment by rugk** [comment]
Btw next time there is no need to create an issue first. You can just create the PR right away and put all information in there.
