### ISSUE TITLE
Provide a non-JS version to allow the user to choose their own method of encrypting text

### ISSUE THREAD

**Issue by nolsen42** [PrivateBin/PrivateBin#119]
This might sound like an absurd idea, but it has been tossed around in my head for a while, so why not provide a non-JS version of PrivateBin?

This idea has both advantages and disadvantages, one of the disadvantage is the lack of encryption support that PrivateBin provides, but instead, the user can actually use their own encryption, this is great for those who doesn't want to enable javascript. And, you still keep the simplicity and basic security (like CSP) that PrivateBin provides, but this will allow you to use your own method of encrypting messages (like PGP), and allow you to trust whoever is hosting the pastebin.

The use of the non-JS version could be automatic if javascript is disabled on the browser, or will require the user to choose to use the non-JS version.

So, really, it gives the user a bit more choice on whether they want to use javascript, or their own method, and could provide more trust to the hoster of the pastebin.

**Comment by elrido** [comment]
We already kind of have this in the form of the API. There is simply no UI or CLI client that uses it yet. Of course the server has some means to detect if you would just try to send plain text (it checks if the cipher text can be compressed, which it shouldn't as encryption should result in seemingly random data).

The problem is that this breaks the ability to open pastes without using the same client. That's why we should not add this into the default client. But nothing is stopping you to use an alternative client and use the JSON API to store your custom data (wrapped in the APIs JSON format) on a regular PrivateBin server.

**Comment by rugk** [comment]
If you use an alternative encryption method PrivateBin is only a dump data storage.

As for the decryption problem: When such a text cannot be decrypted it should be shown to the user, so they can decrypt it themself. Maybe it would be a good idea to store this information as a metadata, when the paste is created, so an appropriator message could be shown to the user when visiting the site.

In any case it is still to discuss whether it makes sense to integrate this into PrivateBin (pro: For Tor users not wanting to use JavaScript this would be great.; contra: Tor users could also just use any "usual" pastebin for such text, allowing them to insert any data.) or whether an application using the API would be more suitable. (pro: Easier to do than to integrate it into PrivateBin; contra: Things the OP pointed out, such as CSP, would go missing anyway.)

**Comment by rugk** [comment]
@elrido Please add a reason for closing this issue. Also at least a "wontfix" tag.

**Comment by elrido** [comment]
We both provided reasons. To recapitulate:
- A PasteBin service with user provided (non-JS) encryption would just be a regular, unencrypted PasteBin, many other projects provide this already -> out of scope for this project
- If this was meant in regards of an alternative client, eg. CLI, that would be a separate project, too, and one we are now working on
