### ISSUE TITLE
Seamless PrivateBin YOURLS Integration Script

### ISSUE THREAD

**Issue by ajsap** [PrivateBin/PrivateBin#1193]
**The problem**

I have recently created a script that facilitates the integration of YOURLS (Your Own URL Shortener) with PrivateBin, enabling users to generate shortened URLs for their pastes directly within the PrivateBin interface. However, this feature isn't built into PrivateBin and requires users to manually integrate the script.

**The solution**

I propose that PrivateBin incorporates the functionality provided by my script natively within its codebase. By having a built-in URL shortener option, users can effortlessly generate shortened URLs without the need for manual script integration. This could be an optional feature that admins can enable or disable based on their preferences. Without this feature, users will have to continue relying on external scripts or manual methods to shorten URLs, which could be cumbersome and less user-friendly.

I've published the script on GitHub: [PrivateBin YOURLS Integration Script](https://github.com/ajsap/privatebin-yourls/blob/main/shorten_url.php)

**Alternatives**

An alternative could be to provide official support and documentation for integrating external URL shortener scripts like the one I've created. This way, while the feature isn't built natively, there’s official guidance available for those who wish to implement it.

**Additional context**

Having a built-in URL shortener feature would significantly enhance the user experience by providing easy sharing options. Moreover, it could attract a wider user base who values such seamless functionality. Below is a screenshot of how the "Shorten URL" button appears within the PrivateBin interface after integrating the script.

The script has been tested and confirmed to work with PrivateBin version 1.6.0 and YOURLS version 1.9.2. This proposal aims at enhancing the usability and feature set of PrivateBin, aligning to make data sharing simple, secure, and efficient.

**Comment by elrido** [comment]
This looks pretty close to what we merged recently with #997 - Could you compare your implementation with that one and let us know if it would still add any additional features over that implementation or other benefits your implementation might have, that we should improve in the other?

**Comment by elrido** [comment]
@ajsap Did you have time to compare your implementation with the existing one? What features do we lack?

**Comment by ajsap** [comment]
Dear El RIDO,

Thank you for your follow-up. I appreciate the opportunity to discuss the integration of my shorten_url.php script into PrivateBin. I've conducted a thorough comparison between my implementation and the existing shortenviayourls.php, and here are my insights:

While shortenviayourls.php offers robust features like deep configuration integration, enhanced security through URL validation, and detailed error reporting, my shorten_url.php script brings its unique strengths to the table:


  1.  Simple Setup: It's designed for ease of integration, with clear instructions tailored for PrivateBin users. This simplicity could be particularly beneficial for those who prefer a straightforward approach.
  2.  Direct API Integration: The script integrates directly with the YOURLS API using predefined variables, making it less complex and more accessible for users who might not be deeply technical.
  3.  User IP Inclusion: A unique feature of shorten_url.php is the inclusion of the user's IP address in the request to YOURLS, including when proxied through CloudFlare or other reverse proxies such as Nginx, offering accurate insights and potential analytics capabilities.
  4.  Basic Input Validation: It ensures the correctness of the provided URL, contributing to the overall reliability of the URL shortening feature.

From a user experience standpoint, shorten_url.php emphasises ease of use and quick integration, which could be particularly appealing to a segment of our user base. Its customisability and straightforward nature make it a valuable addition to PrivateBin, especially for those seeking a less complex yet effective solution.

In conclusion, while shortenviayourls.php excels in deeper integration and security, shorten_url.php stands out for its simplicity and enhanced user experience. The choice between them would ideally be based on the specific needs and preferences of the PrivateBin instance administrators.

I look forward to your thoughts on this and am open to further discussions or modifications to better align with PrivateBin's vision and user requirements.

Cheers,

Andy Saputra<https://saputra.org>

This e-mail was prepared using voice recognition software. Whilst attempts have been taken to ensure clarity of meaning and accuracy, the writer requests that any grammatical and typographical errors are kindly excused.

» Go ahead, print it. Paper is a renewable resource ♻️

All incoming emails are scanned and filtered by IT Mate email security system. This could result in a legitimate email being deleted before being read by its addressee.

CAUTION — This message is intended for the addressee named above. The contents of this e-mail and its attachments:

· are confidential and privileged. Any unauthorised use of the contents is expressly prohibited and may be unlawful. If you are not the intended recipient, you must not use, copy or distribute this e-mail or attachments. If you receive this e-mail in error, please notify us immediately and delete the e-mail;
· may become scrambled, truncated or altered in transmission due to electronic mail being insecure media. Please check attachments for viruses and defects before opening or using them and notify us of any anomalies. IT Mate does not accept liability for any computer viruses, data corruption, or any other defects in respect of our emails (including attachments); and,
· are subject to copyright. No part of them may be reproduced, adapted or transmitted without the written permission of the copyright owner.

By replying to this email message you agree that the time of receipt for the purposes of the Electronic Transactions Act 2002 in respect of that reply or any subsequent replies from you will be when the email message actually comes to our attention.

On 21/11/2023, at 7:52 PM, El RIDO ***@***.***> wrote:



@ajsap<https://github.com/ajsap> Did you have time to compare your implementation with the existing one? What features do we lack?

**Comment by elrido** [comment]
Ok, so several points seem to be worth improving. I personally would not want to have 2 (or 3, if you count the generic urlshortener implementation) to maintain in the project, especially since I do myself not use this, admittedly popular, feature. I would therefore prefer to a merge request that adds features or rewrites the logic of to the [YourlsProxy class](https://github.com/PrivateBin/PrivateBin/blob/master/lib/YourlsProxy.php).

We deliberately avoid using the curl library, since the request is a very simple one and none of the crafty, advanced curl features should be required in this case - this lets us avoid requiring this extra dependency, keeping the container image sizes small:
https://github.com/PrivateBin/PrivateBin/blob/9614ee90f24e5bb24aea7bae6c36293c0c922bfc/lib/YourlsProxy.php#L62-L79

For the JSON parsing we use a small OOP wrapper, that throws when detecting an error, so we don't forget to check for them:
https://github.com/PrivateBin/PrivateBin/blob/9614ee90f24e5bb24aea7bae6c36293c0c922bfc/lib/YourlsProxy.php#L80-L86

**Comment by ajsap** [comment]
Dear El RIDO,

Thank you for your detailed feedback and insights regarding the YourlsProxy class and the overall approach to URL shortening within PrivateBin.

I appreciate the time and thought you've put into reviewing the potential integration of my shorten_url.php script. After considering your points, I've decided to maintain my implementation as a separate fork. This approach allows me to tailor the solution to specific use cases, as evidenced by its successful real-world application on https://cya.nz since 2012. To date, it has tracked 8,246 links with 2,204,990 clicks, and the numbers are still growing!

I respect the direction and standards you've set for PrivateBin and understand the importance of maintaining a streamlined and efficient codebase. Please feel free to reach out if there are any future opportunities for collaboration or if you find any aspect of my implementation that could be beneficial for PrivateBin.

Thank you once again for the opportunity to discuss this integration.

Cheers,

Andy Saputra<https://saputra.org>

This e-mail was prepared using voice recognition software. Whilst attempts have been taken to ensure clarity of meaning and accuracy, the writer requests that any grammatical and typographical errors are kindly excused.

» Go ahead, print it. Paper is a renewable resource ♻️

All incoming emails are scanned and filtered by IT Mate email security system. This could result in a legitimate email being deleted before being read by its addressee.

CAUTION — This message is intended for the addressee named above. The contents of this e-mail and its attachments:

· are confidential and privileged. Any unauthorised use of the contents is expressly prohibited and may be unlawful. If you are not the intended recipient, you must not use, copy or distribute this e-mail or attachments. If you receive this e-mail in error, please notify us immediately and delete the e-mail;
· may become scrambled, truncated or altered in transmission due to electronic mail being insecure media. Please check attachments for viruses and defects before opening or using them and notify us of any anomalies. IT Mate does not accept liability for any computer viruses, data corruption, or any other defects in respect of our emails (including attachments); and,
· are subject to copyright. No part of them may be reproduced, adapted or transmitted without the written permission of the copyright owner.

By replying to this email message you agree that the time of receipt for the purposes of the Electronic Transactions Act 2002 in respect of that reply or any subsequent replies from you will be when the email message actually comes to our attention.

On 23/11/2023, at 9:00 AM, El RIDO ***@***.***> wrote:



Ok, so several points seem to be worth improving. I personally would not want to have 2 (or 3, if you count the generic urlshortener implementation) to maintain in the project, especially since I do myself not use this, admittedly popular, feature. I would therefore prefer to a merge request that adds features or rewrites the logic of to the YourlsProxy class<https://github.com/PrivateBin/PrivateBin/blob/master/lib/YourlsProxy.php>.

We deliberately avoid using the curl library, since the request is a very simple one and none of the crafty, advanced curl features should be required in this case - this lets us avoid requiring this extra dependency, keeping the container image sizes small:
https://github.com/PrivateBin/PrivateBin/blob/9614ee90f24e5bb24aea7bae6c36293c0c922bfc/lib/YourlsProxy.php#L62-L79

For the JSON parsing we use a small OOP wrapper, that throws when detecting an error, so we don't forget to check for them:
https://github.com/PrivateBin/PrivateBin/blob/9614ee90f24e5bb24aea7bae6c36293c0c922bfc/lib/YourlsProxy.php#L80-L86

**Comment by elrido** [comment]
Fair enough, take care.

**Comment by rugk** [comment]
Also, _please_ don't use ChatGPT to reply to issues or at least tell it not to write it's default lonish stuff. And if you did not use it I am sorry, but otherwise please just be transparent about it.

**Comment by rugk** [comment]
Oh I am sorry, I overread it. Especially as email replies (especially with that long signature/addendum) get rendered as _very_ long texts on GitHub. I don't know how accessible GitHub's website is, but if it is possible for you, you could reply here too or so.
And no did not use any software for that, was a pure guessing based on thee writing style. Again I am sorry.
