### ISSUE TITLE
Format Source Code almost unreadable on dark themes

### ISSUE THREAD

**Issue by PeGaSuS-Coder** [PrivateBin/PrivateBin#1196]
**Did you use the FAQ section?**
- [x] Yes, I have read [the FAQ](https://github.com/PrivateBin/PrivateBin/wiki/FAQ) and I found no solution/answer there.

## Steps to reproduce

1. Use a dark theme
2. Use `Source Code` as format

### What happens
All the text is black, which makes it almost unreadable, except on the horizontal white stripes that will appear (they're not pretty either).

### What should happen
A better colour palette should be used (no suggestions here).

## Additional information

Screenshot of the relevant part of the issue:

![PrivateBin_Source_Code](https://github.com/PrivateBin/PrivateBin/assets/25697531/8d83cb7d-0648-4ff9-9a6e-b973b780fa9c)

## Basic information

**Server address**: https://tools.eggdrop.fr/privatebin/ (not owned by me)

**Server OS:** N/A

**Webserver:** N/A

**Browser:** Google Chrome Version 119.0.6045.123 (Official Build) (64-bit) on Ubuntu (not related but still)

**PrivateBin version:** 1.6.0 (according to the main page)

I can reproduce this issue on <https://privatebin.net>: Probably `Yes` if a dark theme is used

**Comment by elrido** [comment]
As per the [configuration wiki](https://github.com/PrivateBin/PrivateBin/wiki/Configuration#syntaxhighlightingtheme), we recommend to change the syntaxhighlightingtheme:

>  For the page, bootstrap-dark and bootstrap-dark-page PrivateBin templates we suggest using the sons-of-obsidian theme.

**Comment by PeGaSuS-Coder** [comment]
Understood.

I'll give a shout to the pastebin owner.

Although, probably, a better colour palette could be used/chosen?

**Comment by elrido** [comment]
I normally would ask you to raise this with the upstream project, as we do provide [all 5 themes](https://github.com/PrivateBin/PrivateBin/tree/master/css/prettify) they offered and new ones should be brought up with them. Unfortunately that project is now abandoned and we are looking at replacing it in #835.
