### ISSUE TITLE
urlshortener question

### ISSUE THREAD

**Issue by PeterTGarner** [PrivateBin/PrivateBin#120]
I've updated to PrivateBin 1.0 (_great_ software!) and am looking to write an on-site URL shortener using PHP.

My question is, when the URL shortener receives the long link from PrivateBin, is supposed to:

* Simply return a short link to the user's device and let them do what they want/need with it
or
* Create the short link then pass it back to PrivateBin, in which case, is there any code that I can use to do this?

Thanks in advance!

**Comment by elrido** [comment]
Hello Peter

Short answer: 1.

Its not quite as complicated as point 2. The URL-Shortener link generated in PrivateBin simply points you to the shortener and gets the URL of the paste attached as a GET parameter. The shortener does not need to know about PrivateBin and is not expected to send you back to it. Usually you point to the URL-Shorteners input form target. A public shortener might simply present you with a page describing how to use the generated short link, while a private shortener might require a login before it lets you create a shortlink.

Before you create your own shortener, consider using an existing project. For PHP I have used [yourls](http://yourls.org/) for a couple of years, without any issues.

**Comment by PeterTGarner** [comment]
Thanks - that option works fine for me and I'll be checking out yourls as well.
