### ISSUE TITLE
English language is not selectable since v1.6.1

### ISSUE THREAD

**Issue by CirnoT** [PrivateBin/PrivateBin#1208]
**Did you use the FAQ section?**
- [x] Yes, I have read [the FAQ](https://github.com/PrivateBin/PrivateBin/wiki/FAQ) and I found no solution/answer there.

## Steps to reproduce

1. Install PrivateBin v1.6.1
2. Try to change auto-detected language to English

### What happens

English is not one of selectable languages

### What should happen

User should always be able to switch to English, just like any other language

## Additional information

Caused by https://github.com/PrivateBin/PrivateBin/commit/896a49c8cf96ae9351796bd84050d2a0b249ddb3

## Basic information

**Server address**: N/A

**Server OS:** N/A

**Webserver:** N/A

**Browser:** N/A

**PrivateBin version:** v1.6.1

I can reproduce this issue on <https://privatebin.net>: Yes

**Comment by elrido** [comment]
Thank you for reporting this. Merge request raised, will try and release a 1.6.2 hotfix soon, when it got merged.

**Comment by elrido** [comment]
Sorry, the issue got fixed, but we did agree in the PR that I'll add a test case to ensure we don't regress again, so I'll reopen the issue to remind me of doing that.
