### ISSUE TITLE
Release could accidentially be triggered when pushing a branch with just number

### ISSUE THREAD

**Issue by rugk** [PrivateBin/PrivateBin#1216]
https://github.com/PrivateBin/PrivateBin/blob/9b07e3ff62166a49c3ecb12e4feddb45754f6457/.github/workflows/release.yml#L5

This means we could AFAIK accidentally trigger a release if we push a branch named `5`  or so (which is not really a release number, but is interpreted as release 5.0.0).

Not a big issue (as releases are just drafted), but IMHO not _that_ good. :wink: 
Also because we then already have generated SLSA provenance etc. for that release, so the culprit can never be reversed. :wink:

**Comment by rugk** [comment]
Ah no forget it, it needs at least `5.0`, so one dot is required. I think that's fine.

**Comment by elrido** [comment]
Also, it only applies to tags, not branches.
