### ISSUE TITLE
Safari burns document during automatic preview from highlighting URL

### ISSUE THREAD

**Issue by joshuakraitberg** [PrivateBin/PrivateBin#1219]
**Did you use the FAQ section?**
- [x ] Yes, I have read [the FAQ](https://github.com/PrivateBin/PrivateBin/wiki/FAQ) and I found no solution/answer there.

## Steps to reproduce

1. Use Safari with link preview enabled
2. Create a paste
3. When highlighting link, safari will open a preview, triggering burn

### What happens
Safari link preview triggers burn

### What should happen
There should be a button to copy link without highlighting.
If this is somehow unsafe, could be opt-in using config.

## Basic information

**Server address**:

**Server OS:**

**Webserver:**

**Browser:**

**PrivateBin version:**

I can reproduce this issue on <https://privatebin.net>: Yes

**Comment by r4sas** [comment]
Related: https://github.com/PrivateBin/PrivateBin/issues/541

**Comment by rugk** [comment]
Can someone provide the user agent from Safari used for this feature? Or more documentation about it?

Then we can block this and it should be safe.

**Comment by joshuakraitberg** [comment]
This is what I have.

```
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.1.2 Safari/605.1.15
```

**Comment by rugk** [comment]
This seems the normal Safari UA, we cannot block it, after all… do they use this one for the preview feature?

**Comment by IvanMishin1** [comment]
Maybe implementing a click to view button for this user agent could be the solution?

**Comment by elrido** [comment]
@IvanMishin1 Is this still occurring with release 1.7.1? We introduced a mechanism in release 1.7 that should prevent the preview from downloading burn after reading pastes without a user interaction to confirm a dialog. Specifically, #1237 should have resolved this issue.

**Comment by rugk** [comment]
Feel free to check back and comment the result (you can still do so), but to update the status of this issue correctly, I also assume this is closed by the mentioned PR. Thus, closing it.
