### ISSUE TITLE
PHP Fatal error:  Uncaught Error: Class "Aws\S3\S3Client" not found in .../lib/Data/S3Storage.php:114

### ISSUE THREAD

**Issue by pommetjehorlepiep** [PrivateBin/PrivateBin#1222]
**Did you use the FAQ section?**
- [X ] Yes, I have read [the FAQ](https://github.com/PrivateBin/PrivateBin/wiki/FAQ) and I found no solution/answer there.

Installed PrivateBin 1.6.2 successfully and everything works OK when using file storage.
Tried to switch over to S3Storage, but getting fatal errors.

Fatal error in PHP log:
```
PHP Fatal error:  Uncaught Error: Class "Aws\S3\S3Client" not found in <root>/lib/Data/S3Storage.php:114
Stack trace:
#0 <root>/lib/Model.php(85): PrivateBin\Data\S3Storage->__construct()
#1 <root>/lib/Controller.php(202): PrivateBin\Model->getStore()
#2 <root>/lib/Controller.php(125): PrivateBin\Controller->_create()
#3 <root>/index.php(18): PrivateBin\Controller->__construct()
#4 {main}
thrown in <root>/lib/Data/S3Storage.php on line 114
```

## Steps to reproduce
1. Install PrivateBin 1.6.2 from tar file + created custom `conf.php` from `conf.sample.php`
2. Comment out [model] class = Filesystem 
```
;[mode]
;class = Filesystem
;[model_options]
;dir = PATH "data"
```
3. Uncomment [model] class = S3Storage (in my case using MinIO):
```
[model]
class = S3Storage
[model_options]
bucket = "privatebin"
endpoint = "http://minio.mydomain.com:9000"
use_path_style_endpoint = true
accesskey = "..."
secretkey = "..."
```
4. Verified that credentials etc worked ok using `aws CLI`

### What happens
As soon as you try to `send` you get:   **Could not create paste: server error or not responding**

### What should happen
Paste should have been successfully saved in the designated S3 bucket and no fatal errors

## Additional information
![image](https://github.com/PrivateBin/PrivateBin/assets/8982487/0a50a2d2-a1c5-4635-94c0-935eaeb6e4b6)

## Basic information

**Server address**:

**Server OS:**  Alpine 3.19

**Webserver:** Caddy 2

**Browser:** Brave 

**PrivateBin version:** 1.6.2

I can reproduce this issue on <https://privatebin.net>: No

**Comment by elrido** [comment]
While we do vendor in the core libraries, we refrained from including the GCP and S3 dependencies, as they each depend on their cloud vendors' PHP SDK and are measured in many megabytes - several times more as our repository at this time.

Let's take this as an opportunity to improve our installation documentation. In short, you will need to have [composer installed](https://getcomposer.org/doc/00-intro.md#installation-linux-unix-macos) or available on your system and then run either of these commands to use S3 storage or the GCS one:
```
# for S3 storage:
$ composer require aws/aws-sdk-php
# for GCS storage:
$ composer require google/cloud-storage
```

**Comment by rugk** [comment]
So as it seems this question has been answered and I thus close this issue. If anyone has further questions on that topic, feel free to comment here, again.

**Comment by pommetjehorlepiep** [comment]
Sorry for the late response, but `composer require aws/aws-sdk-php` + installing PHP simplexml resolved the original problem, but now PrivateBin won´t start! 

Now getting this error:

```
[08-Jan-2024 08:04:03 ...] PHP Fatal error:  Uncaught Error: Class "PrivateBin\Controller" not found in <root>/index.php:18
Stack trace:
#0 {main}
thrown in <root>/index.php on line 18
```

**Comment by elrido** [comment]
> ```
> ./composer.json has been created
> ```

It may be that our projects composer.json (and possibly composer.lock) is required to be present for this operation, as we instruct composer there how to include the PrivateBin namespace into the autoloader:
https://github.com/PrivateBin/PrivateBin/blob/9fb7aee589726d3ad8fccb0d010e634a7312e0e8/composer.json#L39-L43

See also our docker install, where these get downloaded just before running the require:
https://github.com/PrivateBin/docker-nginx-fpm-alpine/blob/master/Dockerfile#L72-L76

**Comment by rugk** [comment]
Yeah… maybe that should be documented somewhere?
