### ISSUE TITLE
js/zlib-1.3.wasm 404 (Not Found)

### ISSUE THREAD

**Issue by roughnecks** [PrivateBin/PrivateBin#1242]
**Did you use the FAQ section?**
- [x] Yes, I have read [the FAQ](https://github.com/PrivateBin/PrivateBin/wiki/FAQ) and I found no solution/answer there.

## Steps to reproduce

1. Upgrade to latest 1.7.0 release
2.  Il tuo browser non supporta WebAssembly, utilizzato per la compressione di zlib. Puoi creare documenti non compressi, ma non è possibile leggere quelli compressi.

### What happens
My privatebin tries to access js/zlib-1.3.wasm, which is not there

### What should happen
The actual library seems to be js/zlib-1.3.1.wasm

## Additional information

![image](https://github.com/PrivateBin/PrivateBin/assets/1666536/47a9a9c2-ee38-4390-b593-7bf5f38c67ff)

## Basic information

**Server address**: <https://paste.woodpeckersnest.space/>

**Server OS: Debian Stable**

**Webserver: nginx**

**Browser: Chrome Versione 121.0.6167.161**

**PrivateBin version: 1.7.0**

I can reproduce this issue on <https://privatebin.net>: No

**Comment by roughnecks** [comment]
Fixed by 1.7.1
Thanks

**Comment by elrido** [comment]
_Sigh_ - I'm so terribly sorry about this! I had already published the images when I caught it, so I released the hotfix.

**Comment by roughnecks** [comment]
👍
