### ISSUE TITLE
:hourglass_flowing_sand:  Document Release Policy

### ISSUE THREAD

**Issue by adriens** [PrivateBin/PrivateBin#1243]
## The problem

We are using `privatebin` and are realy hapy with it. I would like to applu governance on maintenance process, hence I would need to get the lifecycle policy about for example support strategy, end of life,...

## The solution

Provide some guidelines , for example by providing a [`SECURITY.md`](https://github.com/quarkusio/quarkus/blob/main/SECURITY.md) like on the repo explaining clearly how users should maintain their instance.

For exammple, saying that each major version reaches its end of life as soon as a new major version is released. 

## Alternatives

Give the web page where it is documented.

## Additional context

The main idea would to add it to https://endoflife.date/ (see the [dedicated DEV.to series](https://dev.to/adriens/series/21232)):

- [⌛ Manage EoLs like a boss with endoflife.date 🛑](https://dev.to/optnc/manage-eols-like-a-boss-with-endoflifedate-2ikf)
- 🔁[ Browse Neo4J EoL versions inside Neo4J AuraDB 🤓 ](https://dev.to/optnc/browse-neo4j-eol-versions-inside-neo4j-auradb-1ncb)
- [Kaggle dataset : ⏳ endoflife.date database (duckdb)](https://www.kaggle.com/datasets/adriensales/endoflife-date-database)

**Comment by elrido** [comment]
At the moment our policy in that regard is very simple: We only support the latest release as we have no capacity (in terms of maintainers) to handle multiple releases such as a long term supported one. This is indeed documented in our SECURITY.md file here in the repo:
https://github.com/PrivateBin/PrivateBin/blob/eb59f3a4f3aa06ff2f5284156ba6fd8ef6ec11a1/SECURITY.md?plain=1#L1-L8

For vulnerabilities, there is [one precedent where we provided a backport of the fix to the prior minor version](https://privatebin.info/reports/vulnerability-2020-01-11.html). In other such incidents we did either [provide a workaround that could get applied via configuration change to several prior releases](https://privatebin.info/reports/vulnerability-2022-04-09.html) or did [try and identify and contact the affected instances' administrators](https://privatebin.info/reports/vulnerability-2017-09-29.html).

We have and would still use the information visible publicly in the [directory](https://privatebin.info/directory/) to assess how widespread a problem is. Should many instances affected by a problem still be on an older minor release, a code change to mitigate to problem necessary and not too difficult to backport, I would consider doing so. At the time of writing this, shortly after the 1.7 releases, there are for example still many instances with 1.6 and 1.5 out there, but only a handful of 1.4 ones left.

The part that is less clear to me is updates in our libraries. So far we had only [one report of a vulnerability in one weakening pastes security](https://privatebin.info/reports/vulnerability-2018-08-11.html). We do update as many of them as possible to the latest versions prior each of our releases, but so far have not considered any of them a reason for a backport. We really need someone looking into upgrading bootstrap, for example. Luckily that is mostly CSS, so while it makes the UI look dated, it's unlikely to affect us in terms of security.

**Comment by rugk** [comment]
An addendum:
> The main idea would to add it to https://endoflife.date/ (see the [dedicated DEV.to series](https://dev.to/adriens/series/21232)):

Yeah sure, feel free to add it there/propose a PR there. If anything more than what we have (`SECURITY.md`) is needed for that, please let us know.

**Comment by adriens** [comment]
Awesome, thanks a lot for the kind and cool feedback @rugk :pray:

**Comment by adriens** [comment]
WIP
- https://github.com/endoflife-date/endoflife.date/pull/4657

**Comment by adriens** [comment]
I'll let you know if I need some more resources, probably the _releasePolicyLink_ :thinking:
