### ISSUE TITLE
Alignment of file picker dialog in right-to-left languages (RTL)

### ISSUE THREAD

**Issue by elrido** [PrivateBin/PrivateBin#1251]
Originally reported by translator Lazerns via Crowdin:

## The problem

> Also this should be there :)

![Also this should be there :)](https://github.com/PrivateBin/PrivateBin/assets/1017622/7520cd59-b8c5-4c80-ad08-07e85f7b59c4)

## The solution

Ensure that the alignment matches the templates RTL mode. Bootstrap CSS should have facilities for this, we may have used the wrong CSS class.

## Alternatives

Worst case, we change the alignment class based on the RTL setting PHP-side.

## Additional context

Affects the two RTL translations, Arabic & Hebrew. There may be other drop downs in the menu that have similar issues.

**Comment by rugk** [comment]
Modern bootstrap seems to have some (experimental) support for it: https://getbootstrap.com/docs/5.0/getting-started/rtl/ They use https://rtlcss.com/ under-the-hood, maybe that is helpful for us too. (Also it's likely easy to migrate then, if we already use the same lib and update to bootstrap 5.)

**Comment by elrido** [comment]
This issue is now resolved in the bootstrap5 template:

![file upload in arabic on bootstrap5](https://github.com/PrivateBin/PrivateBin/assets/1017622/f9e65042-d65a-4fee-a321-46579b531ab5)

Since we plan to deprecate the bootstrap(3) template over the next year, I'll close this issue as concluded.
