### ISSUE TITLE
Allow to include third-party scripts from the config file

### ISSUE THREAD

**Issue by Zwyx** [PrivateBin/PrivateBin#1260]
## The problem

I've added a third-party script (for analytics) in the `head` of [`bootstrap.php`](https://github.com/PrivateBin/PrivateBin/blob/master/tpl/bootstrap.php#L8).

I also had to update the CSP header, and this is already easily possible with the `cspheader` entry in the config file.

**Having the possibility to add third-party scripts directly from the config** file would be useful and would allow adding third-party scripts while using the docker image (and keeping it `read_only`).

## The solution

Add an entry `thirdpartyscripts` in the config file, which would take a list of `<script ..></script>` tags to be included in the `head` of `bootstrap.php`.

I'd be happy to work of this and submit a PR, if you like the idea :slightly_smiling_face:

**Comment by rugk** [comment]
> I've added a third-party script (for analytics) in the head of [bootstrap.php](https://github.com/PrivateBin/PrivateBin/blob/master/tpl/bootstrap.php#L8).

Honestly, I guess this would be a good argument against making that easier. As “analytics” is usually a thing most users of PrivateBin likely don't want. Or, generally, any third-party scripts that could collect information on the sensitive data this tool may be used for. Privacy is a top priority for PrivateBin, for obvious reasons – it's in the name, after all.
As such, any webadmin is of course free to modify their instance as they wish, and you may surely add it and also found out how it has been added. But I see no compelling reason why we should make it easier to do that.

@elrido you agree?

> would allow adding third-party scripts while using the docker image (and keeping it read_only).

BTW you can keep it readonly and just mount your (new/adjusted) template file into the image from the outside, that should be no problem.

**Comment by elrido** [comment]
> @elrido you agree?

I fully concur!

> > BTW you can keep it readonly and just mount your (new/adjusted) template file into the image from the outside, that should be no problem.
> 
> Could you tell me more about this? I've done some research and try with:
> 
> ```shell
> docker cp bootstrap.php privatebin:/srv/tpl/bootstrap.php
> ```

Instead of copying the template (which means it will disappear when you upgrade the image), try mounting it during your docker run, like we explain [in the README.md for the custom configuration](https://github.com/PrivateBin/docker-unit-alpine?tab=readme-ov-file#custom-configuration):

```shell
$ docker run -d --restart="always" --read-only -p 8080:8080 -v $PWD/bootstrap.php:/srv/tpl/bootstrap.php:ro -v $PWD/privatebin-data:/srv/data -t privatebin privatebin/unit-alpine:1.7.1
```
(obviously adjust the above line with any of your changes to port, image variant or version, etc.)

**Comment by Zwyx** [comment]
Ah excellent!! I can't believe that was already in the documentation :facepalm: Sorry about that.

No worries, I understand your positions. Thank you so much guys for your help!
