### ISSUE TITLE
The notice bar needs improvements...

### ISSUE THREAD

**Issue by nolsen42** [PrivateBin/PrivateBin#128]
I think it's a good idea if the notice have some way to be closed out to save space on the webpage, and have features like multi-language support (because an english notice on a spanish pastebin makes no sense).

The multi-language support could be added by adding a notice for a specific language in the config.

**Comment by elrido** [comment]
Multi-language support for the notice message is already implemented. Just introduce the message as given in the conf.ini as a [message ID with associated translations](https://github.com/PrivateBin/PrivateBin/wiki/Translation) into all suitable i18n/*.json files and your done.

Regarding the dismissal: There is an [alert.js plugin](http://getbootstrap.com/components/#alerts-dismissible) for bootstrap, so at least in templates based on that CSS library it can be implemented.
