### ISSUE TITLE
[Clarification request] File uploads: are uploaded/downloaded files also e2e-encrypted ?

### ISSUE THREAD

**Issue by Wikinaut** [PrivateBin/PrivateBin#129]
It's not clear from the description, and FAQ, whether uploaded files are also end-to-end (e2e) encrypted.

I suggest you experts add some lines of information to the
- https://privatebin.info/ Main page ; and
- https://github.com/PrivateBin/PrivateBin/wiki/FAQ FAQ

**Comment by elrido** [comment]
Sorry, I did think that was clear, but rereading our docs I agree that there are only these sentences regarding this:

> Data is encrypted/decrypted in the browser using 256bit AES in Galois Counter mode.
> [...]
> Encryption of data sent to server.

To clarify this, the following things are encrypted end-to-end, so for both up- and download:
* paste text (without formatting, which is done after decryption)
* files
* user names, if given in discussion posts
* discussion posts

What is not encrypted is certain meta data of a paste, in particular:
* timestamp the paste or discussion post was created (can also be deducted via access to paste/discussion files on the file system)
* expiration time in seconds, if chosen
* format of the paste (plain text, source code or markdown)
* if the discussion was enabled (true/false)
* the IP based user icon if a user name was given

What is not stored or transmitted at all:
* generated decryption key of the paste, it is part of the URL after the hash
* password, if given

Note that all encrypted items in a paste and its discussion use unique salts (the salts are not encrypted) hence one can't easily deduct i.e. two discussion user names being the same name without having the key. But you can deduct if the same IP was used in a discussion without decryption, as the user icons (generated when a user name is used) are not encrypted. Then again it is easier to gather this information via the server access log.

**Comment by elrido** [comment]
This was now (finally) added to the FAQ:
https://github.com/PrivateBin/PrivateBin/wiki/FAQ#what-parts-are-or-arent-encrypted-in-a-paste
