### ISSUE TITLE
Improve documentation regarding comments. 

### ISSUE THREAD

**Issue by nain-F49FF806** [PrivateBin/PrivateBin#1291]
## The problem

The API documentation for comments feature is hard to find or incomplete.  
The [API page](https://github.com/PrivateBin/PrivateBin/wiki/API#as-of-version-13) describes the encrypted comment structure. 
But I couldn't easily find the structure of the plaintext version, like is demonstrated for pastes [here](https://github.com/PrivateBin/PrivateBin/wiki/Encryption-format#data-passed-in). And had to resort to browsing through the [code](https://github.com/PrivateBin/PrivateBin/blob/ec02afca0469017a77fa5c8b952241c879883882/js/privatebin.js)

Eventually I found the description in [this file](https://raw.githubusercontent.com/PrivateBin/PrivateBin/master/js/types.jsonld).
But this location is not obvious. 

It's not intuitive that `CommentCipherMessage` (or even `PasteCipherMessage`) struct can be found in this file when one doesn't already know it's there or what to look for. Also, the file is hard to read in the browser with no formatting etc. 

## The solution

The plain message structs can be linked to in API page or referred to in the [preparation](https://github.com/PrivateBin/PrivateBin/wiki/Encryption-format#data-passed-in) section

**Comment by nain-F49FF806** [comment]
> From what I see, maybe just linking the JSON-LD is needed or is there more?

@rugk I think on [`encryption format`](https://github.com/PrivateBin/PrivateBin/wiki/Encryption-format#data-passed-in) page adding a comment example would be helpful too.

> Anyway, sure the doc can be improved? Would you create a PR? Or edit the wiki?

Yeah, sure, I can try :). 
FTR: I haven't used the wiki feature for writing before. Would I need permission to edit?

**Comment by nain-F49FF806** [comment]
Found a similar issue that was opened earlier. 
So it seems like this has indeed been a common friction point. 
I've updated the wiki. Please have a look when you can to ensure it's okay.

**Comment by rugk** [comment]
Thanks a lot!
