### ISSUE TITLE
`Save Paste` button should save to .md extension if paste format is markdown

### ISSUE THREAD

**Issue by nain-F49FF806** [PrivateBin/PrivateBin#1293]
## The problem

I recently opened a paste that was marked markdown, like [this one](https://p.darklab.sh/?dee29af612943f6b#9XSAfWNwMTnaSyDv4xoG8yYUx4QqbMXXd8Y3YiQ6fjV2).
When clicking on save paste button, I found it cool that it downloaded a file automatically with the pastes id as name. But the extension was .txt. 

## The solution

 
For regular plaintext pastes the above makes sense, but since the paste format was Markdown, and is also being displayed as markdown, maybe it'd be more intuitive and seamless if the download is also with extension .md ?

**Comment by 9401adarsh** [comment]
Hey there, can I take up this issue ? Would appreciate some if someone could lend a few pointers on where to begin.

**Comment by elrido** [comment]
Sure thing, go for it. It should not be too complicated, the filename is the first thing generated in the [TopNav.downloadText](https://privatebin.info/jsdoc/TopNav.html#.downloadText) method:

https://github.com/PrivateBin/PrivateBin/blob/28f3e544b8543e8777e92ba23ed142b66407673b/js/privatebin.js#L3825-L3834

You could look up the current format using the [PasteViewer.getFormat](https://privatebin.info/jsdoc/PasteViewer.html#.getFormat) method - you would look for it to be `markdown` to change the suffix to `.md`.

**Comment by 9401adarsh** [comment]
Thanks for the pointers, will keep you posted of the progress here.

**Comment by 9401adarsh** [comment]
Hello, sorry wasn't able to get back in the last couple of weeks. I have made the changes to the `privatebin.js` file as per your suggestion, however I am facing some issues in running the unit tests. 

I made a Github codespace based on the PrivateBin repositoy, and saw that I'd have to run the PHP units to validate the changes made in any `.js` file. 

I navigated to the `/tst` folder and ran `phpunit` as per the docs, however I got the following error. 
```
bash: phpunit: command not found
```

The composer.json file has the reference to the phpunit module. 

```
	"require-dev" : {
		"phpunit/phpunit" : "^9"
	},
```

Looking forward to your inputs, thank you.

**Comment by rugk** [comment]
Sure, if it is good [create a pull request](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request) and we can review it and suggest changes, if needed.

**Comment by 9401adarsh** [comment]
Will create a pull request from my feature branch of the forked repo to the master branch of the official repo. Hope that works ?

**Comment by rugk** [comment]
Sure, it should, just do it.
