### ISSUE TITLE
Removing page template and cleaning up code

### ISSUE THREAD

**Issue by rugk** [PrivateBin/PrivateBin#1298]
## The problem

Upgrade to Bootstrap 5 in https://github.com/PrivateBin/PrivateBin/pull/1287 has shown:
* we have a big maintenance burden by maintaining the page template
* we have to care when adjusting JS to not break all the templates and test with all of them
* when we adjust the templates, in reverse, we have to care for the JS and cannot easily change the HTML structure yet again and adjust it to some modern one etc.

## The solution

* first of all: remove the page template altogether
* later/maybe not yet(?): remove the old bootstrap template
* rename CSS classes/unify them
* use proper/modern HTML tags where useful, [like `<template>`](https://github.com/PrivateBin/PrivateBin/pull/1287#discussion_r1575454988)
* adjust the JS if needed
* remove outdated JS code only useful for older bootstrap versions etc.
* [add the CSS classes intended for boootstrap 5](https://github.com/PrivateBin/PrivateBin/pull/1287#discussion_r1575426846)/adjust and remove custom CSS styling if needed
* fix some accessibility issues [like for alerts and buttons](https://github.com/PrivateBin/PrivateBin/pull/1287#discussion_r1575383746).

## Alternatives

* keep maintaining stuff, the desire does not seem to be big though

**Comment by elrido** [comment]
Just noticed that this is already tracked in #265.
