### ISSUE TITLE
[Bug?] Language detection does not work

### ISSUE THREAD

**Issue by Wikinaut** [PrivateBin/PrivateBin#131]
My installation ignores the (Browser=de) language detection and the settings in conf.ini .

Any idea what is wrong, is it a bug ?

```
; by default PrivateBin will guess the visitors language based on the browsers
; settings. Optionally you can enable the language selection menu, which uses
; a session cookie to store the choice until the browser is closed.
languageselection = true

; set the language your installs defaults to, defaults to English
; if this is set and language selection is disabled, this will be the only language
languagedefault = "en"
```

or even force "de" 

```
languagedefault = "de"
```

are ignored.

I **can** manually select a language, which works.

**Comment by elrido** [comment]
As [per documentation](https://github.com/PrivateBin/PrivateBin/wiki/Configuration#languageselection--languagedefault), that combination is the trickiest one:

> uses browser language or the one last selected and stored in the cookie and uses "fr" as the fallback for unknown browser languages

Hence it should use always the same one that was last selected via the "lang" cookie and uses "de" only if your browser has no or an unsupported language set. If you delete the "lang" cookie in your browser, it will select the highest ranked language that is supported by PrivateBin, which might not be "de" or "en".
