### ISSUE TITLE
S3 provider broken in 1.7.2

### ISSUE THREAD

**Issue by sqlstatement** [PrivateBin/PrivateBin#1316]
**Did you use the FAQ section?**
- [x] Yes, I have read [the FAQ](https://github.com/PrivateBin/PrivateBin/wiki/FAQ) and I found no solution/answer there.

## Steps to reproduce

1. Pull the 1.7.2 image from privatebin/s3
2. Set up S3 connection, try to submit a paste

### What happens

There is an error:
```
nginx-fpm-alpine-1  | 2024/05/06 20:01:02 [error] 19#19: *1 FastCGI sent in stderr: "PHP message: PHP Deprecated:  Return type of Aws\HandlerList::count() should either be compatible with Countable::count(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /srv/vendor/aws/aws-sdk-php/src/HandlerList.php on line 284; PHP message: PHP Deprecated:  Return type of Aws\Api\AbstractModel::offsetExists($offset) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /srv/vendor/aws/aws-sdk-php/src/Api/AbstractModel.php on line 41; PHP message: PHP Deprecated:  Return type of Aws\Api\AbstractModel::offsetGet($offset) should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /srv/vendor/aws/aws-sdk-php/src/Api/AbstractModel.php on line 30; PHP message: PHP Deprecated:  Return type of Aws\Api\AbstractModel::offsetSet($offset, $value) should either be compatible with ArrayAccess::offsetSet(mixed $offset, mixed $value): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /srv/vendor/aws/aws-sdk-php/src/Api/AbstractModel.php on line 36; PHP message: PHP Deprecated:  Return type of Aws\Api\AbstractModel::offsetUnset($offset) should either be compatible with ArrayAccess::offsetUnset(mixed $offset): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /srv/vendor/aws/aws-sdk-php/src/Api/AbstractModel.php on line 46; PHP message: PHP Deprecated:  Return type of Aws\Endpoint\Partition::offsetExists($offset) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /srv/vendor/aws/aws-sdk-php/src/HasDataTrait.php on line 41; PHP message: PHP Deprecated:  Retur
nginx-fpm-alpine-1  | 2024/05/06 20:01:02 [error] 19#19: *1 FastCGI sent in stderr: "e] attribute should be used to temporarily suppress the notice in /srv/vendor/aws/aws-sdk-php/src/HasDataTrait.php on line 36; PHP message: PHP Deprecated:  Return type of Aws\Command::offsetUnset($offset) should either be compatible with ArrayAccess::offsetUnset(mixed $offset): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /srv/vendor/aws/aws-sdk-php/src/HasDataTrait.php on line 46; PHP message: PHP Deprecated:  Return type of Aws\Command::count() should either be compatible with Countable::count(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /srv/vendor/aws/aws-sdk-php/src/HasDataTrait.php on line 56; PHP message: PHP Deprecated:  Return type of Aws\Command::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /srv/vendor/aws/aws-sdk-php/src/HasDataTrait.php on line 13; PHP message: PHP Deprecated:  Creation of dynamic property GuzzleHttp\Handler\CurlMultiHandler::$_mh is deprecated in /srv/vendor/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php on line 58; PHP message: PHP Deprecated:  Return type of Aws\Api\DateTimeResult::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /srv/vendor/aws/aws-sdk-php/src/Api/DateTimeResult.php on line 37; PHP message: PHP Deprecated:  Return type of Aws\Result::offsetExists($offset) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /srv/vendor/aws/aws-sdk-php/src/HasDataTrait.php on line 41; PHP message: PHP Deprecated:  Return type of & Aws\Result::offsetGet($offset) should either be compatible with ArrayAccess:
nginx-fpm-alpine-1  | 2024/05/06 20:01:02 [error] 19#19: *1 FastCGI sent in stderr: "->_create()
nginx-fpm-alpine-1  | #6 /var/www/index.php(18): PrivateBin\Controller->__construct()
nginx-fpm-alpine-1  | #7 {main}
nginx-fpm-alpine-1  |   thrown in /srv/vendor/aws/aws-sdk-php/src/AwsClient.php on line 209" while reading response header from upstream, client: <snip>, server: , request: "POST / HTTP/1.1", upstream: "fastcgi://unix:/run/php-fpm.sock:", host: "<snip>"
```

### What should happen

The upload should succeed.

## Additional information

Seems like there in an issue with a dependency added/changed in the 1.7.2 update
## Basic information

**Server address**: n/a

**Server OS:** Debian 12

**Webserver:** Caddy v2.7.6

**Browser:** Firefox Nightly 127.0a1

**PrivateBin version:** 1.7.2

I can reproduce this issue on <https://privatebin.net>: No

**Comment by guohaolee** [comment]
+1 
using privatebin/s3 docker container and logs returned as below

`24/05/07 10:46:49 [error] 20#20: *818 FastCGI sent in stderr: "PHP message: PHP Deprecated:  Return type of Aws\HandlerList::count() should either be compatible with Countable::count(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /srv/vendor/aws/aws-sdk-php/src/HandlerList.php on line 284; PHP message: PHP Deprecated:  Return type of Aws\Api\AbstractModel::offsetExists($offset) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /srv/vendor/aws/aws-sdk-php/src/Api/AbstractModel.php on line 41; PHP message: PHP Deprecated:  Return type of Aws\Api\AbstractModel::offsetGet($offset) should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /srv/vendor/aws/aws-sdk-php/src/Api/AbstractModel.php on line 30; PHP message: PHP Deprecated:  Return type of Aws\Api\AbstractModel::offsetSet($offset, $value) should either be compatible with ArrayAccess::offsetSet(mixed $offset, mixed $value): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /srv/vendor/aws/aws-sdk-php/src/Api/AbstractModel.php on line 36; PHP message: PHP Deprecated:  Return type of Aws\Api\AbstractModel::offsetUnset($offset) should either be compatible with ArrayAccess::offsetUnset(mixed $offset): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /srv/vendor/aws/aws-sdk-php/src/Api/AbstractModel.php on line 46; PHP message: PHP Deprecated:  Return type of Aws\Endpoint\Partition::offsetExists($offset) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /srv/vendor/aws/aws-sdk-php/src/HasDataTrait.php on line 41; PHP message: PHP Deprecated:  Ret
2024/05/07 10:46:49 [error] 20#20: *818 FastCGI sent in stderr: "PrivateBin\Controller->_create()
#8 /var/www/index.php(18): PrivateBin\Controller->__construct()
#9 {main}`

**Comment by elrido** [comment]
These look like deprecation warnings and partial stack traces. It's the latter that we need to be able to debug this. There should be lines starting with `#1` that indicate the source of the problem.

Closing this as a duplicate, please share your full findings or responses from the upstream on #1315
