### ISSUE TITLE
In version 1.7.2, the user-selected expiration is ignored

### ISSUE THREAD

**Issue by schlimazel** [PrivateBin/PrivateBin#1320]
Steps to reproduce:
1. When creating a paste, select an "Expires" time (other than the default).
2. Click the "Create" button.
3. Open the link.

What happens:
The "Expires" time reverts to the default.

What should happen:
The "Expires" time should remain whatever the user selected.

**Comment by Ozwel** [comment]
I do confirm this happens to me as well and can be reproduced with all other 1.7.2 instances I could find on the web.

**Comment by Ozwel** [comment]
Looks like it has already been discussed here:
https://github.com/PrivateBin/PrivateBin/issues/1309

**Comment by rugk** [comment]
Duplicate of https://github.com/PrivateBin/PrivateBin/issues/1320

**Comment by rugk** [comment]
Thanks all for reporting! This is indeed critical. Please don't update to the latest version in between.
