### ISSUE TITLE
PhpUnit tests should be able to run from another dir

### ISSUE THREAD

**Issue by rugk** [PrivateBin/PrivateBin#133]
## Steps to reproduce

1. in the root dir run `phpunit tst`.

(`cd tst` and `phpunit` afterwards work.)

### What happens
```
PHPUnit 4.2.6 by Sebastian Bergmann.

PHP Fatal error:  Class 'Helper' not found in [...]/PrivateBin/tst/ConfigurationTest.php on line 14
PHP Stack trace:
PHP   1. {main}() /usr/bin/phpunit:0
PHP   2. PHPUnit_TextUI_Command::main() /usr/bin/phpunit:42
PHP   3. PHPUnit_TextUI_Command->run() /usr/share/php/PHPUnit/TextUI/Command.php:138
PHP   4. PHPUnit_TextUI_TestRunner->doRun() /usr/share/php/PHPUnit/TextUI/Command.php:186
PHP   5. PHPUnit_Framework_TestSuite->run() /usr/share/php/PHPUnit/TextUI/TestRunner.php:423
PHP   6. PHPUnit_Framework_TestSuite->run() /usr/share/php/PHPUnit/Framework/TestSuite.php:703
PHP   7. PHPUnit_Framework_TestCase->run() /usr/share/php/PHPUnit/Framework/TestSuite.php:703
PHP   8. PHPUnit_Framework_TestResult->run() /usr/share/php/PHPUnit/Framework/TestCase.php:771
PHP   9. PHPUnit_Framework_TestCase->runBare() /usr/share/php/PHPUnit/Framework/TestResult.php:643
PHP  10. ConfigurationTest->setUp() /usr/share/php/PHPUnit/Framework/TestCase.php:831
```

### What should happen
The PHPUnit tests should be able to be started from another dir.

## Basic information

**PrivateBin version:** 64e1e0d7c4e3d0e62ca9d615831ebc3596910594

**Comment by elrido** [comment]
AFAIK the unit tests can't work from _any_ directory. As per [PHPUnits documentation of the `--configuration` option](https://phpunit.de/manual/current/en/textui.html#textui.clioptions):

> If phpunit.xml [...] exist in the current working directory and --configuration is not used, the configuration will be automatically read from that file.

Our phpunit.xml is located in the tst directory and all the paths given in it are relative to that directory. If you moved that XML file to the projects root directory, you'd need to adjust all these relative paths to still create the reports in the right places, include the right files etc. Also the paths in .travis.yml would then need to be adjusted.

If you would change the paths in the XML to absolute paths it would work from any directory using the `--configuration` option to select the XML if you are not in the correct working directory, but then of course we would need to force all developers to store the project in the same path, say /usr/src/privatebin, on their machines and would exclude any windows users.

This is just my research on the topic and its possible I have misinterpreted the docs or not seen a viable workaround. Hence I'll assign the request to you for further investigation or closing it, should you come to the same conclusion.

**Comment by rugk** [comment]
Did not know about the `--configuration` option, but even when it is given an error is shown:
```console
$ phpunit --configuration tst/phpunit.xml
PHP Warning:  copy(../cfg/conf.ini.sample): failed to open stream: No such file or directory in /path/to/PrivateBin/tst/Bootstrap.php on line 18
PHP Stack trace:
PHP   1. {main}() /usr/bin/phpunit:0
PHP   2. PHPUnit_TextUI_Command::main() /usr/bin/phpunit:42
PHP   3. PHPUnit_TextUI_Command->run() /usr/share/php/PHPUnit/TextUI/Command.php:138
PHP   4. PHPUnit_TextUI_Command->handleArguments() /usr/share/php/PHPUnit/TextUI/Command.php:148
PHP   5. PHPUnit_TextUI_Command->handleBootstrap() /usr/share/php/PHPUnit/TextUI/Command.php:650
PHP   6. PHPUnit_Util_Fileloader::checkAndLoad() /usr/share/php/PHPUnit/TextUI/Command.php:814
PHP   7. PHPUnit_Util_Fileloader::load() /usr/share/php/PHPUnit/Util/Fileloader.php:77
PHP   8. include_once() /usr/share/php/PHPUnit/Util/Fileloader.php:93
PHP   9. copy() /path/to/PrivateBin/tst/Bootstrap.php:18
PHP Warning:  require(../vendor/autoload.php): failed to open stream: No such file or directory in /path/to/PrivateBin/tst/Bootstrap.php on line 21
PHP Stack trace:
PHP   1. {main}() /usr/bin/phpunit:0
PHP   2. PHPUnit_TextUI_Command::main() /usr/bin/phpunit:42
PHP   3. PHPUnit_TextUI_Command->run() /usr/share/php/PHPUnit/TextUI/Command.php:138
PHP   4. PHPUnit_TextUI_Command->handleArguments() /usr/share/php/PHPUnit/TextUI/Command.php:148
PHP   5. PHPUnit_TextUI_Command->handleBootstrap() /usr/share/php/PHPUnit/TextUI/Command.php:650
PHP   6. PHPUnit_Util_Fileloader::checkAndLoad() /usr/share/php/PHPUnit/TextUI/Command.php:814
PHP   7. PHPUnit_Util_Fileloader::load() /usr/share/php/PHPUnit/Util/Fileloader.php:77
PHP   8. include_once() /usr/share/php/PHPUnit/Util/Fileloader.php:93
PHP Fatal error:  require(): Failed opening required '../vendor/autoload.php' (include_path='.:/usr/share/php:/usr/share/pear') in /path/to/PrivateBin/tst/Bootstrap.php on line 21
PHP Stack trace:
PHP   1. {main}() /usr/bin/phpunit:0
PHP   2. PHPUnit_TextUI_Command::main() /usr/bin/phpunit:42
PHP   3. PHPUnit_TextUI_Command->run() /usr/share/php/PHPUnit/TextUI/Command.php:138
PHP   4. PHPUnit_TextUI_Command->handleArguments() /usr/share/php/PHPUnit/TextUI/Command.php:148
PHP   5. PHPUnit_TextUI_Command->handleBootstrap() /usr/share/php/PHPUnit/TextUI/Command.php:650
PHP   6. PHPUnit_Util_Fileloader::checkAndLoad() /usr/share/php/PHPUnit/TextUI/Command.php:814
PHP   7. PHPUnit_Util_Fileloader::load() /usr/share/php/PHPUnit/Util/Fileloader.php:77
PHP   8. include_once() /usr/share/php/PHPUnit/Util/Fileloader.php:93
```

Absolute paths are of course no option. But anyway this issue is not that bad. One only has to know to cd into the tst dir and execute the tests there.

**Comment by elrido** [comment]
I explained in my previous comment why simply using the -c option won't work (it would require absolute paths, which I agree is no realistic option).

Regarding "one has to know": That's why its documented in `tst/README.md`, RTFM :wink:

**Comment by rugk** [comment]
(now I understand that XML there)
:joy: Yeah, I think this issue is not so serious to care about it. Maybe we'll leave this open to contributors.

**Comment by elrido** [comment]
I'll close this for now. Maybe a future phpunit release offers a solution for that.
