### ISSUE TITLE
Bootstrap(5) and footer feedback (textarea height)

### ISSUE THREAD

**Issue by Ilav1** [PrivateBin/PrivateBin#1349]
**Did you use the FAQ section?**
- [x] Yes, I have read [the FAQ](https://github.com/PrivateBin/PrivateBin/wiki/FAQ) and I found no solution/answer there.

## Steps to reproduce

1. Open PrivateBin on small display (not mobile phone)

### What happens

The input is bigger than the screen with bootstrap5 theme. You can`t see the footer anymore.
When you open a link, the footer is directly under the message. When you have small messages the footer is much bigger than the message itself.

### What should happen

The input field should be scaled to the display and should not be bigger than the screen when loading PrivateBin.
The footer should be fixed on the bottom.

On mobile phones it doesn´t make sense to fix the footer. It only should be fixed on desktop versions.

## Additional information

In the screenshoot you can see the input is much bigger than the screen with bootstrap5 tpl.

![grafik](https://github.com/PrivateBin/PrivateBin/assets/102852954/e2f5d9d3-10e9-4aba-990d-4c98fcacbefd)

![grafik](https://github.com/PrivateBin/PrivateBin/assets/102852954/dda348e3-e035-4fa9-af30-2a147281e258)

![grafik](https://github.com/PrivateBin/PrivateBin/assets/102852954/4ab84502-b32a-4f07-b06e-62c2d711faec)

![grafik](https://github.com/PrivateBin/PrivateBin/assets/102852954/c0c2cc7e-bac3-4aae-a6d6-0ebd408fe590)

## Basic information

**PrivateBin version:** 1.7.3

I can reproduce this issue on <https://privatebin.net>: Yes / No
Yes and No (bootstrap 5 is not used)

**Comment by elrido** [comment]
Thanks for the reminder! We had [discussed this in another issue](https://github.com/PrivateBin/PrivateBin/issues/1317#issuecomment-2121743386), but I forgot to open a new/separate issue and lost track of it. My notes from there, on this subject, were:

> Reg. the textarea height, we seem to have gotten some tools in bootstrap 5.3 that help with sizing relative to the viewport: https://getbootstrap.com/docs/5.3/utilities/sizing/#relative-to-the-viewport - we probably needed something like 75% or 80% or such and maybe only set these for larger screen heights? Anyhow we should probably move that into a new issue. [...]
