### ISSUE TITLE
Wrong translation for Norwegian popup

### ISSUE THREAD

**Issue by awisur** [PrivateBin/PrivateBin#1351]
The popup information in Norwegian for "This secret message can only be displayed once....." is wrong and gives no meaning.

Right now the Norwegian message translates to this: "Burning after reading pasta can only be displayed while loading. Do you want to see it now?"

**A way better translation would be:**

- _Denne hemmelige meldingen kan bare vises én gang. Vil du se den nå?_

**Comment by elrido** [comment]
Thank you for reporting this. You can find the [full guide on translating PrivateBin in the wiki](https://github.com/PrivateBin/PrivateBin/wiki/Translation), but the shortest version is to just use the [Crowdin](https://crowdin.com/project/privatebin) webinterface (with your Github account to sign in) to change what messages need improvements. This will behind the scene manage the file changes, raise a merge request, etc.

I'll submit your above change there, but please, if you have a moment to spare, have a look on there if you can spot any other dodgy Norwegian translations and help us improve them.
