### ISSUE TITLE
BS5 light-mode as source is hard to read

### ISSUE THREAD

**Issue by HLeithner** [PrivateBin/PrivateBin#1354]
**Did you use the FAQ section?**
- [X] Yes, I have read [the FAQ](https://github.com/PrivateBin/PrivateBin/wiki/FAQ) and I found no solution/answer there.

using the source highlighting view type makes it impossible to read the text in light mode with Bootstrap 5 

## Steps to reproduce

1. Create an note with type source
2. activate light mode with bootstrap 5

### What happens
First line not visible

### What should happen
Better colors

## Additional information
![image](https://github.com/PrivateBin/PrivateBin/assets/1497730/7bbdbfb6-d9ee-418c-94d7-b1f15a0f52b4)

## Basic information

**Server address**: https://privatebin.at

**Browser:** Vivaldi

**PrivateBin version:** 1.7.3

I can reproduce this issue on <https://privatebin.net>: No

**Comment by elrido** [comment]
I've not been able to reproduce this, except if I set the syntaxhighlighting theme to "sons-of-obsidian" / uncomment this option: 
https://github.com/PrivateBin/PrivateBin/blob/d190507fbe3d137c20a08d92d7950d76ba38223a/cfg/conf.sample.php#L39-L40

Did you maybe migrate from a configuration with darkstrap theme that required setting this? You now can un-set this property or set it to a version that matches the light mode of bootstrap5 - when switching to dark-mode it will switch it to "sons-of-obsidian" + some bootstrap5 tweaks.
