### ISSUE TITLE
Change separator # by another character

### ISSUE THREAD

**Issue by funkyremi** [PrivateBin/PrivateBin#1358]
## The problem

I need a way to change the delimiter in url # by another character

## The solution

I tried to change the line 85 and line 4882 of privatebin.js with @ but the generated link don't work. Could you please tell me which other files needs to be changed to allow this?

**Comment by funkyremi** [comment]
Actually it would send the decryption key to the server so forget about this one.

**Comment by rugk** [comment]
Yes, exactly that's the reason this is conceptually not possible.
