### ISSUE TITLE
pgsql: crash when serice account do not have SELECT right on `pg_catalog.pg_user`

### ISSUE THREAD

**Issue by Lowaiz** [PrivateBin/PrivateBin#1361]
**Did you use the FAQ section?**
- [x] Yes, I have read [the FAQ](https://github.com/PrivateBin/PrivateBin/wiki/FAQ) and I found no solution/answer there.

When using `pgsql` database as storage for pastes, if the account used for the connection do not have the right to `SELECT` on `pg_catalog.pg_user` table, the creation of a paste (and maybe the reading of one, but I didn't have a link to try) triggers a crash.

The crash log: `PDOException: SQLSTATE[42501]: Insufficient privilege: 7 ERROR:  permission denied for view pg_user in /srv/lib/Data/Database.php:98`.

This is linked to the query defined here: https://github.com/PrivateBin/PrivateBin/blob/master/lib/Data/Database.php#L600

Query added 12 year ago here:
https://github.com/PrivateBin/PrivateBin/commit/421e6cba97d079e0206042dbf8daef1fcbfc4b63

Maybe there is a another or newer way to do this table list, without the cited right. 

## Steps to reproduce

1.  Use an pgsql config with an account without `SELECT` right on `pg_catalog.pg_user` table
2.  Try to create a paste.

### What happens

Crash.

### What should happen

No Crash

## Basic information

**Server address**: N/A

**Server OS:** N/A

**Webserver:** N/A

**Browser:** N/A

**PrivateBin version:** 1.6.2

I can reproduce this issue on <https://privatebin.net>: No, only affects self-hosted.

**Comment by elrido** [comment]
Not a PG expert, sorry. If any are around here, your input would be appreciated. Searching around the net, the following query is mentioned several times: `SELECT * FROM pg_catalog.pg_tables WHERE schemaname != 'pg_catalog' AND schemaname != 'information_schema'`. Does this work on your system with the limited permissions and list the same tables as the current query (with elevated permissions)?

AFAIK the original query was lifted from the Zend Framework 1.0 sources.

**Comment by Lowaiz** [comment]
The number of results are the same between the 2 queries, just the old one return only the table names.

Your query works with the unprivileged user, a  `SELECT tablename` and it will be almost the same result as the old one; only the name of the result column will change from `table_name` to `tablename` compared to the old query (and maybe the order of the results, but shouldn't be a blocking thing).

Anyway, thanks for the reactivity!

**Comment by elrido** [comment]
Ok, so the suggested improvement would be to run `SELECT tablename FROM pg_catalog.pg_tables WHERE schemaname != 'pg_catalog' AND schemaname != 'information_schema'` instead of the current, complex `UNION` query.

Anyone of the other maintainers opposed to that? @rugk @cryptomilk @r4sas ?
