### ISSUE TITLE
Icons not showing on Firefox when using bootstrap5

### ISSUE THREAD

**Issue by eirikff** [PrivateBin/PrivateBin#1362]
**Did you use the FAQ section?**
- [x] Yes, I have read [the FAQ](https://github.com/PrivateBin/PrivateBin/wiki/FAQ) and I found no solution/answer there.

## Steps to reproduce

1. Use the bootstrap5 template
2. Open the privatebin page using Firefox

### What happens

The icons for all the buttons are not showing correctly on Firefox. I've tested it on Firefox 127 on Windows and Firefox 127 on MacOS, and both doesn't show the icons. Light or dark theme doesn't affect the icons, they don't appear in either of the color themes. I haven't tested it with other Firefox versions. 

### What should happen

The icons should appear on all the buttons on Firefox. In Edge on Windows and Safari on Mac OS, the icons appears as expected. For the other bootstrap templates, the icons work as expected. 

## Additional information

In Firefox:

![image](https://github.com/PrivateBin/PrivateBin/assets/1403257/6e8376bb-e41f-4912-995d-9d01424d37c2)

In Edge:

![image](https://github.com/PrivateBin/PrivateBin/assets/1403257/29611a68-0724-4718-aa3c-52b08343c405)

In Firefox dev tools, this is code for the fire icon: 

![image](https://github.com/PrivateBin/PrivateBin/assets/1403257/e912ac00-be81-4421-8481-0d8279153be6)

The `img/bootstrap-icons.svg` file does exist and can be opened in my browser, and all the icons are defined when I inspect the source. 

## Basic information

**Server address**: 

**Server OS:** Ubuntu Server 24.04 running microk8s 

**Webserver:** Using docker image `privatebin/nginx-fpm-alpine:stable` at time of writing (2024-06-25).

**Browser:** Firefox 127

**PrivateBin version:** 1.7.3

I can reproduce this issue on <https://privatebin.net>: No (since it doesn't use bootstrap5)

**Comment by elrido** [comment]
That sounds like the CSP-related issue that we pointed out in the release notes and documented in the config file:
https://github.com/PrivateBin/PrivateBin/blob/0eae149474252d228af70b280fb1bd722e0fc499/cfg/conf.sample.php#L98-L99

Once we switch to bootstrap5 by default (hopefully by the end of this year or so), we can make this change the default for the CSP, but at the moment it would be an unnecessary relaxation for the bootstrap(3) and page ones.

**Comment by eirikff** [comment]
Yep, you're right! Thank you! Sorry I didn't read the documentation well enough, I should have caught that.
