### ISSUE TITLE
Unable to customise the expiration times except the default ones

### ISSUE THREAD

**Issue by balajinbabu** [PrivateBin/PrivateBin#1369]
**Did you use the FAQ section?**
- [ ] Yes, I have read [the FAQ](https://github.com/PrivateBin/PrivateBin/wiki/FAQ) and I found no solution/answer there.

## Steps to reproduce

1. using the below line of code by setting the expiration to 3days
privatebinapi.send(self.base_url, text=text, expiration="3days") 

### What happens

Unable to customise the expiration times except the default ones. (#expiration must be in ('5min', '10min', '1hour', '1day', '1week', '1month', '1year', 'never'). We have an option to set 3 days from the console. whereas, if we set 3days in the below code, Its not allowing and throwing errors.

  def pb_url(self, text):
    pb_send = privatebinapi.send(self.base_url, text=text, expiration="1day") 
    return pb_send["full_url"]

Errors:

    raise BadExpirationTimeError('expiration %s must be in %s' % (repr(expiration), EXPIRATION_TIMES))
privatebinapi.exceptions.BadExpirationTimeError: expiration '3days' must be in ('5min', '10min', '1hour', '1day', '1week', '1month', '1year', 'never')

### What should happen

-- If i am able to set the expiration to 3 days from the console then the script should work with 3 days as well.

## Basic information

Linux

NA

NA

Name: PrivateBinAPI
Version: 1.0.1
Summary: A wrapper for the PrivateBin API
Home-page: https://github.com/Pioverpie/privatebin-api/
Author: Pioverpie
Author-email: 
License: 
Location: /Users/balajibabun/upwork/lib/python3.9/site-packages
Requires: httpx, PBinCLI, requests
Required-by: 

I can reproduce this issue on <https://privatebin.net>: Yes / No 
we have our own privatebin URL within our network and using it

**Comment by elrido** [comment]
Please raise this with the relevant third-party project in https://github.com/Pioverpie/privatebin-api/issues - this is not maintained by us. PrivateBin itself lets server admins configure different expiration times, but that is a per instance setting, so not all instances will allow sending arbitrary values.

Finally, note that the configuration should be called "3day", not in plural. See also the other samples:
https://github.com/PrivateBin/PrivateBin/blob/f6626405540a762166776740bf4f305f6b0051ca/cfg/conf.sample.php#L132-L143

**Comment by rugk** [comment]
So as it seems this question has been answered and I thus close this issue. If anyone has further questions on that topic, feel free to comment here, again. Also, as said, it's a downstream issue, so please report it there.
