### ISSUE TITLE
Message not shown when attachment is present

### ISSUE THREAD

**Issue by bugnumber9** [PrivateBin/PrivateBin#1385]
**Did you use the FAQ section?**
- [v] Yes, I have read [the FAQ](https://github.com/PrivateBin/PrivateBin/wiki/FAQ) and I found no solution/answer there.

When creating a secret with both text and attachment, text is not shown when opening the secret.

## Steps to reproduce
1. Create a secret with text and attachment
2. Open the secret. Text is not shown, there's only a button to download it.

Sharing text only:

![image](https://github.com/user-attachments/assets/8fdea448-3f84-4467-b8b0-baf7b02e3eb4)

Sharing text with attachment:

![image](https://github.com/user-attachments/assets/34218475-94f3-48af-aa26-0299ff796308)

## Basic information

**Server OS:**
CloudLinux

**Webserver:**
LiteSpeed

**Browser:**
Chrome

**PrivateBin version:**
1.7.4

I can reproduce this issue on <https://privatebin.net>: Yes

**Comment by elrido** [comment]
I've not been able to reproduce this in the browsers at my immediate disposal (Chrome 126 / Firefox 115 esr). Could you please clarify:
- Can you reproduce this on other devices?
- Which exact Chrome version is affected?
- On the affected installations of Chrome, do you use any plugins or have internet security products installed on these devices or in the network (i.e. at a business with deep-packet-inspection networking gear)?

**Comment by bugnumber9** [comment]
Hmm, looks like this only happens in Chrome on one of my devices.
Sorry, false alarm. It works in Firefox and in Chrome on a different device.
