### ISSUE TITLE
prout

### ISSUE THREAD

**Issue by bibimagic** [PrivateBin/PrivateBin#1388]
I have a big fucking problem.
the same as a million billion people before me.
I get this message on my screen every time I try to create a new paste.
Here's the message: "Could not get paste data: server error or not responding".

The message appears when the paste is retrieved, after I've pasted the link into the web browser's address bar. When I want to display the broadcast code.

I'm behind a Ngynx reverse proxy.
I've given rights to the "privatebin" folder to the www-data user and group.

is there anyone here who can help me? 
I've been pulling my hair out over this problem for days, weeks and months.
please help my hairdresser charge me for my next haircut.

if you won't do it for me, at least do it for him!

Translated with DeepL.com (free version)

**Comment by elrido** [comment]
> Translated with DeepL.com (free version)

Please raise a ticket with that translation service - they added a lot of rude words and snotty remarks and cringy statements into your question. I'd be offended, but that would probably just feed a troll (yourself or someone else taking up the bait).

As a server administrator, I'd expect you to be able to read and understand server logs and to work out where you have misconfigured your environment. As a starting point, check the diagram at https://github.com/PrivateBin/PrivateBin/wiki/Configuration#sizelimit and validate that all these settings in your webserver and php engine are configured adequately. If you are not able to validate this or figure out how things work, consider using a container image, where these things are preconfigured for you.
