### ISSUE TITLE
fix the footer at the bottom of the screen 

### ISSUE THREAD

**Issue by Ilav1** [PrivateBin/PrivateBin#1392]
## The problem
The footer is always directly unter the text-box. When I have small messages (e.g. passwords) the footer is more dominant than the message.

## The solution
Fix the footer to the bottom of the screen. So the message is more separated and you can see small messages easier.
Maybe it only makes sense to fix the footer on big screens. On small screens like on Smartphones the footer should have a distance to the message. 

I think the best way is to put the footer on the bottom of the screen as default as long as the message is fit to the display area else the footer is fixed (on big screens) OR moves down with an offset to the messagebox.

## Additional context
On the screenshot the footer (red) should move to the green area.

![Screenshot_20240827-202345_1_1](https://github.com/user-attachments/assets/c0449c5c-91f5-47d4-a752-ec1a764099a6)

**Comment by elrido** [comment]
We might be able to solve this similarly as was done for the textarea in #1357 - maybe both elements are in the same parent tag and it could get stretched?

**Comment by Ribas160** [comment]
I think the best way is to use a flex wrapper that has a ```min-width: 100vh```. It will allow to push footer to the bottom using ```space-between``` option and will also natively increase the height as the message box gets bigger.

Example:
```
.flex-wrapper {
  display: flex;
  min-height: 100vh;
  min-height: calc(var(--vh, 1vh) * 100);
  flex-direction: column;
  justify-content: space-between;
}

```
```
<div class="flex-wrapper">
  <div class="container">The content</div>
  <div class="footer">The Footer</div>
</div>

```

Also, if just add ```min-height: 100vh``` there will be a little scroll due to the browser address bar. To prevent this I suggest calculating the viewport height via javascript and adding the value to the css as a variable.
```
let vh = window.innerHeight * 0.01;
document.documentElement.style.setProperty('--vh', `${vh}px`);
```

If you agree with this solution I can work on it.

**Comment by Ilav1** [comment]
I personally build my own footer like this:

```
.footer {
        display: flex;
        align-items: center;
        justify-content: center;
        background-color: #A4A4A4;
        color: black;
        position: fixed;
        bottom: 0px;
        padding: 2px 0px;
        width: 100%;
}
```

```
<div class="footer"> 
    <span id="footer-link">Powered by <a href="https://privatebin.org" target="_blank" rel="noopener noreferrer">P<div class="footer">o $VERSION; ?></a></span>
</div>
```

The footer is fixes at the bottom all the time. This is not a solution to original footer because I'm using a very small footer just to link to privatebin.org.

When the original footer is fixed, there is no more space left, especially on small screens like smartphones. I can't try your code at the moment, maybe someone else is able to.

**Comment by Ribas160** [comment]
@Ilav1 I uploaded the solution to my server. You can see it at [link](https://test.ribas160.ru/privatebin/).

**Comment by rugk** [comment]
Thanks for your help and proposals, if you are confident with a solution, is is also very much appreciated if you submit it directly as a PR. (Please include a screenshot for such visual changes, though.)

**Comment by Ilav1** [comment]
@Ribas160 in my opinion it looks very nice and is exactly what I was thinking of 👍 

The footer is fixed at the bottom and expand with the textare when the text is bigger than the screen.

Also on small screens (smartphone) it looks great.

@rugk I think this will improve the UX if it PR will be accepted ☺️
