### ISSUE TITLE
v1.7.4 - Cannot calculate expiration date - 3days

### ISSUE THREAD

**Issue by abacao** [PrivateBin/PrivateBin#1393]
Hello all,

I'm trying to setup new time expiration dates in the configuration file.

I would like to create a "3days" option but when I add it to the file, all seems well but after creating the note/secret, I get the error "Cannot calculate expiration date"

Awkward or not, a simple page refresh concludes the creation of the note/secret but with a different time to expire.

example of conf file:

```
[expire]
default = "3days"

[expire_options]
5min = 300
10min = 600
1hour = 3600
1day = 86400
3days = 259200
1week = 604800
```

Am i doing something wrong or there are issues?

**Comment by elrido** [comment]
Use the singular: `3day` - thats how we have it setup on the privatebin.net demo site.
