### ISSUE TITLE
Markdown Table CSS styling improvement

### ISSUE THREAD

**Issue by fnadde42** [PrivateBin/PrivateBin#140]
The HTML \<table\>s created by the Markdown to HTML converter does not use Bootstrap's table CSS. This is from [the Bootstrap docs](https://bootstrapdocs.com/v3.3.5/docs/css/#tables):

> For basic styling—light padding and only horizontal dividers—add the base class `.table` to any `<table>`. It may seem super redundant, but given the widespread use of tables for other plugins like calendars and date pickers, we've opted to isolate our custom table styles.

Without styling the tables look really shitty. Here are before and after using built-in styling.

![table-not-styled](https://cloud.githubusercontent.com/assets/1107419/20829960/c0a7b41e-b87e-11e6-9163-3eb61f6134d2.png) ![table-styled](https://cloud.githubusercontent.com/assets/1107419/20829961/c0a96994-b87e-11e6-8ef4-2d5b5e5e256d.png)

I couldn't find where Markdown was converted to HTML and send a pull request but there are two solutions as far as I can see:

1. Change the Markdown>HTML parsing formula from `<table>` to `<table class="class="table-condensed table-bordered table-hover">`.
2. Change the CSS to modify `<table>`-tag globally (which might not be a good idea) to include styling.

I have tested this with the latest version of master branch. I have the same result on https://privatebin.net/.

**Comment by elrido** [comment]
PrivateBin uses the [showdown library](https://github.com/showdownjs/showdown) for that. There are a few options that we can set, but as far as I can tell there is nothing that specific for table classes.

We probably need to add these classes using jQuery onto all table tags within the clearText-element [after it is filled](https://github.com/PrivateBin/PrivateBin/blob/3f2de319f38070bd3e8a409a099104a0940494c6/js/privatebin.js#L655) with the rendered markdown.
