### ISSUE TITLE
When "source code" is selected

### ISSUE THREAD

**Issue by klapvogn** [PrivateBin/PrivateBin#1419]
Hi,

First off I don't know if I made a wrong setting. But when I choose "Source code" as Format I get this
https://prnt.sc/ntl5sIlhM1DT

Have can I change that ?

**Comment by elrido** [comment]
This is likely a duplicate of #1359 - The solutions are:
- if you use `bootstrap-dark` or `page` templates, also configure the `syntaxhighlightingtheme` to `sons-of-obsidian` ([see wiki](https://github.com/PrivateBin/PrivateBin/wiki/Configuration#syntaxhighlightingtheme))
- or consider using the `bootstrap5` template, which switches to dark mode automatically, depending on browser settings.
