### ISSUE TITLE
Current main broken in Safari / WebKit engine (/iOS devices)

### ISSUE THREAD

**Issue by rugk** [PrivateBin/PrivateBin#1423]
**Did you use the FAQ section?**
- [x] Yes, I have read [the FAQ](https://github.com/PrivateBin/PrivateBin/wiki/FAQ) and I found no solution/answer there.

## Steps to reproduce

Load a dev version in/on iOS/Safari/any WebKit browser. In my case, I used GNOME Web (epiphany).

### What happens
![image](https://github.com/user-attachments/assets/7a225357-8f2a-43ed-b81c-6524226afc04)

Loading message does not go away.

### What should happen
Loading as usual.

## Additional information

Log:
```
[Error] Unrecognized Content-Security-Policy directive 'manifest-src'.

[Error] Unrecognized Content-Security-Policy directive 'manifest-src'.

[Error] Error: Bootstrap's JavaScript requires jQuery
	Global Code (bootstrap-3.4.1.js:6:89)
[Error] ReferenceError: Can't find variable: jQuery
	Global Code (privatebin.js:15)
```

Originally reported in https://github.com/orgs/PrivateBin/discussions/1405, thanks to @HBubli

## Basic information

**Server address**: https://obscure-parakeet-g44wvxv9pww2wwp5-8080.app.github.dev/ (dev codespace, may go down soon)

**Server OS:** N/A

**Webserver:** N/A

**Browser:** GNOME Web 

**PrivateBin version:** 702831ea38199ad19884b758faade176bae1f959

I can reproduce this issue on <https://privatebin.net>: No as "stable"

**Comment by rugk** [comment]
Same with `bootstrap5` theme:
```
[Error] Unrecognized Content-Security-Policy directive 'manifest-src'.

[Error] Unrecognized Content-Security-Policy directive 'manifest-src'.

[Error] ReferenceError: Can't find variable: RawDeflate
	Global Code (privatebin.js:5673)
[Warning] jQuery.Deferred exception: undefined is not an object (evaluating '$.PrivateBin.Controller') (2) (jquery-3.7.1.js, line 2)
(anonymous function) — privatebin.js:41
e — jquery-3.7.1.js:2:27034
(anonymous function) — jquery-3.7.1.js:2:27332
undefined
[Error] TypeError: undefined is not an object (evaluating '$.PrivateBin.Controller')
	(anonymous function) (jquery-3.7.1.js:2:28768)
```

![image](https://github.com/user-attachments/assets/1b19755c-9c22-43fd-827d-17020469bfc9)

**Comment by rugk** [comment]
@elrido okay, tested your idea that [`defer` could be the problem](https://github.com/orgs/PrivateBin/discussions/1405#discussioncomment-10770768), but it did not work out hmm… removed all `defer`, but it still does not load.

Also, after all, `defer` is of course supported by Safari…
https://caniuse.com/script-defer

**Comment by rugk** [comment]
Okay even moving these scripts to the bottom of the HTML does not work (they then load in Firefox, but not WebKit):
```diff
diff --git a/tpl/bootstrap5.php b/tpl/bootstrap5.php
index f3bfe55f..a6ad1b1f 100644
--- a/tpl/bootstrap5.php
+++ b/tpl/bootstrap5.php
@@ -25,7 +25,6 @@ if ($SYNTAXHIGHLIGHTING) :
 endif;
 ?>
 		<noscript><link type="text/css" rel="stylesheet" href="css/noscript.css" /></noscript>
-		<?php $this->_scriptTag('js/jquery-3.7.1.js', 'defer'); ?>
 <?php
 if ($QRCODE) :
 ?>
@@ -57,7 +56,6 @@ endif;
 ?>
 		<?php $this->_scriptTag('js/purify-3.1.6.js', 'async'); ?>
 		<?php $this->_scriptTag('js/legacy.js', 'async'); ?>
-		<?php $this->_scriptTag('js/privatebin.js', 'defer'); ?>
 		<!-- icon -->
 		<link rel="apple-touch-icon" href="<?php echo I18n::encode($BASEPATH); ?>img/apple-touch-icon.png" sizes="180x180" />
 		<link rel="icon" type="image/png" href="img/favicon-32x32.png" sizes="32x32" />
@@ -499,4 +497,6 @@ if ($FILEUPLOAD) :
 endif;
 ?>
 	</body>
+	<?php $this->_scriptTag('js/jquery-3.7.1.js', 'defer'); ?>
+	<?php $this->_scriptTag('js/privatebin.js', 'defer'); ?>
 </html>
```

**Comment by rugk** [comment]
Okay tried `git bisect` just to be sure, and after some steps – no surprise – it ends at the defer/async commit 8b3b16be4442ba2415c67c02336ac8b8078a872b from 

```git
8b3b16be4442ba2415c67c02336ac8b8078a872b is the first bad commit
commit 8b3b16be4442ba2415c67c02336ac8b8078a872b (HEAD)
Author: El RIDO <elrido@gmx.net>
Date:   Sun Jul 7 16:36:52 2024 +0200

    SRI hashes are now configurable, no longer hardcoded in templates
    
    - addresses #1365
    - should make upgrades easier for those using custom templates
    - if the JS files got customized, the default SRI hashes can be replaced in the conf.php file, added commented section in conf.sample.php

 CHANGELOG.md          |  1 +
 cfg/conf.sample.php   |  6 ++++++
 lib/Configuration.php | 17 +++++++++++++++++
 lib/Controller.php    |  1 +
 lib/View.php          | 18 ++++++++++++++++++
 tpl/bootstrap.php     | 24 ++++++++++++------------
 tpl/bootstrap5.php    | 26 +++++++++++++-------------
 tpl/page.php          | 22 +++++++++++-----------
 tst/Bootstrap.php     | 41 +++++++++++++++--------------------------
 tst/ViewTest.php      |  1 +
 10 files changed, 95 insertions(+), 62 deletions(-)
 ```

**Comment by rugk** [comment]
It's also both templates, I am bit lost on what could be the problem here. 

A potential bug I've noticed:
* jquery was changed to async loading for bootstrap, but to defer loading for bootstrap5… that is inconsistent though changing it to either did not make a difference hmm…

**Comment by rugk** [comment]
Also when debugging the PrivateBin Js seems to be executed (as confirmed by the console output), just cannot find sth.?
![image](https://github.com/user-attachments/assets/ad00586f-581d-4e14-a2ed-c739345c40e5)

It's this as mentioned before:
```
jQuery.Deferred exception: undefined is not an object (evaluating '$.PrivateBin.Controller') (2) (jquery-3.7.1.js, line 2)
(anonymous function) — privatebin.js:41
e — jquery-3.7.1.js:2:27034
(anonymous function) — jquery-3.7.1.js:2:27332
undefined
[Error] TypeError: undefined is not an object (evaluating '$.PrivateBin.Controller')
	(anonymous function) (jquery-3.7.1.js:2:28768)
```

And as it can be seen, no, jQuery **is** loaded, too:
![image](https://github.com/user-attachments/assets/d9637c58-24e1-44c1-87c0-b1b32bc56d39)

It just cannot find `.PrivateBin`…

**Comment by rugk** [comment]
## sidenote bug to be fixed

Also whut is this… if I try to use the SRI settings and change them I get a PHP error at a totally different position:
```diff
diff --git a/cfg/conf.sample.php b/cfg/conf.sample.php
index f91c5e89..556edae4 100644
--- a/cfg/conf.sample.php
+++ b/cfg/conf.sample.php
@@ -259,7 +259,7 @@ dir = PATH "data"
 ;version = "latest"
 ;bucket = "my-bucket"
 
-[yourls]
+;[yourls]
 ; When using YOURLS as a "urlshortener" config item:
 ; - By default, "urlshortener" will point to the YOURLS API URL, with or without
 ;   credentials, and will be visible in public on the PrivateBin web page.
@@ -276,8 +276,9 @@ dir = PATH "data"
 ; (optional) the URL of the YOURLS API, called to shorten a PrivateBin URL
 ; apiurl = "https://yourls.example.com/yourls-api.php"
 
-;[sri]
+[sri]
 ; Subresource integrity (SRI) hashes used in template files. Uncomment and set
 ; these for all js files used. See:
 ; https://github.com/PrivateBin/PrivateBin/wiki/FAQ#user-content-how-to-make-privatebin-work-when-i-have-changed-some-javascript-files
 ;privatebin.js = sha512-[…]
+privatebin.js = sha512-SMhfLnN5b0py35etH7Gsk7NmxlQN26K9cKvl68ngJAkLKnJO0VimKVnnq85T1iPPk10Fn+8LmDqV6yt0z7WV5A==
```

```

Warning: syntax error, unexpected '=' in cfg/conf.php on line 284 in /workspaces/PrivateBin/lib/Configuration.php on line 136

Fatal error: Uncaught TypeError: array_key_exists(): Argument #2 ($array) must be of type array, false given in /workspaces/PrivateBin/lib/Configuration.php:138 Stack trace: #0 /workspaces/PrivateBin/lib/Configuration.php(138): array_key_exists('main', false) #1 /workspaces/PrivateBin/lib/Controller.php(169): PrivateBin\Configuration->__construct() #2 /workspaces/PrivateBin/lib/Controller.php(122): PrivateBin\Controller->_init() #3 /workspaces/PrivateBin/index.php(17): PrivateBin\Controller->__construct() #4 {main} thrown in /workspaces/PrivateBin/lib/Configuration.php on line 138
```

The quoted lines are about expire options I mean what?
The error goes away when I comment in the line again:
```ini
;privatebin.js = sha512-SMhfLnN5b0py35etH7Gsk7NmxlQN26K9cKvl68ngJAkLKnJO0VimKVnnq85T1iPPk10Fn+8LmDqV6yt0z7WV5A==
```

**Edit:** Ah it was bad doc. The "quotation marks" were missing…

**Comment by rugk** [comment]
Okay no the SRI feature does not work… I now quoted it, but it does not change the default SRI hash:
![image](https://github.com/user-attachments/assets/18bbf44a-2aa9-4c4c-9b44-5993c03ba59f)


![image](https://github.com/user-attachments/assets/bc09120e-864d-47c3-8c15-5fec296d4b1e)


Okay I'll give up this side-bug… needs tom be looked into, but uff…

I now just relace the PHP thing with HTML code… for testing…

**Comment by rugk** [comment]
https://github.com/PrivateBin/PrivateBin/pull/1424/commits/eabf763c41d08df92f0b0e9a090fe2bdbae561f6 seems to have "fixed" the issue of PrivateBin not being registered for jQuery, but now the second error stays:
![image](https://github.com/user-attachments/assets/b1a041cd-194f-4b0c-b7c5-f3907d767015)
```
[Error] ReferenceError: Can't find variable: RawDeflate
	Global Code (privatebin.js:5666)
```

**Comment by rugk** [comment]
Okay, I needed to (defer/non-asyncronously load) some libs, not only jquery, but also base and deflate, see https://github.com/PrivateBin/PrivateBin/pull/1424/commits/64ed6e96ee7132cb111268cc9fe4d8540d37f588

I still ponder over this, but really… not an issue for today.

Also, found another bug (maybe related or not?) – the dark mode (slider) does not work, it's always light mode. Yes, even when manually toggling it.

**Comment by rugk** [comment]
I now unassign zthis, if you want to continue tinkeling @elrido, feel free… I also looked whether a codespace can be shared to some other person, but apparently, it cannot hmm?

**Comment by rugk** [comment]
OKay it seems the suggested way is just use the life share extension: https://docs.github.com/de/codespaces/developing-in-a-codespace/working-collaboratively-in-a-codespace

I'll send you the link, though, okay, it's not much different and when I open it it's buggy so hmm. You likely can just commit as me then oh no :see_no_evil: 

Maybe you just develop it as usual and use the branch.

**Comment by elrido** [comment]
Yeah, sorry, the github stuff doesn't cut it for me. Let's just use a branch as usual, then I can use my preferred tools and editors.
