### ISSUE TITLE
Use composer.lock file for development

### ISSUE THREAD

**Issue by rugk** [PrivateBin/PrivateBin#1428]
## The problem

Composer always complains about missing `composer.lock` file. I guess it's like `package-lock.json` for npm.

See https://getcomposer.org/doc/01-basic-usage.md#installing-dependencies why they want it. Otherwise you e.g. cannot ensure the installed version of composer is always the same. At each install it updates to the latest one, potentially:
```
$ composer install -n
No composer.lock file present. Updating dependencies to latest instead of installing from lock file. See https://getcomposer.org/install for more information.
```

## The solution

Run the compßoser init command there and commit the lock file. As far as I see, that's it. The CI should use it automatically…

## Alternatives

We could also pin the version very fixed in the composer file, but really then we miss good update options.

**Comment by elrido** [comment]
I'm confused - we do have a composer.lock file committed, AFAIK:
https://github.com/PrivateBin/PrivateBin/blob/b31bb4f4e2f960dfa4beadb7ebdcabed5c3bee21/composer.lock#L1-L6

**Comment by rugk** [comment]
Okay uhm sorry, to be sure I tried to reproduce it and installing via composer does not yield this message. No idea, how I got the message :see_no_evil:  (Maybe I just ran the command while being in a different directory?)

Anyway, solved for my own's stupidity :sweat_smile:
