### ISSUE TITLE
Is privatebin affiliated with a brewery?

### ISSUE THREAD

**Issue by nain-F49FF806** [PrivateBin/PrivateBin#1436]
**Did you use the FAQ section?**
- [x] Yes, I have read [the FAQ](https://github.com/PrivateBin/PrivateBin/wiki/FAQ) and I found no solution/answer there.

## Steps to reproduce

1. Visit https://github.com/PrivateBin/PrivateBin/wiki/Experience-at-Northshire

### What happens

You see a page about a brewery 

### What should happen

Pages on privatebin wiki should probably talk about privatebin

If the page is intended, no worries. Seemed fishy though

**Comment by elrido** [comment]
Thanks for reporting this vandalism. I removed the wiki page and blocked and reported the user that did it. From their history it seems they also vandalized other projects such as vim. :-(

PrivateBin does not get any financial sponsorships (would require an org and someone managing and documenting the use of such funds), but we do get services sponsored for free, such as this git project management on GitHub, various CI/CD jobs running on GitHub, Scrutinizer, StyleCI, Snyk and others, container image hosting on DockerHub and GitHub and browser testing via BrowserStack (see also the [badges doc](https://github.com/PrivateBin/PrivateBin/blob/master/BADGES.md)).

**Comment by nain-F49FF806** [comment]
@elrido Another page that may be unintended: https://github.com/PrivateBin/PrivateBin/wiki/File

**Comment by rugk** [comment]
Thanks, deleted. Though not with bad intent, likely someone posted their config file there.
