### ISSUE TITLE
Incorrect parsing i18n ru translation

### ISSUE THREAD

**Issue by r4sas** [PrivateBin/PrivateBin#145]
Hi. I trying write russian translation.
When I added plural formule to lib\i18n.php and started testing translation, I saw that Expires field used incorrect variant of translation.

I added
```
case 'ru':
    return $n % 10==1 && $n % 100 != 11 ? 0 : $n % 10 >= 2 && $n % 10 <= 4 && ($n % 100 < 10 || $n % 100 >= 20) ? 1 : 2;
```
in lib\i18n.php and my translation, where I see problem (one of all)
`"%d minutes": ["%d минуту", "%d минуты", "%d минут"],`
Example options of [expire_options] is 
```
1min = 60
3min = 180
10min = 600
21min = 1260
```
What i must see with translation
----
> 1 минуту
> 3 минуты
> 10 минут
> 21 минуту

What I really watching:
----

> 1 минут
> 3 минуты
> 10 минут
> 21 минут

Any ideas?

**Comment by elrido** [comment]
Just to check some basics first: I assume you added the formula to both [lib/i18n.php](https://github.com/PrivateBin/PrivateBin/blob/master/lib/I18n.php#L294) and in [js/privatebin.js](https://github.com/PrivateBin/PrivateBin/blob/master/js/privatebin.js#L409), right?

**Comment by r4sas** [comment]
@elrido yup, I added it in both places.

**Comment by rugk** [comment]
A PR is always very much appreciated.

**Comment by r4sas** [comment]
@rugk https://github.com/PrivateBin/PrivateBin/pull/146

**Comment by elrido** [comment]
Ok, spotted the problem. Please use this formula instead (note the additional brackets):

  return $n % 10==1 && $n % 100 != 11 ? 0 : **(**$n % 10 >= 2 && $n % 10 <= 4 && ($n % 100 < 10 || $n % 100 >= 20) ? 1 : 2**)**;

**Comment by r4sas** [comment]
@elrido ok, I'll try it.

**Comment by r4sas** [comment]
One more problem:
```
"Your paste is <a id=\"pasteurl\" href=\"%s\">%s</a> <span id=\"copyhint\">(Hit [Ctrl]+[c] to copy)</span>":
    "Ссылка на запись <a id=\"pasteurl\" href=\"%s\">%s</a> <span id=\"copyhint\">(Нажмите [Ctrl]+[c] чтобы скопировать ссылку)</span>",
```
Not translated, "Delete data" link too.

**Comment by elrido** [comment]
FYI: When merging you translation I added a unit test for this exact problem, so it won't be reintroduced down the line.

As the polish translation is similarly complex, I added a similar test case there, too. This lead to the discovery of a similar problem and some errors in the translation file. These are now fixed, too, all thanks to your issue report. :smiley:

**Comment by r4sas** [comment]
You're welcome ;)
