### ISSUE TITLE
Bin is not loading properly 

### ISSUE THREAD

**Issue by SREshalin** [PrivateBin/PrivateBin#1459]
**Did you use the FAQ section?**
- [ ] Yes, I have read [the FAQ](https://github.com/PrivateBin/PrivateBin/wiki/FAQ) and I found no solution/answer there.

## Steps to reproduce

1. Open bin in browser which as some pre installed plugins 

### What happens
Bin is not loading properly, it needs to be refreshed manually.

### What should happen
Bin should load properly

## Basic information

**Server address**:

**Server OS:**

**Webserver:**

Google Chrome (Version 131.0.6778.70 (Official Build) (x86_64)) 

**PrivateBin version:**

PrivateBin 1.7.4 
I can reproduce this issue on <https://privatebin.net>: Yes

**Comment by SREshalin** [comment]
<img width="1792" alt="Screenshot 2024-11-19 at 1 38 14 PM" src="https://github.com/user-attachments/assets/d7f6342b-9dcb-44ef-8476-20c074843257">

**Comment by elrido** [comment]
Not reproducible on privatebin.net with the browser mentioned, outdated version and not enough information given in the template. Sorry, I have to close this.

If you could update the issue template with the requested information and re-test this on the latest release (1.7.5) and still reproduce this on several devices, do re-open it, though.
