### ISSUE TITLE
Add HTTP header for detecting PrivateBin

### ISSUE THREAD

**Issue by rugk** [PrivateBin/PrivateBin#147]
Required for https://github.com/PrivateBin/WebExtension/issues/5

Should we also add the version there?

Example HTTP header:
```
PrivateBin: 1.0
```
(AFAIK the `X-` headers are depreciated)

**Comment by elrido** [comment]
Well you can get the version by looking at the version number in the GET parameter[ appended after zerobin.js or privatebin.js](https://github.com/PrivateBin/PrivateBin/blob/master/tpl/bootstrap.php#L14) (yes, this even works for the original ZeroBin releases).

**Comment by rugk** [comment]
Yes, but anyway we can also send the version there. (I have no other idea what other useful information we could send there)

**Comment by elrido** [comment]
What is your use case for this feature request?

**Comment by rugk** [comment]
And as I don't think we should continue this PrivateBin browser extension, I'd say this issue is obsolete here.
