### ISSUE TITLE
'never' expiry time issues

### ISSUE THREAD

**Issue by adambh** [PrivateBin/PrivateBin#149]
## Steps to reproduce

1. Use an sqlite database
2. Upload a file with 'never' expiry date

### What happens
It gets deleted after some time.

### What should happen
It should never be deleted.

## Additional information
I have tried everything, I believe this is related to using sqlite.
I couldn't find the solution up to now.

* I can reproduce this issue on <https://privatebin.net>: No, not sure.

## Basic information

**Server address**: https://pastebin.gtanet.work

**Server OS:** Linux Ubuntu Server 16.04 LTS

**Webserver:** nginx/1.10.0

**Browser:** Any, I used Chromium (Cent Browser)

**PrivateBin version:** Release v1.0

**Comment by rugk** [comment]
So when you temporarily disable the DB connection and use the file storage, does it work?

**Comment by adambh** [comment]
I still haven't tried that, but I suppose it shouldn't be the case using file storage.

**Comment by elrido** [comment]
Thank you very much for reporting this.

I was able to write a unit test reproducing the behaviour and discovered the missing check in the database abstraction.
