### ISSUE TITLE
Strange password requests

### ISSUE THREAD

**Issue by elrido** [PrivateBin/PrivateBin#15]
@rugk:

Reproduce:
0. Download the image file attached below. (Sha256: `0b74cc841a9ab82568078b92edb5273594fd74bda0a7a324760271e7ae4675d6`)
1. Create a new ZeroBin with this file.
2. Select "one time text" and enter some text.
3. Click on "Send" and upload  the file.
4. Copy the URL and paste it into the browser.

**What happens:**
For some strange reason I'm prompted for a password, although I have not set one.

**What should happen:**
Just show me the content. :smiley: 

File: [abstract_firefox_wallpaper_by_steam10.jpg](https://cloud.githubusercontent.com/assets/11966684/15448500/a0620e48-1f63-11e6-97e4-cbc3e7e772aa.jpg)

Zerobin v0.22, using MySQL as a database

---

@elrido:

Could you let me know if your server is using Suhosin or a similar security module? What is your PHPs max_post_size setting?

I have found a system were I could reproduce this. On that system it happens independently of the backend with uploads roughly larger then 600 - 800 KiB, when only an attachment is given with an empty text. If both are given, no password is requested, the text is displayed, but the image is still missing. When I debug the $_POST it does not contain the `attachment` key although it is sent (as checked with wireshark).

I have not been able to pinpoint it definitely, but strongly suspect that Suhosin is messing with the POST variables. It offers `suhosin.request.max_value_length` and `suhosin.post.max_value_length` settings which are by default limited to 1000000. Your file is almost 900 kiB and with encryption and base64 encoding the full POST content becomes over 2 MiB, so on my system it would certainly have `max_value_length`s over 1000000. Unfortunately I have not yet been able to find a Suhosin configuration that would allow an upload on that system.

I will try to add some code that at least checks if an `attachmentname` was sent but the `attachment` is missing, so that we can display an appropriate error message to the users, like "Your file upload did not succeed, your file is too large for this servers settings". Also I should add a check in the JS logic for the configured `sizelimit` option, so we don't even bother posting too large files (base64 increases the size that is sent by 33-36%) and can again display an appropriate message.

---

@rugk:

`max_post_size` should be the default (it does not appear in my php config)

> Suhosin

AFAIK not. PHP is installed from the Debian repos.

```
PHP 5.6.20-0+deb8u1 (cli) (built: Apr 27 2016 18:21:41) 
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies
```

Webserver is nginx BTW.

> 600 - 800 KiB,

Yes, that's the size I also experienced...

> When only an attachment is given with an empty text. If both are given, no password is requested, the text is displayed, but the image is still missing. 

In my case I also tried it with both things and always had the same result (password is requested).

**Comment by rugk** [comment]
Actually I found a potential cause: When I got this error again I saw that the file of the broken Bin has a `null` as a file content.

Try creating pads with no data (or as less as possible - so one character e.g.) and you may be able to reproduce it.

I attached a data dir of such an installation with this error. The decryption link is this: http://127.0.0.1/?6e87dee1fba4a919#gAzTVXd90fCTuSOpKHF+adIzgS37vdEMPHRUKzWMx8c=

[PBdata.zip](https://github.com/PrivateBin/PrivateBin/files/412113/PBdata.zip)

**Comment by elrido** [comment]
I don't mind to handle this together with the previous point but this is certainly another issue. In the original issue the generated file contained a valid JSON, but the attachment got mangled.

I think the "null" comes from an error in the last json_encode before your paste is saved. I checked the [docs](http://php.net/manual/en/function.json-encode.php) and there are other functions to [detect errors](http://php.net/manual/en/function.json-last-error.php) and in later PHP versions even [return a human readable error message](http://php.net/manual/en/function.json-last-error-msg.php).

I will implement such a check before saving the file, so at least you get a visible error when it happens, which might help us to figure out by what inputs this can be triggered.

**Comment by elrido** [comment]
Update: Unfortunately I was unable to reproduce the issue on my side, but with commit 6cb7454d I added tests for JSON errors. It would be most interesting if you could send me any JSON error messages that get displayed if you can reproduce it with that version.

**Comment by rugk** [comment]
Unfortunately I cannot reproduce it right now too.
Maybe it has to do with the input, which was only one character when the issue happend last. Unfortunately I don't know which character it was.

**Comment by elrido** [comment]
Ok, then lets close it for now. Feel free to reopen a new issue if it happens again and you got a JSON error message so we can work around the actual problem.
