### ISSUE TITLE
Composer cleanup

### ISSUE THREAD

**Issue by PunKeel** [PrivateBin/PrivateBin#150]
Hello, 

Shouldn't you remove vendor & add a composer.lock?

Just asking, I don't really care… best practice and stuff like that. :-)

**Comment by rugk** [comment]
Yes I also discussed this with @elrido and we came to the conclusion that it is better to leave the filled there, so that anyone can use the software instantly after cloning it and it does not depend on any third-party software.

**Comment by PunKeel** [comment]
ok then

For your information, if what you want is "end" users being able to click&install PrivateBin, it is possible to ask Travis to upload "usable archives"

**Comment by rugk** [comment]
Actually you can just use the archives in the [release section](https://github.com/PrivateBin/PrivateBin/releases) or just do a `git clone` on your server.

**Comment by PunKeel** [comment]
What I meant was that Travis could upload the archive in the release section, sorry

**Comment by rugk** [comment]
I think we can do this manually. And from a security perspective we also need to do so as we want to sign the releases.
