### ISSUE TITLE
Feature : User-Agent blacklist

### ISSUE THREAD

**Issue by olivierlemoal** [PrivateBin/PrivateBin#156]
It would be wonderful to have an UA blacklist in order to prevent connections from Facebook / Skype / other preview bots to access a paste, and destroy it if "burn after reading" is used.
Some requests made by IM services when copying a link in a conversation :
```
listening on [any] 80 ...
connect to [] from (UNKNOWN) [31.13.110.111] 54202
GET / HTTP/1.1
User-Agent: facebookexternalhit/1.1 (+http://www.facebook.com/externalhit_uatext.php)
Accept: */*
Accept-Encoding: deflate, gzip
Range: bytes=0-524287
Host: [...]
Connection: close
```

```
listening on [any] 80 ...
connect to [...] from (UNKNOWN) [104.45.18.178] 1064
GET / HTTP/1.1
User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) SkypeUriPreview Preview/0.5
Host: [...]
Connection: Keep-Alive
```

**Comment by rugk** [comment]
This should rather be handled by your web server and for Apache we already offer a small [template config](https://github.com/PrivateBin/PrivateBin/blob/master/.htaccess.disabled). Of course you can easily adapt it for your own web server if you use a different one.
As for your examples Skype is already included and I also [added Facebook](https://github.com/PrivateBin/PrivateBin/commit/eb6d994672725105445fd8a655c118bb57d5ce3e) now.

**Comment by elrido** [comment]
Also note that bots deleting burn after reading pastes was fixed [way back in 2015](https://github.com/elrido/ZeroBin/issues/11) by having the deletion be triggered in JS only after a _successful_ decryption.
