### ISSUE TITLE
Hide decryption status from traffic analysis

### ISSUE THREAD

**Issue by cryptolok** [PrivateBin/PrivateBin#159]
Greetings and a happy 2\*9\*17th prime.
To prevent a traffic analysis it would be great to implement a plausible deniability.
Since if someone would record a traffic he would know if the decryption has succeeded or not (success - 2 SSL packets after the decryption, fail - none) if the burning flag was set, to notify the server to burn the message.
As for mitigation, one of my propositions is that both successful decryption and a fail should send packets to the server with a same size. Another solution is to burn the message regardless the decryption failure.
This in order to mitigate traffic analysis and prevent an attacker for proving the message consulting.
Would be a good addition to a nice project In My Hackish Opinion.

**Comment by rugk** [comment]
What you suggest is not really plausible deniability, which is a cryptographic feature/goal, but just to hide some meta data.
I'd agree that this is a good idea, however.

**Comment by cryptolok** [comment]
I called it a deniability since we can deny a message decryption.
For instance, you received a "_weird email that you opened by curiosity_", on the attacker's perspective he would not have any meaning to prove that you have decrypted the message or not, thus we can plausibly deny that the message was indeed destined to us and that we are in capacity to decrypt it.
Nevertheless, I wouldn't insist on a name because, you know your project better than me and anyway, it's better to spend some more energy on work rather than on "_philosophical_" discussions (like a "_real_" OSI layer of SSL).

**Comment by rugk** [comment]
Indeed that's it. It does hardly matter how we call it. I think we understood the concept and this is what matters here.

**Comment by cryptolok** [comment]
Em, for me the issue isn't closed completely.
You see, when specifying deletion flag and putting (or not) the password, the client still sends a POST json request with deletetoken=burnafterreading value in case of a successful data retrieval.
Since we can use time analysis (in case of a password), we can accurately predict whether the paste was decrypted on purpose or not.
In this case the action can't be denied.
As of my knowledge, a solution has been proposed in #216, but I just tested the main site and it wasn't the case.

**Comment by rugk** [comment]
Yes, https://privatebin.net/ runs a stable version of PrivateBin, so with the next release this will be updated.

**Comment by cryptolok** [comment]
Oh ok then, sorry, I didn't know.
Then the issue is closed and good job guys :)
