### ISSUE TITLE
Set Link header for server push

### ISSUE THREAD

**Issue by elrido** [PrivateBin/PrivateBin#16]
@rugk:

It would be nice if you could set link headers for pushing assets to the user. Especially the [HTTP/2 server push](https://blog.cloudflare.com/announcing-support-for-http-2-server-push-2/) is an efficient way of doing that and it really speeds up website loadings.

And you have a lot of assets, which are *always* loaded, so this is a very good scenario for HTTP/2 server push.

You can [use it with PHP](https://blog.cloudflare.com/using-http-2-server-push-with-php/).

---

@elrido:

I reviewed the links you posted, but I don't think this applies to Zerobin.

We currently only have one HTTP request that is processed by PHP, which is the call to the index.php (contains HTML and the encrypted paste and file/image). All the other resources are static images, CSS and JS-Scripts. These are cached in your browser automatically after the first load.

So even if we handle all these resources through PHP (slowing these calls down and consuming more resources server-side), it would only affect the first page load.

We would probably gain more loading performance by including fewer resources (i.e. by including all JS-Scripts and CSS into one file / using an image map instead of separate images for the classic page design). Currently we do (only when calling a given domain for the first time) 16 requests. By combining files belonging together we could reduce this to 4. The trade-off would be that the paste takes longer to render, since it can only start after the single JS has fully finished loading.

---

@rugk:

Well... This is about server push. So of course you do not have to serve the files via PHP somehow.

You just have to serve the necessary headers when the index page is requested, so that it serves the files which are likely requested afterwards. Of course these are static files, but that's exactly what matters.

And when caching works it of course speeds up the first request, but this is still important, because users may e.g. clean caches.

**Comment by elrido** [comment]
Maybe I am misunderstanding the concept of the server push. Please correct me if my assumptions below are not correct:

**Classic scenario (_no_ server push)**

1. on first visit in the given browser (or after cache clearing):
    1. Browser requests /, Server renders and delivers index.php (if a parameter was given it would include the requested paste, otherwise the data section will be empty, but the HTML will be identical)
    2. Browser parses HTML-headers and sees the included JS, CSS and the logo image and waterfalls into loading them (by separate (HTTP 1.x) or pipelined (HTTP 2) connections)
    3. Browser parses CSS and discovers it needs additional images or fonts, downloads these, too
2. on second visit:
    1. Browser requests /, Server renders and delivers index.php
    2. Browser parses HTML-headers and sees the included JS, CSS and the logo image and waterfalls into asking the server if these changed. The server will usually (as long as the install wasn't updated in between requests) reply with a short "304 Not modified" answer and no files are transferred.
    3. Browser parses CSS and discovers it needs additional images or fonts, asks the server if these changed, too. The server will usually reply with a short "304 Not modified" answer and no files are transferred.

**Scenario _with_ server push**

1. on first visit in the given browser (or after cache clearing):
    1. Browser requests /, Server renders and delivers index.php, including the server push HTTP-headers (if a parameter was given it would include the requested paste, otherwise the data section will be empty, but the HTML will be identical)
    2. Browser parses HTTP-headers and requests (by separate (HTTP 1.x) or pipelined (HTTP 2) connections) all the included JS, CSS, images and fonts (note that it is not easy to predict which fonts are really needed by the browser, so the safe option will be to send it all font formats, increasing the total download size by up to 200 KiB), then parses the HTML-headers and should find no additional included files. Hence the 
    3. Browser parses CSS and should not discover any additional images or fonts to download
2. on second visit:
    1. Browser requests /, Server renders and delivers index.php, including the server push HTTP-headers
    2. Browser parses HTTP-headers and sees the included JS, CSS, images and fonts and starts asking the server if these changed. The server will usually (as long as the install wasn't updated in between requests) reply with a short "304 Not modified" answer and no files are transferred.
    3. Browser parses CSS and should not discover any additional images or fonts to download

What this means for our project, as far as I understand it:
- Using server push we transfer more data in the first request, but have the same amount of requests with 304 replies in subsequent requests.
- Server push would allow additional content to be requested earlier in parallel or in a pipelined connection, then having to wait until the HTML-header is parsed by the browser (which is done while the download of index.php is still ongoing).
- Given that rendering and sending the index.php can take less then 25 ms, we would only see a minute gain of possibly 10 or 15 ms. This tiny gain probably will even be eaten up by the 4 additional fonts requested due to using the server push.

I do absolutely see the value of server push if the subsequent sites might contain vastly different includes then the first site (e.g.: slim homepage, complex article pages with additional media). There it makes sense to preload stuff that doesn't necessarily get requested on the first visit. But in our case there is only ever one site and we always request the same content and so the server push can't play out its potential.

**Comment by rugk** [comment]
Yes, I think your explanation is largely correct. And, yes it might not be something very valuable for PrivateBin.
