### ISSUE TITLE
CSP appears to have broken my deployment

### ISSUE THREAD

**Issue by TheFiZi** [PrivateBin/PrivateBin#166]
## Steps to reproduce
1. Ran 'git update'
2. Unable to access PrivateBin deployment. Error in my browsers console is "Content Security Policy: The page’s settings blocked the loading of a resource at self (“script-src https://paste.fizi.ca”)."

### What happens
Perpetual loading page. I do not use a CDN.

### What should happen
Pastebin should load

## Additional information
* I can reproduce this issue on <https://privatebin.net>:  No

## Basic information
**Server address**: paste.fizi.ca

**Server OS:** CentOS 6.8 64-bit

**Webserver:** Apache 2.2.15-56

**Browser:** Firefox 51 and Vivaldi 1.6.689.40

**PrivateBin version:** 1.1

My HTTP logs (temporarily enabled for troubleshooting) are attached.
[paste.fizi.ca-log.txt](https://github.com/PrivateBin/PrivateBin/files/739717/paste.fizi.ca-log.txt)

**Comment by rugk** [comment]
You've read [this FAQ entry](https://github.com/PrivateBin/PrivateBin/wiki/FAQ#why-does-not-the-loading-message-go-away)?

Also I'd like to notice you that if you run git update (or how the actual command is called: `git pull`) you do not use v1.1 of PrivateBin anymore. You use the another (more or less unstable) version from this repo. You can get the exact git commit hash = the "version" in your case) via `git rev-parse HEAD`.

I've just confirmed that 368aa2305bf551a9b8ca3c88354c0131d1a1442d is working as intended.

So are you sure you have not modified the JS files in any way?

**Comment by TheFiZi** [comment]
I did read the FAQ entry and since none of those suggestions applied I didn't dig further.

`# git rev-parse HEAD
368aa2305bf551a9b8ca3c88354c0131d1a1442d`

I do not modify any of the files provided by the repo other than the configuration file. That being said I ran the composer command in the FAQ anyway. No change.

I've added the following to my Apache vhost for the site:

`Header append Cache-Control "no-transform"`

No change.

`git fetch
git checkout 1.1`

PrivateBin is now working. I'm guessing 1.1 is before CSP was implemented.

**Comment by elrido** [comment]
Interesting is that I had this too, when I accessed your site just now. I had previously used it, so the scripts were cached in my browser. I had then done a [Ctrl]+[F5] to force a refresh of the page and now it works.

I too am using Firefox 51. At this point I haven't yet a solution to offer you apart from the above (which is not a real solution, as your visitors won't know what to do). :-( I will try to reproduce it and test it with other browsers to try and understand what the real issue is and how else it could be resolved.

**Comment by rugk** [comment]
Currently https://paste.fizi.ca/ works for me. Or are you still using the 1.1 version, @TheFiZi?

**Comment by rugk** [comment]
Also note that a CSP error is different to a SRI error. And both can add false-positive (error) messages to the console when used with add-ons.
From looking at your server it seems the CSP header is right (the default we've specified). You have not modified the CSP header, have you?

BTW: We've added support for CSP and SRI in v1.0 [already](https://github.com/PrivateBin/PrivateBin/releases/tag/1.0), so there is something wrong with the current master.

**Comment by TheFiZi** [comment]
@rugk @elrido Sorry I left it on 1.1.

I've just switched back to MASTER.

Here is my vhost config if it helps.

```
<VirtualHost *:443>
        ServerName paste.fizi.ca
        DocumentRoot /data/wwwPublic/sitePrivateBin

        #CustomLog logs/paste.fizi.ca.log combined
        #ErrorLog logs/paste.fizi.ca-error.log

        SSLEngine on
        SSLHonorCipherOrder on
        SSLProtocol all -SSLv2 -SSLv3
        SSLCipherSuite EECDH+ECDSA+AESGCM:EECDH+aRSA+AESGCM:EECDH+ECDSA+SHA384:EECDH+ECDSA+SHA256:EECDH+aRSA+SHA384:EECDH+aRSA+SHA256:EECDH+aRSA+RC4:EECDH:EDH+aRSA:RC4:!aNULL:!eNULL:!LOW:!3DES:!MD5:!EXP:!PSK:!SRP:!DSS:!RC4
        Header always set Strict-Transport-Security "max-age=63072000; includeSubDomains"
        Header append Cache-Control "no-transform"

        SSLCertificateFile /etc/httpd/conf/certs/fizi.ca.crt
        SSLCertificateKeyFile /etc/httpd/conf/certs/fizi.ca.key
        SSLCertificateChainFile /etc/httpd/conf/certs/sub.class2.server.sha2.ca.pem
        SSLCACertificateFile /etc/httpd/conf/certs/ca-sha2.pem
</VirtualHost>
```

I need to get off CentOS 6 bad :)

**Comment by rugk** [comment]
Thanks for switching. So in fact with both Firefox and Chromium I do not get any CSP or SRI errors (only one false-positive CSP error from an add-on). The scripts are also loading, but either not executed or they do not hide the Loading message…
So this is no usual SRI error here, which is the common case for this type of error.

**Comment by elrido** [comment]
Can now consistently reproduce on your site, too. Will try to recreate it on my test server.

**Comment by elrido** [comment]
I can't reproduce this behaviour with the current master. What is odd is that your server is returning the files in windows-1252 encoding, not utf-8. I wonder if this causes one of the libraries to fail and halts the execution of the scripts.

That still wouldn't explain why this only happens with the master and not release 1.1 though.

**Comment by TheFiZi** [comment]
Checked my httpd.conf file

`AddDefaultCharset UTF-8`

Also added this to my vhost:

```
<Directory /data/wwwPublic/sitePrivateBin>
      AddDefaultCharset UTF-8
</Directory>
```

No change.

**Comment by elrido** [comment]
Jupp, and I discovered something, too. I can reproduce it on zerobin-test.dssr.ch, but only when using a clean browser profile.

I see no CSP or SRI errors logged, no errors in the console at all. It simply doesn't seem to start the code. As I now have an instance that reproduces it, you can reset your server to 1.1, if you like.

**Comment by TheFiZi** [comment]
Always nice to know I'm not crazy/doing something wrong.

**Comment by elrido** [comment]
I found the reason: The initialization of the application did run prematurely. This could explain why it did not happen consistently. I bet one of the recent changes (restructuring for the unit testing or the update of the showdown library) in the JS triggered it.

I do some more testing with my patch and then commit it to master.

**Comment by TheFiZi** [comment]
Confirmed. The latest code is working on my server as well.
