### ISSUE TITLE
Should update url after saving new bin

### ISSUE THREAD

**Issue by jelhan** [PrivateBin/PrivateBin#167]
## Steps to reproduce
1. Create a new Private Bin.
2. Save it.

### What happens
Browsers URL stays the same e.g. https://privatebin.net/ aka missing `history.pushState()`.

### What should happen
Browsers URL should contain URL to newly created PrivateBin e.g. https://privatebin.net/?5909ce97a16531e0#BXRqO3gVF+q2H6IYOAiMNWta3TZbim0uqXy/6jKLPfY=

## Additional information

* I can reproduce this issue on <https://privatebin.net>: Yes

## Basic information

**Browser:**
* Firefox
* Chromium

**Comment by elrido** [comment]
If we do this, won't it cause any burn after reading pastes to be deleted immediately?

**Comment by rugk** [comment]
No (I just tested it) as we only need to modify the part after `?`, no. Of course you however cannot change the URL to a foreign one of other sites (This causes: `SecurityError: The operation is insecure.`).

**Comment by rugk** [comment]
And I'd say we [rather use](https://stackoverflow.com/questions/17507091/replacestate-vs-pushstate#answer-17507140) `replaceState()` as one cannot re-visit the response site anyway.

**Comment by jelhan** [comment]
> If we do this, won't it cause any burn after reading pastes to be deleted immediately?

If you push a new state in history, browser should not download the url. It's just about clients browser history.

> And I'd say we rather use replaceState() as one cannot re-visit the response site anyway.

I don't think user would expect this behaviour. If he creates a new bin and going back he expects to see the creation form again and not the site he has visit before. To give an example:
1. User searches in google for PrivateBin and opens privatebin.net.
2. He creates a new bin.
3. Sees his newly created bin, decides to write another one and uses browser back button therefore.

`replaceState()` would override the history step of part 2 and therefore user would be transitioned to his google search.
`pushState()` therefore would add another history step. User would be transitioned to step 2.
