### ISSUE TITLE
Use CSP sandbox

### ISSUE THREAD

**Issue by rugk** [PrivateBin/PrivateBin#168]
See https://scotthelme.co.uk/csp-cheat-sheet/#sandbox

So what do we need?
* [x] allow-forms
* [x] allow-same-origin
* [x] allow-scripts
* [x] allow-top-navigation
* [x] allow-popups
* [ ] allow-pointer-lock

Can you confirm this, @elrido?

**Comment by elrido** [comment]
I am quite sure we need almost all of them, so the sandbox directive seems quite pointless for our project.

**Comment by rugk** [comment]
I've already ticked the one we need, …
They should be the minority. At least we do not need the last three.

**Comment by elrido** [comment]
We do use pop-ups (in the page template).

I suspect that sandboxing would break many of our use cases, as:

> The sandbox applies a same origin policy, prevents popups, plugins and script execution is blocked.

Source: https://content-security-policy.com/

This would, among other things, break password managers.
