### ISSUE TITLE
How to paste content of files or stdin to a privatebin site?

### ISSUE THREAD

**Issue by tjensch** [PrivateBin/PrivateBin#171]
most of the pastebins ship small CLI tools to send the content of files to the pastebin. one mighty fine usecase is pasting of logfiles.
There is one available (zerobinpaste), but it only works for another fork of the original zerobin.

**Comment by rugk** [comment]
You can use [this client](https://github.com/ziirish/zerocli) for this, but it has not been [confirmed yet](https://github.com/ziirish/zerocli/issues/11) to work with PrivateBin. If you want to work on it, feel free to fork the repo.

**Comment by elrido** [comment]
One of the reasons I want to implement the unit testing for JS is that it will help us in planning and working on changes of the storage format.

As a side effect teaches me how to run the JS in a CLI environment compared to a full DOM in the browser. One of the unit tests will be to encrypt and decrypt random content for validation purposes and a stripped down version of this combined with API tests would provide the core of a CLI client that runs on NodeJS.
