### ISSUE TITLE
Add upload notification

### ISSUE THREAD

**Issue by r4sas** [PrivateBin/PrivateBin#172]
Please add data upload notification after pressing "Send" button.
For example, hide all controls except the icon and display a message there.

**Comment by elrido** [comment]
If the data was successfully uploaded, the paste is created. This is displayed with a message including the URL of the paste. What would you like to see there in addition?

**Comment by rugk** [comment]
Maybe a progress bar?

**Comment by r4sas** [comment]
No, I mean between pressing Send button and message about successful upload, not progress bar (that also can be good choice).
![1](https://cloud.githubusercontent.com/assets/7023612/22628602/d3289bfc-ebe7-11e6-88fe-1dff5466e42c.png)

Why I need that: I use PrivateBin in I2P network, where data transfer speed is low (network feature).
