### ISSUE TITLE
Error when opening logo link in new tab

### ISSUE THREAD

**Issue by rugk** [PrivateBin/PrivateBin#176]
## Steps to reproduce

1. Create a new paste, open it.
2. (In this case: a password-protected paste with a wrong password)
3. Now right-click on the PrivateBin logo at the top and choose "Open in new tab"

### What happens
The new tab URL contains the query string (e.g. `/?08203e363f7d86d3`) from the previously opened paste and thus a decryption error is shown.

### What should happen
Go to home page (without any query string)

## Additional information

* I can reproduce this issue on <https://privatebin.net>: Yes

## Basic information

**Browser:** Firefox 51.0.1

**PrivateBin version:** e483d60eed35ce621ea62971442c4461e99dcaa3

**Comment by r4sas** [comment]
Confirm it: Firefox ESR 45.5.1
