### ISSUE TITLE
Bump PHP version to v5.4

### ISSUE THREAD

**Issue by rugk** [PrivateBin/PrivateBin#186]
Continuing https://github.com/PrivateBin/PrivateBin/issues/48 what about requiring PHP >=5.4 (currently: 5.3). This would allow us to use `<?=`, which would make our templates much easier to read…

Just my two cents… Maybe there are other advantages.

**Comment by elrido** [comment]
You can use `<?=` since PHP 3 or 4, but its considered bad practice. It only saves a few bytes and is less clear to read.

Why artificially increase the version our software runs on?

**Comment by rugk** [comment]
> You can use <?= since PHP 3 or 4

Ah, yeah, but only since v5.4 it "is always available regardless of the short_open_tag ini setting." ([source](https://secure.php.net/manual/en/language.basic-syntax.phptags.php)). And as admins should rather have this setting disabled (because the real short open tags are bad practise and potentially confusing), we can only use this with PHP 5.4 or above…

> but its considered bad practice. It only saves a few bytes and is less clear to read.

That it is bad practise is only your opinion. I've never read this anywhere else (and please don't confuse it with the real short opening tags, which are indeed bad practise - for technical reasons)…
Actually it makes the code [easier to read](https://stackoverflow.com/questions/14188397/why-are-echo-short-tags-permanently-enabled-as-of-php-5-4#answer-14188438) because you do not need `echo` anymore so

```php
<a href="<?= $link ?>"><?= $text ?></a>
```

is certainly easier to read than if this code would be blown up with `echo` every time you just need to echo some things…

**Comment by elrido** [comment]
This is not a personal opinion, Zend (the PHP developers) themselves do advise not to use these as far back as with ZF 1.12:
https://framework.zend.com/manual/1.12/en/zend.view.introduction.html#zend.view.introduction.shortTags

**Comment by rugk** [comment]
> However, the default for the php.ini short_open_tag setting is typically off in production or on shared hosts -- making their use not terribly portable. 

Okay, that's a good fact against them…
Long tags have likely better support…

**Comment by rugk** [comment]
But I am stupid. Zend is wrong or outdated ( I mean the doc you linked to is clearly outdated), as this whole thing was about PHP 5.4 or higher.

To quote myself:
> Ah, yeah, but only since v5.4 it "is always available regardless of the short_open_tag ini setting."

So Zend's argument does not apply. If we use PHP >= 5.4 you can use `<?=` on every server. [Here is](
https://stackoverflow.com/a/200666) a similar reply (from 2014). First the outdated information, followed by "This should mean they're safe to use in portable code but that does mean there's then a dependency on PHP 5.4+.". So well… we're only 0.1 versions away from this dependency, it would likely not hurt anyone.
Also we might have a look what else we could sue with PHP 5.4.

**Comment by rugk** [comment]
Other features [from this release announcement](https://secure.php.net/manual/en/migration54.new-features.php) I'd like to sue:
* short array syntax: `[1, 2, 3]` is so much better`array(…)`
* don't know whether the [file upload progress](https://secure.php.net/manual/en/session.upload-progress.php) could be useful for us…

**Comment by elrido** [comment]
Here are some (more) arguments for going PHP 5.4 as a minimum:
- at the moment PHP 5.4 is the oldest PHP version we can unit test using Travis CI, hence at the moment we can't even be sure if we haven't our current code still works in PHP 5.3
- The [check in the Request class](https://github.com/PrivateBin/PrivateBin/blob/dd721c651b216fd334d985a5f282a079f37ab86d/lib/Request.php#L84) could be removed, plus the [stripslashesDeep method in the Filter class](https://github.com/PrivateBin/PrivateBin/blob/dd721c651b216fd334d985a5f282a079f37ab86d/lib/Filter.php#L32). Less code to maintain, less risk of bugs.

**Comment by rugk** [comment]
So now we can change `<?php echo $bar ?>` to `<?= $bar ?>` …

**Comment by elrido** [comment]
If it bothers you so much, do it. I personally would not change working code into something less readable just to save those few bytes, though. Our code checkers might complain about it, too.

**Comment by rugk** [comment]
It is not less readable. It's much more readable… :laughing: 
Need to check the code checkers. I think they should have no reason to complain… :smiley:

**Comment by elrido** [comment]
Reopening to keep track of necessary changes this requires:
* README and INSTALL (and their wiki counterparts)
* All translation files

**Comment by rugk** [comment]
[wiki updated](https://github.com/PrivateBin/PrivateBin/wiki/Installation/_compare/ddbdb49cc8b351ac8c2f8dc6b6df59ee72a79438...056bf96d48cd13c7716933ad0913c8a60d74d34d). As for translation files going with `%s` is a good [idea](https://github.com/PrivateBin/PrivateBin/issues/201#issuecomment-288960981).
