### ISSUE TITLE
Permit certain IPs to be exempt from paste throttling

### ISSUE THREAD

**Issue by nolsen42** [PrivateBin/PrivateBin#191]
Perhaps it would a neat idea to permit certain IPs from paste throttling, like 127.0.0.1, for those who run a hidden service, while still throttling clearnet connections. Other IPs can be exempt in the configuration file with that.

Throttle on a hidden service = Gonna have a bad time :P

**Comment by rugk** [comment]
> Throttle on a hidden service = Gonna have a bad time :P

Why? It's not so much different to clearnet…
The only thing I'd argue is that hidden services are already quite slow, so it might not strictly be necessary, but well…

As for the idea itself: Yes, we could do so. It might be useful in many circumstances…

**Comment by nolsen42** [comment]
@rugk Because tor uses one IP for connecting to the server the hidden service is configured to, 127.0.0.1. So if you have a popular pastebin, this can cause a problem as many people are trying to paste using one IP, constantly triggering the throttle.

**Comment by rugk** [comment]
Uh, ah, of course… 😐 Did not thought about this.

**Comment by elrido** [comment]
For now I would simply run two instances that share the data folder/use the same database. The tor instance would be configured with the traffic limit set to 0 and the public net one left at the default.

**Comment by rugk** [comment]
As @rodehoed also asked for this in https://github.com/PrivateBin/PrivateBin/issues/786 and wants to do a PR, IMHO, one thing about the implementation:
* IMHO it should also support IP ranges like `/24` or other subnets, so you can more easily also whitelist whole networks, not (only) single IPs.

**Comment by rodehoed** [comment]
Yes do the validating with cidr and IPv6 will be the hardest part. What if an ip address is invalid? Is that an exception or should it be ignored?

**Comment by elrido** [comment]
The IP address is taken from the request as passed down by the webserver. If it is invalid, this likely means that a) the wrong header was configured or b) the protocol isn't IP, but something else (say, some new-fangled non-IP network protocol, or some retro-computing enthusiast accessing their instance over Novel IPX or Microsoft NetBIOS or AppleTalk or EcoNet or ...).

As long as the string passed down in the [configured HTTP header field](https://github.com/PrivateBin/PrivateBin/blob/2b8534d49e0a0b57511892e658dd75aa40e6a2e1/cfg/conf.sample.php#L138-L140) is unique per device or session, the traffic limiter should remain functional.

So, if one validates the received address and it isn't a valid IP, the code should just do a string match against already logged sha256 hashes and an un-hashed match against the exemption list, if one is set. Same for the elements in the exemption list: Don't fail if they aren't valid IPs, just match them as strings.

**Comment by rodehoed** [comment]
Lemme rephrase that. I mean the values coming from the config.php.

Also we are using https://packagist.org/packages/mlocati/ip-lib ourselves. It works with all PHP versions and has no dependencies. Is that ok?

**Comment by elrido** [comment]
That library looks like a good candidate, too. As long as we can easily keep it updated via composer and it is maintained, it definitely beats rolling and maintaining our own logic.

**Comment by rodehoed** [comment]
I did a  PR #787 for this one (based on 1.3.5). Please let me know.

**Comment by elrido** [comment]
Resolved in #787.
