### ISSUE TITLE
conf.ini readable from Apache 2.4 with default .htaccess

### ISSUE THREAD

**Issue by EchoDev** [PrivateBin/PrivateBin#194]
## Steps to reproduce
1. Install Apache 2.4
2. Install PrivateBin
3. Access conf.ini from browser

### What happens
conf.ini is readable from www

### What should happen
conf.ini should not be readable from www

## Additional information

Apache 2.4 changed some access control settings ( https://httpd.apache.org/docs/2.4/upgrading.html )
The .htaccess that is included with PrivateBin will not stop anyone from reading the conf.ini from www.

The proper way to deny this in Apache 2.4 (atleast what seemed to work for me) is
Require all denied

## Basic information

**Server address**:

ALL OS

Apache 2.4 and up

ALL Browser

ALL versions of Privatebin?

* I can reproduce this issue on <https://privatebin.net>: Yes / No
No

**Comment by elrido** [comment]
Hi @EchoDev, thanks for reporting this!

For reference, the recommended way to install PrivateBin involves [moving any sensitive folders out of the webroot and changing the PATH](https://github.com/PrivateBin/PrivateBin/wiki/Installation#changing-the-path). `.htaccess` files only work with Apache. Other webservers like nginx need to move the path or use additional configuration to protect these folders.

**Comment by elrido** [comment]
Argh, some .htaccess files get created automatically and those still had the old format. Reopening until fixed (by me).

**Comment by EchoDev** [comment]
Would it not be better to write both formats in the .htaccess? Not everyone will switch to Apache 2.4 and users who use Apache <2.4 will still need the old format. 

Tho I'm not sure if this will work.
