### ISSUE TITLE
Deprecate CSP referrer

### ISSUE THREAD

**Issue by elrido** [PrivateBin/PrivateBin#196]
Firefox 52 displays the following message in the console:

> Content Security Policy: Referrer Directive "no-referrer" has been deprecated. Please use the Referrer-Policy header instead.

Reproduced in PrivateBin 1.1 and the current master branch.

**Comment by rugk** [comment]
Yeah, but we already use `Referrer-Policy`. And `no-referrer` might still be required for older browser. Maybe at some time we can drop using it.

**Comment by Salokyn** [comment]
> Yeah, but we already use Referrer-Policy.

I can't find where the header `Referrer-Policy` is set (I mean outside CSP where it should not remain eventually) ?

**Comment by rugk** [comment]
It's actually used as a HTML tag, not as a header. (Browsers allow both, however.)

https://github.com/PrivateBin/PrivateBin/blob/fcf9cf63b5dbeb67088b70abb8325d1030e9d593/tpl/bootstrap.php#L13

**Comment by Salokyn** [comment]
Thank you.
Sorry I think my comment reopened the issue 😓

**Comment by rugk** [comment]
No, it's all fine. This issue has been open all the time anyway…
