### ISSUE TITLE
Stuck on "Sending paste..." when file upload disabled

### ISSUE THREAD

**Issue by paddy01** [PrivateBin/PrivateBin#209]
## Steps to reproduce

1. Enter the site
2. set something in the edit window
3. push "send"

### What happens
The "Sending paste..." appear and then nothing happens.

### What should happen
I suspect information should be sent to the server, but that is not happening.

## Additional information

![image](https://cloud.githubusercontent.com/assets/2136198/24322289/ed089c4a-1160-11e7-8961-58a53f55489f.png)

Nothing is seen on the server - even tried a tcpdump but nothing..

## Basic information

**Server address**:

**Server OS:**
Debian GNU/Linux 8.7 (jessie)

**Webserver:**
Server Version: Apache/2.4.10 (Debian) mod_fcgid/2.3.9 Phusion_Passenger/4.0.53
    mod_python/3.3.1 Python/2.7.9 OpenSSL/1.0.1t

**Browser:**
Tried
Firefox 52.0.1
Microsoft Edge
Google Chrome 56

**PrivateBin version:**
e80c726f92c3694e7f60e58fec472e3070eddf9d

* I can reproduce this issue on <https://privatebin.net>: Yes / No
No

**Comment by paddy01** [comment]
Tried both PHP 5.6 and 7.1 running under php-fpm

**Comment by elrido** [comment]
I was not able to reproduce it with commit e80c726 or the one after that ([test instance](https://zerobin-test.dssr.ch/)). I don't think its related to the server, as the error message indicates that there was en error in the base64 JS library we use.

If you copy the file to the server, could you update base64-2.1.9.js to ensure there was no problem due to the transfer of that file?

Do you see any other errors in the browser console, maybe during the loading of the page, before the paste is sent?

**Comment by paddy01** [comment]
I've uploaded the base64 file several times without it making any difference, I tried the "compatibility" mode as well so it used an older version but it also throwed an exception (not u but s in that case)

I added every possible error checking into firebug and this is a complete log output from it

![image](https://cloud.githubusercontent.com/assets/2136198/24323556/c3abf808-1177-11e7-941b-aa7efb05ba0a.png)

Most is just CSS errors but the only thing that pops up after I push "send" is the base64 error.

**Comment by paddy01** [comment]
I tried the same thing with a portable firefox without any addons at all.. and the issue persists.. but as it works on your test installation I must be something my server is doing different I suppose..

**Comment by elrido** [comment]
Could you check the encoding that your webserver sent these files in? eg. via menu "view" -> "text encoding": It should be showing "unicode". Or via the console in the "Net" tab.

All our files are stored as utf-8 and you should configure the webserver to deliver this projects file as such if it is not the case (by adding "AddDefaultCharset utf-8" to the virtual host configuration for privatebin in case of an Apache webserver).

**Comment by paddy01** [comment]
The view->Text Encoding is showing "unicode" and firebug is showing

HTTP/1.1 200 OK
Date: Sat, 25 Mar 2017 16:31:56 GMT
Server: Apache/2.4.10 (Debian)
X-Powered-By: PHP/7.1.3
Cache-Control: no-store, no-cache, no-transform, must-revalidate
Pragma: no-cache
Expires: Sat, 25 Mar 2017 16:31:56 GMT
Vary: Accept,Accept-Encoding
Content-Security-Policy: default-src 'none'; manifest-src 'self'; connect-src *; script-src 'self'; style-src 'self'; font-src 'self'; img-src 'self' data:; referrer no-referrer; sandbox allow-same-origin allow-scripts allow-forms
x-xss-protection: 1; mode=block
x-frame-options: DENY
X-Content-Type-Options: nosniff
Last-Modified: Sat, 25 Mar 2017 16:31:56 GMT
Content-Encoding: gzip
Content-Length: 3792
Keep-Alive: timeout=5, max=100
Connection: Keep-Alive
Content-Type: text/html; **charset=UTF-8**

**Comment by elrido** [comment]
Hm, the only odd thing in there is the sandbox policy not allowing popups:
sandbox allow-same-origin allow-scripts allow-forms **allow-popups**

But that would only be a problem with displaying password protected pastes when using the "page" theme.

Do you use [Cloudflare](https://github.com/PrivateBin/PrivateBin/wiki/FAQ#how-to-make-privatebin-work-when-using-cloudflare-for-ddos-protection) or a similar service that might change how the javascript files get delivered to the browser?

**Comment by paddy01** [comment]
Yes, I removed allow-popups according to the conf.ini information .. but I can re-add it altho I did have it earlier and still had the same issue.

No I don't use Cloudflare or similar.
You can check it yourself.. I'll change subdomain later either way :)
https://pbin.paddy.guru

**Comment by elrido** [comment]
Thank you for sharing the link, debugging the JS right now.

**Comment by elrido** [comment]
Ok, I found it: The JS refactoring introduced a bug that causes this issue if file uploads are disabled.

Sorry for making you look in all the wrong places. :-(

I'll provide a patch asap.

**Comment by paddy01** [comment]
Ahh! Than you thought I was crazy somehow! :) Been looking through the web config and making all kinds of modifications.. LOL

**Comment by elrido** [comment]
The patch in cd40717 should fix that.

**Comment by paddy01** [comment]
pulled it from git and updated the needed files, and now it works perfectly!
Thank you for very fast support! :)
