### ISSUE TITLE
traffic limiter related unit tests fail in HHVM

### ISSUE THREAD

**Issue by elrido** [PrivateBin/PrivateBin#21]
The unit tests related to traffic limiting (trafficlimiterTest::testTrafficGetsLimited() & zerobinTest::testCreateInvalidTimelimit()) fail when tested under HHVM. Since these tests use sleep calls this might be related to [#4744 in HHVM](https://github.com/facebook/hhvm/issues/4744). 

Disabling hhvm.xenon.period did not resolve the problem, so I have disabled the HHVM testing in travis for now. If anybody has some HHVM experience, please take a look on this and let us know if this is a problem outside of the unit test or how we could improve the tests.

**Comment by HLeithner** [comment]
I think you can close this, hhvm no longer support php only hack
