### ISSUE TITLE
ZH translation plural question

### ISSUE THREAD

**Issue by rugk** [PrivateBin/PrivateBin#217]
/to @4679

Is not [this](https://github.com/PrivateBin/PrivateBin/blob/37f5d99bc4d2d4853a4f134ff2cd85825d9f0a41/js/privatebin.js#L484) the same as the default [here](https://github.com/PrivateBin/PrivateBin/blob/37f5d99bc4d2d4853a4f134ff2cd85825d9f0a41/js/privatebin.js#L493)?
We do not handle negative numbers there anyway, AFAIK…

**Comment by elrido** [comment]
Of course they aren't the same. What about 0? 1 and 0 get the singular in French, Occitan and Chinese, while 0 gets the plural in the fallback (English, German, etc.).

Also note that these rules all come from this resource, as noted in the comment above that logic:
http://localization-guide.readthedocs.org/en/latest/l10n/pluralforms.html

**Comment by rugk** [comment]
Oh, I had not thought we actually use `0`. "0 pastes have been deleted…" :laughing: 

Okay, yes, all right.
