### ISSUE TITLE
Add CodeChecker for PHP

### ISSUE THREAD

**Issue by rugk** [PrivateBin/PrivateBin#22]
@rugk
There are several code checkers for PHP files. So why not add them?

* [x] [Code Climate](https://codeclimate.com/)
* [x] [Scrutinizer-Ci](https://scrutinizer-ci.com/)
* [x] [SensioLabsInside](https://insight.sensiolabs.com/)
* [x] [Codacy](https://www.codacy.com/) - [done](https://github.com/elrido/ZeroBin/commit/e8eb77eaab9b4a35889609a1355718ab234b8ccf)

----

@rugk
For adding this repo to https://insight.sensiolabs.com/ one must be the owner of the repo. Therefore, @elrido you have to do this. It's basically just a few clicks.

----

@rugk
For https://scrutinizer-ci.com too.

----
@rugk

In codeclimate.com I cannot change the settings, but at least here is an analysis: https://codeclimate.com/github/elrido/ZeroBin [![Code Climate](https://codeclimate.com/github/elrido/ZeroBin/badges/gpa.svg)](https://codeclimate.com/github/elrido/ZeroBin)
The score is so bad, because the JS are not excluded from analysis yet.

**Comment by rugk** [comment]
I updated the badges, but tehre is still something to do:
* CodeClimate coverage badge does not work right now. I think the coverage must somehow pushed to it. Or is it possibly Travis-related? Travis is not setup right now?
* Scrutinizer-Ci - Can we get a link @elrido ?
* And SensioLabsInside is still a ToDo.

**Comment by elrido** [comment]
* codeclimate - fixed the paths and env vars in travis, coverage works now
* Scrutinizer - https://scrutinizer-ci.com/g/PrivateBin/PrivateBin/

**Comment by elrido** [comment]
AFAIK this is now done. Let me know if anything is missing or close it if its fine for you, too.

**Comment by rugk** [comment]
Yes, all done. I also added all the badges.

**Comment by rugk** [comment]
BTW it's interesting to see how much the coverage varies depending on which service analyses it.

**Comment by rugk** [comment]
Wait, now https://insight.sensiolabs.com is missing...

**Comment by elrido** [comment]
Is it because the project was marked private? I just changed that...

**Comment by rugk** [comment]
Yes, think so. I [found it](https://insight.sensiolabs.com/projects/57c9e74e-c6f9-4de6-a876-df66ec2ea1ff/analyses/1). However I cannot access any settings (is there the possibility to add another user?). I cannot even access the badge code, so it would be nice if you could place the badge there.
BTW pretty serious things it reports with the potentially SQL injection. I'll open an issue for it.

**Comment by elrido** [comment]
It says: "Collaborators: Upgrade to a Business plan to be able to share your analyses."

And these "SQL injections" could only be triggered by editing the config file. It's the table prefix it complains about.

Here is the badge code for future reference:
`[![SensioLabsInsight](https://insight.sensiolabs.com/projects/57c9e74e-c6f9-4de6-a876-df66ec2ea1ff/mini.png)](https://insight.sensiolabs.com/projects/57c9e74e-c6f9-4de6-a876-df66ec2ea1ff)
`
