### ISSUE TITLE
Typo on website

### ISSUE THREAD

**Issue by C0rn3j** [PrivateBin/PrivateBin#220]
https://privatebin.info/

Therefore such installations can be upgraded to this fork without loosing any data.

Should be "losing", single o.

There's also a typo in the 1.1 release changelog, where there's "cpsheader" instaed of "cspheader"

 https://github.com/PrivateBin/PrivateBin/releases

**Comment by rugk** [comment]
Thanks for your information. :+1: 
As for the website, you can do a PR [here](https://github.com/PrivateBin/privatebin.info-pelican). (You may also fix the blog post of v1.1, which likely has the same typo) I've corrected the release info on GitHUb.

**Comment by C0rn3j** [comment]
Created a PR.

https://github.com/PrivateBin/privatebin.info-pelican/pull/14
