### ISSUE TITLE
Uploading a paste through curl

### ISSUE THREAD

**Issue by C0rn3j** [PrivateBin/PrivateBin#221]
File: `curl https://ptpb.pw -F c=@PATH_TO_FILE`. 

Command output: `COMMAND | curl https://ptpb.pw -F c=@-`.

Other services allow uploading text/files through curl, like so.

http://i.imgur.com/gOphMjZ.png

Would it be possible to implement this in PrivateBin, or is it already a possibility that is not documented?

**Comment by rugk** [comment]
As the paste data is encrypted (locally on your device) with curl alone it is not possible (unless you manually encrypt the data and paste it into curl).

It is however possible to create a CLI tool for this task as PrivateBin has a API. One CLI client is currently being created, see https://github.com/PrivateBin/PrivateBin/issues/188.

**Comment by C0rn3j** [comment]
That makes sense, thanks for reply!
