### ISSUE TITLE
Better favicon

### ISSUE THREAD

**Issue by rugk** [PrivateBin/PrivateBin#23]
@rugk
I think we really need a nicer favicon. The current one is a big dark blue square where you can hardly see the "Z" when it is displayed in a small version.
Especially for the light styles, this favicon does not suit and would have to be much lighter.

**Comment by rugk** [comment]
BTW I would prefer if it is created with open source tools such as [Inkscape](https://inkscape.org). Of course we should also release the source and the basic image should be an SVG. With [RealFaviconGenerator](https://realfavicongenerator.net/) we can then optimize this, to minify the file size and make it looking nice on every platform.

**Comment by elrido** [comment]
See dbdeba527, working on it

**Comment by rugk** [comment]
I think you used the wrong issue for posting this reply... :smile: (Or the wrong commit hash)

**Comment by rugk** [comment]
I think that icon is a bit simple...
I mean it has no colour at all...

**Comment by elrido** [comment]
No problem, I just liked the :bee: mentioned in that naming thread. Feel free to replace it with something else.

**Comment by rugk** [comment]
Yeah :bee: is nice, but this is a black & white bee.

Maybe someone has some ideas or can contribute a good icon?

**Comment by rugk** [comment]
So maybe we should make this a bit more metaphorical. What about a honeycomb where data is locked in? For small 16x16 favicons this is a simple structure and easy to recognize.

**Comment by elrido** [comment]
This is where I got the other :bee: icons from, there are also some honeycombs in there: https://thenounproject.com/term/bee/

**Comment by rugk** [comment]
So I've pushed some things to https://github.com/PrivateBin/assets/tree/master/images. That's basically the idea I had:
* A honeycomb with a lock/ a "honeycomb-padlock", but one cannot see this connection at the first glance
* and I use some metal-filter in Inkscape so it looks strong... :smile: 

![PrivateBeen ;)](https://raw.githubusercontent.com/PrivateBin/assets/master/images/icon.png)

What do you think?

**Comment by elrido** [comment]
It looks great! One can clearly see its outline even in favicon resolution.

How about using #ffcc00 as the color? Would be a bit more honey-y...

**Comment by rugk** [comment]
> How about using #ffcc00 as the color? Would be a bit more honey-y...

Yeah, good idea. A bit more orange clearly does not hurt...
I'm still not sure about the border/outline yet. I make it a bit bigger (also in the big versions).

**Comment by rugk** [comment]
So, next version:

![](https://raw.githubusercontent.com/PrivateBin/assets/master/images/preview/icon.png)

**Comment by rugk** [comment]
Favicon package generated: https://github.com/PrivateBin/assets/tree/master/favicon

Now we only have to include it into PrivateBin. Currently you already seem to use some icons, but not all of the ones RealFaviconGenerator recommends. Additionally they [recommend](https://realfavicongenerator.net/faq#why_icons_in_root) to put the files at the root of your site. (this is also what I've choosen when generating the favicons, but I can do it again if you rather want to place it somewhere else)
