### ISSUE TITLE
Error message displayed when Markdown is disabled

### ISSUE THREAD

**Issue by Hexalyse** [PrivateBin/PrivateBin#237]
I've noticed than when we disable the Markdown formatter, the showdown library is not loaded : https://github.com/PrivateBin/PrivateBin/blob/master/tpl/page.php#L44-L48

The problem is that is privatebin.js, we check if showdown is loaded, otherwise we display an error :
https://github.com/PrivateBin/PrivateBin/blob/master/js/privatebin.js#L1957-L1962

So... disabling markdown ends up displaying an error, which is not required since Markdown is disabled.

What would be the best solution ? Disabling this requirement check altogether ?

**Comment by rugk** [comment]
Welcome back @Hexalyse!

> Disabling this requirement check altogether ?

Yeah, I think so. (At least if markdown processing is disabled…)

**Comment by Hexalyse** [comment]
> Yeah, I think so. (At least if markdown processing is disabled…)

Well, the thing is that this verification is done in privatebin.js, client-side. And we can't disable if "only if markdown processing is disabled" because no PHP-code is modifying this js... which anyway must be static because there is an SRI hash in the template, to ensure integrity).

So I guess we'll have to disable it completely (which I did on the PrivateBin instance I'm configuring).

**Comment by rugk** [comment]
Sure, do it and close this issue in the commit. Although a PR would maybe be more suitable, because we nowadays try to [sign our git commits](https://github.com/PrivateBin/PrivateBin/wiki/FAQ#how-can-i-securely-clonedownload-your-project). So well… yeah, a PR would be better.
