### ISSUE TITLE
Cannot submit large source code, wrong decryption key

### ISSUE THREAD

**Issue by hogze94** [PrivateBin/PrivateBin#239]
## Steps to reproduce

1. Paste HTML code of this webpage https://stackoverflow.com/questions/6125351/good-class-design-by-example into a new paste
2. Click submit, paste burn/expiry/formatter options makes no difference.
3. Click newly generated link.

### What happens
Asks for decryption key whether you entered a password or not. Entering the correct password if set results in same thing.

### What should happen
Show the paste

## Additional information
Resulting paste HTML + Key https://pastebin.com/DzXezAR4
Simple pastes work, even 5 paragraphs of lorem ipsem works: http://www.lipsum.com
Seems to be code only.

## Basic information

**Server address**:

Linux server 4.4.0-79-generic #100~14.04.1-Ubuntu SMP Fri May 19 18:36:51 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

nginx version: nginx/1.12.0

Chrome + firefox latest

https://github.com/PrivateBin/PrivateBin/commit/674ebbc6fb3697ec034e79175d4f5aa0a55f9605

I can reproduce this issue on <https://privatebin.net>: No https://privatebin.net/?994bc9089741cebb#Jzu1hhq7BJrH1jCgkofMbFLWzQ7zE2xETHEnrB+4gGs=

**Comment by rugk** [comment]
Actually it's strange that this is not reproducible on privatebin.net. I also tried your link/instance, but there 404 errors appear and the tls certificate is self-signed, BTW.

Did you maybe modify the JS code or so somehow?

**Comment by hogze94** [comment]
No modifications, just pulled the repo, modified config.ini.

blah.com is not my domain, just a filler to keep my test server anonymous.

**Comment by k0nsl** [comment]
I posted the same paste [on my own instance](https://p.0x0f.su/?2ebb7d4b8af2928a#lW/qkSBEoJUGQ28SYTOawvGSsvnS6DTAklgMOFP79QE=) (synchronized yesterday) with no issue, although I run Caddy and without MySQL,

**Comment by rugk** [comment]
> blah.com is not my domain, just a filler to keep my test server anonymous.

Just FYI: I think there is an RFC or so, which recommend `*.example` domains or `example.com` for that purpose. Just because actually the fake domain you used, did exist, which is a bit confusing…

Actually the backend should hardly matter, as the paste is encrypted, so it is just some "garbage" for the more-or-less dump storage method.
In any case, could you try plain-text storage, @hogze94?

**Comment by r3pek** [comment]
Same problem on my server (MariaDB backend)

**Comment by rugk** [comment]
Only with this piece of code or can you reproduce it with other code too?

**Comment by r3pek** [comment]
Maybe just with that code.

Tried 100 paragraphs from http://lipsum.com/ and works ok.

**Comment by hogze94** [comment]
This works: https://raw.githubusercontent.com/php/php-src/master/Zend/zend_API.c

HTML issue perhaps?

**Comment by rugk** [comment]
Okay, so what if you take GItHub's HTMl code – e.g. on this site (ala `view-source:https://github.com/PrivateBin/PrivateBin/issues/239`)?

**Comment by hogze94** [comment]
Yep, asks for decryption key.

**Comment by rugk** [comment]
Ah, that console log is actually really useful.

**Comment by elrido** [comment]
Hi, I could no longer reproduce this in the latest version of our master. If anyone still finds an example that fails in this way, please send it in.

**Comment by rugk** [comment]
Just note that I could never reproduce this on privatebin.net…

**Comment by rugk** [comment]
Another user reported a similar problem with text in general. Small text worked, large not.

Could you provably check whether you have enough RAM on the server?
