### ISSUE TITLE
IRC

### ISSUE THREAD

**Issue by rugk** [PrivateBin/PrivateBin#24]
Raised by @k0nsl:

> Hello,
> 
> I tried searching for any information on your site and on the repository itself if you had any means to chat, typically something like IRC. However, I couldn't find any clues as to where and on which network you might be.
> If you don't have an IRC channel I would be honoured to provide one for you on my own IRC network. Would anyone be interested in that?
> 
> You can check out my IRC network by connecting round-robin irc.k0nsl.org . I have very few users and they all hangout in #k0nsl.
> At any rate, it was just a thought. Let me know what you think :)

Continuing https://github.com/elrido/ZeroBin/issues/109

**Comment by ZerooCool** [comment]
The link is dead.

**Comment by elrido** [comment]
Yes, I had to disable it on some ones insistence :-/ But it did only contain exactly what is already quoted above.

**Comment by ZerooCool** [comment]
Could using Discord be an interesting tool today?
Perhaps IRC offers advantages in terms of security and anonymity?
Discord brings the advantage of creating multiple work rooms, and, audio rooms.
A discord group could quickly be created, and, directors appointed.

**Comment by elrido** [comment]
This is about formatting a paste containing an IRC chatlog.

I of course don't mind if anyone sets up an IRC room or Discord forum for the project. Personally I prefer to use asynchronous communication, so mail (-ing-lists), forums more then interactive chats or voice or video. We had discussed about running a forum on the fediverse at some point, but these days the Mastodon-fediverse-client seems most popular, which doesn't support these, AFAIK.

**Comment by ZerooCool** [comment]
Ok, just do it, there is a channel Discord for PrivateBin :
https://discord.gg/a8Kf3ya

**Comment by rugk** [comment]
Also think this issue is not very useful and we don't plan an IRC server nor Discord or any other instance. The community can of course set them up, but there is no official server.

Official resources are the website, blog (with RSS feed), GitHub etc.

**Comment by ZerooCool** [comment]
Le site officiel de PrivateBin : https://privatebin.info/

Le dépôt officiel de PrivateBin : https://github.com/PrivateBin/PrivateBin
La documentation de PrivateBin : https://github.com/PrivateBin/PrivateBin/wiki/Configuration

The Blog / RSS ? Where ?

**Comment by rugk** [comment]
That's the blog basically: https://privatebin.info/category/news.html
And here is the corresponding RSS feed: https://privatebin.info/feeds/all.atom.xml
