### ISSUE TITLE
collaborative text editor/edit paste

### ISSUE THREAD

**Issue by DeadBrain1** [PrivateBin/PrivateBin#241]
Why you dont make that text to be edited later somehow or just make collaborative text editor
for me and more i guess  using like this is limited

**Comment by rugk** [comment]
This is way harder than you think, at least an collaborative text editor. However, for the other idea… this is already possible more or less: On every paste (when not auto-deleting or so) there is a clone button, which you can use to clone the paste and afterwards edit it.

**Comment by rugk** [comment]
If you have any further questions just comment.

**Comment by elrido** [comment]
duplicate of #114
