### ISSUE TITLE
Attachment checks seem to have an issue

### ISSUE THREAD

**Issue by sferich888** [PrivateBin/PrivateBin#242]
## Steps to reproduce
1. Try example from python PBCLI - https://github.com/r4sas/PBinCLI/issues/1

### What happens
When trying to us the PBCLI examples, I get issues with the serve side, trying to validate the attachments: https://github.com/PrivateBin/PrivateBin/blob/master/lib/Model/Paste.php#L183-L211

### What should happen
The paste should be accepted, and posted to the server. 

## Basic information

**Server address**: Internal and not public 

**Server OS:** Red Hat Enterprise Linux

**Webserver:** httpd 2.4 

**Browser:** Google Chrome | 59.0.3071.104 (Official Build) (64-bit)

**PrivateBin version:** 1.1

I can reproduce this issue on <https://privatebin.net>: Yes

**Comment by r4sas** [comment]
That's cause in PBinCLI still not realized compression. Please read here: https://github.com/PrivateBin/PrivateBin/issues/188#issuecomment-281284360

**Comment by elrido** [comment]
You can use the [nodejs based CLI client](https://github.com/PrivateBin/PrivateBin-Cli) that works with the current buggy deflate implementation until we have introduced the a new paste format, addressing changes in crypto and making compression an option.

**Comment by otaku** [comment]
I've created a pull request https://github.com/r4sas/PBinCLI/pull/5 that was able to successfully upload attachments.  I don't believe there's an issue with the Sjcl::isValid function.

**Comment by r4sas** [comment]
Thank you, @otaku. I've merged your PR, so that issue can be closed.
