### ISSUE TITLE
Rich Text Format Support

### ISSUE THREAD

**Issue by cryptolok** [PrivateBin/PrivateBin#243]
Would be outstanding if PrivateBin supported RTF, like [CryptPad](https://cryptpad.fr/).
More features without losing security/privacy/confidentiality.
Seems not to be difficult to [implement](https://github.com/ianstormtaylor/slate).

**Comment by rugk** [comment]
You can already do most of these things by using markdown. However, adding some interface using a real WYSIWYG editor is an idea, at least.

**Comment by cryptolok** [comment]
true, but a notable exception is image storage (without counting file upload)

**Comment by cryptolok** [comment]
you're right, that's what I used :) however, not everyone have CryptoFox/shell/tool for encoding/decoding and RTF will prevent unnecessary file storage
but I'll admit that various tricks are possible indeed, that's just for "normal" users (although, "normal" people wouldn't use PrivateBin I suppose:) )

**Comment by rugk** [comment]
Oh you actually BAse64-encoded it?

If you only want to attach one picture, just do what i described in the last sentence. Choose a hoster with file upload enabled and attach the picture as a file.

**Comment by cryptolok** [comment]
well, a more "versatile" solution what I actually used is to store image/text/data with CryptPad and share the link using PrivateBin
if only RTF would be supported, CryptPad wouldn't be used at all (except for collaboration)

**Comment by cryptolok** [comment]
but if the image would br prompted after file upload, that would be sufficent indeed, nonetheless, not every hoster supports that, which is the case for text

**Comment by cryptolok** [comment]
as you said - an idea, at least
I'm sure you guys have more important things to do
by the way, I saw that you have patched #159 , which is nice

**Comment by rugk** [comment]
Yeah, https://github.com/PrivateBin/PrivateBin/pull/216 is just "stuck" at the unit tests, so any help is appreciated.

**Comment by rugk** [comment]
> but if the image would br prompted after file upload, that would be sufficent indeed

I do not really understand that sentence. The current behavior is: After decryption the file will automatically be displayed, if it is an image file.

**Comment by cryptolok** [comment]
that's what I meant, if the image is prompted (displayed) instead of being downloaded as an attachment, then it's good enough

**Comment by rugk** [comment]
But that is already implemented:
![grafik](https://user-images.githubusercontent.com/11966684/29186305-4d141d18-7e0c-11e7-94b3-0c563ec80895.png)

https://snip.dssr.ch/?892268940ce81286#BIGr/aMrJx3j4yzykF8f3Coa785yeFeQ5XeTgCCw1+E=

**Comment by cryptolok** [comment]
now I know :)
I used p.0x0f.su for files though
