### ISSUE TITLE
JavaScript unit tests fail

### ISSUE THREAD

**Issue by rugk** [PrivateBin/PrivateBin#244]
https://travis-ci.org/PrivateBin/PrivateBin/jobs/263238599

> Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.

**Comment by rugk** [comment]
I think this issue can be closed, can't it? @elrido

**Comment by elrido** [comment]
correct, I increased the timeouts. Travis performance has significantly decreased. :-(
