### ISSUE TITLE
Installation/Configuration problem

### ISSUE THREAD

**Issue by funnyuser001** [PrivateBin/PrivateBin#256]
## Steps to reproduce
1. Install Zerobin with database as a storage
2. The webpage is just blank.
3. Go back to file based storage to check if db is configured wrongly
4. The webpage is just blank.

### What happens

Zeobin webpage stays blank.

### What should happen

Zerobin webpage should work.

## Additional information

I'm configuring this thing for first time,
All file permissions are set to www-data:www-data
My PATH is configured to be: /var/www/paste.domainname.tld/

## Basic information

**Server OS:** Debian 7 64 bit.

**Webserver:** Apache2

**Browser:** Firefox

**PrivateBin version:** Newest from your wiki tutorial

I can reproduce this issue on <https://privatebin.net>: No

Also: mcrypt is installed on my server, I've checked if that works with this code:

if(function_exists('mcrypt_encrypt')) {
    echo "mcrypt is loaded!";
} else {
    echo "mcrypt isn't loaded!";
}

**Comment by rugk** [comment]
This project is named PrivateBin since some time, so are you sure you installed PrivateBin and not ZeroBin. Better check the version (it should be mentioned in the ZIP file name) and copy & paste it here. (That's what we have the "PrivateBin version" field in the template.)

Your issue looks like a configuration issue. And we'd need more information to see what the culprit is:
* when you access the site, which return code do you get? (in browser via F12)
* can you execute PHP code at exactly the same "position" as PrivateBin? (for testing, e.g. modify the index.php)
* did you look into the webserver log? Maybe post the log here (with sensitive infos redacted, if needed) to get more information.

**Comment by rugk** [comment]
Okay so you actually get a HTML response. That is strange. What is the http status code?
Also check the access.log, it should show your requests.

Can you access any other (static) files manually in the dir?

**Comment by funnyuser001** [comment]
Favicon is loading so I guess that I can download static content, I even checked if I can show the icon in my browser, it works.
Info abou my request from /var/log/apache2/access.log

`xx.xx.xx.xx - - [02/Nov/2017:20:44:21 +0100] "GET / HTTP/1.1" 500 3894 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:56.0) Gecko/20100101 Firefox/56.0"
xx.xx.xx.xx - - [02/Nov/2017:20:44:22 +0100] "GET /favicon.ico HTTP/1.1" 200 15568 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:56.0) Gecko/20100101 Firefox/56.0"
`

**Comment by rugk** [comment]
So the return code is 500 (you can see that in the log and in your browser, press F12). That means something is wrong, some kind of server error.

**Comment by funnyuser001** [comment]
Yes, I know that this is server error.
But I have no idea on how to debug php code, that's why I created this issue in the first place.

**Comment by elrido** [comment]
Hello @funnyuser001, you will find the error in either a specific PHP error log, if configured in the `error_log` setting of your php.ini file, in the webserver log or a php-fpm error log.

On Debian with Apache and mod_php, by default the error log should be in /var/log/apache/error.log or var/log/apache/ssl_error.log (if your using HTTPS). But this may have been overwritten in the virtual host configuration for your site.

Let us know what the php error is, once you find the log.

**Comment by funnyuser001** [comment]
@elrido 
I'm using ssl and there is no such thing as: /var/log/apache/ssl_error.log
After tweaking some php.ini settings I got error log in my syslog.

`apache2: PHP Fatal error:  Uncaught exception 'Exception' with message 'PrivateBin requires configuration section [model_options] to be present in configuration file.' in /var/www/paste.domain.tld/lib/Configuration.php:141#012Stack trace:#012#0 /var/www/paste.domain.tld/lib/PrivateBin.php(182): PrivateBin\Configuration->__construct()#012#1 /var/www/paste.domain.tld/lib/PrivateBin.php(131): PrivateBin\PrivateBin->_init()#012#2 /var/www/paste.domain.tld/index.php(18): PrivateBin\PrivateBin->__construct()#012#3 {main}#012  thrown in /var/www/paste.domain.tld/lib/Configuration.php on line 141`

**Comment by rugk** [comment]
Okay, so that configuration options is missing. Either add it manually or just create a new config based on the template supplied.
Was it really a fresh installation?

**Comment by funnyuser001** [comment]
@rugk Ok, it's kinda my fault.

I had:
;[model_options]
Instead of
[model_options]

When I was configuring this thing for the first time I thought that ";[model_options]" is just comment, not actual part of the config.

**Comment by rugk** [comment]
So your issue is solved? If so, great! 👍 (And if that is the case you can just close it, BTW.)
