### ISSUE TITLE
Reloadlink class image not displaying

### ISSUE THREAD

**Issue by haywardgb** [PrivateBin/PrivateBin#257]
### What happens

Reloadlink class image not showing.

### What should happen

It should show the image top left, but it only shows the default text.

## Additional information
I've checked the folders and the files are there. 

## Basic information

**Server address**: https://thecloud.org.uk/paste

**PrivateBin version:** 1.1.1

I can reproduce this issue on <https://privatebin.net>: No

**Comment by rugk** [comment]
The instace you are using (Is it your opwn?/are you the/an admin?) seems to be broken anyway. It cannot load the JavaScript, it cannot load the image file. Just all 404 errors.

So basically this is a configuration problem. Your webserver does not serve the files correctly, maybe it has permission problems or so.
There is nothing we can do here. Better check your server configuration.

If you have further questions, feel free to ask.

**Comment by elrido** [comment]
The problem seems related to the email-decode.min.js which does not follow the content security policy and therefore interrupts the JS execution. You could put that JS file into the js/ folder with the other scripts to get rid of the error.

**Comment by haywardgb** [comment]
I figured out that the image not loading was due to that file type not being supported inside my nginx configs. Fixed that easily enough. 

The email-decode.min.js is a cloudflare addon. It stop people from scraping my site for email addresses. Do you know of anyway around this without having to turn off email obfuscation ? 

Thank for your help .

**Comment by haywardgb** [comment]
The issue with email obfuscation was specific to Cloudflare , it can be fixed by adding a page rule on cloudflare cpanel.

**Comment by rugk** [comment]
Ah, so this is something you may want to add to the FAQ question [here](https://github.com/PrivateBin/PrivateBin/wiki/FAQ#user-content-how-to-make-privatebin-work-when-using-cloudflare-for-ddos-protection)… You can edit the wiki.

**Comment by haywardgb** [comment]
Cheers. Haven't used Wiki markup in ages. Hence the multiple edits, sorry about that.

**Comment by rugk** [comment]
Thanks for that. I'd just "merged" it to the other Cloudflare question and did some rewording.

BTW your page still does not work, you may still disable the rocket loader or so.

**Comment by haywardgb** [comment]
That's strange, because its been working fine for me and my friends today. I don't have Rocket Loader enabled. Any ideas ?

**Comment by rugk** [comment]
Works with Tor here too, maybe it's some (Cloudflare) caching or so…

**Comment by haywardgb** [comment]
Purged the cache. I'm connecting ok with my mobile and kindle too, on separate wifi connection over VPN. CloudFlare is really good when it works, but a pain in the bottom when it plays up like this..

**Comment by haywardgb** [comment]
Ok, this seems to be the ultimate fix for CloudFlare users, however it does turn off a lot of CloudFlares protection.. Here's the two rules you need to set, in page rules:

Disable Security:

Disables the following features:
    Email Obfuscation
    Server Side Excludes
    WAF
    Rate Limiting
    Scrape Shield

 
Disable Performance:

Disables the following features:
    Minification
    Rocket Loader
    Mirage
    Polish

**Comment by rugk** [comment]
Indeed it is, because Cloudflare messes with the JavaScript files. If it does, Subresource Integrity is triggered, detecting an error, stopping JavaScript…
Our JS files are really small, so you do not need minification or such things anyway…

Maybe you can add the features to the FAQ at https://github.com/PrivateBin/PrivateBin/wiki/FAQ#user-content-how-to-make-privatebin-work-when-using-cloudflare-for-ddos-protection?
