### ISSUE TITLE
[Insight] Database queries should use parameter binding - in lib/zerobin/db.php, line 282

### ISSUE THREAD

**Issue by rugk** [PrivateBin/PrivateBin#26]
Of course I think `self::$_prefix` is entirely static and therefore no danger, but for the matter of principle I think it would be a good idea to change it anyway.
Insights reports this 7 times. Always  `self::$_prefix`.

----

**[in lib/zerobin/db.php, line 282](https://github.com/PrivateBin/PrivateBin/blob/dbdeba5274b1fa2289f041f10448e0cc8f15446e/lib/zerobin/db.php#L282)**

> If provided by the user, the value of `self::$_prefix` may allow an SQL injection attack. Avoid concatenating parameters to SQL query strings, and use parameter binding instead.

```php
     * @return void
     */
    public function delete($pasteid)
    {
        self::_exec(
            'DELETE FROM ' . self::$_prefix . 'paste WHERE dataid = ?',
            array($pasteid)
        );
        self::_exec(
            'DELETE FROM ' . self::$_prefix . 'comment WHERE pasteid = ?',
            array($pasteid)
```

---------------------

_Posted from [SensioLabsInsight](https://insight.sensiolabs.com/projects/57c9e74e-c6f9-4de6-a876-df66ec2ea1ff/analyses/1)_

**Comment by elrido** [comment]
c33c50f and 3b3b527 address this, odd characters (`[^A-Za-z0-9_]`) would now simply be removed from the configured table prefix.
