### ISSUE TITLE
Empty paste

### ISSUE THREAD

**Issue by rugk** [PrivateBin/PrivateBin#260]
@tobast posted on https://github.com/sebsauvage/ZeroBin/issues/114:

>Hello,
>
>In some cases, a (non-empty) paste yields an empty paste link. For instance, when trying to paste this text, ie.
>
> ```
> 
> 1 subgoal
> 
> inv : Assert
> expr : Expr
> sBody : Instr
> deduction : (|- [|inv /\ assertOfExpr expr|] sBody [|inv|])%assert
> IHdeduction : (|= [|inv /\ assertOfExpr expr |] sBody [|inv|])%assert
> mem : Mem
> preInMem : inv mem
> m : Mem
> n : nat
> interpRel : interp (nth_iterate sBody n) (MemElem mem) = CpoElem Mem m
> lastIter : interp (nth_iterate sBody n) (MemElem mem) |=e expr_neg expr
> notLastIter : forall p : nat,
>               p < n -> interp (nth_iterate sBody p) (MemElem mem) |=e expr
> isWhile : interp (while expr sBody) (MemElem mem) =
>           interp (nth_iterate sBody n) (MemElem mem)
> 
> ======================== ( 1 / 1 )
> conseq_or_bottom inv (interp (nth_iterate sBody n) (MemElem mem))
> ```
> 
> the paste is first rendered as non-empty, but following the given link will result in an empty paste…

**Comment by rugk** [comment]
Thanks for your report. So I can reproduce your issue on privatebin.net. And it is really awkward. Just changing a single character somewhere (new line characters at start/end do not seem to matter) and it is shown correctly.

The paste is, however, not really empty, it just cannot decrypt it. (and thus asks for a password even if none is set)

Do you have more examples of text snippets triggering this behavior?

----

Maybe it has to with some base64 errors? (https://github.com/PrivateBin/PrivateBin/pull/193)

**Comment by tobast** [comment]
No, I don't have any other examples… I just stumbled upon this example while trying to paste this text on my own instance.

**Comment by elrido** [comment]
I have created a unit test to get to the bottom of this. En- and decrypting the message with random keys and password I failed to reproduce the error. I then took an error case produced on a live instance and could pinpoint the error to the deflation of the message, while the decryption and the base64 unpacking still work.

What remains to be tested is how to reproduce the error in a unit test, to be sure that it is in the deflate library (which would be solved when switching to the pako library) and not in some other part of our logic. It could be that the error is introduced while reading the message from the textarea, which may strip whitespace characters at the beginning and end.

**Comment by eneerge** [comment]
I've recently set PrivateBin up and we have experienced this error a lot.  Mostly when attaching a file. Do you need any more test cases?

**Comment by eneerge** [comment]
By a lot, I mean it's almost been 50% of the time this first week when trying to send smallish Excel files out of about 10 files or so. I'll try and send a few examples.

**Comment by elrido** [comment]
I suggest we revisit this once we have the new format using the non-buggy compression out. I suspect that with compressed files (Excel nowadays is XML in a zip wrapper) the change of hitting the magic combination of bytes somewhere in the file that triggers the bug in [Dan Kogai's](https://en.wikipedia.org/wiki/Dan_Kogai) rawdeflate library. We are working on replacing it in the upcoming release. If it is this bug, then there is no quick fix except to upgrade once the next release is done. (any help to speed this up would be appreciated)
