### ISSUE TITLE
Small template for imprint

### ISSUE THREAD

**Issue by ukcb** [PrivateBin/PrivateBin#267]
Please complete a configurable template (raw-html or similar) for an imprint on each page.
This is required by law in some countries.
Many Thanks.

**Comment by rugk** [comment]
Just include a link in a template linking to one simple (HTML) page you create, which shows the imprint or such stuff.

**Comment by ukcb** [comment]
You would have to reinstall the link with each (template) update every time, because the template is overwritten. That would not be nice. I would like a footer by default, because the imprint would have to be available anytime and immediately.

**Comment by rugk** [comment]
Ah so you would like to have a config option?
That is certainly possible.

**Comment by ukcb** [comment]
A config option would be good. I tested something, see the example.

cfg/conf.php

```
; optional footer to display
footer = '<div id="footer">
 <a href="/">Home</a> |
 <a href="/">Terms</a> |
 <a href="/">Privacy</a> |
 <a href="/">Security</a> |
 <a href="/">Help</a> |
 <a href="/">Imprint</a>
</div>'
```

lib/Configuration.php in main array

`'footer' => '',`


lib/PrivateBin.php in function _view

`$page->assign('FOOTER', $this->_conf->getKey('footer'));`


tpl/bootstrap.php before `</body>`

```
<?php
if (strlen($FOOTER))
 echo $FOOTER;
?>
```

css/bootstrap/privatebin.css

```
#footer {
 text-align:center;
 color:#ddd;
 background-color:#eee;
 border-top:#ddd 2px solid;
}
```

A small screenshot of what it might look like.

![bild](https://user-images.githubusercontent.com/22983914/34356438-08a48840-ea3e-11e7-8d66-806629266817.png)

It would be great if such a thing would be possible by default.

**Comment by elrido** [comment]
You could just use the [`notice`](https://github.com/PrivateBin/PrivateBin/wiki/Configuration#notice) option. It would even appear above the text area.

If you would rather have it in the footer, editing the template is the better option. Since the templates don't change that frequently, you could just copy the `tpl/bootstrap.php` to another name to preserve your changes when updating. Only the hashes in the Javascript include tags would need to be updated when you update your installation.

**Comment by ukcb** [comment]
The notice option is not optimal, because it works with function htmlspecialchars, since you can't work with html. If I have to edit the template every time I update it, then I can include a file e.g. menu.php as well. The effort would be the same. Optimal course would be a persistent configuration, which survives an update. Would be nice if you would think again. :-)

**Comment by rugk** [comment]
Personally I would have nothing against a PR, which makes the changes [suggested here](https://github.com/PrivateBin/PrivateBin/issues/267#issuecomment-353962392), but without HTML code, but a more generic listing in the INI file with "text -> link" pairs.
