### ISSUE TITLE
Image upload from clipboard

### ISSUE THREAD

**Issue by koehn** [PrivateBin/PrivateBin#273]
First, fantastic product! Super-easy to configure, and very handy.

That said, it would be fantastic if you could paste an image a la https://pasteboard.co.

**Comment by rugk** [comment]
You can already do. Just enable file upload.
When images are uploaded there and users are accessing the created paste, it then automatically embeds/shows these there.

**Comment by koehn** [comment]
What I’d like is an easy way to upload a screenshot from the clipboard without creating a file.

**Comment by rugk** [comment]
Ah all right. Yeah, that'd be a nice-to-have thing.

Note: In any case a preview of what you actually pasted should be shown somewhere then, as otherwise you might miss the fact that you accidentally pasted some (sensitive) information.

**Comment by paalbra** [comment]
Pasting images (from clipboard) works in 1.2.1. I'm not sure when this feature was added though.

But there is no preview and no confirmation message when you paste the image.

I made an issue concerning the missing confirmation message in #400

**Comment by elrido** [comment]
closing this in favour of #400 for the remaining work.
