### ISSUE TITLE
Delete empty directories in cron

### ISSUE THREAD

**Issue by rugk** [PrivateBin/PrivateBin#277]
Split out of https://github.com/PrivateBin/PrivateBin/issues/276

The softcron may leave empty directories on the disk.

This:
* may cause the softcron process to get ineffectively over time and potentially delete fewer pastes when it is not executed so much (see https://github.com/PrivateBin/PrivateBin/issues/276#issuecomment-361225552)
* clutters the file system
* uses useless inodes

**Comment by mbressman** [comment]
Any news on this?

**Comment by ZerooCool** [comment]
Alternative with cron : 

```
# Script
find /var/www/privatebin.visionduweb.fr/data -type d -empty -delete
```

```
# Cron :
# sudo crontab -e
# 6h 00 : 
0 6 * * * find /var/www/privatebin.domain.ext/data -type d -empty -delete
```

I read #276 ASAP.
