### ISSUE TITLE
Feature request: short domain url shortener

### ISSUE THREAD

**Issue by aryasenna** [PrivateBin/PrivateBin#278]
Is there any plan to add shortener for custom domain.
Bitly API support would be the easiest, I guess or maybe YOURLS for something more self-hosted.

**Comment by elrido** [comment]
That is already a supported feature. See the comments in this thread for examples:
https://github.com/PrivateBin/PrivateBin/issues/238#issuecomment-359089168

**Comment by rugk** [comment]
And if you mean to use the shortener via AJAX, see https://github.com/PrivateBin/PrivateBin/issues/238.

**Comment by aryasenna** [comment]
My bad! should have read FAQ first.

https://github.com/PrivateBin/PrivateBin/wiki/FAQ#the-url-is-so-long-cant-i-just-use-an-url-shortener
https://github.com/PrivateBin/PrivateBin/wiki/Configuration#urlshortener

Thanks for the clarification.

**Comment by Razva** [comment]
> Bitly API support would be the easiest, I guess or maybe YOURLS for something more self-hosted.

Did you managed to implement bitly? If yes, can you please share a small walkthrough?
