### ISSUE TITLE
Private backend and  public frontend?

### ISSUE THREAD

**Issue by aryasenna** [PrivateBin/PrivateBin#279]
Hi, probably a stupid question: is it possible to make Privatebin as really "private" (as opposed to public usable).
So in the sense there is backend for the user to input the paste, and the www just see the paste results in frontend.
Ofc backend may require auth.

Could there be a simple way to achieve this?

**Comment by elrido** [comment]
Yes, you would only allow access to the / (the document root of the PB installation) by password protection or your fixed IP in your webserver configuration, while allowing public access to the paste URLs at /?[a-z0-9]{16}

In addition you could modify the template, removing the new and clone buttons and remove/change the link behind the logo. That way users would not feel invited to use these buttons to create pastes.

**Comment by aryasenna** [comment]
@elrido 

Yeah, just did exactly what you suggested.
In Apache it's as simple as:

```
#PrivateBin
<Directory "www/path/to/privatebin/">
RewriteCond %{REQUEST_URI} ^/privatebin
RewriteCond %{QUERY_STRING} ^$
RewriteRule ^ - [E=auth:1]

AuthName "PrivateBin"
AuthType Basic
AuthUserFile "/path/to/.htpasswd"

# first, allow everybody
Order Allow,Deny
Satisfy any
Allow from all
Require valid-user
# then, deny only if required
Deny from env=auth
</Directory>
```

Have to tweak the template a bit, but you're right, since no server-side check is done it's simply 'discouraging' in most sense, also commenting for public link doesn't with my approach, teh form is submitted to the root path "" it seems.

but good enough.

**Comment by rugk** [comment]
> since no server-side check is done it's simply 'discouraging' in most sense

Well... you just added the server side check. It is the Apache config.
And when you disallow the root, nobody without a password can create paste. And as comments are also an "edit action", which is handled via the root, you also cannot create comments. See [the API docs](https://github.com/PrivateBin/PrivateBin/wiki/API) for details about the paths.

So your instance would basically be "read-only" for public users.

**Comment by rugk** [comment]
So as it seems this question has been answered and I thus close this issue. If anyone has further questions on that topic, feel free to comment here, again.

**Comment by rugk** [comment]
Nice work. As for the SRI (JS error mesage), see [the FAQ](https://github.com/PrivateBin/PrivateBin/wiki/FAQ#why-does-not-the-loading-message-go-away). In your case, you could also just remove the SRI hash there, then the browser would load it all.

I'm afraid it would likely not make sense to incooperate this into the main PB, however. Especially not with a unmaintained dependency (last commit 4 years ago…). :smile:

Anyway, what you do with your fork is your thing. Personally I'd rather go with server config changes, as it has been explained before.

**Comment by haywardgb** [comment]
I'm not seeing any js error messages. I followed the official guide as llinked to from your faq. Hope I didn't give you the wrong impression, I was just offering a solution for those who wanted this feature. I put the framework together, which works nicely. But I'm just asking if anyone with more coding experience than me to volunteer and help bring the scripts up to date.

Meanwhile, I'll continue to proudly host my PrivateBin instances :)

Thank you .

**Comment by akzkak** [comment]
Anyone got this working with newest Caddy webserver? Tried multiple different query matches and just dont work and will keep asking for password.

`	@auth {
		not query *=*
	}

	basicauth @auth {
		user <pass>
	}`


`	@auth {
		not	expression `{query} != ""`
	}

	basicauth @auth {
		user <pass>
	}`

`	@auth {
		not expression {uri}.contains('?')
	}

	basicauth @auth {
		user <pass>
	}`

**Comment by Kofl** [comment]
Did you get it running with Caddy?

**Comment by Herve-M** [comment]
@Kofl In case of, this allows access but block public creation: 

With basic_auth
```caddyfile
@share host bin.domain.com
	handle @share {
		@write_methods {
			not method GET HEAD
		}
		basic_auth @write_methods {
			# Username "Bob", password "hiccup"
		        Bob $2a$14$Zkx19XLiW6VYouLHR5NmfOFU0z2GTNmpkT/5qqR7hx4IjWJPDhjvG
		}

		reverse_proxy privatebin:8080
	}
```

**Comment by rugk** [comment]
@Herve-M feel free to create a wiki page/link it [from this FAQ](https://github.com/PrivateBin/PrivateBin/wiki/FAQ#how-can-i-link-to-a-read-only-mode-where-users-cant-submit-pastes) so others can find it more easily.
