### ISSUE TITLE
urlshortener does not work in master

### ISSUE THREAD

**Issue by rogierm** [PrivateBin/PrivateBin#280]
## Steps to reproduce

1. git clone master
2. update conf.php to enable urlshortener
3. There is no  Shorten URL button. 

### What happens
No Shorten URL button appears when you enable urlshortener in conf.php

### What should happen
The Shorten URL button should appear

## Additional information
When I checkout tags/1.1.1 the Shorten URL button works as expected.

## Basic information

**Server address**:

**Server OS:** CentOS 7

**Webserver:** Nginx PHP-FPM

**Browser:**

**PrivateBin version:** master does not work

I can reproduce this issue on <https://privatebin.net>: Yes / No

**Comment by sprnza** [comment]
I was struggling with it for 2 hours! I thought something's wrong with my url-shorteners!! I don't have the shorten button even with 1.1.1 though.

**Comment by rugk** [comment]
But you can confirm it does not work in master?

**Comment by sprnza** [comment]
Yes, no button in master.

**Comment by elrido** [comment]
@rugk I did test it on my instance and could also replicate it. The HTML with the "data-shortener"-property containing the configured URL gets generated, but when sending the paste, the JS removes the "shortenbutton" ID, regardless of the presence of the "data-shortener"-property being there or not.

I assume this is a regression of the JS refactoring. Will try to provide you a unit test case over the weekend. Would be great if you could look into this.
