### ISSUE TITLE
Missing translation for: 'Cloning paste…'

### ISSUE THREAD

**Issue by elrido** [PrivateBin/PrivateBin#282]
## Steps to reproduce
1. Look at any paste (create one if necessary)
2. Open the browser console pressing [F12] and select the "Console" tab in it
3. Click on the clone button

### What happens
The paste gets cloned, the browser console contains the message:
"Missing translation for: 'Cloning paste…' in language de"

### What should happen
No "Missing translation" message in the console.

## Additional information
The message in question "Cloning paste…" is not translated in any of the json files. It is added to the status bar by the JS logic (js/privatebin.js, line 3888) until the UI was updated with the cloned paste in the new paste interface. Then the message is hidden again (line 3921, I assume).

Since I don't have any machine (not even on my mobile phone) that is so slow that the message is ever visible for even the blink of an eye, I suggest that instead of adding this message to the translation, we remove the lines 3888 and 3921. The Alert.showLoading() interface, to me, makes more sense for network interactions that can be slow. The UI should (hopefully) refresh fast enough that these extra steps can be skipped (making the UI even faster :wink:).

## Basic information

**Server address**: https://zerobin-test.dssr.ch/

**Browser:** Firefox 58 with German localization (I assume the same error happens for any non-English localization that we support)

**PrivateBin version:** 9c132cd839fd5e91da18e4a1e8ebef64fce605fb

I can reproduce this issue on <https://privatebin.net>: No

**Comment by elrido** [comment]
@rugk What do you think of my proposition on this issue? Should we just remove this message instead of adding it to the translation?

**Comment by rugk** [comment]
I don't know exactly where it is used, but is not it just the replacement of the "Loading…" message that is also shown when the paste is e.g. downloaded.
So as we also localize the loading message, I'd say just show it anyway. 
But if no network interaction is done while cloning the paste (which it is AFAIK), it likely is always fast (the best thing you could do is test it on a mobile device), so I don't care if you just remove it.

**Comment by r4sas** [comment]
So, what to do? Add that message to lanf file (I'll update `ru`)

**Comment by elrido** [comment]
The message is never visible, not even on mobile as it is only "displayed" during a DOM element copy. Hence I suggested to just remove lines 3888 and 3921 (or whatever these now are). I think rugk is fine with it.
