### ISSUE TITLE
Error loading raw text

### ISSUE THREAD

**Issue by ageis** [PrivateBin/PrivateBin#284]
This was a one-time paste made with the 'privatebin' CLI program (which I will be submitting some PRs to add more options)

The raw text never loaded and tihs was in my console. 
![rawtext](https://user-images.githubusercontent.com/1161532/36475340-26b31476-16af-11e8-94ca-3ace60db4a34.png)

If you need any further info from me, let me know. I might have some security headers and non-standard nginx configs.

**Comment by rugk** [comment]
Which version do you use? (Generally, please use the issue template, when reporting bugs.)

And the text does load when you do not use raw?

**Comment by ageis** [comment]
Yes, it loads without raw. I'm running latest Chrome  64.0.3282.167. Your latest tarball 1.1.1 from the releases page. I'll test this in Firefox in a moment.,

**Comment by ageis** [comment]
OK, I am tentatively blaming this on Cloudflare's [Rocket Loader](https://support.cloudflare.com/hc/en-us/articles/200168056-What-does-Rocket-Loader-do-)...I have some knowledge as a former employee.
I cleared the cache and I started getting invalid SHA512 digest errors. Then disabled Rocket Lodader, cleared it again, and raw text loads. Auto-minify is fine.

**Comment by ageis** [comment]
@rugk You should look at adding `data=cfasync=false`. Reference: https://support.cloudflare.com/hc/en-us/articles/200169436-How-can-I-have-Rocket-Loader-ignore-my-script-s-in-Automatic-Mode-

**Comment by ageis** [comment]
This is a little deeper. I think the auto-minify feature might be involved by changing the hash of the JS? 

```Failed to find a valid digest in the 'integrity' attribute for resource 'https://paste.cointel.pro/js/jquery-3.1.1.js' with computed SHA-256 integrity '46t/87Ci6dVYyXhdR7BUGsURsZH7ZD8gLEmNWJEMGw8='. The resource has been blocked.
paste.cointel.pro/:1 Failed to find a valid digest in the 'integrity' attribute for resource 'https://paste.cointel.pro/js/sjcl-1.0.6.js' with computed SHA-256 integrity 'Y43KaWNpaTU1SqEO/QbqkdFfMFzEJ3Bk8CcqdFuG758='. The resource has been blocked.
paste.cointel.pro/:1 Failed to find a valid digest in the 'integrity' attribute for resource 'https://paste.cointel.pro/js/kjua-0.1.2.js' with computed SHA-256 integrity 'GFSjIieVfZ/LDME97q6hd9jK1q4JwzeJ7ssimXGQvkM='. The resource has been blocked.
paste.cointel.pro/:1 Failed to find a valid digest in the 'integrity' attribute for resource 'https://paste.cointel.pro/js/rawdeflate-0.5.js' with computed SHA-256 integrity '/+ZUNyHiaR3949OkBz2ghRaTrD5ln/vRbkZM2E7ysvM='. The resource has been blocked.
paste.cointel.pro/:1 Failed to find a valid digest in the 'integrity' attribute for resource 'https://paste.cointel.pro/js/rawinflate-0.3.js' with computed SHA-256 integrity '7y4SHL162M7wOnt2x2cVVl5NXTI9d4BoU+a+IFg/37c='. The resource has been blocked.
paste.cointel.pro/:1 Failed to find a valid digest in the 'integrity' attribute for resource 'https://paste.cointel.pro/js/bootstrap-3.3.7.js' with computed SHA-256 integrity '8ldiyV/YLjnDL6ZCgl81UM3UFGMkPrFOCNJXL3itBrw='. The resource has been blocked.
paste.cointel.pro/:1 Failed to find a valid digest in the 'integrity' attribute for resource 'https://paste.cointel.pro/js/prettify.js?1.1.1' with computed SHA-256 integrity 'JONiSL104IHYjdUbqPME8rx/ZLrhmPTV8J54baYHv30='. The resource has been blocked.
paste.cointel.pro/:1 Failed to find a valid digest in the 'integrity' attribute for resource 'https://paste.cointel.pro/js/purify-1.0.3.js?1.1.1' with computed SHA-256 integrity 'TzQFfUYoWoORNxOH2sq4EiD65iXKb6EQOp9UKc/Pv5M='. The resource has been blocked.
paste.cointel.pro/:1 Failed to find a valid digest in the 'integrity' attribute for resource 'https://paste.cointel.pro/js/privatebin.js?1.1.1' with computed SHA-256 integrity 'qsLp7Qq9p+gjqRFBBk1UUOOBIYm/agenBBPaBEa01Mk='. The resource has been blocked.```

I turned all that off, and then I realized I had an nginx proxy_cache too that I should clear... I took the site off Cloudflare again, and it loaded and I could enter pastes. 

I turned Cloudflare back on with auto-minify JS disabled and both raw text and pasting into the form worked. (but also disabled some other stuff with their "Page Rules". Might necessitate a note for anyone who uses them for DNS.

**Comment by rugk** [comment]
> OK, I am tentatively blaming this on Cloudflare's Rocket Loader...I

Oh, Cloudflare again...

> I think the auto-minifying feature might be involved by changing the hash of the JS?

Yeah, of course. It changes the SRI hash.

All that is a known issue. See the [FAQ](https://github.com/PrivateBin/PrivateBin/wiki/FAQ#user-content-how-to-make-privatebin-work-when-using-cloudflare-for-ddos-protection). It's always a good idea to look at the FAQ... 😉 

>You should look at adding data=cfasync=false.

Interesting. Does that fix the issue and work with Cloudflare?
For this feature, I'll keep this issue open. If it works, feel free to send a PR.
