### ISSUE TITLE
Fix composer build

### ISSUE THREAD

**Issue by rugk** [PrivateBin/PrivateBin#288]
For each commit or so I get a mail that tells me the composer build failed.

Basic reason:
> License "zlib" is not a valid SPDX license identifier, see https://spdx.org/licenses/ if you use an open license.
If the software is closed-source, you may use "proprietary" as license.

**Comment by elrido** [comment]
Yep, got those, too. According to that site, we have to either use "Zlib" or "zlib-acknowledgement", but "zlib" isn't recognized anymore. Hence my commit df921ad658690d5844a435fa9c359e5c91750e11 a couple of days ago. I have now merged this into all the branches.
