### ISSUE TITLE
Suggestion for API documentation

### ISSUE THREAD

**Issue by Gmax76** [PrivateBin/PrivateBin#289]
Hello,
After struggling for a while and reading through various issues, I realised that data encryption for the api can only be done using the RawDeflate.js in this repo, and no other method can work as this js lib appears not to be RFC compliant and I couldn't find it implemented in any other language. 
Can you please mention this in the API wiki so that other people won't try and implement non js API clients in vain?
I understand that backward compatibility is the main purpose in this application updates, but maybe you could propose a new version using standard methods for compression and provide backward compatibility using RawDeflate.js the same way you provided compatibility with Zerobin?

[edit] just noticed new encryption methods is in the roadmap!

Thanks!

**Comment by rugk** [comment]
It is not only on the roadmap, but there is actually a PR for that: https://github.com/PrivateBin/PrivateBin/pull/193

**Comment by rugk** [comment]
I've mentioned the issue in https://github.com/PrivateBin/PrivateBin/wiki/Encryption-format.
