### ISSUE TITLE
Could not create paste: server error or not responding

### ISSUE THREAD

**Issue by hyperdefined** [PrivateBin/PrivateBin#291]
## Steps to reproduce

1. When I create a paste.

### What happens
"Could not create paste: server error or not responding"

## Additional information
I am using nginx, and it is giving me this error in the log:
https://gist.github.com/hyperdefined/aec551c192b5ae624c6b0fa26fcd5174

I removed some info obviously.

**PrivateBin version:**
Latest version

**I can reproduce this issue on <https://privatebin.net>: Yes / No**
No, self-hosted issue.

**Comment by rugk** [comment]
PHP cannot create a dir, so this looks like a permission issue. Maybe have a look at https://github.com/PrivateBin/PrivateBin/wiki/FAQ#what-are-the-recommended-file-and-folder-permissions-for-privatebin to see the recommend permissions, or create the dir manually.
