### ISSUE TITLE
PHP form + PrivateBin API

### ISSUE THREAD

**Issue by emillod** [PrivateBin/PrivateBin#294]
Hi guys
i want to create form in PHP and create field to enter password(my friends will be able to share with me some passwords).
If someone enter password i want to sent that password through API PrivateBin and attach URL to PrivateBin note to e-mail with informations from form. 

I can build form and prepare everything else, but i have some problems with creating those notes through PrivateBin API. Maybe someone have already some examples in PHP using cURL or something :)

**Comment by rugk** [comment]
I doubt it is generally a good idea to send your password to someone (independent of the way/encryption), but theoretically it should be possible.
Also, it makes even less sense, when you do not use the self-destroy option, but let's not talk about the actual use case. (although I am interested in what you actually want to accomplish/why)

So theoretically it should be possible. Maybe also have a look at the [existing third-party clients](https://github.com/PrivateBin/PrivateBin/wiki/Third-party-clients).

**Comment by emillod** [comment]
Thanks for reply.
I have default marked checkbox destroy after someone read note :) 

For example if you're web developer and Your clients want to share with You some passwords to website and etc. They're in most cases use e-mail with passwords in plaintext. 
Some client - sure, want to secure passwords and They trying PrivateBin. But more then 50% don't want to sent password through PrivateBin because interface have too many options and etc. So i think about it and i create in my head something like simple form with few fields. If they want to share with me some passwords, they can paste those passwords in field and after they click "Sent", my script will sent those information to PrivateBin through api :)

**Comment by rugk** [comment]
> I have default marked checkbox destroy after someone read note

Note that when you use the API, that of course does not apply. The default setting is just a UI thing.

> PrivateBin because interface have too many options

I doubt that, but fine… :smile: 

So okay, I think you still need to call the API. if it is a website, you also may need to allow cross-origin requests, depending on how PrivateBin/where PrivateBin is hosted.

**Comment by emillod** [comment]
But i can set up destroy after someone read note, right? :) 
I know that UI have simple interface, but i think some old clients can be confused.

OK. Can You help me with prepare some API request for PHP? Because i already tried something in Postman, but i can't create note.

**Comment by rugk** [comment]
Have a look at the wiki (https://github.com/PrivateBin/PrivateBin/wiki/API) and  [existing issues](https://github.com/PrivateBin/PrivateBin/issues?utf8=%E2%9C%93&q=is%3Aissue+curl).

**Comment by elrido** [comment]
How about a different approach: Instead of trying to implement all the client side JS logic to encrypt the data you send to the API (the API will only accept encrypted content encapsulated in JSON, not plain GET or POST data), you could maybe just hide the bits of one of the existing templates that you don't want to support in your instance.

Here is the [Wiki page on templates](https://github.com/PrivateBin/PrivateBin/wiki/Templates) as a very brief start. Just copy one of the template files, configure your PrivateBin to use it and start to remove the parts of the UI that you want to hide. If that fails, you could try to just hide these elements using a custom CSS file.

**Comment by emillod** [comment]
@elrido  thanks for reply. I can try :) I need to think about this. Thanks again
