### ISSUE TITLE
Internet Explorer can't download files

### ISSUE THREAD

**Issue by nielsvr** [PrivateBin/PrivateBin#295]
## Steps to reproduce
1. Upload a file using the file upload method form PrivateBin
2. Try to download the file with Internet Explorer (10, 11, Edge)

### What happens
Nothing happens, the browser does not download the file.

### What should happen
A file download should be initiated

## Additional information
Tried with the latest version from PrivateBin I pulled from this repo.

## Basic information

**Server OS:**
CentOS 7

**Webserver:**
APACHE 2

**Browser:**
Internet explorer 10, 11, EDGE

**PrivateBin version:**
1.1.1

I can reproduce this issue on <https://privatebin.net>: No / File uploads disabled

**Comment by nielsvr** [comment]
I figure it has something to do with the data:application/pdf;base64 URL structure.

**Comment by elrido** [comment]
Historically this project has never supported IE. Personally I do not have any Windows installations and hence have no chance to even test or debug this.

We can leave this issue open, of course, in case someone has the means and wants to spend time on this.

**Comment by rugk** [comment]
BTW IE, okay, but the OP says it also affects Edge, so a recent browser.

**Comment by elrido** [comment]
There is still no Edge on Linux. ;-)

**Comment by r4sas** [comment]
@nielsvr can you send example uri to paste with file?

**Comment by rugk** [comment]
BTW how big was the file? Did you try it with a small file?

Currently used [data URIs can be a bit restricted](https://caniuse.com/#feat=datauri) (max. 4GB and only "linked resources" – whatever that means) So can you test it with a small CSS file, e.g.?
