### ISSUE TITLE
Unable to load when browser has no preferred language defined

### ISSUE THREAD

**Issue by pantunez** [PrivateBin/PrivateBin#296]
## Steps to reproduce
Tested with Firefox
1. Remove all preferred languages : Options > Languages > Choose your preferred language for displaying pages
2. The list is empty. Now you can go to https://privatebin.net

### What happens
You are not able to load the webpage. You follow the [FAQ to troubleshoot](https://github.com/PrivateBin/PrivateBin/wiki/FAQ#why-does-not-the-loading-message-go-away) but this doesn't help.

The console shows the messages about `loadTranslations`

### What should happen
The page should load with a default language.

I can reproduce this issue on <https://privatebin.net>: Yes

**Comment by rugk** [comment]
How can you reproduce this on https://privatebin.net? You don't have access to the configuration there… :smile: 

Also you link to the FAQ about the "Loading message". So is this message shown or not?

Maybe you can attach a screenshot?
And please add the console output, too.

--

Actually, i got what you mean. The browser options. It does indeed do something, but JS fails and ends with some undefined:

![grafik](https://user-images.githubusercontent.com/11966684/38446208-1fa0fa3e-39f7-11e8-9820-5e9ca8c14fd2.png)

That's funny… Likely a rare browser configuration, but of course this should not cause PB to break. :smiley: 

Are you able to test it with a version from master?
