### ISSUE TITLE
Deleting expired pastes

### ISSUE THREAD

**Issue by elrido** [PrivateBin/PrivateBin#3]
@Draky50110:

Hello (again)

A simple tool : http://links.kevinvuilleumier.net/?qzwJlQ (zip file in title).

When a paste is expired, the file is still on the server.
This tool deletes expired files/pastes.
It also displays some info (numbers of pastes, of expired pastes, and so).

Of course, it will only work if the "database" is "zerobin_model".

But this might be a good option : when a paste is created, this fonction is ran to clear the system.
Transparent :)
Could be disabled in conf.ini ("runpurgewhencreatingpaste") ?

And maybe possible to adapt it with other database model (mysql/pgsql/etc.)...

---

@Hexalyse:

This tool shouldn't be run on each paste creation. Imagine a Zerobin with thousands of pastes and dozens of active users, it would ruin your disk I/Os.
We could consider running it at paste creation, if it hasn't been run for X minutes/hours, it would be more modulable and configurable.

---

@Draky50110:

Ok, in fact I don't know how is it possible to configure it ;) but the tool is here though... :) 

---

@elrido:

I would also rather go with a "softcron" approach as Hexalyse suggests. Ideas could be:
- per triggered "cron" only delete i.e. up to 10 (configurable) outdated pastes to reduce the delay introduced by the operation.
- have a rate limiting mechanism to ensure it only runs (earliest) after certain interval (similar to the traffic limiter)
- the method to find outdated pastes might be different in DBs (where its just another where condition) then in the data file model

---

@bpvarsity:

As anyone come up with a way to run a cron to delete the outdated pastes yet? Seems odd that the site doesn't delete expired pastes automatically. 

---

@elrido:

Nope, sorry, did not yet look into this.

I made some progress in regards to [#60](https://github.com/elrido/ZeroBin/issues/60) and plan to get back to work on release 0.23 (which should include this feature) when I am finished migrating all my sites and services to my new infrastructure.

---

@bpvarsity:

Awesome thanks

**Comment by Draky50110** [comment]
@elrido I know this tool, it is because I use it that I suggested this idea as integrated in ZeroBin :p

**Comment by elrido** [comment]
I'm sorry if the migration of the issues into the renamed repo of the fork caused any confusion. :-(

**Comment by Draky50110** [comment]
No problem.
Why did you rename it by the way ?
Cause dev from scratch ?

**Comment by elrido** [comment]
See this issue here: [Detach this repo / New name](https://github.com/elrido/ZeroBin/issues/79)

**Comment by elrido** [comment]
Sorry, I forgot to add these options in the configuration file.

**Comment by ZerooCool** [comment]
@Draky50110 say :
A simple tool : http://links.kevinvuilleumier.net/?qzwJlQ (zip file in title). 

...

It's the PrivateBin/data/purge.php ?

**Comment by elrido** [comment]
Yes, when this ticket was originally opened, the purge limiter hadn't been implemented yet. It got added in f8bc40b4e47 and 20cf678a75c in July 2016.
