### ISSUE TITLE
Update sjcl

### ISSUE THREAD

**Issue by rugk** [PrivateBin/PrivateBin#30]
We might update sjcl to [1.0.3](https://github.com/bitwiseshiftleft/sjcl/releases/tag/1.0.3) or 1.04 [if there is such a version](https://github.com/bitwiseshiftleft/sjcl/issues/310).

**Comment by rugk** [comment]
Tag for 1.0.4 was added, so this is the most recent version.

**Comment by elrido** [comment]
I did not find any change log, but all our functions are still there and I could not create any regressions with existing pastes, so I upgraded it with commit 6b20836.

**Comment by rugk** [comment]
Nice. The only "changelog" I could find is https://github.com/bitwiseshiftleft/sjcl/tree/1.0.4#103---104...
