### ISSUE TITLE
Document project goals

### ISSUE THREAD

**Issue by rugk** [PrivateBin/PrivateBin#300]
We are so bad, we don't even have some design goals for contributions. :wink: 
Maybe add them [in the Readme](https://opensource.guide/building-community/#treat-your-readme-as-a-constitution)…

E.g. the fact that we really want server admins to git pull the repo and use it. So no pre-processing…
-> setting up 

This issue appeared because of https://github.com/PrivateBin/PrivateBin/pull/299.

**Comment by elrido** [comment]
Is this maybe related to #177 (Create threat model)? Both seem to indicate that our current documentation is not clear enough in certain aspects.

**Comment by rugk** [comment]
Yes certainly related, but not really more. These are two different aspects, although there may be some overlaps.

**Comment by elrido** [comment]
Have extended our [development wiki page](https://github.com/PrivateBin/PrivateBin/wiki/Development) quite a bit. Hope this covers all you had in mind for this. Let me know if there are additional topics you think we should cover in that document.

**Comment by rugk** [comment]
Well:

> E.g. the fact that we really want server admins to git pull the repo and use it. So no pre-processing…

This is still not mentioned. :smile: 

Your guide-rewriting is great and really needed, but for "project goals" I had simpler things in mind, e.g.:
* offer a simple service, where you can paste in stuff
* preview/format pasted text
* make it reasonable secure (-> link to threat model e.g.)
* be easy and simple to setup (i.e. the stuff mentioned above)

**Comment by elrido** [comment]
Super, thanks for the input.

**Comment by elrido** [comment]
I added "Basic Features" and "Ease of Installation" sections to cover these. IMHO these are really common sense things. We do not want server admins to install using git clones, that is a use case for developers. The main installation method should be using git archive generated release archives.
