### ISSUE TITLE
next release?

### ISSUE THREAD

**Issue by jeyca** [PrivateBin/PrivateBin#306]
Since the version 1.1.1 there has been nearly 400 commits already, are you planning a new release soon? I am also asking because I am not sure if I should install from master or from the release tag which is quiet old!?

**Comment by rugk** [comment]
There are still some quite big PRs, which are still open, but we'll have a look at when we can release the next version.

**Comment by elrido** [comment]
Having spent over a year working on and off on the JS unit tests, I think we may need to draw a line somewhere and publish the release as it is. It may still have some obscure regressions from the refactoring in it that we haven't found, but at least the major features now all seem to work again. I'll be loocking at the PRs and we can then start to prepare a release, following the usual checklist.

**Comment by cryptomilk** [comment]
Ping! :-)
