### ISSUE TITLE
New logo suggestion

### ISSUE THREAD

**Issue by pozzo-balbi** [PrivateBin/PrivateBin#31]
How about a new logo. Here two simple suggestions generated from GNOME icons. One logo and one icon to be used as favicon.

![privatebin svg](https://cloud.githubusercontent.com/assets/3755138/16711834/5386cc1c-4678-11e6-9265-cf39c06685a6.png)
![privatebin-icon svg](https://cloud.githubusercontent.com/assets/3755138/16711835/57c03476-4678-11e6-959c-5c6ebc38e3a6.png)
[privatebin.zip](https://github.com/PrivateBin/PrivateBin/files/355852/privatebin.zip)

**Comment by rugk** [comment]
This icon is nice, but you could have posted this in https://github.com/PrivateBin/PrivateBin/issues/23.
So I am closing this as a dupe.

However it is still a black & white icon. Also if we use this icon it should not look too similar to the original GNOME icons. Can you show us the GNOME icons you used?

Furthermore there is nothing :bee: related. :wink:
