### ISSUE TITLE
Minor bug: Invalid URL generated

### ISSUE THREAD

**Issue by duhow** [PrivateBin/PrivateBin#310]
If you load the url with ending `/?`, for example using public https://privatebin.net/? , when generating the paste link, it contains two `??`, making the URL invalid, for example `https://privatebin.net/??d63275...`

**Comment by Arregi** [comment]
I wasn't able to reproduce this bug, working with version 1.2.1. 
In fact you can generate a link and use it, when you hit 'new' from there, the url has the ending of the used paste but is not interfering in any way. o_O
Am I missing something?

**Comment by duhow** [comment]
Seems to be already fixed.

**Comment by elrido** [comment]
Thank you for reporting this back! Sorry, for not having reviewed this earlier. It was likely fixed during the refactoring of the JS code for 1.2. The [changes from 1.2 to 1.2.1](https://github.com/PrivateBin/PrivateBin/compare/1.2...1.2.1#diff-cf28a0bc390eee2482509aca8212f831) are rather minimal on the JS side.
