### ISSUE TITLE
Improve drag & drop UI

### ISSUE THREAD

**Issue by rugk** [PrivateBin/PrivateBin#317]
The UI should:
* show an indicator/stuff (like full page dark overlay) when a file is hovered
* it may open the "attach file" dropdown when a file is dropped, so one knows it has been accepted

**Comment by Haocen** [comment]
Is this WIP? Because I want to take it.

**Comment by elrido** [comment]
Don't think anyone started working on it -> Go for it!

**Comment by Haocen** [comment]
Yep, got it working on 1.2.1, will port it onto 1.3

**Comment by Haocen** [comment]
![upload UX](https://user-images.githubusercontent.com/10842569/63139149-3a4dc980-bfab-11e9-9121-18460d16d143.gif)

Does this looks good to everyone?

**Comment by elrido** [comment]
Looks very promising!
