### ISSUE TITLE
Two file names shown when using both file picker & drag/drop

### ISSUE THREAD

**Issue by rugk** [PrivateBin/PrivateBin#318]
https://github.com/PrivateBin/PrivateBin/issues/315#issuecomment-390805312

![](https://user-images.githubusercontent.com/7023612/40324591-ab16be38-5d41-11e8-8a6f-1048573f4c72.png)

**Comment by r4sas** [comment]
Way to reproduce:
1. Select attachment with `Browse` button.
2. Copy file in filesystem or picture to buffer.
3. Execute "paste" (Ctrl+V) command on PrivateBin page.

**Comment by r4sas** [comment]
Can we use `AttachmentViewer.removeAttachment` with `addDragDropHandler` and `addClipboardEventHandler`?

**Comment by rugk** [comment]
The drop handler is and should always be there, of course.

The issue is `$fileWrap.find('input').val('');` is only possible for clearing the file picker. For security reasons, you cannot manualyl set a file name even there.
`removeAttachment` does something completely different if I remember (it's about the preview) correctly.

What we could do is hide the file picker completely if drag- and drop is done, but then you cannot select a different file with the file picker, afterwards.

**Comment by r4sas** [comment]
I'm trying to suggest to clear the field of the selected file when adding a file from the buffer (like `Remove attachment` action before processing pasted file with `readFileData` function).
