### ISSUE TITLE
Migrate pastes from flat files to database

### ISSUE THREAD

**Issue by brunob** [PrivateBin/PrivateBin#321]
Just a quick question, is there a way to migrate pastes stored in flat files to a mysql db ?

We are in the process of switching a zerobin to a privatebin and i haven't found any mention of this use case in the wiki or older issues.

Thx ++

**Comment by rugk** [comment]
Well… you would have to write some scripts, I guess. There is no built-in way, at least.

**Comment by brunob** [comment]
@rugk thx for the info, feel free to close this issue ;)
