### ISSUE TITLE
PDOException, SQL Error near 'IF NOT EXISTS comment_parent ON comment(pasteid)'

### ISSUE THREAD

**Issue by radonthetyrant** [PrivateBin/PrivateBin#324]
## Steps to reproduce

1. Perform clean install with Version 1.1.1
2. Setup config so that it uses mysql without table prefix
3. Try to add a paste

### What happens
When Creating a new paste, the page displays "Could not create paste: server error or not responding"
The php log says:
```
PHP Fatal error:  Uncaught PDOException: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'IF NOT EXISTS comment_parent ON comment(pasteid)' at line 1 in /path/to/PrivateBin-1.1.1/lib/Data/Database.php:610
Stack trace:
#0 /path/to/PrivateBin-1.1.1/lib/Data/Database.php(610): PDO->exec('CREATE INDEX IF...')
#1 /path/to/PrivateBin-1.1.1/lib/Data/Database.php(120): PrivateBin\\Data\\Database::_createCommentTable()
#2 [internal function]: PrivateBin\\Data\\Database::getInstance(Array)
#3 /path/to/PrivateBin-1.1.1/lib/Model.php(88): forward_static_call('PrivateBin\\\\Data...', Array)
#4 /path/to/PrivateBin-1.1.1/lib/Model.php(58): PrivateBin\\Model->_getStore()
#5 /path/to/PrivateBin-1.1.1/lib/PrivateBin.php(282): PrivateBin\\Model->getPaste()
#6 /incomplete-path/su in /path/to/PrivateBin-1.1.1/lib/Data/Database.php on line 610
```

### What should happen
The paste should be inserted into the table.

## Additional information
Trying to add the paste again results in a different sql error:
```
PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000]: General error: 2014 Cannot execute queries while other unbuffered queries are active.  Consider using PDOStatement::fetchAll().  Alternatively, if your code is only ever going to run against mysql, you may enable query buffering by setting the PDO::MYSQL_ATTR_USE_BUFFERED_QUERY attribute. in /path/to/PrivateBin-1.1.1/lib/Data/Database.php:671
Stack trace:
#0 /path/to/PrivateBin-1.1.1/lib/Data/Database.php(671): PDO->exec('ALTER TABLE pas...')
#1 /path/to/PrivateBin-1.1.1/lib/Data/Database.php(138): PrivateBin\\Data\\Database::_upgradeDatabase('0.21')
#2 [internal function]: PrivateBin\\Data\\Database::getInstance(Array)
#3 /path/to/PrivateBin-1.1.1/lib/Model.php(88): forward_static_call('PrivateBin\\\\Data...', Array)
#4 /path/to/PrivateBin-1.1.1/lib/Model.php(74): PrivateBin\\Model->_getStore()
#5 /path/to/PrivateBin-1.1.1/lib/PrivateBin.ph in /path/to/PrivateBin-1.1.1/lib/Data/Database.php on line 671
```
conf.php (portion with the database model)
```
;[model]
; name of data model class to load and directory for storage
; the default model "Filesystem" stores everything in the filesystem
;class = Filesystem
;[model_options]
;dir = PATH "data"

[model]
; example of DB configuration for MySQL
class = Database
[model_options]
dsn = "mysql:host=localhost;dbname=privatebin;charset=UTF8"
tbl = ""	; table prefix
usr = "privatebin"
pwd = ***
opt[12] = true	  ; PDO::ATTR_PERSISTENT

;[model]
; example of DB configuration for SQLite
;class = Database
;[model_options]
;dsn = "sqlite:" PATH "data/db.sq3"
;usr = null
;pwd = null
;opt[12] = true	; PDO::ATTR_PERSISTENT
```

## Basic information

**Server address**: private

**Server OS:** Ubuntu 16.04.4 LTS

**Webserver:** apache2

**Browser:** Chromium

**PrivateBin version:** 1.1.1

I can reproduce this issue on <https://privatebin.net>: No

**Comment by elrido** [comment]
The first is a permission error, the second is likely the result of the first query failing and PHP therefore not having cleaned its connection buffer (MySQL can have only one query result buffered per session, so the results need to be fully fetched before another one can be prepared - we prepare all queries, for SQL injection protection).

Anyway: You are doing the right thing by limiting the permissions of privatebin, but it blocks the automatic table creation and table update mechanisms. You can manually create the tables to avoid having to give PrivateBin these permissions. The schemas are in the [install wiki](https://github.com/PrivateBin/PrivateBin/wiki/Installation#using-a-database-instead-of-flat-files). I'll update the article with the required permissions for MySQL.

**Comment by radonthetyrant** [comment]
@elrido I commented out `opt[12] = true	  ; PDO::ATTR_PERSISTENT` in the mysql config and the error vanished.
Were the missing permissions related to this PDO setting?

**Comment by elrido** [comment]
It has nothing to do with permissions, but is to keep the session with MySQL alive between requests to PrivateBin. Without it, you will see lower performance, as we have to reconnect (login) every time there is a call to PrivateBin that goes to database (storing or retrieving pastes). This may not be a big issue, we are talking a few more milliseconds per request, but has more impact on large sites (> 100 requests per second).

It certainly solves the second error, which was about an unbuffered query that wasn't concluded. It could have something to do with permissions in case you changed the permissions after trying to save a paste and then not running a `FLUSH PRIVILEGES;`, which applies the privileges AFAIK also to running sessions.
