### ISSUE TITLE
editing of metadata is possible

### ISSUE THREAD

**Issue by himpierre** [PrivateBin/PrivateBin#326]
## Steps to reproduce
1. create paste with "burn after reading" option
2. edit metadata "burnafterreading:true" to "burnafterreading:false"
3. paste has no longer burnafterreading feature

### What happens
paste no longer burns after reading

### What should happen
i'm not sure. can we encrypt the metadata too?

thanks and cheers

**Comment by rugk** [comment]
You mean you edit it on the server? Yeah, totally possible.

As for the "burn after reading" this cannot be encrypted, as the server has to verify/know it has to delete the paste. And we cannot trust the client's response there, as it could be forged.

What we could do if we use an AEAD is to put it into the "only signed, not encrypted" part, but what is actually the point of signing it? If the server admin was to prevent the paste deletion, they would have many other ways…

So no, this is unfortunately not possible.

**Comment by himpierre** [comment]
@rugk thanks for the explanation.
