### ISSUE TITLE
Mega not properly linked in Plain Text format

### ISSUE THREAD

**Issue by psycholyzern** [PrivateBin/PrivateBin#331]
## Steps to reproduce

1. Paste link from mega.nz (Example: https://mega.nz/#!aqRwQQiS!GVjYc3kAS4nYvsv2kHyTbvf4TRZUpdTMz5CZ6bVFwo)
2. Submit as Plain Text

### What happens
Only `https://mega.nz/#` converted into clickable link. The other part (`!aqRwQQiS!GVjYc3kAS4nYvsv2kHyTbvf4TRZUpdTMz5CZ6bVFwo`) is ignored.

### What should happen
Full url should be converted into clickable link

## Basic information

**Server address**:

**Server OS:** Ubuntu 16.04

**Webserver:** Nginx 1.14.0

**Browser:** Chrome for Android

**PrivateBin version:** 1.1.1

I can reproduce this issue on <https://privatebin.net>: Yes

**Comment by elrido** [comment]
Yepp, the [regex doing that](https://github.com/PrivateBin/PrivateBin/blob/14d422617372a94d0b69be8851bb435a7b868ee6/js/privatebin.js#L148) doesn't include exclamation marks for https links.

**Comment by rugk** [comment]
So I've added our regex with some unit tests from [here](https://mathiasbynens.be/demo/url-regex) here: https://regex101.com/r/h4ACei/1

Of course we do not need to pass all these unit tests, that would be unlikely to be done. But I have them for comparing 

An easy fix for this would be https://regex101.com/r/h4ACei/2 (just added `!`).
https://regex101.com/r/h4ACei/3 may be even better to also allow Wikipedia-style links (with `()`). 

The issue with these both of course is, that they may still match at the end of the sentence, i.e. when you end with a link like https://privatebin.info! (the link ends with ! there).

So maybe we generally search for a common one. I wonder which one services like GitHub, Stackoverflow or Markdown parsers in general use…

This https://regex101.com/r/h4ACei/4 (https://stackoverflow.com/questions/161738/what-is-the-best-regular-expression-to-check-if-a-string-is-a-valid-url#answer-2015516) looks quite nice.

**Comment by elrido** [comment]
Sure, feel free to change it. Just make sure it still passes our unit test (run the mocha unit test, i.e. in Janitor or our unit-testing container).

**Comment by rugk** [comment]
BTW also found the RegEx that showdown uses for detecting URLs and similar stuff. It's here:

https://github.com/showdownjs/showdown/blob/3db9200d2c293d3977948558b2a4aace3e86d6ac/src/subParsers/makehtml/autoLinks.js#L3-L7

For us, this would be: https://regex101.com/r/8nasII/2

So maybe we better use it? Or not, as it seems to be a bit too permissive, i.e. e.g. not catching when the URL just ends with a `)`. Or actually it somehow manages/checks it via JS then and does something with that, huh… :man_shrugging:

**Comment by elrido** [comment]
While the mega link issue is fixed, @rugk found another issue with brackets (i.e. wikipedia links) so the PR is not concluded yet, but at least the OPs original problem will (finally) be solved in an upcoming release.

**Comment by dausruddin** [comment]
Bracket detection still not fixed?
