### ISSUE TITLE
CSP 'style-src' error in dark template

### ISSUE THREAD

**Issue by r4sas** [PrivateBin/PrivateBin#332]
Hi!
I tested CSP on my installation of PBin, and got that error:
```
Content Security Policy: The page’s settings blocked the loading of a resource at self (“style-src https://paste.i2pd.xyz”).
```
Browser: Firefox ESR 52.5.2.
conf.php:
```
cspheader = "default-src 'self'; manifest-src 'self'; connect-src *; script-src 'self'; style-src 'self'; font-src 'self'; img-src 'self' data:; media-src data:; object-src data:; report-uri https://<removed>.report-uri.com/r/d/csp/enforce;"
```

How to set-up correclty that rules?

**Comment by rugk** [comment]
You use a custom theme? In most cases it's easy: do not use inline CSS, but put everything in extra files. For more details see https://content-security-policy.com/.

**Comment by r4sas** [comment]
Tested on FF ESR 60.0.2 with NoScript only installed (domain added to trusted, nothing is blocked), and see same error.

FF ESR 60.0.2 with clean profile without any plugins - same.

**Comment by elrido** [comment]
I have gotten report from a colleague about that error a while back in firefox and we found out that it was caused by the LastPass plugin, since that one injects JS into every page for UI changes (a button in password fields to access the password manager).

What plugins do you guys have installed?

**Comment by r4sas** [comment]
> What plugins do you guys have installed?
no add-ons installed, absolutely clean profile.

**Comment by elrido** [comment]
Obsoleted with the bootstrap5 template, unfortunately.
