### ISSUE TITLE
Security: disable browser thumbnails

### ISSUE THREAD

**Issue by macropin** [PrivateBin/PrivateBin#337]
## Steps to reproduce

Post a secret to PrivateBin with Chrome or other browser that creates automatic screen captures.

### What happens

After posting a  secret, I observed the thumbnail of secret visible in the Chrome favourite sites shortcut icons.

### What should happen

Thumbnail should not be generated.

## Additional information
See https://stackoverflow.com/questions/40612490/how-to-control-the-screenshots-of-my-website-in-the-recently-used-websites-list for discussion of mitigations.

## Basic information

**Server address**:
n/a

**Server OS:**

Debian 8. We're using this Docker image https://github.com/panubo/docker-privatebin

**Webserver:**

Apache w/ mod PHP.

**Browser:**

Google Chrome.

**PrivateBin version:**

Version 1.1.1

I can reproduce this issue on <https://privatebin.net>: Have not tried.

**Comment by elrido** [comment]
Has anyone been able to reproduce this issue?

**Comment by elrido** [comment]
Please re-open when anyone can find a way to reproduce this (aka provide a browser name and version this occurs in, so we can test it using browser stack or similar tools).
