### ISSUE TITLE
New Markdown and link libraries

### ISSUE THREAD

**Issue by rugk** [PrivateBin/PrivateBin#338]
I just stumbled upon https://github.com/markdown-it/markdown-it and https://github.com/markdown-it/linkify-it. They both look pretty nice and seem to solve a few issues, we have.
First of all, we could drop all these creepy RegEx'es for detecting links and stuff and use real libraries/parsers for it.

It would e.g. fix https://github.com/PrivateBin/PrivateBin/issues/33, and https://github.com/PrivateBin/PrivateBin/issues/310.

We may even have no need for DOMPurify anymore then (see https://github.com/PrivateBin/PrivateBin/issues/330) as [it uses a whitelist-mode by default](https://github.com/markdown-it/markdown-it/blob/master/docs/security.md), i.e. only support specific Markdown-syntax and not all kinds of HTML. This is a feature change, but AFAIK PrivateBin 1.1 also does only support that specific HTML…

So yeah, I think this could be a great way to renew some old libraries.

**Comment by elrido** [comment]
Please feel free to reopen when new plan has been developed reg. the above.
