### ISSUE TITLE
Translation of formatter ?

### ISSUE THREAD

**Issue by Draky50110** [PrivateBin/PrivateBin#34]
Hello.

In conf.ini, those options can be changed : 

[formatter_options]
; Set available formatters, their order and their labels
plaintext = "Plain Text"
syntaxhighlighting = "Source Code"
markdown = "Markdown"

But would it be possible to have them translated, as with other texts ?

In French, "Source Code" = "Code source" ;) and "Plain Text" = "Texte brut"

**Comment by elrido** [comment]
Actually, [they already get translated](https://github.com/PrivateBin/PrivateBin/blob/master/i18n/fr.json#L46). If you change the (always English) label in the conf.ini, you need to change the message ID in your translation files accordingly.
