### ISSUE TITLE
Allow files in discussion comments

### ISSUE THREAD

**Issue by sheddup** [PrivateBin/PrivateBin#343]

**Comment by elrido** [comment]
Sure, why not. Would require a change of the comment format. Lets discuss this as part of the paste format change.

**Comment by elrido** [comment]
It just occurred to me that if this is added, you might access a paste with a bunch of files appended in the comments, then you may end up having to load (and decrypt) a very large JSON message in your browsers memory. The comments are all loaded with the paste at the moment. I think it would make sense to implement comment pagination #5 at the same time with this feature, then you would only get i.e. 10 comments at a time and can flip back and forth between them.

**Comment by guzzisti** [comment]
scope creep as well....this is supposed to be a pastebin tool, not a fully fledged messageboard/forum software or even file hoster.

**Comment by rugk** [comment]
Yeah, indeed scope creep and it would basically allow bypassing the file size limitation set by the server admin by just attaching a file split into many smaller ones in one paste.
Currently you would have to create a new paste one by one then.

I'd also say we should close this as "wontfix".
