### ISSUE TITLE
Bump version in CHANGELOG.md to 1.2

### ISSUE THREAD

**Issue by t2d** [PrivateBin/PrivateBin#344]
I'm parsing `CHANGELOG.md` automatically. It says at the moment
```
1.2 (not yet released)
```
But 1.2 is already there. Please just get rid of `(not yet released)`. Thanks

**Comment by elrido** [comment]
I'll be adding the date and create a new "not yet released" section for future changes.

**Comment by t2d** [comment]
Thank you!

Von meinem iPhone gesendet
