### ISSUE TITLE
Using KDF for protecting against bruteforce attacks

### ISSUE THREAD

**Issue by user9209** [PrivateBin/PrivateBin#350]
Hi,

as fare as I see the password is only hashed with SHA256.
[Encryption](https://github.com/PrivateBin/PrivateBin/blob/10201dc4631102bd3c29e791375fa9a18dccb853/js/privatebin.js#L585)
[Decryption](https://github.com/PrivateBin/PrivateBin/blob/10201dc4631102bd3c29e791375fa9a18dccb853/js/privatebin.js#L605)

I have a suggestion to improve:

> Use a password if you want your paste to be private. In this case, make sure to use a strong password and only share it privately and end-to-end-encrypted.

By using a key derivation function (KDF) instead of using SHA256 the security of shorter passwords can improved. As it runs in javascript on client side the server needs no changes or power assumptions. As a result attacker using brute force need much more time to hack even a short password.

How can that achieved?

A KDF takes some input, here password or password + salt, a iteration number and returns a new password. Depending on the user password the iteration number can be chosen different. To make each KDF hash unique for each entry the hash of the message or the creation time can take as salt.

An example:

Passwords with size smaller 8 take 400.000 iterations and need 5 seconds to calculate.
Passwords with size 8 - 14 chars take 100.000 iterations need 1 seconds to calculate.
Passwords more than 14 chars take 1000 iterations need online some milliseconds.
(all values are randomly taken, only for understanding, real times may differ extremely)

As a result an attacker needs  62^4 * 5s = 855 days, 62^8 * 1 s = 6923519 years and 62^5 * 1 ms = 292471208 years to brute force all combinations.
Given attacker 1 million time faster:   14 seconds, 6 years and 292 years
Using no KDF with 100 MH/s (+1 million time faster): <1 second, 2 seconds and 1 day

As you can see, a KDF would improve the security of the passwords significantly.

The implementation of this feature should be relatively easy as adding a KDF and parsing all passwords through the KDF is sufficient. A switch can used for determine the iteration count.

Of course, the values can be chosen to minimize the negative impact on users.
For example passwords smaller 8 chars take 1 second and all other less than 300 ms.

Good if whole database is stollen or passwords are weak.

**Comment by elrido** [comment]
The password is never stored, so it can't be stolen (from the server). It has to be shared by another channel.

The [SJCL library automatically uses PBKDF2](https://github.com/bitwiseshiftleft/sjcl/wiki/Symmetric-Crypto#cipher-modes) as KDF, if the given password is a JS String.

I do agree that feeding a sha256 of the password is needlessly reducing its complexity (from any unicode character, down to just hexadecimals).

In the paste format change planned for the 1.3 release we had planned to use the raw password instead and also not to use the base64 of the key, but the raw 256 random bits. @rugk already pointed out, that this forms a potential weakening, as we are limiting the available permutations, while increasing the sizes of the whole. It is an open question (to us) if the two effects balance each other out or not, but we agreed that we should just trust the implementation and use KDFs for that purpose instead of doing something on our own AND use a KDF on top.

**Comment by user9209** [comment]
> The SJCL library automatically uses PBKDF2 as KDF, if the given password is a JS String.

The default iteration is 1000, see: [SJCL](https://github.com/bitwiseshiftleft/sjcl/blob/cc887b518c026407e4ad11ecef37ad9e40d4bd40/core/pbkdf2.js#L16)


NIST recommends 10,000 iterations:
> For PBKDF2, the cost factor is an iteration count: the more times the PBKDF2 function is iterated, the longer it takes to compute the password hash. Therefore, the iteration count SHOULD be as large as verification server performance will allow, typically at least 10,000 iterations.

[NIST Special Publication 800-63B](https://pages.nist.gov/800-63-3/sp800-63b.html#sec5)

**Comment by elrido** [comment]
We can apply when replacing SJCL with the web crypto API as we have to change the format of the pastes anyway. Thank you for the recommendations!

**Comment by elrido** [comment]
This got implemented in the webcrypto branch and since the number of iterations already is part of the existing format, it is even backwards compatible (the existing version can read pastes created with higher iteration counts and vice-versa).

**Comment by rugk** [comment]
> (the existing version can read pastes created with higher iteration counts and vice-versa).

…which is _very_ strange though (as obviously the output of PBKDF2 should be different at different rounds, otherwise that whole key stretching makes no sense). I wonder what sjcl's implementation did there…

**Comment by elrido** [comment]
The PBKDF2 needs to be told how many iterations to use. In SJCL we hadn't specified that and so it was the default 1000. This number always was part of the outputted paste format. This means that the number can be increased for new messages without loosing the ability to read the old format. And if we would change only the iterations, SJCL would be able to decrypt these new messages, as it just uses the number as specified in the paste to do so. We plan to change more then that, though...

**Comment by rugk** [comment]
Ah, now I see, thanks.

**Comment by rugk** [comment]
About the number itself, here another suggestion:
https://bugzilla.mozilla.org/show_bug.cgi?id=1320222#c7

So 100k may be quite good.
