### ISSUE TITLE
Potential Memory Leak after upgrading to 1.2.1

### ISSUE THREAD

**Issue by benkernan** [PrivateBin/PrivateBin#353]
## Steps to reproduce

1. running on centos7 with httpd
2. install version 1.2.1 over 1.2.0

### What happens
Potential memory leak, saw a large drop over a period of 24 hours

### What should happen
No memory leak

## Basic information

CentOS Linux release 7.5.1804 (Core)

Server version: Apache/2.4.6 (CentOS)
Server built:   Jun 27 2018 13:48:59

Chrome

8db98becb79e65b7985779fbf51cc4d0ea82d4d8

I can reproduce this issue on <https://privatebin.net>: Yes / No
Not yet

**Comment by rugk** [comment]
on the server? at which process? PHP?

Otherwise could also be many users (DDOS :wink: ) or so. Actually the changes in the new version only affected the JS in the client, so the update is very likely not the cause.

**Comment by elrido** [comment]
Can we assume you are running this with Apache mod_php? How many apache processes are there and how large does the memory usage per process get? On privatebin.net we use php-fpm and there I see about 3-4 processes of around 100 MiB each, but there are other PHP sites served by the same processes which may have higher requirements. Which PHP version do you see this with

Semi-related: We do measure memory consumption during the php unit tests and given the 99% coverage almost every line of code should get executed at least once. There we measure between 27 MiB and 18 MiB memory usage, depending on the PHP versions (5.4 / 7.0 are very low, the later releases use more memory). These reports are [public](https://travis-ci.org/PrivateBin/PrivateBin/builds/414953486), BTW.

**Comment by benkernan** [comment]
I think I was wasting your time on this one. After the server reboot and monitoring it for a few days, memory usage appears steady. Perhaps there was a with the httpd process not closing properly and sucking up memory, which would explain why I saw a sudden drop as soon as I restart the process. We can close this ticket.

**Comment by elrido** [comment]
No worries, and thanks for sharing your findings with us.
