### ISSUE TITLE
Clicking 'New' on a previously submitted paste does not blank address bar

### ISSUE THREAD

**Issue by TheFiZi** [PrivateBin/PrivateBin#354]
## Steps to reproduce

1. Create a new paste and send it
2. Without navigating away click 'New'
3. Examine browsers address bar

### What happens
When creating a new paste after a previously submitted one the 'New' button does not wipe out the URL in the address bar to the previous paste. If you were to accidentally hit 'F5' or <ENTER> in the address bar field the previous paste would be reloaded and if it was marked 'burn after reading' the paste is now gone.

### What should happen
Address bar should be reset to base URL of the site

## Additional information
![pasteurlexample](https://user-images.githubusercontent.com/1762426/44417490-8e55d780-a52a-11e8-975f-497b00ac57ec.gif)

## Basic information

**Server address**: paste.fizi.ca

**Server OS:** CentOS 6 64-bit

**Webserver:** Apache 2.2.15-69

**Browser:** Firefox 61.0.2 and Chrome 67.0.3396.99

**PrivateBin version:** 1.2.1

I can reproduce this issue on <https://privatebin.net>: **Yes**

**Comment by Arregi** [comment]
Not exactly as described, if you reload the page your message will be shown and therefore destroyed, but your paste will be on display and so, you can retrieve that information. I wouldn't say it's a bug, all in all is a good enhancement to implement.

Regards!

**Comment by plaa** [comment]
I agree it's a bad design choice that when creating a "burn after reading" message the browser URL is set to the message URL.  If you accidentally reload the page (e.g. close the tab and reopen or browser crashes and reopens tabs) your message is immediately burnt.  For "burn after reading" messages the browser URL should be something safe, for other messages is can be the message URL.  (I accidentally did exactly this and had to send a new link to a customer.)

**Comment by r4sas** [comment]
Same happens when using deletion link.
