### ISSUE TITLE
PHP Warning: QRCODE not defined

### ISSUE THREAD

**Issue by cryptomilk** [PrivateBin/PrivateBin#355]
I get the following warning in the logs:

`PHP Notice:  Undefined variable: QRCODE in /srv/www/vhosts/cpaste/privatebin/tpl/bootstrap.php on line 174`

QR Code is disabled:

```
$ grep qrcode cfg/conf.php 
; qrcode = true
```

**Comment by elrido** [comment]
I have tried to reproduce this, but failed so far. Even on an installation without qrcode in the configuration file, it will still be set to `true` via the default in [Configuration.php](https://github.com/PrivateBin/PrivateBin/blob/master/lib/Configuration.php#L54) and gets injected into the template in the [Controller.php](https://github.com/PrivateBin/PrivateBin/blob/master/lib/Controller.php#L427) (formerly PrivateBin.php).

Which release are you getting this with and could you compare the two linked lines with your version?

**Comment by elrido** [comment]
And how do the two linked files look like on your system? I had tested it with master and 1.2.1 but did not get those notices, except if I started to remove the default value in Configuration.php.

**Comment by elrido** [comment]
closing this for now due to inactivity, feel free to reopen, when you had time to review the suggestions
