### ISSUE TITLE
Malformed raw text

### ISSUE THREAD

**Issue by Mephistophiles** [PrivateBin/PrivateBin#358]
## Steps to reproduce

1. Open https://privatebin.net/
2. Enter in textarea text ```#include <stdio.h>```
3. Click "Send/Отправить" button
4. Copy new link (ctrl + c)
5. Open new tab with new link (ctrl + v)
6. Click "Raw Text/ Исходный текст"

### What happens

Out

```
#include 
```

### What should happen

```
#include <stdio.h>
```

## Basic information

**Server address**: https://privatebin.net/

**Browser:** chromium

**PrivateBin version:** 1.2.1

I can reproduce this issue on <https://privatebin.net>: Yes

**Comment by r4sas** [comment]
idk:
![image](https://user-images.githubusercontent.com/7023612/44800633-91eafd80-abbf-11e8-8680-f040e404516d.png)
current + old-stable.

**Comment by r4sas** [comment]
Seems like problem in Chromium. I'm testing it in Firefox 52.5.2 ESR.

![image](https://user-images.githubusercontent.com/7023612/44801918-0e331000-abc3-11e8-95f4-afc5061ae4a6.png)

**Comment by rugk** [comment]
You have to click on the button _Raw text_ at the top.

I can reproduce this in Firefox v63.

**Comment by rugk** [comment]
Could be the same issue as in https://github.com/PrivateBin/PrivateBin/issues/328.

**Comment by Mephistophiles** [comment]
Thanks!

**Comment by elrido** [comment]
FYI: This is another regression from our refactoring in v1.2, back in v1.1 we [did escape the HTML](https://github.com/PrivateBin/PrivateBin/blob/978ab1a59f8dcf404ad68de59ee64d2a669507e7/js/privatebin.js#L1283).
