### ISSUE TITLE
migration script to change storage

### ISSUE THREAD

**Issue by Dryusdan** [PrivateBin/PrivateBin#359]
Hi :)
Thank you for Privatebin first, I use lot of time this tools and I deploy this for other people.
Actually I have some people who read and write paste with little duraton or not and I think the performance is not better in DB or flatfile... But I can't migrate flatfile on DB and DB on flatfile...
I think this tool may be usefull for somebody. So, can it possible to add a script to change storage ? :)

Regards :)

**Comment by aeris** [comment]
FYI, here is a ruby script migrating from filesystem to PostgreSQL.
Should be easy to port to MySQL or PHP.

https://gist.github.com/aeris/d908c3214b7038a566f657a2b9cc0f07

**Comment by elrido** [comment]
resolved in #1012
