### ISSUE TITLE
RainTPL refactoring

### ISSUE THREAD

**Issue by elrido** [PrivateBin/PrivateBin#36]
RainTPL seems no longer maintained and the RainTPL.com domain, returned by exceptions inside of the library (mentioned in #35), is no longer available. There is also a lot of dead code in the library that we don't use in our templates, as can be seen in the code coverage reports.

Hence I suggest to refactor the library:
* Replace non working URLs with working ones, e.g. by retrieving old content from Archive.org and creating a wiki page to host it.
* remove dead code that is _never_ used in the way we use templates.
* maybe even remove some of the _features_ that are not really needed for our templates. They can always be re-added later if a template really needs it.
* ensure that the "tmp" folder used to store the compiled templates is created inside of PATH instead of in the main PrivateBin folder.

**Comment by rugk** [comment]
Can't we switch to a maintained alternative? Would that be possible? This way we would not have to maintaine this code by ourself.

**Comment by k0nsl** [comment]
@rugk: in my view that would've been the ideal solution and I tried to come up with alternatives, but I had so much other stuff to do that I haven't had any time to look.
One other option would be to go through the RainTPL code and removing everything we won't be using and fine-comb it for potentially dangerous / badly written code, or just plain outdated code -- which can be a security hazard.
As I understand it RainTPL hasn't really been maintained in a long time.´

I think stripping it down entirely to just the bare minimum of what we need would be one alternative if we don't want to hunt for an entirely new replacement.

PS:
PrivateBin runs perfectly on PHP 7 for me.

**Comment by elrido** [comment]
Well, our templates are so lightweight (inserting some variables, some ifs and wrapping some calls to the translation function `i18n::_()`) it might actually be easier to just switch to plain PHP files. Maybe call them phtml so they can't be executed on their own and to denote that they are templates?

**Comment by rugk** [comment]
> Maybe call them phtml so they can't be executed on their own and to denote that they are templates?

`.phtml`is not really a standard and of course executing them also should not hurt. But I think a better name choice might be `.inc`, which stands for "includes" in general.

**Comment by k0nsl** [comment]
Why not the more obvious extension: `.tpl`

That's just my five reichsmarks ;)

**Comment by elrido** [comment]
Ok, fine, I'll stick with the boring old `.php` then. :stuck_out_tongue:
