### ISSUE TITLE
GCP App Engine app.yaml config

### ISSUE THREAD

**Issue by aiggo** [PrivateBin/PrivateBin#363]
Hello!

I would like to host PrivateBin from a GCP App Engine, but I don't know how to configure the app.yaml file. If somebody has done this before, I would appreciate the help. :)

**Comment by aiggo** [comment]
I have tried two options, but both of them did not work:

runtime: php55
api_version: 1
threadsafe: yes

handlers:

- url: /.*
  script: index.php

(Looks like poop)

&

runtime: php55
api_version: 1

handlers:

- url: /(.*\.(ico$|jpg$|png$|gif$|htm$|html$|css$|js$|xml$))
  static_files: \1

  upload: (.*\.(ico$|jpg$|png$|gif$|htm$|html$|css$|js$|xml$))
  application_readable: true

- url: /(.+)
  script: \1

- url: /
  script: index.php

(Paste error)

**Comment by elrido** [comment]
It seems you can [deploy containers in the GCP](https://cloud.google.com/compute/docs/containers/deploying-containers?hl=en)? How about using our [docker container image](https://hub.docker.com/r/privatebin/nginx-fpm-alpine/)?

Aside: The runtime seem really old, but should work. If possible I would recommend a php 7.x version for speed and security. How do you tell GPC that the data path needs to be writeable and shared among all instances (with the container you'd use a persistent volume for /srv/data)?

**Comment by aiggo** [comment]
Thank you, deployment with the container image worked! 😃
