### ISSUE TITLE
[Docker] Unable to paste anything more than a few Kb, permission denied error

### ISSUE THREAD

**Issue by Shadow00Caster** [PrivateBin/PrivateBin#368]
## Steps to reproduce

1. Paste text more than a few lines or attach an image or file more than a few Kb

### What happens
Could not create paste: server error or not responding
`
2018/10/24 19:08:27 [crit] 14#14: *39 open() "/var/tmp/nginx/client_body/0000000008" failed (13: Permission denied), client: x.x.x.x, server: , request: "POST / HTTP/1.1", host: "x.x.x.x"`

### What should happen
No error and redirect to link.

## Additional information

I have tested by accessing the installation directly as well as through HAProxy with SSL.
I have the sizelimit in conf.php set to 262144000
Setting nginx and client_body dir's within the docker volume to 777 results in normal operation, but the volume this resides in is not persistent, so it can get wiped.  The documentation only notes to make `/privatebin/data` and `/privatebin/cfg` persistent.

## Basic information

**Server address**:

**Server OS:** Ubuntu 18.04, Docker Standalone 18.06.1-ce 

**Webserver:** Docker image jgeusebroek/privatebin latest

**Browser:** FF and Chrome latest

**PrivateBin version:** 1.2.1 from Docker jgeusebroek/privatebin latest

I can reproduce this issue on <https://privatebin.net>: No

**Comment by elrido** [comment]
Hi Shadowcaster,

To allow larger file uploads, there are three settings that need to be adjusted: The webserver configuration has to allow large POSTs, the php's post_max_size and then the setiing in PrivateBin that you adjusted.

The error indicates that there is another issue, though, that the nginx webserver can't write into its temporary folder where it probably wants to cache the request before sending it to php. Looking over that that [containers Git repo](https://github.com/jgeusebroek/docker-privatebin/), I would guess the nginx server runs under the "privatebin" user and as that user is created [in the entrypoint script, the chown line](https://github.com/jgeusebroek/docker-privatebin/blob/master/entrypoint.sh#L10) needs to encompass the nginx temporary folder. If you create a request over in that project, I can provide a PR for this over there.

On that note, if this is an option for you, could you test [our projects docker image](https://hub.docker.com/r/privatebin/nginx-fpm-alpine/), too, and if it has similar issue with larger paste sizes, please [create a ticket in the images Git repo](https://github.com/PrivateBin/docker-nginx-fpm-alpine/issues)?

Best,
El RIDO

**Comment by Shadow00Caster** [comment]
Hi @elrido 

Using the `privatebin/nginx-fpm-alpine` image seems to have worked.
