### ISSUE TITLE
[Feature Request] Progress bar for file upload

### ISSUE THREAD

**Issue by Shadow00Caster** [PrivateBin/PrivateBin#369]
Would be nice to have a progress bar for file uploads.

**Comment by elrido** [comment]
This is a rather long standing feature request #9 that seems not quite as easy to implement. For large files, the compression, encryption and base64 encoding of the message tends to take longer then the upload, so those steps would have to be included in the bar, too. Neither SJCL nor webcrypto API or the other used libraries support progress notifications, so a rudimentary bar would just jump between the four states.
