### ISSUE TITLE
Delete privatebin post

### ISSUE THREAD

**Issue by Atlantidee** [PrivateBin/PrivateBin#373]
Hello

i would ask if it is possible to request a delete of a privatebin post. This because Anonymous shared sensible data and i need this to be deleted. Is there a way to do this?

I can reproduce this issue on <https://privatebin.net>: Yes

**Comment by r4sas** [comment]
You can do it manually, by deleting file or record in DB with paste ID (part before "#").

**Comment by Atlantidee** [comment]
> You can do it manually, by deleting file or record in DB with paste ID (part before "#").

Can you show me the procedure? I never used privatebin. The post is https://privatebin.net/?34272204ebaca766#ouI62XhQYJR4NX9Gn8KgKWmwacK2AbBKyH+8B1uHQdU=

**Comment by rugk** [comment]
Obviously you have to have database/server access to do this. If it is at another server, you have to contact the server admin.

Also obviously it is not a good idea to post a link (with decryption key) to it if you say it contains private data. As such to be sure I've deleted it.

As for whether and how it may/can be deleted, please contact @elrido (via mail) as he's the one managing this server. As you do not really want to spread this data further, I guess it is not a good idea to discuss this in this public GitHub issue.

**Comment by Atlantidee** [comment]
> Obviously you have to have database/server access to do this. If it is at another server, you have to contact the server admin.
> 
> Also obviously it is not a good idea to post a link (with decryption key) to it if you say it contains private data. As such to be sure I've deleted it.
> 
> As for whether and how it may/can be deleted, please contact @elrido (via mail) as he's the one managing this server. As you do not really want to spread this data further, I guess it is not a good idea to discuss this in this public GitHub issue.

Yes i know, don't worry. I already changed the data in the link, it was just an example. Thanks for the help
