### ISSUE TITLE
[bug] 'burn after reading' option in combination with password option

### ISSUE THREAD

**Issue by tehbeatnix** [PrivateBin/PrivateBin#374]
## Steps to reproduce
1. select 'burn after reading' option and pick a password to send in a paste
2. surf to the paste url and submit incorrect password
3. data is still deleted

### What happens
when 'burn after reading' option is selected in combination with password set, privatebin will delete the data upon visit even if incorrect password is submitted.

### What should happen
when 'burn after reading' option is selected and password is set as well, privatebin should not delete the data upon visit of the url but upon correct decryption through correct password input.

## Additional information
since javascript support is required for privatebin to function anyway, its better to construct a ping back from javascript upon correct decryption based on which a paste is deleted if 'burn after reading' option is set. 

## Basic information
**PrivateBin version:** 1.2.1

I can reproduce this issue on <https://privatebin.net>: Yes

**Comment by elrido** [comment]
In #174 it was recognized as security issue that a paste could be downloaded multiple times, even if it is marked as burn after reading. Later, in #347 the idea of introducing a challenge response mechanism to address this got discussed. It is at this time not considered a bug but was disabled on purpose. In a future version we may be able to offer such a feature again, if it can be done safely.

**Comment by megabert** [comment]
Just a note: Even if the protected paste is deleted after an incorrect try, one has multiple tries within the same browser window, which I think is an essential possibility. Typos are normal.
