### ISSUE TITLE
Paste creation date: Keep secret or display in UI?

### ISSUE THREAD

**Issue by rugk** [PrivateBin/PrivateBin#390]
> > We could still keep the pastes creation date internal (it currently gets exposed).
>
> Okay, that's a "metadata leak" that currently is there. So IMHO, we should keep it secret. It has no value on the client and for a paste creator it is not obvious it is exposed.
The other option would be: Display it somewhere in the UI. Then, it's obvious for a paste creator that it is shown…

from https://github.com/PrivateBin/PrivateBin/issues/28#issuecomment-447999902

I have no strong feeling here, so let's colect arguments for the two ways. IMHO, the current way is bad. But either ways are equally good:
* **display** a "paste created XY days/months/… ago" in a useful way, maybe with the tooltip for the exact time & date (see how GitHub does it e.g. when you hover over that time in your comment)
* **do not expose it**, just don't let the client know. Keep in mind: Server admins can still figure it out, if they e.g. get a National Security Letter or something like that. (so question is: does it increase security or just provide a false sense of security?)

**Comment by elrido** [comment]
I opted to not expose it in the v2 paste API, but it still is in use for the comments, both to order them sequentially by creation and displayed in the UI.

**Comment by rugk** [comment]
IMHO I would equally like when it is displayed somewhere in the UI. Just need to know, whether this is useful for PrivateBin users or rather a not-so-interesting detail.
