### ISSUE TITLE
Feature request: Generate a mailto link when creating a paste

### ISSUE THREAD

**Issue by abulgatz** [PrivateBin/PrivateBin#398]
99% of the time when I'm creating a paste I'm copying the generated URL into an email client, writing a warning note about the burn-after-reading and time to expiration, and sending the email.

It would be great if PrivateBin could generate a mailto link with the paste URL, as well as relevant warnings for burn-after-reading and/or time to expiration based on the settings selected for the paste. This link could then be displayed after creating a paste, allowing one-click email creation with all relevant information and warnings.

Here's an example:

<a href="mailto:?subject=Secure%20document%20link&amp;body=Note%3A%0A%0A-%20This%20link%20will%20self-destruct%20after%20being%20opened.%0A-%20This%20link%20will%20self-destruct%20after%207%20days.%0A%0A%0ALink%20to%20secure%20document%3A%0A%0Ahttps%3A%2F%2Fprivatebin.net%2F%3Fc60ded25fdbfa83a%23%2BPnHchrN%2BJfx7po6qtzQvL3Sp0Ah1gIalKwTk98p7OY%3D%0A">Generate email</a>

**Comment by elrido** [comment]
I like this idea.

**Comment by xXxAaRkEtxXx** [comment]
me too

**Comment by Haocen** [comment]
Cool idea, is this issue taken?

**Comment by elrido** [comment]
Don't think anyone started working on it -> Go for it!

**Comment by Haocen** [comment]
Playing with the code a little big, doesn't seemed too hard, while I iron out some problems in UX, do you think a custom email template should be supported? Will it be too complex for user to configure?
If we do support custom email template, how do we want to support it? with a custom php file?

**Comment by elrido** [comment]
As that the mailto is a single line of URI, the easiest would be to use three translated strings, one for the subject, body and link description and then construct the link, i.e.:

```php
<a href="mailto:?to=&subject=<?php echo rawurlencode(I18n::_('Sharing a document with you')) . '&body=' . rawurlencode(I18n::_('Hey, here is your link: %s', $LINK)); ?>"><?php echo I18n::_('share via email'); ?></a>
```
Of course the same also works with the translation functions on the JS side, if you would rather inject that link from that end.

**Comment by Haocen** [comment]
I might be over thinking this.

Let's keep this simple and achieve with frontend code first.

**Comment by Haocen** [comment]
This turns out to be harder than I thought:
- Cannot reliably detect expiration date(since sending a email saying `2 days until expire` doesn't really make sense, noboby know when receiver will read the email).
- Cannot reliably detect burn after read status, as email might be sent either on paste success view or paste reading view.

Any suggestion?

**Comment by Haocen** [comment]
Adding over 100 lines of code to make it possible, tedious and ugly.
Currently code logic and structure make afore-mentioned specs hard to achieve.
Need to rethink.

**Comment by elrido** [comment]
I would suggest to limit the scope of this to just the following:
- show the mail link only on paste creation, not any time the paste gets viewed (so you don't have to consider the burn after reading case - the system is intentionally designed as not to leak information on the state of burn-after-reading pastes)
- (optional) this would also let you use the expiration date, as it can be assumed the mail is created around the time the paste is created (well, except with 5 min expiration and the user waits for minutes after creating the paste to send out the mail)

So I would simply go for a minimal use case of a mailto link just on creation and maybe not even bother to include an expiration time in the suggested body text. That would already cover a lot of use cases.

**Comment by Haocen** [comment]
Reimplemented, code still a little ugly but much better.

<img width="1026" alt="link email" src="https://user-images.githubusercontent.com/10842569/63476762-51c7ff00-c450-11e9-8aa6-b952578fd2a2.png">
<img width="557" alt="email link" src="https://user-images.githubusercontent.com/10842569/63476763-51c7ff00-c450-11e9-949c-7e2e1df4968c.png">

Current limitations:
1. Expiration date calculated on paste success page CAN be different from the paste viewing page, but expiration date calculated on paste viewing page is guranteed to be consistent.
2. Expiration date is calculated in UTC instead of local time to avoid leaking timezone information.
3. The Email template is fixed, non-tweakable.

**Comment by Haocen** [comment]
DEMO site:
https://privatebin.cf
Now has this implemented.

@elrido Please let me know how you like it, thanks.

**Comment by elrido** [comment]
I do like the minimal approach. The content is just a guideline and the mail sender can modify it as needed. The strings are all translatable. The Email button is offered for both the creator of the paste as well as the reader. I think this is already a very useful feature and would be pleased to merge it.

As an aside: I like the addition of icons to all the buttons in the navigation bar. Nice touch! Should we add this as an additional template or merge this in the existing one?

**Comment by Haocen** [comment]
Sorry, the discussion happened in wrong place.

This is my second attempt for taking on this, let me know if it looks good thanks.

https://privatebin-staging.herokuapp.com/
