### ISSUE TITLE
Remaining theoretical attacks

### ISSUE THREAD

**Issue by rugk** [PrivateBin/PrivateBin#40]
So here the remaining issues of the [security audit](https://github.com/PrivateBin/PrivateBin/issues/20):
- [ ] 4.2. urls2links XSS
- [x] 4.5. Is SJCL used correctly?
- [x] 4.6. Possible XSS in tpl/page.html

I mark this issue as "help wanted", so if anyone wants to look into this, feel free to do this. All of them are very theoretical and are therefore not serious.
If any issues may get obsolete (because the underlying system is changed, such as 4.5 when #28 is implemented, please also tick the issue).

**Comment by rugk** [comment]
As RainTPL has been removed is 4.6. still relevant?

**Comment by elrido** [comment]
All the returned variables currently get encoded/escaped, so I still consider this fixed.

Of course custom templates could have flaws, as the template creators needs to take care of the the escaping, too. We could move the escaping into the main PrivateBin class, then template creators don't have to mind and we reduce code duplication.

**Comment by rugk** [comment]
Okay, so for now I ticked 4.6.

**Comment by rugk** [comment]
Anything to do about "4.5."? Basically we can only write to the authors of SJCL.

**Comment by elrido** [comment]
We could do that, but really... Just compare our implementation (its [these 10 lines](https://github.com/PrivateBin/PrivateBin/blob/addb666a235872cf11ebe0ade20d5dd48c6d5ec6/js/privatebin.js#L492)) with the example given [on their homepage](http://bitwiseshiftleft.github.io/sjcl/) and the details on the encrypt function in the [API docs](http://bitwiseshiftleft.github.io/sjcl/doc/symbols/sjcl.json.html#.encrypt). There is really not much one could do wrong, is there?

**Comment by rugk** [comment]
I also think most issues may only be made with the parameters passed to SJCl and this would not be an "incorrect use of SJCL". So I tick this box too.

**Comment by rugk** [comment]
Okay, actually I found some things which are not clear to me there. I'll open a new issue for that.

**Comment by rugk** [comment]
So here it is: https://github.com/PrivateBin/PrivateBin/issues/74

Now we also really fixed 4.5.

**Comment by elrido** [comment]
Regarding 4.2: The only allowed protocols in the urls2link code are http, https, ftp and magnet. As these are hardcoded XSS that uses "javascript:" or hides the use of the same would not trigger URLs to be created.
