### ISSUE TITLE
No confirmation message from UI when pasting image

### ISSUE THREAD

**Issue by paalbra** [PrivateBin/PrivateBin#400]
## Steps to reproduce
1. Copy image data to clipboard
2. Open new privatebin (with fileupload allowed)
3. Paste clipboard (CTRL+V)

### What happens
Image data is silently attached as image.png

### What should happen
It would be nice to have some sort of message from the UI confirming that you pasted/attached the image.

## Basic information
**Browser:** Firefox 64
**PrivateBin version:** 1.2.1

I can reproduce this issue on <https://privatebin.net>: No (fileupload isn't allowed)

**Comment by Haocen** [comment]
Related to:
https://github.com/PrivateBin/PrivateBin/issues/317

And fixed in:
https://github.com/PrivateBin/PrivateBin/pull/488
