### ISSUE TITLE
Disclosure of Information on privatebin

### ISSUE THREAD

**Issue by MikeVitamina** [PrivateBin/PrivateBin#401]
Hello team 
There is a bin showing confidential information, as email addresses, full names and phone numbers, this information can be used to perform fraud against those people. 

I kindly ask you to removed this bin, in order to prevent fraud or some other illegal actions.   As r4sas, i will wait the administrator contact for providing the URL.

**Comment by r4sas** [comment]
Please don't publish openly links like that. Just write message about this and wait for site administrator reply/contact with him.

**Comment by MikeVitamina** [comment]
Ok r4sas, i apologize... but i hope this resolves soon.

**Comment by rugk** [comment]
As @r4sas said, please do write to the responsible administrators of the PrivateBin instance.

**Comment by r4sas** [comment]
> As @r4sas said, please do write to the responsible administrators of the PrivateBin instance.

Current issue in touch with privatebin.net.

**Comment by rugk** [comment]
Okay, note @elrido hosts the server, so I've notified him.

**Comment by MikeVitamina** [comment]
> Okay, note @elrido hosts the server, so I've notified him.

Thanks rugk. can he contact me?

**Comment by rugk** [comment]
Best if you mail him directly…
