### ISSUE TITLE
Page not loading

### ISSUE THREAD

**Issue by Bencey** [PrivateBin/PrivateBin#405]
Hey, my privatebin page is not loading and in the browser logs I get this message

Failed to find a valid digest in the 'integrity' attribute for resource 'https://privatebin.bencey.co.nz/js/privatebin.js?1.2.1' with computed SHA-256 integrity 'JqLznHC4nAqxqRWs6uAU1AKq20yzDq/YMd3Hcws93oo='. The resource has been blocked.

**Comment by Bencey** [comment]
When I use a vpn it loads fine... Could it be since im hosting it on my own network?

**Comment by rugk** [comment]
Generally, the message means the JS delivered by your web server has been modified in transit. (Do you e.g. use some kind of proxy?)

> Could it be since im hosting it on my own network?

Generally, no.

Did you have a look at https://github.com/PrivateBin/PrivateBin/wiki/FAQ#why-does-not-the-loading-message-go-away and tried all solutions listed there?

**Comment by Bencey** [comment]
Yes I have tried the solutions, I am able to connect to the site on a vpn I just cannot access it without one (My mobile data also works)

**Comment by Bencey** [comment]
maybe because my router doesnt have loopback?

**Comment by rugk** [comment]
> maybe because my router doesnt have loopback?

You can try to manually resolve your domain to your internal network's address. (e.g. using a hosts file on your local device, or adjusting the resolver, if that is running on your router.) 

Also possibly look into the JS files that PrivateBin tries to load, to see what is modified there.

**Comment by Bencey** [comment]
Hmm this issue is strange, friends of mine can access the site fine and I just tried installing firefox to test and that also works, Is there an issue with chrome and brave not working?

**Comment by Bencey** [comment]
Alright went into cloudflare and purged all the cache which I just found out I could do, Ill see if it loads when I get back to my home wifi

**Comment by Bencey** [comment]
All working now, Thank you for your help :)

**Comment by rugk** [comment]
It is very clearly documented in the FAQ that there are issues with Cloudflare. If the instructions, written there, to solve it, are not enough, please do adjust them.

(Apart from the fact that Cloudflare is of course not optional for security, as it's built-in MITM.)
