### ISSUE TITLE
file size of attachment cannot exceed 2MiB

### ISSUE THREAD

**Issue by MarkusP** [PrivateBin/PrivateBin#406]
Hi everyone,
running my own version of PrivateBin and have an issue with not being able to upload files with more then 2MiB filesize.

Within the cfg directory I modified the "conf.php" file to allow 20MiB filesize.

> ; size limit per paste or comment in bytes, defaults to 2 Mebibytes
> ;sizelimit = 2097152
> sizeLimit = 20971520

But as you see in the screenshot it is not working. Any idea what I am doing wrong?

TIA,
Markus

![20190210-194346](https://user-images.githubusercontent.com/1380385/52538095-b7835200-2d6e-11e9-99e2-d60d228a7366.png)

**Comment by r4sas** [comment]
Check your PHP settings.

**Comment by rugk** [comment]
Yes, see @r4sas. 

**Note** for us to close this issue, I think we should document/hint at that fact somewhere [here in the config help](https://github.com/PrivateBin/PrivateBin/wiki/Configuration#fileupload).

**Comment by MarkusP** [comment]
I am sorry... didn't want to bother you... I checked my php.ini settings before opening this case...

> [root@host etc]# cat php.ini | grep -i size | grep -v ";"
> post_max_size = 2500M
> upload_max_filesize = 2048M
> pdo_mysql.cache_size = 2000
> mysqli.cache_size = 2000
> [root@host etc]# 

As you can see, everything should be ok... if there is something I overlooked I would appreciate a hint/tip tp solve this.

Thanks
Markus

**Comment by r4sas** [comment]
What you use as webserver? apache or nginx?

**Comment by r4sas** [comment]
@MarkusP huh... I see problem (I think)

>sizeLimit

It must not be with capital letter.

**Comment by MarkusP** [comment]
Oh my god... shame on me!!!!!!!! I am sorry!!!!! :-(

**Comment by rugk** [comment]
Anyway, as noticed we do not even hint to the PHP upload size...
So I adjusted [it](https://github.com/PrivateBin/PrivateBin/wiki/Configuration#sizelimit) and [added a note](https://github.com/PrivateBin/PrivateBin/wiki/Configuration/_compare/949cc1c013dcb591147d3b4665754c641a77d718...a55d130f5b6efa88b86f810f83798a6df65d1907).

**Comment by MarkusP** [comment]
Thx, good job!!
