### ISSUE TITLE
Uncaught PDOException: could not find driver in /srv/lib/Data/Database.php:106,

### ISSUE THREAD

**Issue by DracoMilesX** [PrivateBin/PrivateBin#410]
## Steps to reproduce

1. Setup privatebin with mysql
2. try to make a paste

### What happens

2019/03/07 13:35:33 [error] 10#10: *19 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught PDOException: could not find driver in /srv/lib/Data/Database.php:106,
#0 /srv/lib/Data/Database.php(106): PDO->__construct('mysql:host=xxx....', 'xxx', 'xxx', Array)

### What should happen

Paste should be created correctly

## Additional information

database info in config.php:

[model]
; example of DB configuration for MySQL
class = Database
[model_options]
dsn = "mysql:host=ip:port;dbname=dbname;charset=UTF8"
tbl = "prefix_"  ; table prefix
usr = "user"
pwd = "pass"
;opt[12] = true   ; PDO::ATTR_PERSISTENT

## Basic information

Using docker with the latest tag on mariadb

**Comment by rugk** [comment]
Did you check the credentials for the MySQL database are correct? (The config you posted is basically just the default. But obviously do not post your real credentials here.)

**Comment by DracoMilesX** [comment]
Hello @rugk the credentials are correct.

The webserver config are from the official docker image from privatebin https://github.com/PrivateBin/docker-nginx-fpm-alpine

**Comment by elrido** [comment]
The docker image is not set up with the PHP PDO module for MySQL databases (look for a `pdo_mysql` section in the output of the phpinfo function).

In Debian/Ubuntu, the package needed for this driver is called `php7.0-mysql`, in CentOS/RHEL it's `php-mysql`, in Alpine it's `php7-pdo_mysql`, etc.
