### ISSUE TITLE
Can I use this privateBin in my React app? 

### ISSUE THREAD

**Issue by victoriaHan** [PrivateBin/PrivateBin#412]
Hi, this is just silly question. I read all API, FAQ... However, I am still confused that I can use this privateBin in my React App.

Can create my own the page to paste text/copies etc just using API provided? Do you have any guide for it? I could not find it.

**Comment by rugk** [comment]
Well... we have an [API](https://github.com/PrivateBin/PrivateBin/wiki/API), but note you obviously need to do the client-side encryption.

Except of that, I doubt React is any different from any other (JS) app.

**Comment by elrido** [comment]
Don't know if the API is exactly what you need, depending on your use case:

- If you want to "skin" your PrivateBin instance to look like a page in your React app, just create a [custom template](https://github.com/PrivateBin/PrivateBin/wiki/Templates) that uses the existing HTML/CSS of your app to mimic its looks and integrates with your navigation. Obviously this wouldn't really be part of the single page app, just look like it on the surface. Users may notice that navigating to this page would do a full page refresh.
- If you really want to write a custom client that uses the server component of PrivateBin to store and retrieve something, you can use the API that rugk mentioned. The server side can't decrypt the contents of whatever you store on it, so it just sanity tests, if the sent paste follows the correct format and the base64 encoded, encrypted part of it can't be compressed (encrypted content should look like random noise and therefore not compress). But you could store anything in there, as long as it has the right format.
- If you want to integrate the existing PrivateBin client into your React App, you don't need to provide the full template, but just include certain key DOM elements with specific IDs that are used to interact with the UI in privatebin.js. You can search for them in the init() functions of the various classes, where these elements get preloaded (like in [TopNav.init()](https://github.com/PrivateBin/PrivateBin/blob/master/js/privatebin.js#L3318) for example). You would also need to load all the JS libraries used in the project into your app.

**Comment by rugk** [comment]
So as it seems this question has been answered and I thus close this issue. If anyone has further questions on that topic, feel free to comment here, again.
