### ISSUE TITLE
How to start privatebin in a domain subpath?

### ISSUE THREAD

**Issue by kivagant-ba** [PrivateBin/PrivateBin#414]
... wrong issue

**Comment by elrido** [comment]
In answer to the original question, you need to setup your reverse proxy (nginx?) to rewrite the path, i.e. to proxy_pass http://privatebinurl**/**. This is outlined in the [proxy_pass documentation](http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_pass), where it explains that "[i]f proxy_pass is specified without a URI, the request URI is passed to the server in the same form as sent by a client[...]".

**Comment by kivagant-ba** [comment]
Thank you, the root cause of the problem was different in my case, so I deleted this.

**Comment by kivagant-ba** [comment]
If someone find the ticket, here's a scratch (not production ready) of Nginx config:

```
location /privatebin {
      rewrite ^/privatebin$ /privatebin/ permanent;
      rewrite ^/privatebin/(.*)$ /$1 break;
      access_log off; # do not store logs
      proxy_pass http://privatebin_backend_url;
    }

```
