### ISSUE TITLE
Function request: Recaptcha in password form

### ISSUE THREAD

**Issue by emillod** [PrivateBin/PrivateBin#416]
Hello
i think that someone should add to this field where we can enter password(if note is password protected) recaptcha.

**Comment by rugk** [comment]
First, this would be a huge privacy invasion for a private service like this.

And secondly, I think it is currently also not possible, as it requires a server to validate the Captcha response.

Latter may however be solved when we finish https://github.com/PrivateBin/PrivateBin/issues/245, but I think https://github.com/PrivateBin/PrivateBin/issues/245 in general may be the better idea: The server could also just limit attacks by limiting password retries.
