### ISSUE TITLE
Setup errors: Permission errors

### ISSUE THREAD

**Issue by BrianCutler** [PrivateBin/PrivateBin#418]
## Steps to reproduce

1. Install Virtual box on your Mac
2. Build a Centos 7.2 VM in Virtual box.
3. Log into the instance, switch to root, and run the following:
# Update system first
   yum -y update
   reboot
# Setup for installing php-mcrypt
   yum -y install epel-release
# Setup for additional utilities
   yum install -y git tree vim wget
# Install Apache and PHP
# Based on info from: https://nxnjz.net/2019/02/how-to-install-privatebin-on-fedora-29/
#                     https://www.addictivetips.com/ubuntu-linux-tips/personal-pastebin-alternative-linux/ 
    yum install -y httpd php php-common php-xml php-mbstring php-mysqlnd php-pdo php-mcrypt php-json php-gd

# Start and configure httpd system service
   systemctl start httpd
   systemctl enable httpd
   systemctl status httpd

Note that I also create a php script -  /var/www/html/PrivateBin/info.php.  In it is the line:
  <?php phpinfo(); ?>
When I execute the script via the browser, I get the php info page.  It does indicate that mcrypt and gd are installed.

### What happens
When I try to paste into a Privatebin server I have built, I get the error "Could not create paste: server error or not responding"

The /var/log/httpd/errorlog indicates "unable to create directory data".  I create the directory and change ownership 'chown apache:apache /var/www/html/PrivateBin/data'.

I try to paste again and I get the same "Could not create paste: server error or not responding".  The error_log file indicates 'unable to write to file data/.htaccess'.  I create the file  '/var/www/html/PrivateBin/data/.htaccess' and chown it apache:apache.

I try to paste again and  I get the same "Could not create paste: server error or not responding".  The error_log file indicates 'unable to write to file data/salt.php'.  I create the salt.php file and change ownership to apache:apache.

I try to paste again and  I get the same "Could not create paste: server error or not responding".  The error_log file indicates 'unable to read file data/salt.php'
Now I am stuck ... any ideas what I need to do?

### What should happen
The paste should work.

## Basic information

**Server address**:

**Server OS:**

**Webserver:**

**Browser:**

Latest version

I can reproduce this issue on <https://privatebin.net>: No

**Comment by rugk** [comment]
Are you sure you've chowned/chmod'ed `data` correctly? Best do it with `-R` to recursively adjust permissions.

See also: https://github.com/PrivateBin/PrivateBin/blob/master/INSTALL.md#file-level-permissions

**Comment by elrido** [comment]
Please also consider SELinux contexts of the files, as described in the RHEL & SELinux install guide (CentOS should behave identical, as it is the community rebuild from RHEL sources):
https://github.com/PrivateBin/PrivateBin/wiki/Installation-on-Red-Hat-with-SELinux

PS: 7.2 is several years old, please consider upgrading to the current 7.6, yum update should get you there.

**Comment by levatrubrik** [comment]
I'm having exact same issues.  Have you been able to resolve it?

**Comment by rugk** [comment]
Did you follow the guide [linked in the comment before](https://github.com/PrivateBin/PrivateBin/issues/418#issuecomment-479751402)? Especially [the SELinux part](https://github.com/PrivateBin/PrivateBin/wiki/Installation-on-Red-Hat-with-SELinux#installation)?

**Comment by levatrubrik** [comment]
Apologies, one thing I should mention is that while I see the same error, I don't have the same setup.  Mine is LAMP on Ubuntu 16.04 (no SELinux).  
I was just able to bypass the error by executing php commands from ServerSalt.php manually in (php -a), so I think it's some permissions issue for me

**Comment by BrianCutler** [comment]
No ... I switched to AWS where everything worked fine with no changes.
very odd.

**Comment by BrianCutler** [comment]
Yes ... still did not work.  Thanks very much for the help but I wound up
doing it in AWS where it worked first shot.

Brian

**Comment by jmeddy** [comment]
I know this is closed, but I traced this back to an issue with SELinux and a particular command in the referenced install guide, at least on a fresh install of CentOS 8 using httpd and php-fpm (standard PHP install after adding epel) with folder permissions set roughly per https://github.com/PrivateBin/PrivateBin/wiki/FAQ#what-are-the-recommended-file-and-folder-permissions-for-privatebin and chown -R apache:apache applied one level back from data (AKA to "path" below).

This command from https://github.com/PrivateBin/PrivateBin/wiki/Installation-on-Red-Hat-with-SELinux#installation did not work:
semanage fcontext -a -t httpd_sys_rw_content_t "/my/path/data(/.*)?"

This set of commands did work:
cd /my/path
semanage fcontext -a -t httpd_sys_rw_content_t 'data'
restorecon -v 'data'

**Comment by rugk** [comment]
That tutorial originates from https://www.pozzo-balbi.com/help/Zerobin. So maybe contact them/discuss it there.
In any case, if you are sure your approach works, you can of course edit the wiki – that's why it's a wiki. :slightly_smiling_face:
