### ISSUE TITLE
raw text tail text after <<""<

### ISSUE THREAD

**Issue by andrew-ld** [PrivateBin/PrivateBin#422]
## Steps to reproduce

1. create new document with `<<""<<owo`
2. open raw text

### What happens
`<owo`  is not shown

### What should happen
the raw text should also show that part

## Basic information

I can reproduce this issue on <https://privatebin.net>: Yes

**Comment by rugk** [comment]
Likely a dupe of https://github.com/PrivateBin/PrivateBin/issues/403
