### ISSUE TITLE
Add new language and translation of a system msg problem

### ISSUE THREAD

**Issue by info-path** [PrivateBin/PrivateBin#424]
## Steps to reproduce

1. I want to add new language, e.g. czech (cs.json)
2. I have duplicated any existing language file, e.g. 'de.json' to 'cs.json'
3. Added 'cs' to supported languages in js/privatebin.js
4. Some phrases still appear untranslated.

For example, I'm unable show this phrase translated:
_"Your paste is <a id=\"pasteurl\" href=\"%s\">%s</a> <span id=\"copyhint\">(Hit [Ctrl]+[c] to copy)</span>":_

This message still appears in English. All others system messages (green or blue box) are not translated too. I missed something important or is there any other config for activating additional languages?

Tested on PrivateBin 1.2.1 (Docker :: jgeusebroek/privatebin)

Thx

**Comment by r4sas** [comment]
Doesn't have that issue on 1.1.1 and 1.2.1 from release.

**Comment by elrido** [comment]
Hi @info-path,

I'll be happy to help you solving the issue and also to merge into the project. Could you share your repository with us to take a look at your translation file?

I would guess that there is an issue with the escaping of the double quotes (`"`) using a backslash (`\`) inside of the HTML snippet.

Best,
El RIDO

**Comment by r4sas** [comment]
Yes, I want write about this too.

Untranslated and translated text must contain escaped quotes, so your string must see like:
```
"Your paste is <a id=\"pasteurl\" href=\"%s\">%s</a> <span id=\"copyhint\">(Hit [Ctrl]+[c] to copy)</span>":"Your paste is <a id=\"pasteurl\" href=\"%s\">%s</a> <span id=\"copyhint\">(Hit [Ctrl]+[c] to copy)</span>"
```

**Comment by info-path** [comment]
I apologize for the delay...

Guys, I duplicated an original lng file (de.json to cs.json) and **replaced only fourth** therm to: **"en": "cs"**. Add a 'cs' key to **supportedLanguages** in privatebin.js file. That should be enough for testing, right? 

Of course, there are still escape chars in translation, becasuse I did not change anything except the fourth therm (I used an original de.json file renamed to cs.json and change a tag to form "en": "cs").

After sending a paste this english result appears:

**Your paste is** https://xxx/?8d21d3369e34516e#FSINvENH4etvzkPdZEIGaOAggbAjp3CmCpViI2F4stI= (**Hit [Ctrl]+[c] to cop**y)

Although this original phrase in the cs.json file is an original:

    "Your paste is <a id=\"pasteurl\" href=\"%s\">%s</a> <span id=\"copyhint\">(Hit [Ctrl]+[c] to copy)</span>":
        "Dein Paste ist unter <a id=\"pasteurl\" href=\"%s\">%s</a> zu finden <span id=\"copyhint\">(Drücke [Strg]+[c] um den Link zu kopieren)</span>",


Can anyone try same steps, please?

**Comment by r4sas** [comment]
Can you upload full file?

**Comment by info-path** [comment]
Ok, this is a testing file mentioned in the previous post:
[http://foo.path.cz/cd.json.tgz](http://foo.path.cz/cd.json.tgz)

**Comment by r4sas** [comment]
All errors because your browser contain old `privatebin.js`. I think you can find that error in devtools console:
`Language 'cs' is not supported. Translation failed, fallback to English.`

Drop cache by using CTRL+F5.

Also please add new rule for plurals:
```js
me.getPluralForm = function(n) {
...
case 'cs':
    return n === 1 ? 0 : ((n >= 2 && n <= 4) ? 1 : 2);
default: ...
```

And update your translation according to three plural forms (see how its done in russian) and dont forget to fix that:
```json
"en": "de",
```

**Comment by info-path** [comment]
Thanks @r4sas for helping me, but I'm still unsuccessful. I think I edited everything that was necessary, but the system text doesn't translate. I have no idea what the problem is. My edited files are available for download [here](http://foo.path.cz/affected_files.rar) (a screenshot included). Of cource, I cleared the browser cache.

**Comment by r4sas** [comment]
Did you removed integrity check in template after changing privatebin.js?

**Comment by r4sas** [comment]
@info-path any updates?

**Comment by r4sas** [comment]
@elrido lets add czech translation as is for now, cause here no response?

**Comment by elrido** [comment]
Thank you @info-path for providing the translation. I have added your translation, updated it with the latest changes we introduced since and all the necessary changes in privatebin.js plus a unit test to ensure the plurals work as intended. In my tests it seems to work.

Please feel free to reopen the issue if you still have issues using it from the master version and of course you may want to add more translations via a pull request.
