### ISSUE TITLE
Mistake work in wiki page Encryption-format

### ISSUE THREAD

**Issue by christian-momon** [PrivateBin/PrivateBin#426]
In wiki page https://github.com/PrivateBin/PrivateBin/wiki/Encryption-format : 

> "format": "plantext" or "syntaxhighlighting" or "markdown",

Suggestion: replace "plantext" with "plaintext".  :smile:

**Comment by rugk** [comment]
Thanks. However, you can edit the wiki by yourself. Please just click "edit". :smile:

**Comment by christian-momon** [comment]
Ok, thanks. Done :smile:
