### ISSUE TITLE
PrivateBin wants to load SQLite, but I don't...

### ISSUE THREAD

**Issue by Husky110** [PrivateBin/PrivateBin#429]
Hey folks,  
I could use some help here...  
Got PrivateBin up and running on PHP 7.3.5 with nginX and I want PrivateBin to store the stuff in MySQL.
So I've set up my config like this:  
`[model]
; name of data model class to load and directory for storage
; the default model "Filesystem" stores everything in the filesystem
class = Database
[model_options]
dir = PATH "data"

;[model]
; example of DB configuration for MySQL
;class = Database
;[model_options]
;dsn = "mysql:host=localhost;dbname=MYDBNAME;charset=UTF8"
;tbl = "privatebin_"	; table prefix
;usr = "MYUSERNAME"
;pwd = "MYPASSWORD"
;opt[12] = true	  ; PDO::ATTR_PERSISTENT

;[model]
; example of DB configuration for SQLite
;class = Database
;[model_options]
;dsn = "sqlite:" PATH "data/db.sq3"
;usr = null
;pwd = null
;opt[12] = true	; PDO::ATTR_PERSISTENT
`
But every time I try to store a paste, I get the following error:
`2019/05/13 08:58:31 [error] 15198#15198: *246 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught PDOException: could not find driver in /var/www/clients/client1/web11/private/lib/Data/Database.php:106
Stack trace:
#0 /var/www/clients/client1/web11/private/lib/Data/Database.php(106): PDO->__construct('sqlite:/var/www...', NULL, NULL, Array)
#1 [internal function]: PrivateBin\Data\Database::getInstance(Array)
#2 /var/www/clients/client1/web11/private/lib/Model.php(85): forward_static_call('PrivateBin\\Data...', Array)
#3 /var/www/clients/client1/web11/private/lib/Model.php(71): PrivateBin\Model->_getStore()
#4 /var/www/clients/client1/web11/private/lib/Controller.php(258): PrivateBin\Model->purge()
#5 /var/www/clients/client1/web11/private/lib/Controller.php(125): PrivateBin\Controller->_create()
#6 /var/www/clients/client1/web11/web/index.php(18): PrivateBin\Controller->__construct()
#7 {main}
`
So my first intention was to delete the SQLite-Part in the config-file but that didn't help. It looks to me, as if PrivateBin is trying to load the SQLite-stuff, but I don't want that to happen... Help?  
Greetings

**Comment by r4sas** [comment]
Because you set `class = Database`

https://github.com/PrivateBin/PrivateBin/blob/7f1afb2b3e9f46b85910305c0c6004bffb3d61c8/cfg/conf.sample.php#L130-L135

**Comment by Husky110** [comment]
Okay - nevermind... I am to dumb to see that my DB-Class was commented out (;)...
`
[model]
; name of data model class to load and directory for storage
; the default model "Filesystem" stores everything in the filesystem
class = Database
;[model_options]
;dir = PATH "data"

[model]
; example of DB configuration for MySQL
class = Database
[model_options]
dsn = "mysql:host=localhost;dbname=MYDBNAME;charset=UTF8"
tbl = "privatebin_"	; table prefix
usr = "MYUSERNAME"
pwd = "MYPASSWORD"
opt[12] = true	; PDO::ATTR_PERSISTENT
`
now it works... sorry - my fault!

**Comment by r4sas** [comment]
Also comment out that:
```
>[model]
; name of data model class to load and directory for storage
; the default model "Filesystem" stores everything in the filesystem
>class = Database
;[model_options]
;dir = PATH "data"```
