### ISSUE TITLE
"Could not create paste: server error or not responding"

### ISSUE THREAD

**Issue by k0nsl** [PrivateBin/PrivateBin#43]
I am pulling the latest code from the repo and with only minor changes. But I tried to revert most of them and I cannot get this issue out of the way, even if I use `jquery-1.11.3`. It simply doesn't matter in this case, it appears. Yet it seems to be indicating some sort of issue with jQuery.

Error:
`Could not create paste: server error or not responding`

The only thing I see in the Chrome developer console is the following:
![alt text](https://screen.img-cdn.ru/chrome_2016-07-18_12-21-12.png "screenshot")

I switched from PHP7 to PHP5.6 in lieu of #42 .

**Comment by elrido** [comment]
Can you send us the error message found in your webserver / PHP log? Are you using privatebin_db or privatebin_data model? If the latter: Is your `data` directory writable?

**Comment by k0nsl** [comment]
It's the latter and yes the `data` directory is writable. I actually had the project running fine for a week or so until I pulled some of the new code from the repo today.
This is the most recent entries in the error log:
```
[18-Jul-2016 10:01:17 UTC] PHP Fatal error:  Uncaught Error: Class 'RainTPL' not found in /home2/zerobin01/public_html/lib/privatebin.php:425
Stack trace:
#0 /home2/zerobin01/public_html/lib/privatebin.php(154): privatebin->_view()
#1 /home2/zerobin01/public_html/index.php(16): privatebin->__construct()
#2 {main}
  thrown in /home2/zerobin01/public_html/lib/privatebin.php on line 425
[18-Jul-2016 10:06:22 UTC] PHP Fatal error:  Class 'RainTPL' not found in /home2/zerobin01/public_html/lib/privatebin.php on line 425
[18-Jul-2016 10:08:35 UTC] PHP Fatal error:  Class 'purgelimiter' not found in /home2/zerobin01/public_html/lib/model.php on line 65
```

**Comment by elrido** [comment]
Are the files RainTPL.php and purgelimiter.php readable in the lib folder? The error indicates, that these classes weren't loaded.

**Comment by k0nsl** [comment]
@elrido: yes, they are readable and owned by the correct user.

**Comment by k0nsl** [comment]
Now I am getting further:
```
[18-Jul-2016 13:58:10 UTC] PHP Warning:  forward_static_call() expects parameter 1 to be a valid callback, class 'privatebin_data' not found in /home2/zerobin01/public_html/lib/model.php on line 84
[18-Jul-2016 13:58:10 UTC] PHP Catchable fatal error:  Argument 2 passed to model_abstract::__construct() must be an instance of zerobin_abstract, null given, called in /home2/zerobin01/public_html/lib/model.php
```

**Comment by elrido** [comment]
Sorry, then I am at a loss. :-(

I can't reproduce your issue on my test instance with PHP 5.6 and all the unit tests on PHP 7 indicate it is working, too. You need to figure out why these two files aren't included.

**Comment by k0nsl** [comment]
Does the error log posted just before your response help?

**Comment by k0nsl** [comment]
I "solved" it by deleting all the RainTPL functions in my template, as I don't really need those anyway.

It's working fine now!

Test: https://p.k0nsl.org/

😁

**Comment by k0nsl** [comment]
The only thing which is seemingly not working is the syntax highlighting:

https://p.k0nsl.org/?a1c9b8da18108e52#P7xJafjtMZ73XAmmpteNEPLE8ZxPPiFiX1ryte3zgY0=

**Comment by k0nsl** [comment]
Sorry for the flood of comments. I just wanted to say that I had to disable syntax highlighting as it would actually parse both HTML and PHP which made it very dangerous. I don't understand how that could be possible.

**Comment by elrido** [comment]
The HTML encoding issue was recently introduced with the preview feature (#4).

**Comment by rugk** [comment]
@k0nsl Just FYI: It is not necessary to change the title when an issue is solved. We already close issues when they are resolved. :smiley:
