### ISSUE TITLE
Chromium fails to download attachment if bigger than 2MB

### ISSUE THREAD

**Issue by BigWax** [PrivateBin/PrivateBin#432]
## Steps to reproduce

1. Attach any file over 1.5MB (apparently - https://stackoverflow.com/questions/47353040/)
2. Try to download in Chromium (or Chrome)

### What happens

File fails to download with "Failed - Network error"

### What should happen

File downloads successfully as it does in Firefox.

## Additional information

I uploaded a 4MB image file and some builds with confidential information on them and users using Chromium as their Browser failed to download the attachments.

Downloading with Chrome works fine apparently when the files are below 1.5MB because of the way PrivateBin initiates the download.

I've tried the following:

https://stackoverflow.com/a/3916267

Possible solutions:

https://stackoverflow.com/questions/38781968/
https://stackoverflow.com/questions/50458942/
https://stackoverflow.com/questions/53560122/

## Basic information

Debian 9.5

nginx 1.14.0

Chromium (Version 74.0.3729.131)

1.21

I can reproduce this issue on <https://privatebin.net>: No, because it has no file attaching capability

**Comment by rugk** [comment]
https://stackoverflow.com/a/3916267 ends in a 404 error.

**Comment by BigWax** [comment]
Doesn't for me.
Try this one: https://stackoverflow.com/questions/3916191/download-data-url-file/3916267#3916267

**Comment by arregit** [comment]
I have proper access to https://stackoverflow.com/a/3916267
Maybe just a temporary issue with stackoverflow?

**Comment by r4sas** [comment]
Tested with chrome 68 on win, issue reproducable.

**Comment by elrido** [comment]
Does this issue still occur on the [test instance](https://github.com/PrivateBin/PrivateBin/pull/431#issuecomment-493750168) using the webcrypto / zlib development branch? It could be a memory limit in chrome, as we unpack it all into JS variables.

**Comment by r4sas** [comment]
> Example [paste with a moon pic](http://zerobin-test.dssr.ch/?7e9208746bad71ab#GbjtsmX6MHbcKXJEYZjp5V2JsYYXyvLbYbEkLz2KmqUK) to test.

Asks password, bacause you sent http link. With https decodes without problems.
Pic is shown itself at top of paste, but download link turn chrome in endless download state without prompting save location.

**Comment by BigWax** [comment]
The behaviour of the link that r4sas is talking about is that in Chrome, although in Firefox, the http link opens and decrypts fine as well

**Comment by r4sas** [comment]
2see: https://gist.github.com/fupslot/5015897

**Comment by rugk** [comment]
Corresponding line in code:
https://github.com/PrivateBin/PrivateBin/blob/ebbb850b27dfbd9f4d82825e7ab8ce2aef3ef460/js/privatebin.js#L2515

We currently use data URIs for most browsers, only that blob thing for IE. And yeah, this seems to be problematic, because [varying data limits apply](https://stackoverflow.com/a/41755526/5008962). That answer also lists alternatives, [and yeah blob URIs may be a good one](https://chrisrng.svbtle.com/using-url-createobjecturl). That said, we could keep data URIs for Firefox, as they seem to be unlimited in size there… :thinking:

**Comment by r4sas** [comment]
blob URI must be used anyway, because here no more ways to get access to download file from memory, stored in blob.

btw Tegelram Web used blob URI for serving data (such as images, audio, videos) to user, thats why I sent it's code as example.
