### ISSUE TITLE
Automatic dark/light mode

### ISSUE THREAD

**Issue by rugk** [PrivateBin/PrivateBin#433]
There is a quite new CSS media query feature called [`prefers-color-scheme`](https://developer.mozilla.org/docs/Web/CSS/@media/prefers-color-scheme). It allows you to detect whether the system/user wants a dark website, so you can adjust your CSS.

Currently it is only supported by Safari and Firefox 67 or higher.

Maybe we can use it.

BTW: I also have [a Firefox add-on called “Dark Mode Website Switcher”](https://addons.mozilla.org/de/firefox/addon/dark-mode-website-switcher/?src=external-github-issue) ([source code](https://github.com/rugk/website-dark-mode-switcher))  that you can use to toggle this setting in Firefox directly – without needing to change the system option. Maybe that could be helpful.

----

The problem I see, obviously: We currently have two separate themes for dark/light mode. So maybe we could combine them?
As far as I know the HTML itself, is not really different, at least.

**Comment by elrido** [comment]
Not a big problem, they already are the same theme (bootstrap.php). You would just need to send the server some indication which theme to use and he could switch the mode. If this is client-side only, you could do the detection in JS and inject the CSS + perform the small class changes needed.

**Comment by rugk** [comment]
Yes, client-side-only.
Yeah, IMHO, we should maybe add a bootstrap template via `boostrap-auto` that has this automatic switch?
Or should we just replace the old dark/light bootstrap themes with a new one called "bootstrap" only, i.e. remove the possibility for admins to force a specific design?

**Comment by elrido** [comment]
Well, obviously we should let the admins enforce one or the other, but could still have the automatic mode be the default.

It's a good idea for the 1.4 release after the current 1.3 we are working on, as 1.4 will focus on UI changes.

**Comment by rugk** [comment]
I had a quick look, and yes. Best would be, if we also reduce the conditional rewrites by PHP inside there. (adding different classes etc.) (and switch styling in pure CSS)
But ah, this is bootstrap things… argh…

So yeah, could be a little harder than I initially thought.

**Comment by Z3ROGRAV1TYx** [comment]
Yup, would love to see Dark Mode!

**Comment by rugk** [comment]
In https://github.com/PrivateBin/PrivateBin/issues/596 the theme https://bootswatch.com/3/slate/ has been suggested for the bootstrap dark mode.

**Comment by elrido** [comment]
Note to self / whoever has time: At some point we should probably upgrade to bootstrap 4 - at that point this might be a simple solution to add a dark mode to it https://coliff.github.io/dark-mode-switch/

**Comment by JasonHK** [comment]
Could we revisit this topic? A simple `<link type="text/css" rel="stylesheet" href="..." media="(prefers-color-scheme: ...)">` should work.

**Comment by elrido** [comment]
Sure thing, go for it.

**Comment by cellardoor452** [comment]
Is this being worked on?

**Comment by elrido** [comment]
> Is this being worked on?

It seemed @JasonHK wanted to, but I've not seen any pull requests coming our way, yet. So if you, @cellardoor452, would like to tackle this, it would be appreciated.
