### ISSUE TITLE
Source code syntax highlighting looks crazy in Dark theme 

### ISSUE THREAD

**Issue by gerroon** [PrivateBin/PrivateBin#439]
Hi

I am using the dark theme and I just tried source format to see how it looks. It looks messed up such that it is not usable :(

Please see the image for how it looks. Bear in mind that there is code in the dark strips too.

![Screenshot_2019-06-13_19-51-58](https://user-images.githubusercontent.com/8519469/59476131-cc681300-8e3e-11e9-9f4d-d15694428e64.png)

**Comment by r4sas** [comment]
```
; (optional) set a syntax highlighting theme, as found in css/prettify/
syntaxhighlightingtheme = "sons-of-obsidian"
```

**Comment by gerroon** [comment]
Well yeah I have syntax highlighting and I do not want to disable.   I am not sure about what you are offering here as a solution. This bug is about syntax highlighting looking good in darktheme.

**Comment by r4sas** [comment]
I'm offering to change default value (`doxy`) to `sons-of-obsidian` for `syntaxhighlightingtheme` option in config file.

**Comment by gerroon** [comment]
I have the same problem with sons-of obsidian. Sorry i did not make it clear

**Comment by r4sas** [comment]
Have you tried drop cache after changing?

**Comment by r4sas** [comment]
![image](https://user-images.githubusercontent.com/7023612/59483966-9a73a280-8e78-11e9-90e6-4acddb486fe9.png)
bootstrap-dark with sons-of-obsidian.

**Comment by gerroon** [comment]
This is really interesting and curious. I am using the docker install. Which method do you use to install and which version are you on?

**Comment by r4sas** [comment]
That is 1.2.1 installed by hands from release zip running on nginx+php7.1

**Comment by gerroon** [comment]
Thanks, not sure why I have what I shown compared to what you have w your dark theme. This is quite a discrepency for sure

**Comment by r4sas** [comment]
Re-pull container. I see that @elrido updated tags 2 days ago.
Or install from scratch:
```docker run -d --restart="always" --read-only -p 8080:80 -v conf.php:/srv/cfg/conf.php:ro -v privatebin-data:/srv/data privatebin/nginx-fpm-alpine:1.2.1```

**Comment by elrido** [comment]
Hi @gerroon,

If you do inject you own conf.php file in the with the `syntaxhighlightingtheme` option set to the dark syntax highlighting theme called `sons-of-obsidian` in the `[main]` section of your config file as rugk describes above, using the volume option in docker, then your site will look correct. This is documented in the [configuration wiki entry](https://github.com/PrivateBin/PrivateBin/wiki/Configuration#syntaxhighlightingtheme):

> For the page, bootstrap-dark and bootstrap-dark-page PrivateBin templates we suggest using the sons-of-obsidian theme.

Please let us know if this is resolved for you. I did just test all three docker images and they all let you change that option via the config file. If it doesn't work, please share your full config file, obfuscating db passwords, if used.

**Comment by Thatkookooguy** [comment]
Hi all!

I just installed this inside a docker container using
```
docker run -d --name=privatebin --restart="always" --read-only -p 10198:8080 -v $PWD/privatebin/data:/srv/data -v $PWD/privatebin/cfg:/srv/cfg:ro privatebin/nginx-fpm-alpine
```
And I can see the Web interface on `localhost:10198`. I can also see that I got the dark theme from my `conf.php` since I see the dark theme in the UI.

But I still see white lines between each line and the code is unreadable after the syntax highlighting.

Here is my configuration (This is a copy-paste of `conf.sample.php`, so I'll post only the attributes I changed or are relevant):
```php
;<?php http_response_code(403); /*
; config file for PrivateBin
;
; An explanation of each setting can be find online at https://github.com/PrivateBin/PrivateBin/wiki/Configuration.

[main]
; (optional) set a project name to be displayed on the website
; name = "PrivateBin-test"

; The full URL, with the domain name and directories that point to the PrivateBin files
; This URL is essential to allow Opengraph images to be displayed on social networks
; basepath = ""

; enable or disable the discussion feature, defaults to true
discussion = true

; preselect the discussion feature, defaults to false
opendiscussion = true

; enable or disable the password feature, defaults to true
password = true

; enable or disable the file upload feature, defaults to false
fileupload = true

; preselect the burn-after-reading feature, defaults to false
burnafterreadingselected = false

; which display mode to preselect by default, defaults to "plaintext"
; make sure the value exists in [formatter_options]
defaultformatter = "plaintext"

; (optional) set a syntax highlighting theme, as found in css/prettify/
; syntaxhighlightingtheme = "sons-of-obsidian"

; size limit per paste or comment in bytes, defaults to 10 Mebibytes
sizelimit = 10485760

; template to include, default is "bootstrap" (tpl/bootstrap.php)
template = "bootstrap-dark"
```

Even though I followed the instructions and installed the docker based on the readme, I see the following:
![image](https://user-images.githubusercontent.com/10427304/108604787-b4d58180-73b8-11eb-94f9-6a71ee280270.png)
Turning into this:
![image](https://user-images.githubusercontent.com/10427304/108604802-c4ed6100-73b8-11eb-8f74-caf3be64bca2.png)


(also, unrelated, but where can I see the `privatebin-test` **name** that I changed in the settings? all the places in the UI still write privatebin as is)
