### ISSUE TITLE
bootstrap-compact template broken on dropdowns

### ISSUE THREAD

**Issue by brunob** [PrivateBin/PrivateBin#443]
## Steps to reproduce
1. set `template = "bootstrap-compact"` in config
2. change paste expiration

### What happens

expiration is **also** set on formatter dropdown which result in an invalid data post 

## Additional information

This comes from f25661beda3f88a11c9eb8015af77a12d52f8830 which put the `id="formatter"` on the `li` containing the dropdown instead of puttin this id on the `a class="dropdown-toggle"` as it's done for the `expiration` dropdown.

So, the privatebin script doesn't find the right element here https://github.com/PrivateBin/PrivateBin/blob/master/js/privatebin.js#L3807

I can provide a PR movin the `id="formatter"` on the `a` which fix the bug :)

**Comment by brunob** [comment]
FTR i've applied the patch on our instance which use a personal theme based on bootstrap-compact here https://bin.infini.fr/ and it works well.

**Comment by rugk** [comment]
Yes, feel free to provide a PR. Thanks in advantage… :smiley:

**Comment by brunob** [comment]
@rugk i was just pushing this ;)
