### ISSUE TITLE
Python Cli password problem

### ISSUE THREAD

**Issue by MarcoGomes00** [PrivateBin/PrivateBin#445]
## Steps to reproduce

1. Import sjcl module (https://pypi.org/project/sjcl/#description)
2. Generate a cyphertext 
    cyphertext = SJCL().encrypt(b"secret message to encrypt", "shared_secret", mode='gcm')
    Result -> 
{'ks': 128, 'cipher': 'aes', 'mode': 'gcm', 'v': 1, 'adata': '', 'iv': 'uVxZJTC9Fd41w7X7sTEQqA==', 'salt': '3mpNDtn9aMM=', 'ts': 128, 'iter': 10000, 'ct': 'TtT75RHoACUiqHonr2fPqjqRyvHjt7mg9JlN+bDaZn0OzYL6uADCReo='}
3. Make Paste request to server
```
POST  HTTP/1.1
Host: localhost:8080
Content-Type: application/x-www-form-urlencoded
host: localhost:8080
X-Requested-With: JSONHttpRequest
User-Agent: PostmanRuntime/7.13.0
Accept: */*
Cache-Control: no-cache
Postman-Token: a93de4f5-c662-4510-9556-8d2ee16e3f45,201ce56c-1881-4bee-8be2-7afdd7899403
accept-encoding: gzip, deflate
content-length: 385
Connection: keep-alive
cache-control: no-cache

data=%7B%22iv%22%3A%22uVxZJTC9Fd41w7X7sTEQqA%3D%3D%22%2C%22v%22%3A1%2C%22iter%22%3A10000%2C%22ks%22%3A128%2C%22ts%22%3A128%2C%22mode%22%3A%22gcm%22%2C%22adata%22%3A%22%22%2C%22cipher%22%3A%22aes%22%2C%22salt%22%3A%223mpNDtn9aMM%3D%22%2C%22ct%22%3A%22TtT75RHoACUiqHonr2fPqjqRyvHjt7mg9JlN%2BbDaZn0OzYL6uADCReo%3D%22%7D&expire=never&formatter=plaintext&burnafterreading=0&opendiscussion=0

```    
4.Receive the response
```
{
    "status": 0,
    "id": "07b5d0be61f6527a",
    "url": "/?07b5d0be61f6527a",
    "deletetoken": "959860172a50fda7b5bb359cce3cb52b1198f96dfdd73d9b1f2bd4837d84c81a"
}
```
5. Try to see the text on server
http://localhost:8080/?07b5d0be61f6527a#shared_secret

### What happens
Server asks for password, if I insert "shared_secret" it says that is incorrect

### What should happen
Should open the text decrypted

## Basic information

I also tested with public server http://cpaste.org and have the same result

https://github.com/PrivateBin/docker-nginx-fpm-alpine

https://github.com/PrivateBin/docker-nginx-fpm-alpine

**Browser:**

**PrivateBin version:**

I can reproduce this issue on <https://privatebin.net>: No

**Comment by rugk** [comment]
The part after the `#` is one part of the encryption key. This is not the same as the password. (that is optional, anyway)

See https://github.com/PrivateBin/PrivateBin/wiki/Encryption-format#process-data for details on the encryption format.

**Comment by MarcoGomes00** [comment]
Hi Rugk,

Thanks for your response.
The URL to access to paste is not like this? URL>/?<paste_ID>#<base64encode(random_key)
I made a new Pyhon script looking to the link that you sent and you can check on https://github.com/MarcoGomes00/PrivateBin-Cli-Python
The result that I'm having is the same (continue asking for a password)
If you could help me it would be great.

Regards,
Marco Gomes

________________________________
De: rugk <notifications@github.com>
Enviado: 25 de junho de 2019 16:55
Para: PrivateBin/PrivateBin
Cc: MarcoGomes00; Author
Assunto: Re: [PrivateBin/PrivateBin] Python Cli password problem (#445)


The part after the # is one part of the encryption key. This is not the same as the password. (that is optional, anyway)

See https://github.com/PrivateBin/PrivateBin/wiki/Encryption-format#process-data for details on the encryption format.

**Comment by elrido** [comment]
That is the format until and up to 1.2.1, in master the key is base58 encoded and gets fed raw into the PBKDF2 instead of as an encoded base64 string. @r4sas is at the moment working on making his python client work for both that version and the one on the current master branch, which changes the format quite a bit. I suggest you take a look at such an other Python implementation first:
https://github.com/r4sas/PBinCLI/blob/master/pbincli/format.py#L217

**Comment by MarcoGomes00** [comment]
I didn't understand.
I'm using a server with version 1.2.1, so I need to use Format version (v1), right? Base58 it's only used on v2.
I tried to use this client (https://git.cryptomilk.org/projects/cpaste.git/tree/cpaste) and have the same problem. 
Also checked @r4sas's version and update my script encode as same he's doing, but also doesn't work.

**Comment by elrido** [comment]
I had a very brief look at your code and I think your are using the raw key for the key derivation, not the base64 string. This line should probably be:
https://github.com/MarcoGomes00/PrivateBin-Cli-Python/blob/master/create_link.py#L106
```python
cipher_json =encrypt(plaintext,passphrase)
```
There may be other issues, but that was the one that sprang to my eye looking through it.
