### ISSUE TITLE
 PrivateBin requires a modern browser to work.

### ISSUE THREAD

**Issue by yammesicka** [PrivateBin/PrivateBin#446]
## Steps to reproduce
1. Install nginx + php7.2-fpm, clone on an Ubuntu 18.04 LTS server.
2. Configure the nginx (see below)
3. Get LetsEncrypt certificate.

### nginx Configuration
```nginx
server {
    server_name bin.mesicka.com;
    listen [::]:443 ssl; # managed by Certbot
    listen 443 ssl; # managed by Certbot

    root /opt/privatebin;

    index index.php;

    location / {
            try_files $uri $uri/ /index.html /index.php;
    }

    ssl_certificate /...; # managed by Certbot
    ssl_certificate_key /...; # managed by Certbot

# Improve HTTPS performance with session resumption
    ssl_session_cache shared:SSL:10m;
    ssl_session_timeout 5m;

# Enable server-side protection against BEAST attacks
    ssl_prefer_server_ciphers on;
    ssl_ciphers ECDH+AESGCM:ECDH+AES256:ECDH+AES128:DH+3DES:!ADH:!AECDH:!MD5;

# Disable SSLv3
    ssl_protocols TLSv1.2;

# Enable HSTS (https://developer.mozilla.org/en-US/docs/Security/HTTP_Strict_Transport_Security)
    add_header Strict-Transport-Security "max-age=63072000; includeSubdomains";

# Enable OCSP stapling (http://blog.mozilla.org/security/2013/07/29/ocsp-stapling-in-firefox)
    ssl_stapling on;
    ssl_stapling_verify on;

    access_log /var/log/nginx/privatebin_access.log combined;
    error_log /var/log/nginx/privatebin_error.log warn;

    location ~ \.php$ {
        try_files $uri =404;
        fastcgi_pass unix:/run/php/php7.2-fpm.sock;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
      # Prevent exposing nginx + version to $_SERVER
        fastcgi_param SERVER_SOFTWARE "";
    }
}

server {
    if ($host = projects.mesicka.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot
    if ($host = bag.mesicka.com) {
        return 301 https://$host$request_uri;
    }
    if ($host = yam.sh) {
        return 301 https://$host$request_uri;
    }
    if ($host = bin.mesicka.com) {
        return 301 https://$host$request_uri;
    }

    listen 80 ;
    listen [::]:80 ;
    return 404; # managed by Certbot
}
```

### What happens
![image](https://user-images.githubusercontent.com/1492939/60283221-58833b80-9911-11e9-8c7d-51d3dfd8a476.png)

### What should happen
The site should work, I guess.
`isOldBrowser()` should return false.

Changing it to return False results in an infinite loading screen.

## Additional information
![image](https://user-images.githubusercontent.com/1492939/60283136-2a9df700-9911-11e9-83bc-229f8be16f5b.png) - But I don't think it's relevant.

This commit may be the cause: https://github.com/PrivateBin/PrivateBin/commit/f5fee9b44a6493cabf131d77bdb016778ce1dcc0

## Basic information

**Server address**: https://bin.mesicka.com

**Server OS:** Ubuntu 18.04 LTS

**Webserver:** nginx

**Browser:** Chromium, Firefox, Chrome (Updated to latest versions)

**PrivateBin version:** Latest, unstable (ddb1c550f5c7359842f75df6a3b42b04c6d291b3)

I can reproduce this issue on <https://privatebin.net>: No

**Comment by r4sas** [comment]
> Changing it to return False results in an infinite loading screen.
Because you changed js file which has integrity check in template. Just remove `integrity="<info>"` for test.

**Comment by Lmmb74** [comment]
I'm actually getting this message displayed in the latest version of Google Chrome (75.0.3770.100) and Firefox (67.0.4). And I'm currently using https.

**Comment by elrido** [comment]
Huh, I think I flipped that logic.

**Comment by elrido** [comment]
Thank you for reporting this. I think this should be solved with the above commit (tested in Firefox and Chromium).

I did notice that the provided link returns the JS files as windows-1252 encoded, but the SRI hashes don't seem to fail due to this. But in case you get further warnings, you may want to check what is setup as the default encoding or ensure you transfer the files using a method that doesn't change the files encoding.
