### ISSUE TITLE
Trouble with the API

### ISSUE THREAD

**Issue by andrewschreiner** [PrivateBin/PrivateBin#450]
I've having some issues with the API. I am just creating a string that is encrypted. I am able to get it to generate the file on the server but when I try to reference the file with the output id from the JSON, it says the secret doesn't exist or that I can't access it. There shouldn't be a password with the request so i'm not sure what I would be putting after the # 

My url string looks like /?idfromjsoncall#notsurewhatgoeshere

**Comment by elrido** [comment]
The `notsurewhatgoeshere` is the [key you used to encrypt the data](https://sebsauvage.net/wiki/doku.php?id=php:zerobin#how_does_it_work) - in version <= 1.2.1 it is base64 encoded, as of 1.3 it will be base58 encoded instead. It is expected to be a 32 byte long key, created using a cryptographically secure random number generator.
