### ISSUE TITLE
Trying to add target="_blank" to links, but it is not added in the paste

### ISSUE THREAD

**Issue by psycholyzern** [PrivateBin/PrivateBin#451]
## Steps to reproduce

1. add `target="_blank"` in this line https://github.com/PrivateBin/PrivateBin/blob/c707c87cac67359b99349f40c776c8d301f2bf2a/js/privatebin.js#L269 to enable open link in new tab.
2. enable `sandbox allow-popups` in [cspheader](https://github.com/PrivateBin/PrivateBin/blob/c707c87cac67359b99349f40c776c8d301f2bf2a/cfg/conf.sample.php#L73)
3. regenerate SRI hash

### What happens
`target="_blank"` is not added to any links in the paste

### What should happen
`target="_blank"` should present and link can be opened in new tab by default

## Basic information

**Server address**: N/A. I don't have public address at the moment.

**Server OS:** Ubuntu 16.04.6

**Webserver:**  nginx/1.16.0

**Browser:** Firefox and Chrome. Tried both browsers on PC and Android.

**PrivateBin version:** 1.2.1

I can reproduce this issue on <https://privatebin.net>: N/A

**Comment by psycholyzern** [comment]
Just in-case anyone wondering, I already make sure `privatebin.js` loaded was the updated one, not cached.

**Comment by elrido** [comment]
It's possible that DOMpurify sanitizes this, as it is applied on top of the escaped, linked text https://github.com/PrivateBin/PrivateBin/blob/c707c87cac67359b99349f40c776c8d301f2bf2a/js/privatebin.js#L2217

**Comment by psycholyzern** [comment]
Working great! Thanks a lot.

**Comment by rugk** [comment]
If you do so, please also read https://www.jitbit.com/alexblog/256-targetblank---the-most-underestimated-vulnerability-ever/ though!

This opens up a big vulnerability, so add `rel="noopener` too. AFAIK newer Firefox versions do not require `noreferrer` anymore, though.

**Comment by psycholyzern** [comment]
thanks @rugk , I will :)
