### ISSUE TITLE
Loading... Error in Firefox

### ISSUE THREAD

**Issue by cnxsoft** [PrivateBin/PrivateBin#453]
## Steps to reproduce

1. Access pastebin.cnx-software.com in Firefox

### What happens
The page will be stuck in "Loading..." only in Firefox. No problem in Chrome so far.

### What should happen
It should load the page.

## Additional information

Note that I'm using Cloudflare, and I've set-up a rule to disable performance. 

Firefox browser console:
Error: WebExtension context not found! ExtensionParent.jsm:1041:13
Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”). pastebin.cnx-software.com:1:1
Content Security Policy: The page’s settings blocked the loading of a resource at data:application/font-woff2;charset=utf-… (“font-src”).
Content Security Policy: The page’s settings blocked the loading of a resource at data:application/font-woff;charset=utf-8… (“font-src”).
Content Security Policy: The page’s settings blocked the loading of a resource at data:font/woff;base64,d09GRgABAAAAAJAgAB… (“font-src”).
Content Security Policy: The page’s settings blocked the loading of a resource at data:font/woff;base64,d09GRgABAAAAAI7sAB… (“font-src”).
Content Security Policy: The page’s settings blocked the loading of a resource at data:application/font-woff2;charset=utf-… (“font-src”).
Content Security Policy: The page’s settings blocked the loading of a resource at data:application/font-woff;charset=utf-8… (“font-src”).
Content Security Policy: The page’s settings blocked the loading of a resource at data:font/woff;base64,d09GRgABAAAAAJAgAB… (“font-src”).
Content Security Policy: The page’s settings blocked the loading of a resource at data:font/woff;base64,d09GRgABAAAAAI7sAB… (“font-src”).
Content Security Policy: The page’s settings blocked the loading of a resource at data:font/woff;base64,d09GRgABAAAAAIw4AB… (“font-src”).
Content Security Policy: The page’s settings blocked the loading of a resource at data:font/woff;base64,d09GRgABAAAAAEzMAB… (“font-src”).
Content Security Policy: The page’s settings blocked the loading of a resource at data:font/woff;base64,d09GRgABAAAAAI7kAB… (“font-src”).
Content Security Policy: The page’s settings blocked the loading of a resource at data:font/woff;base64,d09GRgABAAAAAI3gAB… (“font-src”).
Content Security Policy: The page’s settings blocked the loading of a resource at data:font/woff;base64,d09GRgABAAAAAIt0AB… (“font-src”).
Content Security Policy: The page’s settings blocked the loading of a resource at data:font/woff;base64,d09GRgABAAAAAIw4AB… (“font-src”).
Content Security Policy: The page’s settings blocked the loading of a resource at data:font/woff;base64,d09GRgABAAAAAEzMAB… (“font-src”).
Content Security Policy: The page’s settings blocked the loading of a resource at data:font/woff;base64,d09GRgABAAAAAI7kAB… (“font-src”).
Content Security Policy: The page’s settings blocked the loading of a resource at data:font/woff;base64,d09GRgABAAAAAI3gAB… (“font-src”).
Content Security Policy: The page’s settings blocked the loading of a resource at data:font/woff;base64,d09GRgABAAAAAIt0AB… (“font-src”).
Content Security Policy: The page’s settings blocked the loading of a resource at data:font/woff;base64,d09GRgABAAAAAG1gAB… (“font-src”).
Content Security Policy: The page’s settings blocked the loading of a resource at data:font/woff;base64,d09GRgABAAAAAGvEAB… (“font-src”).
Content Security Policy: The page’s settings blocked the loading of a resource at data:font/woff;base64,d09GRgABAAAAAGz8AB… (“font-src”).
Content Security Policy: The page’s settings blocked the loading of a resource at data:font/woff;base64,d09GRgABAAAAAGVUAB… (“font-src”).
Content Security Policy: The page’s settings blocked the loading of a resource at data:font/woff;base64,d09GRgABAAAAAG1gAB… (“font-src”).
Content Security Policy: The page’s settings blocked the loading of a resource at data:font/woff;base64,d09GRgABAAAAAGvEAB… (“font-src”).
Content Security Policy: The page’s settings blocked the loading of a resource at data:font/woff;base64,d09GRgABAAAAAGz8AB… (“font-src”).
Content Security Policy: The page’s settings blocked the loading of a resource at data:font/woff;base64,d09GRgABAAAAAGVUAB… (“font-src”).
Content Security Policy: The page’s settings blocked the loading of a resource at data:font/woff;base64,d09GRgABAAAAAKD5AB… (“font-src”).
Content Security Policy: The page’s settings blocked the loading of a resource at data:font/woff;base64,d09GRgABAAAAAJd6AB… (“font-src”).
Content Security Policy: The page’s settings blocked the loading of a resource at data:font/woff;base64,d09GRgABAAAAAKD5AB… (“font-src”).
Content Security Policy: The page’s settings blocked the loading of a resource at data:font/woff;base64,d09GRgABAAAAAJd6AB… (“font-src”).
None of the “sha512” hashes in the integrity attribute match the content of the subresource. pastebin.cnx-software.com
Error: WebExtension context not found! ExtensionParent.jsm:1041:13
None of the “sha512” hashes in the integrity attribute match the content of the subresource. 

## Basic information

**Server address**: pastebin.cnx-software.com

**Server OS:** Ubuntu 16.04.6 LTS

**Webserver:** nginx 1.10.3 (ubuntu)

**Browser:** Firefox 67.0.4

**PrivateBin version:** 1.2.1

I can reproduce this issue on <https://privatebin.net>: No

**Comment by elrido** [comment]
You definitely do have an issue with cloud flare - Note the error message:
> None of the “sha512” hashes in the integrity attribute match the content of the subresource.

This means the browser prevented these scripts from getting executed because they got manipulated in transport. If you do take a look at the scripts in your browsers console you will see that they got minified and all mangled together. I can't give you more suggestions then what is already noted in the [FAQ on cloud flare](https://github.com/PrivateBin/PrivateBin/wiki/FAQ#how-to-make-privatebin-work-when-using-cloudflare-for-ddos-protection). If you can't fix the issue using those suggestions, please raise a support request at cloud flare who are the cause for this issue.

**Comment by cnxsoft** [comment]
I know it's closed, but it's unrelated to Cloudflare since I've disabled Cloudflare on this subdomain, and it's still happening. It's also browser/OS dependent as it's working with Chrome on Ubuntu 18.04, while failing in Firefox, and failed on both Chrome and Firefox in Ubuntu 19.04.

I've attached screenshots. Working with Ubuntu 18.04.2 + Chrome version 75.0.3770.100 (Official Build) (64-bit)
![Screenshot from 2019-07-10 09-56-59](https://user-images.githubusercontent.com/1366138/60936970-18e92600-a2f9-11e9-94ae-dbeb0837bc42.png)

Failed with Ubuntu 19.04 + Chrome version 75.0.3770.100 (Official Build) (64-bit)
![Screenshot from 2019-07-09 21-12-46](https://user-images.githubusercontent.com/1366138/60937153-9dd43f80-a2f9-11e9-8268-9464426c92e2.png)

I've disabled all extensions in the latter, restarted it, and the problem remains the same.  I have no idea what may cause this. Note that a few days ago, I could use PrivateBin in Ubuntu 18.04.2 + Chrome without issues, and then it suddenly stopped working.

**Comment by r4sas** [comment]
> Refused to load the script '.../js/privatebin.js?1.2.1' because it violates the following Content Security Policy directive: "script-src 'none'".

**Comment by cnxsoft** [comment]
Thanks for checking it out. I've started a Windows laptop, and I can load the page in both Edge and Firefox.

Output from the devtools console in Ubuntu 19.04 with Chrome:
`Failed to find a valid digest in the 'integrity' attribute for resource 'https://pastebin.cnx-software.com/js/jquery-3.4.1.js' with computed SHA-256 integrity 'b9+HjKphFauI8nDYHP28y6qTk1kku50BWwxM9KHUg9s='. The resource has been blocked.
pastebin.cnx-software.com/:1 Failed to find a valid digest in the 'integrity' attribute for resource 'https://pastebin.cnx-software.com/js/kjua-0.6.0.js' with computed SHA-256 integrity 'EIoG6QkviT/0UoKl2D+sybLOoPAXiZpks19dBOh38ho='. The resource has been blocked.
pastebin.cnx-software.com/:1 Failed to find a valid digest in the 'integrity' attribute for resource 'https://pastebin.cnx-software.com/js/zlib-1.2.11.js' with computed SHA-256 integrity 'niDqyxq3wG60nsIYJFzSO75PVMRLx8EkooX3RL0j9oY='. The resource has been blocked.
pastebin.cnx-software.com/:1 Failed to find a valid digest in the 'integrity' attribute for resource 'https://pastebin.cnx-software.com/js/base-x-3.0.5.1.js' with computed SHA-256 integrity 'Xtt9C6Op9ZLTfszJraiAbn6U1k0hR/Dettri7EVOOog='. The resource has been blocked.
pastebin.cnx-software.com/:1 Failed to find a valid digest in the 'integrity' attribute for resource 'https://pastebin.cnx-software.com/js/rawinflate-0.3.js' with computed SHA-256 integrity '2iF5EcFFGqVOpHWk+bj9WVyJKBAGFR7b7ecNY2FqX3o='. The resource has been blocked.
pastebin.cnx-software.com/:1 Failed to find a valid digest in the 'integrity' attribute for resource 'https://pastebin.cnx-software.com/js/bootstrap-3.3.7.js' with computed SHA-256 integrity 'sVRSIVKSvm4GwgVeX4Wk2C/ld4SAtuDOPHDrui3Woos='. The resource has been blocked.
pastebin.cnx-software.com/:1 Failed to find a valid digest in the 'integrity' attribute for resource 'https://pastebin.cnx-software.com/js/prettify.js?1.2.1' with computed SHA-256 integrity 'jUFjOIWvvFxVIQrDPeAguwZc9rC3DuIn2EFS+zFF4GM='. The resource has been blocked.
pastebin.cnx-software.com/:1 Failed to find a valid digest in the 'integrity' attribute for resource 'https://pastebin.cnx-software.com/js/purify-1.0.11.js' with computed SHA-256 integrity 'HS2KhdNWbqVUXCE8Wo/LN5KrmctOutbDxtrtBiER5d8='. The resource has been blocked.
pastebin.cnx-software.com/:1 Failed to find a valid digest in the 'integrity' attribute for resource 'https://pastebin.cnx-software.com/js/privatebin.js?1.2.1' with computed SHA-256 integrity '+9VVgJN0dg+oY/9iUMmBHXyrbuSiHu4TazdSFzDP/Us='. The resource has been blocked.`

**Comment by elrido** [comment]
Firefox 67 on Ubuntu 18.04 works here, just tested. Maybe you have some of the mangled JS stuck in your cache (press Ctrl+F5 to force a refresh) or are using some local proxy server that serves you outdated content?

**Comment by cnxsoft** [comment]
OK, it works on all browsers now. Sorry about that (wasting your time).

**Comment by gerroon** [comment]
I have an issue in FF 67 but not Chromium on Linux. Did anyone figure out the actual issue?

**Comment by cnxsoft** [comment]
It's actually still happening to me from time to time. I can't explain it, but pressing Ctrl+F5 fixes the issue. It must be some caching issue.

**Comment by gerroon** [comment]
Setting `javascript.options.wasm` to true fixes it for me

**Comment by elrido** [comment]
That option is true by default. Did you maybe disable it for security concerns or use(d) a plugin that disables it?

**Comment by gerroon** [comment]
Yeah I use user.js

**Comment by gramakri** [comment]
Hit this issue when updating the Cloudron package. Atleast for us, the root cause was that we picked a commit that had an out of date SRI - https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity. Advancing the privatebin code to a commit that updates the SRI, fixes the problem.

For others hitting the same problem, it's probably because your CDN is maybe manipulating the js.
