### ISSUE TITLE
1.3 Default Install Not Working with IIS 8.5 (WebAssembly Error)

### ISSUE THREAD

**Issue by eneerge** [PrivateBin/PrivateBin#457]
## Steps to reproduce

1. Open website in Firefox 68.0 hosted by IIS 8.5

### What happens
The page fails to load.

> Compile error: wasm validation error

### What should happen
The page loads

## Additional information

![image](https://user-images.githubusercontent.com/7434613/61091208-e7f71700-a406-11e9-9119-e94b8a58e79a.png)

## Basic information

**Server address**:
<message me if need it>

**Server OS:**
Windows Server 2016

**Webserver:**
IIS 8.5

**Browser:**
Firefox 68.0

**PrivateBin version:**
1.3

I can reproduce this issue on <https://privatebin.net>: NO

**Comment by eneerge** [comment]
This seems to be an issue with the .wasm extension on the filename.  Need to reconfigure IIS.

**Comment by eneerge** [comment]
Ok, fixed.

I had to add 

.wasm 
application/wasm 

in the MIME types in IIS.

**Comment by elrido** [comment]
Thank you for the feedback. Maybe you could write an few brief install notes for IIS in our wiki?
