### ISSUE TITLE
Are you using the database storage and what benefits do you gain from it?

### ISSUE THREAD

**Issue by elrido** [PrivateBin/PrivateBin#461]
While I had originally added the DB support for PrivateBin in addition to the file storage, I have personally not found any practical use case where I needed to switch from files to database as in practice I never encountered such high server loads that it would have required a distributed setup (load balancer, multiple app servers, DB backend). Out of curiosity, I therefore would like to ask the community:
1. Are you using the database storage or the default file storage?
2. How large is your data folder (when using file storage) or your hourly/daily/whatever SQL backup dump (when using databases)
3. Optional, if you know and can share this, how many hourly connections does your instance handle on average? 
4. If you use the database storage, which DBMS do you use (i.e. MariaDB, MySQL, PostgreSQL, etc.)?
5. What was the reason you picked the file or database storage in the first place?
6. If there where a conversion script, would you consider switching from one storage to the other and why?

**Comment by cryptomilk** [comment]
I'm using MySQL because most of the stuff is stored there. No other reason. If you plan to only support file storage I'm fine with it, however you need a file structure so in case a lot of pastes are stored you don't have 50k of files in one directory. Haven't checked the code if you already do ...

**Comment by elrido** [comment]
No plans on my side and I am happy to keep maintaining it. I purely have started wondering if, beyond of a (to me, so far) hypothetical redundant or load-balancing setup, there are any other use cases that clearly benefit of a database based solution.

**Comment by rugk** [comment]
Yeah, theoretically with a lot of pastes you may run into inode problems. (i.e. all inodes used -> no space, altghough factually there would be space for data)

**Comment by elrido** [comment]
I think I got the feedback I was interested in. It is used and I'll keep maintaining it. As indicated in another issue, we may even consider moving more information into DB that currently still requires file based storage (server salt, rate limiter).
