### ISSUE TITLE
POSTing to API results in an error (1.3)

### ISSUE THREAD

**Issue by BigWax** [PrivateBin/PrivateBin#463]
## Steps to reproduce

1. Do an API POST using settings mentioned below
2.

### What happens
500 Internal Error

`2019/07/15 12:28:46 [error] 28105#28105: *766 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Exception: A JSON error occurred: Syntax error (4) in /var/www/PrivateBin/lib/Json.php:76
Stack trace:
#0 /var/www/PrivateBin/lib/Json.php(52): PrivateBin\Json::_detectError()
#1 /var/www/PrivateBin/lib/Request.php(112): PrivateBin\Json::decode('v=2&adata=%5B%5...')
#2 /var/www/PrivateBin/lib/Controller.php(163): PrivateBin\Request->__construct()
#3 /var/www/PrivateBin/lib/Controller.php(121): PrivateBin\Controller->_init()
#4 /var/www/PrivateBin/index.php(18): PrivateBin\Controller->__construct()
#5 {main}
  thrown in /var/www/PrivateBin/lib/Json.php on line 76" while reading response header from upstream, client:, server: paste.internal, request: "POST / HTTP/1.0", upstream: "fastcgi://unix:/var/run/php/php7.0-fpm.sock:", host: ""`

### What should happen

Paste is created successfully

## Additional information

I do realize this is probably due to me malforming the JSON request, but I'm almost sure I've done everything as per the documentation.

Here is my test paste:

Headers:
--------------------
X-Requested-With
JSONHttpRequest

Content-Type
application/x-www-form-urlencoded

Body:
--------------------
v
2

adata
[["c2FkZnNkZnNnZGc=","ZGFmZ3NmaGZnZGZzYXJxZWZ2MzE1MzQzcjM0ZnF3ZndmYXNlZGY=",100000,256,128,"aes","gcm","zlib"],"plaintext",0,0]

ct
base64(VABoAGkAcwAgAGkAcwAgAGEAIABzAGUAYwByAGUAdAAgAGEAbgBkACAAcwBoAG8AdQBsAGQAIABiAGUAIABoAGkAZABkAGUAbgA=)

meta
{"expire": "5min"}

--------------------

I've tried "ct" without specifying the base64 part at the beginning to no luck.
I saw @cryptomilk having some trouble working through the documentation too.
Any clarification or example we can work off?

## Basic information

**PrivateBin version:** 1.3

I can reproduce this issue on <https://privatebin.net>: Yes

**Comment by elrido** [comment]
Please have a look at the [examples on the API documentation page](https://github.com/PrivateBin/PrivateBin/wiki/API#as-of-version-13), specifically these two bits:

> The full PUT and POST data now is expected to be sent as a JSON string instead of URL-encoded form data.

And the example for "create paste" gives this string as en example of such a payload:

> `{"v":2,"adata":[["base64 encoded iv","base64 encoded salt",100000,256,128,"aes","gcm","zlib"],"plaintext",0,0],"ct":"base64 of cipher text","meta":{"expire":"5min"}}`

For how such base64 encoded values may look like, you can take a peak at the values used for the PHP unit tests at https://github.com/PrivateBin/PrivateBin/blob/master/tst/Bootstrap.php#L54

**Comment by rugk** [comment]
So as it seems this question has been answered and I thus close this issue. If anyone has further questions on that topic, feel free to comment here, again.
