### ISSUE TITLE
PHP 7.0.33 function module is ineffective, and future needs are recommended

### ISSUE THREAD

**Issue by Alicealpha** [PrivateBin/PrivateBin#464]
The "Read After Burning" function module in PHP 7.0.33 does not expire after closing the browser. The "Open Comment" function module cannot be displayed below the comment, and the device browser cannot view the comment. Code formatting needs to be upgraded, especially for color highlighting, see https://paste.ofcode.org/

**Comment by rugk** [comment]
First of all, please create seperate issues for seperate problems.

Secondly, what do you mean with "expire"?

**Comment by r4sas** [comment]
Is that really PrivateBin?

**Comment by rugk** [comment]
Indeed, even looking at the code it seems to be a totally different thing. Closed as off-topic.
