### ISSUE TITLE
Future demand advice

### ISSUE THREAD

**Issue by Alicealpha** [PrivateBin/PrivateBin#465]
Code formatting needs to be upgraded, especially for color highlighting, see https://paste.ofcode.org/

**Comment by rugk** [comment]
You use a custom theme as it seems.

What syntax highlighting theme do you use?
https://github.com/PrivateBin/PrivateBin/wiki/Configuration#syntaxhighlightingtheme

**Comment by rugk** [comment]
Same as https://github.com/PrivateBin/PrivateBin/issues/464. This is not PrivateBin. Closed as off-topic.
