### ISSUE TITLE
Incorrect Documentation

### ISSUE THREAD

**Issue by stephan-schwarz** [PrivateBin/PrivateBin#467]
### What happens
The documentation at https://github.com/PrivateBin/PrivateBin/wiki/Encryption-format states the following:

paste_meta: UTF-8 string containing a JSON structure with the meta data of the paste
paste_meta_json = [
    [
        base64(cipher_iv),
        base64(kdf_salt),
        kdf_iterations,
        kdf_keysize,
        cipher_tag_size,
        cipher_algo,
        cipher_mode,
        compression type - "zlib" or "none" (the rawdeflate library used before PrivateBin version 1.3 is not quite zlib compatible)
    ],
    format of the paste - "plaintext" or "syntaxhighlighting" or "markdown",
    burn-after-reading flag - 1 or 0,
    open-discussion flag - 1 or 0
]

However, in the privatebin.js file the numbering of these fields do not match:
return this.v === 1 ? this.meta.formatter : this.adata[1]; 
return (this.v === 1 ? this.meta.opendiscussion : this.adata[2]); 
return (this.v === 1 ? this.meta.burnafterreading : this.adata[3]);

I assume this is a documentation error?

Kind regards,
Stephan Schwarz

**Comment by elrido** [comment]
I don't see the issue? The doc states that adata[0] is an array/list containing the cipher metadata, then adata[1] to adata[3] are the paste formatter, discussion and burnafterreading properties. Which matches what you see in the code. Doesn't it?

This is also again reflected in the JSON-LD file documenting the pastes `AuthenticatedData`:
https://raw.githubusercontent.com/PrivateBin/PrivateBin/master/js/pastemeta.jsonld

**Comment by stephan-schwarz** [comment]
Let me elaborate, I tried to use the 3rd party client cpaste listed at https://github.com/PrivateBin/PrivateBin/wiki/Third-party-clients
It works perfectly fine except when I try to post a paste with the burn option, which will then return a json error saying invalid data (I think I know why too).

So after looking at the cpaste script I saw how the json data was formed before it was being sent to pastebin.

    paste_adata = [
            [
                base64.b64encode(cipher_iv).decode("utf-8"),
                base64.b64encode(kdf_salt).decode("utf-8"),
                kdf_iterations,
                kdf_keysize,
                adata_size,
                cipher_algo,
                cipher_mode,
                compression_type,
            ],
            paste_formatter,
            int(paste_burn),
            int(paste_opendicussion),
    ]

The script was written according to the documentation at https://github.com/PrivateBin/PrivateBin/wiki/Encryption-format . That page states a different order of the property fields than the pastemeta.jsonId and privatebin.js files.

**Actual order
adata[1] = formatter
adata[2] = discussion 
adata[3] = burnafterreading 

**Order at https://github.com/PrivateBin/PrivateBin/wiki/Encryption-format
adata[1] = formatter
adata[2] = burnafterreading 
adata[3] = discussion 

Since privatebin.js uses hardcoded property field numbers to specify which field contains a certain property, the input json metadata needs to be in the proper order during the post request.

My assumption for getting an invalid data error when I tried to use the script with the burn option, is because I disabled the discussion option in the configuration (and since the order in of properties is different, burn would actually toggle to enable discussion instead).

The main issue is, that with the information provided at https://github.com/PrivateBin/PrivateBin/wiki/Encryption-format, it's not possible to form a proper request when you want to toggle the burn or discussion status. 

Kind regards,
Stephan Schwarz

**Comment by elrido** [comment]
Ok, now I see: The order of open discussion and burn after reading got flipped. Thanks, I corrected that.

The order documented in the JSON-LD files and used in PHP and JS the code is of course the correct one. I had focused mainly on the encryption format being correct when writing that document. For the JSON format please always refer to the actual JSON-LD documents, as explained in the introduction on that document.
