### ISSUE TITLE
"Retry on wrong password" does not work anymore

### ISSUE THREAD

**Issue by Golmote** [PrivateBin/PrivateBin#469]
## Steps to reproduce
1. Open https://privatebin.net/?232fc841513c67f3#6ACpyM4NcpsLB2a7y4GJVh54YD82xXce5ytkjW5gZaCK
2. Enter any password other than the correct one `test`.

### What happens
The "Decrypting paste..." message shows up. And nothing else happens.

### What should happen
An error should be displayed and the Retry button should appear.

I can reproduce this issue on <https://privatebin.net>: Yes

**Comment by Haocen** [comment]
Seemed to be introduced in 1.3
Cannot reproduce on 1.2.1 with Chrome Version 76.0.3809.100 (Official Build) (64-bit)

**Comment by elrido** [comment]
Got resolved as part of #508
