### ISSUE TITLE
Cant upload pastes after update to 1.3

### ISSUE THREAD

**Issue by Destroyer** [PrivateBin/PrivateBin#470]
## Steps to reproduce

1. Paste anything e.g. "aaaa"
2. Click send

### What happens
Could not create paste: server error or not responding
In dev console
```
parsererror SyntaxError: "JSON.parse: unexpected end of data at line 1 column 1 of the JSON data"
    jQuery 3
        s
        l
        o
privatebin.js:3856:25
    run privatebin/js/privatebin.js?1.3:3856
    jQuery 4
        c
        fireWith
        l
        o

```

### What should happen
Paste should be uploaded.

## Additional information

I have updated my 1.2.1 install to 1.3 and I can no longer upload pastes.

![error_chromium](https://user-images.githubusercontent.com/289988/62426253-9c244e80-b6e2-11e9-9a00-ce0484c51c60.png)

Ajax that gets sent
````{"adata":[["ioP2uFo4hjPlSKQVFrQbiA==","7DXKrs+vx1U=",100000,256,128,"aes","gcm","zlib"],"plaintext",0,0],"meta":{"expire":"1day"}}````

## Basic information

**Server OS:** Ubuntu 18.04.2

**Webserver:** nginx/1.17.2, PHP Version 7.2.19

**Browser:** Firefox 68/ Chromium 75

**PrivateBin version:** 1.3

I can reproduce this issue on <https://privatebin.net>: No

**Comment by elrido** [comment]
Is any error reported in the servers PHP and/or nginx error logs? What is the full response of the server in the request that you traced in the network tab of the dev console?

**Comment by Destroyer** [comment]
No errors in nginx or php log. Here's the full request/response
[request.har.txt](https://github.com/PrivateBin/PrivateBin/files/3465224/request.har.txt)

**Comment by elrido** [comment]
Thank you! Given that you don't have any error in the nginx/PHP logs and that the response comes from:
```json
[...]
            {
              "name": "server",
              "value": "cloudflare-nginx"
            },
[...]
```
And is empty instead of a JSON-API response:
```json
[...]
          "content": {
            "mimeType": "application/json",
            "size": 0,
            "text": ""
          },
[...]
```
I am guessing that cloudflare is once more interfering with our content. Can you try to bypass cloudflare (i.e. via port-forwarding the webservers 443 port using SSH to your local machine) and/or disable cloudflares "optimizations"?

**Comment by Destroyer** [comment]
Unfortunately not, the server name is just misleading, I'm not using cloudflare. It's just wrong server header when i disable server_token in nginx. Also cloudflare's server header is just  "cloudflare".

**Comment by elrido** [comment]
Something is eating your API response or the error that gets thrown in PHP or prevents the POST request getting forwarded to the PHP service. Can you at least find a corresponding request getting logged in your server?

**Comment by Destroyer** [comment]
yea, in access.log

   10.10.10.40 - - [05/Aug/2019:21:19:57 +0200] "POST /privatebin/ HTTP/2.0" 200 301 "https://dev.home.local/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0" "0.00"

also if i add `echo "test"` to index.php it gets sent back in the response so it works

and still no errors, even with  display_errors in php.ini enabled and error_reporting = E_ALL

**Comment by r4sas** [comment]
Can you share your nginx virtual server config?

**Comment by Destroyer** [comment]
```
server {
    server_name  dev.home.local;

    root /usr/share/nginx/html;

	gzip on;
        gzip_vary on;
        gzip_comp_level 4;
        gzip_min_length 256;
        gzip_proxied expired no-cache no-store private no_last_modified no_etag auth;
        gzip_types application/atom+xml application/javascript application/json application/ld+json application/manifest+json application/rss+xml application/vnd.geo+json application/vnd.ms-fontobject application/x-font-ttf application/x-web-app-manifest+json application/xhtml+xml application/xml font/opentype image/svg+xml image/x-icon text/cache-manifest text/css text/plain text/vcard text/vnd.rim.location.xloc text/vtt text/x-component text/x-cross-domain-policy;

    location / {
        root   /usr/share/nginx/html;
        index  index.php index.html index.htm;
    }

    # pass the PHP scripts to FastCGI server listening on 127.0.0.1:9000
    #
    location ~ \.php$ {
	fastcgi_pass unix:/run/php/php7.2-fpm.sock;
    #    root           html;
    #    fastcgi_pass   127.0.0.1:9000;
    #    fastcgi_index  index.php;
	fastcgi_intercept_errors on;
        fastcgi_param  SCRIPT_FILENAME  $document_root$fastcgi_script_name;
        include        fastcgi_params;
    }



    listen 443 ssl http2; 
    ssl_certificate /etc/nginx/ssl/dev/fullchain.pem; 
    ssl_certificate_key /etc/nginx/ssl/dev/privkey.pem; 
    include /etc/nginx/options-ssl-nginx.conf; 
    ssl_dhparam /etc/nginx/ssl/dev/ssl-dhparams.pem; 


    add_header Strict-Transport-Security "max-age=31536000" always; 


    ssl_trusted_certificate /etc/nginx/ssl/dev/chain.pem; 
    ssl_stapling on; 
    ssl_stapling_verify on; 

    add_header Referrer-Policy "same-origin";

}

server {
    if ($host = dev.home.local) {
        return 301 https://$host$request_uri;
    } 
    listen       80;
    server_name  dev.home.local;

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
    }

    #error_page  404              /404.html;

    # redirect server error pages to the static page /50x.html
    #
    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}

```

**Comment by r4sas** [comment]
I'm using that:
```
server {
    listen              x.x.x.x:443 ssl http2;
    listen              [x:x:x:x::x]:443 ssl http2;
    server_name         example.com;

    access_log          /dev/null;
    error_log           /dev/null;

    ssl_certificate         /etc/nginx/ssl/example.com/fullchain.pem;
    ssl_certificate_key     /etc/nginx/ssl/example.com/key.pem;
    ssl_trusted_certificate /etc/nginx/ssl/example.com/cert.pem;

    root                /home/www/example.com/public_html;
    index               index.php;
    charset             utf8;

    client_max_body_size 8M;

    location ~ /(cfg|data|lib|tpl|vendor) {
        deny            all;
        return          403;
    }

    location ~* ^.+.(jpg|jpeg|gif|png|ico|css|txt|bmp|js)$ {
        expires         max;
        log_not_found   off;
    }

    location / {
        try_files       $uri $uri/ /index.php;
    }

    location ~ \.php$ {
        try_files       $uri =404;
        fastcgi_param   SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include         fastcgi_params;
        fastcgi_pass    unix:/home/www/example.com/tmp/php-fpm.sock;
    }
}
```

**Comment by elrido** [comment]
Unfortunately we didn't manage to reproduce it or figure out what is causing this. As it seems isolated to this one setup it is likely to be either a configuration issue on the server that seems to cause the issue.

**Comment by 7adietri** [comment]
FWIW, I'm getting exactly this error when I configure `password = false`. It seems totally bizarre, but it's really just this one setting and PrivateBin (1.3.1) totally breaks.

**Comment by elrido** [comment]
@7adietri That seems like something we should easily be able to reproduce. Could you please create a new issue for that one, so we can investigate and fix that case? This issue was closed as none of the current maintainers managed to reproduce it on their own test instances.

**Comment by 7adietri** [comment]
New issue: https://github.com/PrivateBin/PrivateBin/issues/527

**Comment by Destroyer** [comment]
can confirm, i loaded the old snapshot and enabling password in config fixed it
