### ISSUE TITLE
Secure flag for 'lang' cookie

### ISSUE THREAD

**Issue by r4sas** [PrivateBin/PrivateBin#472]
According to Mozilla Observatory checker, we not setting `Secure` flag to cookie of language selection (`lang`).
![image](https://user-images.githubusercontent.com/7023612/62498283-5bfac400-b7e7-11e9-84dc-218f146b8772.png)
![image](https://user-images.githubusercontent.com/7023612/62498308-703ec100-b7e7-11e9-9518-b4abaa48d4f6.png)

That happens if in config enabled `languageselection` and/or used `languagedefault`.

https://github.com/PrivateBin/PrivateBin/blob/c66bff9d1bdb16a7a76ff8b3aed0f9a9d24fa7e0/lib/Controller.php#L170-L174
https://github.com/PrivateBin/PrivateBin/blob/c66bff9d1bdb16a7a76ff8b3aed0f9a9d24fa7e0/lib/Controller.php#L360-L365

Possible solution is appending to `setcookie` parameters that values:
`, 0, '', '', true`

Example: 
```php
setcookie('lang', $lang, 0, '', '', true);
setcookie('lang', $languageselection, 0, '', '', true);
```

After adding `Secure` flag:
![image](https://user-images.githubusercontent.com/7023612/62498881-703fc080-b7e9-11e9-932e-dc9a36c2c426.png)

**Comment by elrido** [comment]
According to docs, the secure flag will enforce that the cookie is only passed if the site is accessed via HTTPS. While we do recommend running all sites via HTTPS, enabling this feature may break sites that use non-HTTPS setups, i.e. over Tor. Hence, if you do a PR with this change, please do include an option to disable this, in case the language selection is enabled on a non-HTTPS site.

**Comment by rugk** [comment]
Indeed that would also break local test/dev instances (on localhost). So a setting could be:
* (by default) "on" – always send secure flag
* "auto" – send secure flag when secure connection is detected (in the request, this can e.g. break if you e.g. use an reverse proxy), this is very useful for local dev
* "off" – never send it

**Comment by r4sas** [comment]
> break sites that use non-HTTPS setups

According to current configuration for usage integrated crypto without `shim`'s, I think in future releases no one will use non-HTTPS setup.
Tor has internal hook for onion sites (to make browser think that site is secured), so I think it will pass that checks.

btw, I now set secure flag for my instance at https://paste.i2pd.xyz, which also accessed in i2p at http://paste.r4sas.i2p. When I open i2p mirror, cookie works without problems, tested with chromium.
