### ISSUE TITLE
Rework privatebin.js to enhance URL shortener integration, clear address bar when create new paste from existing paste

### ISSUE THREAD

**Issue by Haocen** [PrivateBin/PrivateBin#479]
## Steps to reproduce

1. The address bar is not cleared when creating new paste from existing paste.
2. The URL shortener integration is poor.

### What should happen
1. The address bar should be cleared when creating new paste from existing paste.
2. The URL shortener integration should be better:
  - When external URL shortener support CORS, the URL shortener is expected to immediately process the request and replace the URL displayed, this will allow seamless integration with bit.ly(before their V3 API deprecated on March 1, 2020) or self hosted solutions such as Polr or Shlink.
  - When external URL shortener doesn't support CORS or cannot be reached directly, we should open the link pointing to the URL shortener in new browser tab instead of following the link in existing browser tab/window.

## Basic information

**Server address**:
https://privatebin.net

**Server OS:**

**Webserver:**

**Browser:**

**PrivateBin version:**

I can reproduce this issue on <https://privatebin.net>: Yes

## After fix
![shortener](https://user-images.githubusercontent.com/10842569/62988402-4b170780-be12-11e9-8152-af7dd0f64e88.PNG)

**Comment by Haocen** [comment]
Thanks, I've also updated WiKi to reflect this change.

**Comment by zmweske** [comment]
This seems to be integrated and from my understanding, polr supports CORS, though for me, when I click the shorten button in privatebin, a new tab open with just the shortened url instead of replacing the url on the page itself. Has anyone else had a similar problem?
