### ISSUE TITLE
Expiration doesn't work with 'page' template

### ISSUE THREAD

**Issue by sclo** [PrivateBin/PrivateBin#482]
## Steps to reproduce
Use the 'page' template
Select an expiration time for your new paste, Send, click  on the resulting link, the remaining time will be the default expiration and not the choosen one

The default bootstrap template is ok

## Basic information
**Server OS:**
FreeBSD 11 

**Webserver:** nginx 1.6 + php73 + php-fpm

**Browser:** Chrome (latest version)

**PrivateBin version:** master (c66bff9d1bdb16a7a76ff8b3aed0f9a9d24fa7e0)

I can reproduce this issue on <https://privatebin.net>: No, it use the bootstrap template that works fine.

**Comment by elrido** [comment]
Resolved via #1287 & #1322
