### ISSUE TITLE
Showdown.js error when posting svg qrcode

### ISSUE THREAD

**Issue by macropin** [PrivateBin/PrivateBin#485]
## Steps to reproduce

1. post a markdown formatted post with an inline svg qrcode generated using `qrencode` (https://fukuchi.org/works/qrencode/)

2. Open the post

### What happens

The QR code fails to display after the first line. An error is logged in the JS console: `maximum nesting of 10 spans reached!!! (anonymous) @ showdown-1.9.0.js:2`

### What should happen

The QR code should display inline with the markdown.

## Basic information

Upstream bug report https://github.com/showdownjs/showdown/issues/678

**PrivateBin version:**
v 1.3, and possibly 1.2.1. Have not tried other versions.

I can reproduce this issue on <https://privatebin.net>: Yes

**Comment by macropin** [comment]
The fix is apparently to upgrade to Showdown 2.0 or newer.

**Comment by elrido** [comment]
As far as I can see, upstream hasn't release 2.0 yet and we do use the latest 1.9 version. I'll include your patch to master and maybe the official release will be out by the time we prepare our next release and update all the libraries.

**Comment by macropin** [comment]
Thanks!
