### ISSUE TITLE
[REVIEW] Restrict upload using NGINX

### ISSUE THREAD

**Issue by ViRb3** [PrivateBin/PrivateBin#490]
This is a request for review rather than an issue. I just created a wiki page of my approach to restrict uploading pastes using NGINX. It looks secure to me, but I would appreciate a second look:
https://github.com/PrivateBin/PrivateBin/wiki/Restrict-upload-using-NGINX

Thank you!

**Comment by rugk** [comment]
Having a quick look this LGTM.

Maybe just also describe how to "login" then (i.e. the URL) and such things.

**Comment by elrido** [comment]
LGTM as well, but in all fairness I didn't try to replicate it.
