### ISSUE TITLE
On the editing paste view of a cloned paste, if there is attachment, clicking on `New` will not clear out cloned attachment name

### ISSUE THREAD

**Issue by Haocen** [PrivateBin/PrivateBin#491]
## Steps to reproduce

1. Clone a paste with attachmnet
2. On the editing view, instead of sending the paste, click on `New`

### What happens
The attachment name should be cleared

### What should happen
The attachment name still remain, but no longer clickable nor downloadable.

## Basic information

**Server address**:

**Server OS:**
docker-alpine-fpm-nginx

**Webserver:**

**Browser:**

**PrivateBin version:**
1.3
I can reproduce this issue on <https://privatebin.net>: No, as privatebin.net didn't enable file upload.

**Comment by Haocen** [comment]
Fixed on 1.2.1, waiting for back porting.

**Comment by Haocen** [comment]
Remove drag and drop file name is needed as well.

**Comment by Haocen** [comment]
Failed to clear file name when file attached is selected via system dialog.

**Comment by Haocen** [comment]
Also, since we clear the drag & drop file name when creating the new paste, the hint will be gone before user can see it.

**Comment by elrido** [comment]
I can't reproduce this anymore in the latest 1.3.3 version. Is it still an issue?

**Comment by Haocen** [comment]
Sorry forget to close this.
