### ISSUE TITLE
Allow textarea to  be resized vertically only

### ISSUE THREAD

**Issue by Haocen** [PrivateBin/PrivateBin#492]
## Steps to reproduce

1. Resize the textarea

### What happens
The current layout allow resize the textarea vertically and horizontally

### What should happen
Should only allow textarea to be resized vertically

## Basic information

**Server address**:
Privatebin.net

**Server OS:**

**Webserver:**

**Browser:**

**PrivateBin version:**

I can reproduce this issue on <https://privatebin.net>: Yes

**Comment by elrido** [comment]
I do see this as an accessibility feature and not a bug. I personally often times have to resize tabs contents so I can read it more easily and also like to arrange textareas in such a why it makes it easier to enter content. The default font size of bootstrap CSS is too small for my eyesight, especially on large resolution screens these days.

**Comment by Haocen** [comment]
Hi,
After the fix you may still resize the input area horizontally, but only by resizing the width of the browser not by the draggable handler.

Before fix:

![resize](https://user-images.githubusercontent.com/10842569/63273320-c7bf4100-c26b-11e9-8142-850cccc76e3e.PNG)

After fix:

![resize fix](https://user-images.githubusercontent.com/10842569/63273319-c726aa80-c26b-11e9-8f65-0f4d57291ebc.PNG)

**Comment by elrido** [comment]
I usually run my browser in full screen, so would never guess that I can resize the textarea by making it larger then one screen. Only one of my workstations has a dual screens.

Or do you mean that you like to make the textarea permanently the full width of the screen? I would like that. The reason it isn't at the moment is that the bootstrap folks decided that content should have a maximum width on larger screen resolutions, while on mobile it does already now fill the screen. I just implemented the default bootstrap guidelines, assuming they had put some thought in this.

**Comment by Haocen** [comment]
Hi,

It is not about the size of window, it is about textarea size:

https://stackoverflow.com/questions/36825227/i-want-my-textarea-to-have-a-fixed-width

The textarea will still automatically fit to the width of the **window**, the fix simple preventing user from manually changing the width of textarea so it no longer fit to the width of the window.

**Comment by Haocen** [comment]
Please watch the demo below:


![image](https://user-images.githubusercontent.com/10842569/63320504-ff6dcd80-c2eb-11e9-8a89-c73cbf7eaa5d.png)

**Comment by elrido** [comment]
I watched the demo and I understand your intent, but I do prefer the use case where I can resize the textarea myself. When you display PB on a full screen window it doesn't fill the full width of the screen, but only part of it and I like to make the textarea larger in that case, over having to zoom and find the level at which the textarea then spans my screen.

I do realize that I am part of the minority of internet users with severe bad eye sight and am not representative of the general population. Can we have some more viewpoints on this topic, please?

**Comment by Haocen** [comment]
Got it.
We can have a button to override max width set on text area then. After all bootstrap 3 was built long time ago and might failed to address some accessible features.

At the meantime I think browser zooming feature might help, I used it on edge and chrome, both worked really great.

**Comment by Haocen** [comment]
Prefer https://github.com/PrivateBin/PrivateBin/issues/495 over this.
