### ISSUE TITLE
When cloning a paste with format, the format is not cloned

### ISSUE THREAD

**Issue by Haocen** [PrivateBin/PrivateBin#493]
## Steps to reproduce

1. Create a paste with format other than plaintext
2. View the paste and click on clone

### What happens
The format is always plaintext

### What should happen
The format should match the original paste

## Basic information

**Server address**:
Privatebin.net

**Server OS:**

**Webserver:**

**Browser:**

**PrivateBin version:**

I can reproduce this issue on <https://privatebin.net>: Yes

**Comment by Haocen** [comment]
Fixed on 1.2.1
Waiting for back port.

**Comment by elrido** [comment]
Quick question for my understanding: When you write "Fixed on 1.2.1" do you mean to say that you have created a patch for 1.2.1 or do you mean, that it is a regression and used to work in 1.2.1? If the latter, please label it as such.

**Comment by Haocen** [comment]
Hi,

I have my own production instance running 1.2.1 so i usually fix 1.2.1 first.

This bug is observed on both 1.2.1 and 1.3

**Comment by elrido** [comment]
Ok, thanks for clarifying. I would not want to maintain 1.2.1 anymore, but if you want, we can have a branch for that release on this repo that you can maintain if you like and we can then also publish 1.2.x bugfix releases, as long as the main new features get developed on master and in future 1.(3+n) releases (see semantic versioning standard).

I tested using the older versions listed in our directory wiki page and can confirm that this is a regression introduced between 1.1(.1) and 1.2, probably in the large JS refactoring we did back then.

I found a second regression in 1.2+ related to this: The clone button is displayed if the created paste is of the burn-after-reading type. Until 1.1 we hid the clone button in that case.

**Comment by Haocen** [comment]
Should be easy to fix.

I'd prefer to submit pull requests to master branch. I'm maintaining 1.2.1 because I've got a device doesn't support web assembly which shouldn't apply to large majority of the user's.

**Comment by rugk** [comment]
>  I'm maintaining 1.2.1 because I've got a device doesn't support web assembly which shouldn't apply to large majority of the user's.

Off-topic, but this is https://github.com/PrivateBin/PrivateBin/issues/454 okay. We maybe just need a clever fallback there, so v1.3 can work without _requiring_ WebAssembly.
