### ISSUE TITLE
The clone button is displayed if the created paste is of the burn-after-reading type

### ISSUE THREAD

**Issue by Haocen** [PrivateBin/PrivateBin#494]
## Steps to reproduce

1.create a burn after read paste
2.visit the paste

### What happens
The clone button should be hidden

### What should happen
The clone button is visible

## Basic information

**Server address**:

**Server OS:**

**Webserver:**

**Browser:**

**PrivateBin version:**

I can reproduce this issue on <https://privatebin.net>: Yes / No

**Comment by Haocen** [comment]
This bug is introduced by wrong order of execution, the TopNav is still showing `Decrypting Paste` when we try to hide clone button.

**Comment by Haocen** [comment]
Fixed in 1.2.1, will port the fix onto 1.3

**Comment by Haocen** [comment]
Also, hide the raw text button.

**Comment by firecat53** [comment]
Hmmm, are you sure about hiding the raw text button? That can be useful for viewing/copying the paste. It could be one way though...hit the raw text button and then if you go back the paste will be gone. Just a thought!

**Comment by Haocen** [comment]
That could be me going too far, pull request fixing this issue will strictly limited to hiding the clone button, rest assured.
