### ISSUE TITLE
Automatically switch layout to use fluid container if window is wider than certain value

### ISSUE THREAD

**Issue by Haocen** [PrivateBin/PrivateBin#495]
## Steps to reproduce

1.resize the window max width supported by bootstrap 3 ordinary container
2.keep making the window wider

### What happens
Textarea remain same width

### What should happen
Textarea should still fill width

## Basic information

**Server address**:

**Server OS:**

**Webserver:**

**Browser:**

**PrivateBin version:**

I can reproduce this issue on <https://privatebin.net>: Yes / No

**Comment by Haocen** [comment]
Related to https://github.com/PrivateBin/PrivateBin/issues/492

**Comment by Haocen** [comment]
Fixed on 1.2.1 and will be port onto 1.3 along with fix for https://github.com/PrivateBin/PrivateBin/issues/492

**Comment by Haocen** [comment]
Before fix:
![before fluid](https://user-images.githubusercontent.com/10842569/63361890-f823df80-c33e-11e9-97b9-a0889a2f104e.png)

After fix:
![after fluid](https://user-images.githubusercontent.com/10842569/63361909-ff4aed80-c33e-11e9-8b32-00b9954425ce.png)

@elrido Please kindly advise and I'm sorry for the confusion I've caused.

**Comment by elrido** [comment]
This I find very helpful. Thank you!
