### ISSUE TITLE
TopNav bar should automatically expand in loading status and collapse after loading finished

### ISSUE THREAD

**Issue by Haocen** [PrivateBin/PrivateBin#496]
## Steps to reproduce

1.Send a large paste/Load a large paste on mobile device

### What happens
User cannot see visual indicator or message while sending/loading a paste

### What should happen
User should see visual indicator or message while sending/loading a paste

## Basic information

**Server address**:

**Server OS:**

**Webserver:**

**Browser:**

**PrivateBin version:**

I can reproduce this issue on <https://privatebin.net>: Yes

**Comment by Haocen** [comment]
Fixed on 1.2.1, will port onto 1.3

**Comment by Haocen** [comment]
Didn't expect this to be so hard.
Had to do debounce and mobile detection.

**Comment by Haocen** [comment]
Demo site:
privatebin.cf
Now exhibit this new behavior, shrink your browser window to see it in action.

**Comment by Haocen** [comment]
@elrido mind to take a look at this? This is probably a feature not a bug, it would be very kind of you  if you can provide some insight.

There are one more bugfix to do before I make a feature bash, let's decide whether this issue should be included.

**Comment by elrido** [comment]
I think this is definitely more a feature for a custom template. I would love to add your template and make it the new default one. The bootstrap and its flavours one can be kept, of course, to offer some variety.

**Comment by Haocen** [comment]
Merge issue into #502 .
