### ISSUE TITLE
Enhance copy/cut/save/clone protect in burn after read mode

### ISSUE THREAD

**Issue by Haocen** [PrivateBin/PrivateBin#498]
## Steps to reproduce

1.create a paste with burn after reading enabled
2.view the paste and try to select/copy/save text or attachment

### What happens
attachment is saved/copied and text can be selected and copied

### What should happen
attachment should not be saved/copied and text cannot be selected and copied

## Basic information

**Server address**:

**Server OS:**

**Webserver:**

**Browser:**

**PrivateBin version:**

I can reproduce this issue on <https://privatebin.net>: Yes

**Comment by Haocen** [comment]
Very simple enhancement by following changes:
1. add `user-select: none;` in css to disable highlighting/selecting of text/element
2. add event handler that will return false, prevent default and stop propagation to `contextmenu` `copy` `cut` events.

**Comment by Haocen** [comment]
Not completely bullet proof 🔐, anyone know how to open developer console will be able to get around, need to emphasize in Wiki once code is merged.

**Comment by elrido** [comment]
I would not bother to implement this. This is the web and content always can be copied in some way - via developer tools if necessary.

Not offering the clone button for burn after reading is one thing, but it should be obvious that once you can read a paste, you can always make a copy of it. Not offering the clone was intended to avoid accidental persisting of the content - the recipient has to do a deliberate decision and act to save the paste and the UI doesn't encourage him/her to do so.

**Comment by Haocen** [comment]
Keeping it in backlog for now.
