### ISSUE TITLE
VisHash - Get rid of MD5 and SHA-1 usage

### ISSUE THREAD

**Issue by rugk** [PrivateBin/PrivateBin#50]
There are still some parts where [SHA-1 is used](https://github.com/PrivateBin/PrivateBin/search?utf8=%E2%9C%93&q=sha1). Especially somewhere in visual hash? (I though a slightly better hash algorithm could be used here)

So we should investigate how we can replace SHA-1 here.

**Comment by rugk** [comment]
Maybe the `zerobincompatibility` should be expanded to some more parts if necessary...

**Comment by elrido** [comment]
I only see the one usage left in Vizhash. Just replace it with SHA256 with the same mechanism that checks for `zerobincompatibility`.

**Comment by rugk** [comment]
There is also [this](https://github.com/PrivateBin/PrivateBin/blob/79509ad48a2e0e3dd0040f93340dd4ad02f96bfb/tst/configGenerator.php#L558), but this two things should be all.

**Comment by rugk** [comment]
As for VizHash I overlooked one fact of the "strrev". It is not only reversed, but it works like this (I ignore the salt here to simplify the explanation):

0. Long hash, e.g.: `474bfe428885057c38088d585c5b019c74cfce74bbacd94a7b4ffbd96ace0675`
1. It uses the long hash to create one SHA-1 and one MD5 hash and combines them.
    E.g.: `c49e2143913627ea178e66571189628a41526bf3` + `6bb225025371aaa811748da8e011773d`
2. It now appends the whole string revered (to make it longer): `c49e2143913627ea178e66571189628a41526bf36bb225025371aaa811748da8e011773d` + `d377110e8ad847118aaa173520522bb63fb62514a82698117566e871ae7263193412e94c`

Final result: 
`c49e2143913627ea178e66571189628a41526bf36bb225025371aaa811748da8e011773dd377110e8ad847118aaa173520522bb63fb62514a82698117566e871ae7263193412e94c` (strlen: 144)

So what it does is converted a 64-character (256bit) string into a 40 char (160bit) SHA-1 string and 32 char (128bit) string. This means basically you keep the same string length (72chars - 288bit).
And this conversion seems silly to me, because you first reduce the length of a long string (and therefore reduce the entropy)

And now the length is just increased by reversing the string again and appending the same.
All in all this algorithm is silly, because at first we make something long shorter to make it longer again later and the long string also has been some kind of "mirrored".
So in any case you should be aware that this algorithm does not increase entropy (AFAIK), which would be the only reason for doing this.

All in all: This algorithm is silly.
And I know this is the original algorithm, but this input stretching makes only sense when the input is significant *smaller* than the resulting stretched output. In our case it is not as we **know** that the input is a SHA-256 hash.

We could change it to:
```php
$hash=$text . hash('sha1', $text . $this->salt);
```

This would be 64+40=104 characters (or 416bit) long, which would larger than the previous version and does not use strange reversing of the string just to make it larger.

~~So now practically. I created a small test:~~
~~https://jsfiddle.net/2nYsg/18/~~

However this uses VizHash.js which already does this streching, so I just noticed my test is senseless, but one has to modify the VizHash.js...

Of course this issue could also just be solved by switching to another lib: #52

**Comment by elrido** [comment]
Correct, it was originally designed for a very short input.

Maybe use sha512 (should work as of PHP 5.3) in your replacement? Then the resulting string would be 64+128=192 characters long, even longer as the original string!

Regarding the switch: Lets do this small patch now. The switch probably will take significantly more efforts.

**Comment by rugk** [comment]
So we already have  a large 256bit input, I don't know why you want to hash it again through sha512?

If you want to have a string longer than the current one we can use this as I already said:
```php
$hash=$text . hash('sha1', $text . $this->salt);
```

Oh... just noticed the title of this issue... :grin: 

Difficult to stick to your own principles. :wink: 

So maybe really choose SHA-512. So you mean this:
```php
$hash=$text . hash('sha512', $text . $this->salt);
```

This would be okay and it is really a long string...

As for "hard switch" I think you mean https://github.com/PrivateBin/PrivateBin/issues/52. So you see it is already a separate issue. :smiley:
