### ISSUE TITLE
PrivateBin Version 1.3 Does Not Load Properly In ToR Browser Bundle

### ISSUE THREAD

**Issue by OnaELOC** [PrivateBin/PrivateBin#500]
## Steps to reproduce

1. Download Latest ToR Browser bundle and install/setup.
2. Open ToR Browser and navigate to the demo site https://privatebin.net/ (Does not have to be the demo site, any version 1.3 PrivateBin will not load properly).
3. If NoScript is enabled in the ToR Browser either temporarily disable and reload the page or add https://privatebin.net/ to the exclusions and reload page (should happen automatically).

### What happens
PrivateBin landing page only partially loads, no box for paste text and no options.

### What should happen
PrivateBin should load normally, version 1.2.1 works fine.

## Additional information

<img width="1000" alt="PrivateBin 1 3 in ToR Browser" src="https://user-images.githubusercontent.com/54368420/63448134-df91f300-c42c-11e9-8fa5-8381093fb2a7.png">
## Basic information

**Server address**:

**Server OS:**

**Webserver:**

**Browser: ToR Browser Bundle 8.5.4**

**PrivateBin version: 1.3**

I can reproduce this issue on <https://privatebin.net>: Yes

**Comment by Haocen** [comment]
Hi,

Is this related to: https://github.com/PrivateBin/PrivateBin/issues/454 ?

**Comment by elrido** [comment]
Since this occurs on a HTTPS site, it's probably not the lack of secure context that prevents the use of webcrypto api in Chrome over ToR. When I can finally work on #454 we should get a more clear error message in this browser.

**Comment by OnaELOC** [comment]
Hi @Haocen ,

Damn, thinks for pointing that out! It appears to be the same issue. 

I am new here and probably should have done a more thorough check to see if someone had already reported the issue, my bad.

Also, thanks for the input @elrido .

Should I just close this issue I opened? Not sure how to handle it since it is a duplicate.

**Comment by elrido** [comment]
No worries, lets mark it as such and we can reopen it if it turns out to something else after all.
