### ISSUE TITLE
Create a new template to improve overall UX

### ISSUE THREAD

**Issue by Haocen** [PrivateBin/PrivateBin#502]
## Steps to reproduce

1. visit privatebin.net

### What happens
The default layout can use improvements

### What should happen
The default layout should be shiny

## Basic information

**Server address**:

**Server OS:**

**Webserver:**

**Browser:**

**PrivateBin version:**

I can reproduce this issue on <https://privatebin.net>: Yes

DEMO site:
https://privatebin.cf/

Following aspects are improved:
1. TopNav auto shrink when label is too long to be displayed.
2. TopNav now has icons.
3. TopNav reordered to move password to bottom of list(mobile) and top right(desktop)
4. `Because ignorance is bliss` no longer warp on mobile view
5. About section now follow `minimalist` design by marquee across the screen with elegent
6. All links, inside paste content or not, open in new tab and will has `noopener noreferrer` directive
7. User can see visual indicator or message while sending/loading a paste, as topbar auto expand/collapse.

**Comment by Haocen** [comment]
Pending port onto 1.3

**Comment by elrido** [comment]
I like the addition of icons to all the buttons in the navigation bar. Very nice touch!

Should we add this as an additional template or merge this in the existing one? Other opinions?

**Comment by Haocen** [comment]
Roger, will look into creating a new template instead.

**Comment by rugk** [comment]
IMHO I would be fine to have these changes included in the default template.
Reason: This enhancements builds upon the existing one and changes/improves it in a visually nice way.
And these are not very big changes.

Or, we could put these into a new template, but then set this new template as the default one in the config.

Except of one thing: We don't really want [marquee](https://developer.mozilla.org/docs/Web/HTML/Element/marquee) text. We're not in 80s anymore... 😜

**Comment by elrido** [comment]
The marquee and some other quirks was why I suggested to make it a separate template. But I do not mind at all to make this one the new default with or without the marquee banner.

I assume the marquee was used to reduce the space that the disclaimer uses? How about we shorten the message on that theme and only display the full message on mouse over of the area, i.e. via the id attribute (like on xkcd)?

**Comment by rugk** [comment]
Via the `title` attribute you probably mean.
This idea is okay (maybe a little too hidden), but IMHO the text did not take away _taht_ much space, so it should be left there.

**Comment by elrido** [comment]
Obsoleted by the bootstrap5 template, unfortunately.
