### ISSUE TITLE
Clearing drag and drop filename can cause error if file upload is not enabled

### ISSUE THREAD

**Issue by Haocen** [PrivateBin/PrivateBin#512]
## Steps to reproduce

1. Disable file upload in configuration
2. Access privatebin

### What happens
An error will throw in console and `Preparing a new paste...` will never disappear

### What should happen
PrivateBin should operate normally

## Basic information

**Server address**:
https://pbpaste.herokuapp.com/

**Server OS:**
Ubuntu 18

**Webserver:**
nginx-php7-fpm

**Browser:**

**PrivateBin version:**
ff68043c9f3bca718c853d2a26b703f08b72aec9
I can reproduce this issue on <https://privatebin.net>: No, code is not build from master

**Comment by Haocen** [comment]
This is an annoying behavior change on jQuery side, previously when calling `$('#dragAndDropFileName').text()` if the element doesn't exist it simply fail silently, now it result in an error.

**Comment by elrido** [comment]
I think I already encountered this during my work on #508 and it should be solved in [this commit (`js/privatebin.js` line 3000 - 3007)](https://github.com/PrivateBin/PrivateBin/pull/508/commits/c56d777c11efa70c6468092b6e6193fe037db8e9#diff-cf28a0bc390eee2482509aca8212f831L2992).

**Comment by Haocen** [comment]
Looks great!
Sorry for not catching it at an early stage. I'm currently undergoing the process of reegineering the staging/testing deploy of PrivateBin and should be able to do it better next time.

**Comment by elrido** [comment]
And I could have tested during merging as well. No worries.

FYI, maybe it helps you: We are on [Janitor](https://janitor.technology/projects/), a service that allows you to spin up an environment including a web based IDE + the git project checked out (you will have to git pull it to get the latest) + test webserver + all our unit testing tools integrated. Lets you edit the source, run the phpunit that updates the SRI hashes in the templates and then switch to a second tab in your browser to see the change live. Unfortunately the waiting time for an account is a few weeks, but you can also [use the container straight on your local docker](https://github.com/PrivateBin/PrivateBin/wiki/Docker#janitor-image-with-cloud9-and-theia-webide-janitortechnologyprivatebin) installation.

**Comment by Haocen** [comment]
Fixed by https://github.com/PrivateBin/PrivateBin/pull/508/commits/c56d777c11efa70c6468092b6e6193fe037db8e9#diff-cf28a0bc390eee2482509aca8212f831L2992
