### ISSUE TITLE
Templates described on Wiki Templates page are missing

### ISSUE THREAD

**Issue by rossigee** [PrivateBin/PrivateBin#517]
My boss is keen for us to use the 'dark' theme he's seen on the wiki page:

https://github.com/PrivateBin/PrivateBin/wiki/Templates#bootstrap-dark

However, it is missing from the latest docker image, and indeed from the 'tpl' folder here in git:

https://github.com/PrivateBin/PrivateBin/tree/master/tpl

Any ideas why it's missing and where I can find it?

**Comment by rossigee** [comment]
My bad. I was getting a 500 ISE after changing the 'template' from 'bootstrap' to 'bootstrap-dark', and jumped to the conclusion that it was because there wasn't a corresponding file for it.

For some reason, the 500 ISE cleared itself within a few minutes and things then worked as expected with template set to 'bootstrap-dark', as per the wiki page.

**Comment by elrido** [comment]
Purely for future reference: At some point (87fad1fb778 & 67f6c4eb61130ca) we realized that the many flavours of the bootstrap template could be maintained in a single file as most of their HTML overlapped and only a bit of if/else logic was required to handle the differences. Hence they are currently all provided from the `tpl/bootstrap.php` file which makes it easier for us to maintain changes that affect all of these variants. Sorry for any confusion this has caused.
