### ISSUE TITLE
Changing Template in Docker Container

### ISSUE THREAD

**Issue by kcsrnd** [PrivateBin/PrivateBin#518]
What's the best way to change the template while using the docker image?

I'd like to switch it to bootstrap-dark, if possible.

**Comment by elrido** [comment]
Same as in any other installation, via the [configuration file](https://github.com/PrivateBin/docker-nginx-fpm-alpine#custom-configuration). Copy the [conf.sample.php](https://raw.githubusercontent.com/PrivateBin/PrivateBin/master/cfg/conf.sample.php), change the [template setting](https://github.com/PrivateBin/PrivateBin/wiki/Configuration#template) and attach (read-only) it into the image at `/srv/cfg/conf.php`. It needs to be readable to user ID 65534 or group ID 82.
