### ISSUE TITLE
Set lang based on url parameter

### ISSUE THREAD

**Issue by b1f17773** [PrivateBin/PrivateBin#519]
Is there any chance to set language of privatebin based on url?
For example if someone use link: domain.com/?lang=en than privatebin will open in english language?

**Comment by elrido** [comment]
Not in the current implementation, as that focuses on either browser detection or user selectable drop down. If this is your personal instance, you can choose to [configure a single language](https://github.com/PrivateBin/PrivateBin/wiki/Configuration#languageselection--languagedefault) to be used exclusively, regardless of the visitors browser language.

**Comment by b1f17773** [comment]
No, i want to prepare multilanguage version

**Comment by elrido** [comment]
And enabling the drop down so the users can choose on their own is not an option? You have to enforce the language in the link? You could do that by adding some logic to your template that detects the presence of your `$_GET['lang']` parameter and use this to overrides the cookie like so:

https://github.com/PrivateBin/PrivateBin/blob/269def83009af203b2b39c33fb5885b1137ab90c/lib/Controller.php#L172-L173

**Comment by b1f17773** [comment]
OK, i prepared something like this:
```
if(!empty($_GET['lang']))
        {
            $lang = $_GET['lang'];
            setcookie('lang', $lang);
        }  
```
but there is a problem, because i don't know where put this to use that everytime when i'll use lang parameter in url

**Comment by rugk** [comment]
Maybe you can contribute that back as a feature? (pull request) IMHO, it would be a feature that may also be useful to others.

**Comment by elrido** [comment]
Insert it after the two lines I pointed you to in the Controller.php. For a pull request, please consider using the Request objects [`getParam()`](https://privatebin.info/codedoc/classes/PrivateBin.Request.html#method_getParam) method, as the [straight use of superglobals is considered bad practice](https://www.experts-exchange.com/articles/19999/PHP-Design-Avoiding-Globals-with-Dependency-Injection.html).

So for example you use this in your Controller.php:

```php
$lang = $this->_request->getParam('lang');
if(strlen($lang) == 2) {
    setcookie('lang', $lang);
}
```

**Comment by elrido** [comment]
Please feel free to reopen, when a pull request is ready for this.
