### ISSUE TITLE
Switch to new version of visual hash

### ISSUE THREAD

**Issue by rugk** [PrivateBin/PrivateBin#52]
We might switch to [VizHash.js](https://github.com/sametmax/VizHash.js) for more up-to-date implementation of VizHash. Especially as it happens on the client side, it also reduces the things the server has to do and the clients do not need to load an image every time they'll access a bin.

**Comment by elrido** [comment]
I like the idea. Will have to look into, how this changes the storage formats, etc.

**Comment by rugk** [comment]
Especially I like that VizHash.js is compatible to the current hashes. It's just that the [current implementation](https://github.com/PrivateBin/PrivateBin/blob/38ab755733f6c5828eac8a1ecaea9708263430e3/lib/vizhash16x16.php#L92) uses a Salt (presumably the server salt, which we cannot use in the  

Additional argument: The JS version uses antialiasing, so the picture looks nicer.

Contra: It [also](https://github.com/sametmax/VizHash.js/blob/ddac80983c4cd0020a57a73b0f8ee106fa13db12/vizhash.js#L34) uses MD5 and SHA-1 (see #50).

----

**Alternative:** Switch to a complete new algorithm. Use: [Identicons](https://en.wikipedia.org/wiki/Identicon). [Identicons](http://identicon.net/) are well tested and well known for generating an easy-to-remeber icon of
However: *They are not an one-way-function!"* But

There is also a [PHP implementation](https://github.com/yzalis/Identicon) and a JS implementation as a jQuery plugin [using Canvas](https://github.com/yzalis/Identicon).

**Comment by rugk** [comment]
I also think Identicons look much nicer than the current ones.
