### ISSUE TITLE
Yourls shortener issue

### ISSUE THREAD

**Issue by hista** [PrivateBin/PrivateBin#522]
Hi,
I've installed PrivateBin v.1.3.
I've yourls installed in the same server.
I followed the configuration wiki:
"_For YOURLS, the configured value of urlshortener should be formated like following:
https://yourls.org/yourls-api.php?username=admin&password=pass&action=shorturl&format=json&url=
or
https://yourls.org/yourls-api.php?signature=1002a612b4&action=shorturl&format=json&url=_"

That's what (I think) I did.
And yet I've a strange issue: when I click on the shortener button, I get this kind of message:

`{"url":{"keyword":"7","url":"https:\/\/mywebsite.com\/zerobin\/?a85c11e9bbb6bf1a#28GARnDwDwq7Bw6cSB3qdcnPbUrN************","title":"PrivateBin","date":"2019-09-22 21:08:06","ip":"*******"},"status":"success","message":"https:\/\/mywebsite.com\/zerobin\/?a85c11e9bbb6bf1a#28GARnDw[...] added to database","title":"PrivateBin","shorturl":"http:\/\/mywebsite.com\/url\/7","statusCode":200}`

And when I open https://www.mywebsite.com/url/7, it works.
How can I fix this weird message?

Best regards!

**Comment by elrido** [comment]
Hello there,

This was indeed the expected (clunky) behaviour in the releases until and including 1.3. The recently merged PR #480 addressed this and does offer an improved integration via AJAX call to yourls and extracts the short URL from the JSON reply. This is part of the patch release 1.3.1, that we published only yesterday evening.

If you have the chance, could you try to upgrade your installation to the new release and let me know if the improved integration addresses your use case?

Best

**Comment by hista** [comment]
Hi elrido,
Thanks for your quick answer. I'm glad to tell you it works perfectly now with v.1.3.1!

**Comment by elrido** [comment]
Happy to hear and kudos @Haocen who made that improvement.
