### ISSUE TITLE
Disable warning about zlib if compression is disabled globally

### ISSUE THREAD

**Issue by t2d** [PrivateBin/PrivateBin#525]
First, thank you for making the great new release and improving compatibility with TorBrowser!

## Steps to reproduce

1. set `compression = none` in conf.php
2. Visit privatebin with TorBrowser

### What happens
It shows the warning " Your browser doesn't support WebAssembly, used for zlib compression. You can create uncompressed documents, but can't read compressed ones."

### What should happen
Since compression is disabled globally, there is no need to warn about missing zlib compatibility.

## Basic information

**Browser:** TorBrowser 8.5.5

**PrivateBin version:** 1.3.1

I can reproduce this issue on <https://privatebin.net>: Yes

**Comment by qianmengnet** [comment]
add wasm to application / javascript in mime

**Comment by elrido** [comment]
Hi and sorry for the very late reply (in another decade, nonetheless).

I tried recreating this using a Firefox with disabled wasm support and a local test instance with the `compression = "none"` setting, but failed to do so. It should be addressed with commit 5471757fa7a59e69281455cf96595938de31c8e4, which was part of the 1.3.1 release. Would you have the opportunity to retest this on an instance with compression disabled using Tor & TorBrowser?

**Comment by t2d** [comment]
Thank you for looking into this. The problem is caused by weird parsing of the config file.

```
compression = none
```
shows the warning. 

```
compression = "none"
```
disables it.

**Comment by elrido** [comment]
Argh, of course - PHP will parse none as `False` instead of a string. I'll clarify that in the conf.sample.php and the [wiki page on configuration](https://github.com/PrivateBin/PrivateBin/wiki/Configuration).

From the [PHP manual on the function parse_ini_file()](https://www.php.net/manual/en/function.parse-ini-file.php#refsect1-function.parse-ini-file-notes):
> Note: There are reserved words which must not be used as keys for ini files. These include: null, yes, no, true, false, on, off, none.
