### ISSUE TITLE
Translation of New Language problem

### ISSUE THREAD

**Issue by aljawaid** [PrivateBin/PrivateBin#530]
## Steps to reproduce
0. Template file is `pp-bootstrap` which is a duplicate of `bootstrap.php` and works after setting it in `conf.php` as per below:
```
; template to include, default is "bootstrap" (tpl/bootstrap.php)
template = "pp-bootstrap"
```
1. Followed the translation guide to create a new language called `pp.json`
2. Added `pp.json` to `i18n` directory
3. Updated `privatebin.js` as per below:
```
        const languageLoadedEvent = 'languageLoaded';

        /**
         * supported languages, minus the built in 'en'
         *
         * @name I18n.supportedLanguages
         * @private
         * @prop   {string[]}
         * @readonly
         */
        const supportedLanguages = ['bg', 'cs', 'de', 'es', 'fr', 'it', 'hu', 'no', 'nl', 'pl', 'pt', 'oc', 'ru', 'sl', 'zh', 'pp'];
```
4. Updated hash for `privatebin.js` in `pp-bootstrap.php` and in original copy of `page.php`
5. Changed `conf.php` as per below:
```
; by default PrivateBin will guess the visitors language based on the browsers
; settings. Optionally you can enable the language selection menu, which uses
; a session cookie to store the choice until the browser is closed.
languageselection = false

; set the language your installs defaults to, defaults to English
; if this is set and language selection is disabled, this will be the only language
; languagedefault = "pp"
``` 
6. New file is not displayed after clearing browser cache

### What happens
Nothing, the default english still gets displayed

### What should happen
My new language file should show be displayed

## Basic information

**CentOS 7**

**Apache**

**Firefox and Chrome**

**PrivateBin version:**
1.3.1

**Comment by elrido** [comment]
Please have a look at the [gotchas on the wiki page](https://github.com/PrivateBin/PrivateBin/wiki/Translation#gotchas) - probably it is missing in the i18n/languages.json file.

**Comment by aljawaid** [comment]
> 
> 
> Please have a look at the [gotchas on the wiki page](https://github.com/PrivateBin/PrivateBin/wiki/Translation#gotchas) - probably it is missing in the i18n/languages.json file.

Thanks for reply, I forgot to mention, I did already add it to that file too as the last entry

```
    "za": ["Saɯ cueŋƅ", "Zhuang"],
    "zu": ["isiZulu", "Zulu"],
    "pp": ["pp", "English"]
}
```

**Comment by aljawaid** [comment]
I don't know if CSP has anything to do with it, but here is that part if it helps:
```
cspheader = "default-src 'self' domain.co.uk; manifest-src 'self'; connect-src * blob:; script-src 'self' 'unsafe-eval' domain.co.uk; style-src 'self' domain.co.uk; font-src 'self'; img-src 'self' data: https:; media-src blob:; object-src blob:; sandbox allow-same-origin allow-scripts allow-forms allow-modals"
```

**Comment by elrido** [comment]
Do you see in your browser console any errors reg. CSP? Can you see if PB is even attempting to load pp.json in the network tab? Are any other translation errors shown in the the browser console? Are the server side translations, done by PHP, getting picked up at least?

**Comment by elrido** [comment]
Oh, and I assume you have removed the comment (`;`) in front of your setting, correct?

**Comment by aljawaid** [comment]
> 
> 
> Do you see in your browser console any errors reg. CSP? Can you see if PB is even attempting to load pp.json in the network tab? Are any other translation errors shown in the the browser console? Are the server side translations, done by PHP, getting picked up at least?
```
Content Security Policy: The page's settings blocked the loading of a resource at inline ("script-src"). domain:40:1
Content Security Policy: The page's settings blocked the loading of a resource at inline ("style-src").
```

> 
> 
> Oh, and I assume you have removed the comment (`;`) in front of your setting, correct?

oh yes but for some reason that partially works I think.

You can check the website by seeing the domain in the screenshot below (which also shows the Network tab from firefox):
![image](https://user-images.githubusercontent.com/10233708/66394212-6c3c4480-e9cc-11e9-9b62-3e97d890acd2.png)

-----
The csp causes two errors, one which is related to line 40:1 which is the matomo/piwik javascript being blocked - it seems my csp conf setting doesnt still accept it even after I added my domain.co.uk in the csp.  I used a work around suggested by Matomo to load the script within a file on the same domain so I added pptracking.js but that still only partially detects visits, possibly because the actual trackig file if you look in my page source code is still being pulled from domain.co.uk and my csp conf doesnt seem to be applied.

`style-src` doesnt seem to exist in my template page so I am not sure why firefox is detecting or blocking it.

Looking at the network tab, it seems **only** css files are loaded, but it confuses me as the website works fine except the language display not being correct.

**Comment by elrido** [comment]
Ok, so that rules out the CSP, at least on the translation end.

The configuration is required, though, especially since you are using a "custom" language. If you don't enforce a `languagedefault`, PB will choose the language based on your browsers settings sent via a HTTP header to the server / exposed to JS. Since `pp` isn't a language you (likely) have configured in your webbrowsers settings, it won't get picked up.

Alternatively, you could set `languageselection = true` and let users select any of the supported languages from the drop down, including the second English provided by `pp`.

**Comment by aljawaid** [comment]
> 
> 
> Ok, so that rules out the CSP, at least on the translation end.
> 
> The configuration is required, though, especially since you are using a "custom" language. If you don't enforce a `languagedefault`, PB will choose the language based on your browsers settings sent via a HTTP header to the server / exposed to JS. Since `pp` isn't a language you (likely) have configured in your webbrowsers settings, it won't get picked up.
> 
> Alternatively, you could set `languageselection = true` and let users select any of the supported languages from the drop down, including the second English provided by `pp`.

**I have just realised that my `languagedefault` is commented so maybe I need to uncomment that to make it work?**  I can't have a language selection for the purpose of my website usage and also I am only adding a language file to change some of the wording mainly calling a 'paste' a 'secret link'

**Comment by aljawaid** [comment]
> 
> 
> **I have just realised that my `languagedefault` is commented so maybe I need to uncomment that to make it work?** I can't have a language selection for the purpose of my website usage and also I am only adding a language file to change some of the wording mainly calling a 'paste' a 'secret link'

Removing the comment picked up the translated file.

**Comment by aljawaid** [comment]
@elrido Just want to say thank you for the extra help and the pointers on where and what I should be looking for.

Managed to get the CSP issue sorted too
