### ISSUE TITLE
How to add a message only on edit page?

### ISSUE THREAD

**Issue by aljawaid** [PrivateBin/PrivateBin#531]
How can we add a message if it is only for the landing page, not for the paste page?

If I use the `notice` in `conf.php` it appears in both, before and after paste.

I am trying to add some text (instructions) which only shows on the first edit page.

My template is a duplicate of `bootstrap.php`

**Comment by r4sas** [comment]
Modify privatebin.js to hide your block after sending paste.

**Comment by rugk** [comment]
Also note if you do so, you need to change the PHP files as well, in order to regenerate the SRI hashes: https://github.com/PrivateBin/PrivateBin/wiki/Development#subresource-integrity-for-javascript-resources

**Comment by aljawaid** [comment]
Thanks but the privatebin.js is too complicated for my knowledge... I'm basic html/css type of person

I've just added a basic list of instructions in the template
