### ISSUE TITLE
Trying to Add Button for WhatsApp

### ISSUE THREAD

**Issue by aljawaid** [PrivateBin/PrivateBin#532]
Hoping somebody can help.  I'm trying to add a 'share to WhatsApp' button to make it easier for myself when sharing pastes.

I got it to work except the **full secret paste url** is not shown, **just the domain**.  I used `window.location.href` and I even tried `window.location` and another option (commented in the code below)

Anyone know how to show the current secret paste url on the page?

Here is my code:
```html
<div>
<a id="whatsapp-share-secret">WhatsApp Test - DO NOT USE YET</a>
</div>
```
and here...
```javascript
<script type="text/javascript">
// Get the element
$link = document.querySelector("#whatsapp-share-secret");

// Generate url
$url = "whatsapp://send?text=%20%2AWhatsApp%20TEST%2A%20-%20" + window.location.href; //encodeURIComponent(document.URL);

// Set url attribute of the link
$link.setAttribute('href', $url);
</script>
```
The jscode is just before the closing `body` tag

**Comment by rugk** [comment]
The URL should work:
![grafik](https://user-images.githubusercontent.com/11966684/66698507-f0e5d600-ecde-11e9-92f6-3b1f8ef5d123.png)

One problem I see could be the the used CSP, please see the config. It does now allow inline JS, so please put your JS into an extra file.

**Comment by aljawaid** [comment]
> 
> The URL should work:
> 
> One problem I see could be the the used CSP, please see the config. It does now allow inline JS, so please put your JS into an extra file.

Thanks for your suggestion, it never worked.

I have tried putting it into a separate `.js` file with the same end result.

I even tried adding the hash for the `js` file but ith the same result.

I even tried adding the hash to CSP but it never worked also.

For some reason, the end result is always just showing  `*WhatsApp TEST* - https://domain.com/` when it should be ` *WhatsApp TEST* - https://domain.com/?nkjnaknkjnknabakd#kdjnkjankank etc etc`

It seems the string after the trailing slash seems missing

**Comment by aljawaid** [comment]
Here is the contents of my 'separate' `.js` file which loads fine and works fine, except I just can't seem to show the full URL of the secret, just the domain.
```javascript
	// Get the element
$link = document.querySelector("#whatsapp-share-secret");

// Generate url
// $url = "whatsapp://send?text=%20%2AWhatsApp%20TEST%2A%20-%20" + window.location.href; //encodeURIComponent(document.URL);
var $url = "whatsapp://send?text=%20%2AWhatsApp%20TEST%2A%20-%20" + window.location.href + window.location.search + window.location.hash;
// Set url attribute of the link
$link.setAttribute('href', $url);
```

Am I correct in placing the below html just before the `</body>` closing tag?
```html
<script type="text/javascript" src="whatsapp-share.js" integrity="" crossorigin="anonymous"></script>
```

**Comment by rugk** [comment]
Likely yes, maybe you just need to change the target of the `a` link to open in a new tab? Or so?

**Comment by rugk** [comment]
Closing due to lack of response in support case.
