### ISSUE TITLE
Add aria-selected attribute to Editor and Preview buttons

### ISSUE THREAD

**Issue by Flameborn** [PrivateBin/PrivateBin#534]
Currently, a screen reader sees the **Editor** and **Preview** buttons as two links, however, there is no indication of the currently active one.

Adding an **aria-selected** attribute to the buttons when active should fix this.

**Comment by rugk** [comment]
Good idea, maybe we can use https://ffoodd.github.io/a11y.css/errors.html or so to check it.

**Comment by Flameborn** [comment]
I am currently running the master branch as a semi-public instance (which is probably not a good idea). I'm using a screen reader, so I can test changes if needed.
