### ISSUE TITLE
Infinite loading

### ISSUE THREAD

**Issue by lukeeexd** [PrivateBin/PrivateBin#535]
## Steps to reproduce

1. https://paste.tws-mc.com/
2. Loads infinitly 

### What happens
Page loads forever

### What should happen
Should not load forever

## Basic information
I added a page rule in CloudFlare to disable performance. It was working before I did any of that, tried to change the theme and then it just loads forever now

**Server address**:
https://paste.tws-mc.com

**Server OS:**
Ubuntu 18.04.3 LTS

**Webserver:**
nginx

**Browser:**
Chrome

**PrivateBin version:**
1.3.1
I can reproduce this issue on <https://privatebin.net>: Yes / No
No

**Comment by elrido** [comment]
As you can see in your browsers console, none of the SRI hashes are correct. Or the theme that you changed to doesn't match the JS files used. Compare the new themes SRI hashes with those of the working one and correct them if necessary.

I assume you already checked this [FAQ entry reg. SRI hashes](https://github.com/PrivateBin/PrivateBin/wiki/FAQ#how-to-make-privatebin-work-when-i-have-changed-some-javascript-files).

**Comment by lukeeexd** [comment]
> As you can see in your browsers console, none of the SRI hashes are correct. Or the theme that you changed to doesn't match the JS files used. Compare the new themes SRI hashes with those of the working one and correct them if necessary.
> 
> I assume you already checked this [FAQ entry reg. SRI hashes](https://github.com/PrivateBin/PrivateBin/wiki/FAQ#how-to-make-privatebin-work-when-i-have-changed-some-javascript-files).

The thing is, I didnt change any JS files

**Comment by elrido** [comment]
Normally the SRI hashes of all provided themes should match each other and the JS files. If you are changing from one theme to another one from another release or have a custom theme, then you may have to update them yourself, yes.

**Comment by lukeeexd** [comment]
> Normally the SRI hashes of all provided themes should match each other and the JS files. If you are changing from one theme to another one from another release or have a custom theme, then you may have to update them yourself, yes.

Havent done any of that. Just changed theme to bootstrap-dark in conf.php

**Comment by lukeeexd** [comment]
Works now, didn’t do anything lol

**Comment by elrido** [comment]
>  Works now, didn’t do anything lol

Does it work or not?

**Comment by lukeeexd** [comment]
Nope. If you open the link through discord it shows the correct page but if you try enter text and send it won’t work. And still infinite loading otherwise. I thought nuking the directory and downloading again would work but guess not?

**Comment by elrido** [comment]
Ok, this really starts to sound like a caching issue. Do you have any way of circumventing or resetting that cloudflare stuff? Can you i.e. set up an ssh port forwarding from that system to your local machine so that you can verify it's not the cache in browser or the one of CF thats causing the issue?

**Comment by lukeeexd** [comment]
I purged the cache in CF already a few times that should have done it?

**Comment by lukeeexd** [comment]
Tried a brand new install. Removed the directory, removed the section from nginx, made a new cert then added the files back and still having same issue

**Comment by r4sas** [comment]
Re-check CF settings. Here already was few issues same as yours. Please find them in issue tracker.

**Comment by lukeeexd** [comment]
> Re-check CF settings. Here already was few issues same as yours. Please find them in issue tracker.

https://i.imgur.com/bNuGUCl.png

**Comment by r4sas** [comment]
Now I get this:
```Refused to load the script '....js' because it violates the following Content Security Policy directive: "script-src 'none'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.```

**Comment by lukeeexd** [comment]
> I got this in devtools:
> `Refused to load the script '....js' because it violates the following Content Security Policy directive: "script-src 'none'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.`
> 
> But here no `script-src 'none'` rule:
> `content-security-policy: default-src 'none'; manifest-src 'self'; connect-src * blob:; script-src 'self' 'unsafe-eval'; style-src 'self'; font-src 'self'; img-src 'self' data: blob:; media-src blob:; object-src blob:; sandbox allow-same-origin allow-scripts allow-forms allow-popups allow-modals`

What file are they in?

**Comment by r4sas** [comment]
That was because I forgot enable JS for site (NoScript extension in chrome) :D

Enabled JS and all works.

**Comment by lukeeexd** [comment]
> That was because I forgot enable JS for site (NoScript extension in chrome) :D
> 
> Enabled JS and all works.

I still have the loading on my end, JS is enabled in chrome

**Comment by r4sas** [comment]
>So, have you tried drop cache in your browser? Hit CTRL+F5.

And please give screenshot from DevTools Network tab.

**Comment by lukeeexd** [comment]
> > So, have you tried drop cache in your browser? Hit CTRL+F5.
> 
> And please give screenshot from DevTools Network tab.

https://i.imgur.com/3kO2UDj.png
https://i.imgur.com/O7ysmvT.png

I tried ctrl+f5 many times

**Comment by r4sas** [comment]
> https://i.imgur.com/3kO2UDj.png
Can you check Console tab?

**Comment by lukeeexd** [comment]
> > https://i.imgur.com/3kO2UDj.png
> 
> Can you check Console tab?

https://i.imgur.com/O7ysmvT.png

**Comment by r4sas** [comment]
Hmm... thats strange...

**Comment by lukeeexd** [comment]
> Hmm... thats strange...
> Now after reloading page I got same integrity issue...

I made www-data owner of folders, now I can create pastes in firefox but not chrome. Loading in chrome, works in firefox

**Comment by lukeeexd** [comment]
> Hmm... thats strange...
> Now after reloading page I got same integrity issue...
> 
> Again, recheck CF settings.
> 
> ```
> age: 422
> cache-control: public, max-age=14400
> cf-bgj: minify
> cf-cache-status: HIT
> cf-polished: origSize=5194
> ```
> 
> I never used CF, so idk why it turned on `minify` again.

https://streamable.com/4p5zs

**Comment by r4sas** [comment]
Maybe asterisk (*) needed in end of URL?

**Comment by lukeeexd** [comment]
> Maybe asterisk (*) needed in end of URL?

https://i.imgur.com/Eovkwnb.png

**Comment by r4sas** [comment]
Any ways forcebly drop CF cache?

**Comment by lukeeexd** [comment]
> Any ways forcebly drop CF cache?

I just cleared it for paste.tws-mc.com and paste.tws-mc.com/*

**Comment by lukeeexd** [comment]
But why would it work on firefox but not chrome?

**Comment by r4sas** [comment]
![image](https://user-images.githubusercontent.com/7023612/67230022-29a34f00-f445-11e9-859b-a8c0031b127d.png)

As I see, now we fetch JS from cache. See `age` header.

**Comment by r4sas** [comment]
> But why would it work on firefox but not chrome?

No ideas.

**Comment by lukeeexd** [comment]
> > But why would it work on firefox but not chrome?
> 
> No ideas.
> 
> Please check this:
> https://support.cloudflare.com/hc/en-us/articles/200169246-Purging-cached-resources-from-Cloudflare

Thats what I've been doing https://streamable.com/c4db1

**Comment by r4sas** [comment]
I think you must enter URLs ony by one.

**Comment by lukeeexd** [comment]
> I think you must enter URLs ony by one.
> 
> Or use `Purge Everything` button.

Ive entered URL one by one before. I'd rather not purge everything but i'll try it

**Comment by lukeeexd** [comment]
Yeah its working now after purge everything

**Comment by lukeeexd** [comment]
Now should I be able to change theme without it fucking up again lol?

**Comment by r4sas** [comment]
Who knows? :D

**Comment by lukeeexd** [comment]
Lets give it a try lol. thanks for the help

**Comment by r4sas** [comment]
Seems like changed without any issues.

**Comment by rugk** [comment]
Note [that we generally do not recommend Cloudflare](https://github.com/PrivateBin/PrivateBin/wiki/FAQ#user-content-how-to-make-privatebin-work-when-using-cloudflare-for-ddos-protection), but your question/problem seems to be solved, so I am closing this issue.
