### ISSUE TITLE
Error when using FileUpload

### ISSUE THREAD

**Issue by gvirtuoso** [PrivateBin/PrivateBin#542]
I'm getting an error when using Private-bin to share files.

The interesting part is that everything works fine for small files (pictures, text or compressed files).

## Pre-requisites
1. FileUpload enabled

## Steps to reproduce

1. Create a new paste
2. Choose a file with a considerable size (6.5MB in my case, I got the file from here: https://norvig.com/big.txt)
3. You can try to upload the file as a (TXT - 6.5MB) file or as a compressed file (ZIP - 2.4MB)

### What happens
After some time I got the message:
`Could not create paste: server error or not responding`

### What should happen
After choose the file and click on the "Send" button, the app should create a link to share the message.

## Additional information

* On the browser inspect tab, its telling about the 413 http status (Payload too large)

* Checking the php_info() for this instance, I got this info related to file upload: post_max_size=15M and upload_max_filesize=15M (the default values)

## Basic information

**Server OS:** Containered version

**Browser:** Chrome (Version 78.0.3904.70 (Official Build) (64-bit))

**PrivateBin version:** 1.3.1 (privatebin/nginx-fpm-alpine:1.3.1)

I can reproduce this issue on <https://privatebin.net>: Yes / No
NO, on the URL above, the option for attach file is disabled.

**Comment by elrido** [comment]
And what do you see in the docker logs as the error on the server side? Is there maybe another reverse proxy, i.e. for TLS termination, running in front of it that has a lower POST size configured?

**Comment by gvirtuoso** [comment]
@elrido You were right!
The problem was my Ingress. Once I increase the page_body_size, everything works properly.
Thanks for the clue.
