### ISSUE TITLE
Decrypt error in MS Browsers !?!

### ISSUE THREAD

**Issue by rancid91** [PrivateBin/PrivateBin#546]
Hi,
I created a new privatebin in Firefox with password. 
The problem now is that it couldn't be decrypted with other browsers.
I can't open it with Edge for example. The error message shows:
"Could not decrypt data. Did you enter a wrong password? Retry with the button at the top."

The password I choose is correct 'cause I retested it again in Firefox and in another browser on android. Seems like it doesn't work with MS Browsers...

Maybe someone has an idea and can help out here.

cheers!

**Comment by r4sas** [comment]
https://github.com/PrivateBin/PrivateBin/issues/468
