### ISSUE TITLE
Is there any Captcha or Spam protection?

### ISSUE THREAD

**Issue by asterismo** [PrivateBin/PrivateBin#547]
Is just a question

**Comment by rugk** [comment]
There is a trffic limiter https://github.com/PrivateBin/PrivateBin/blob/476b9c90e2c045e41eb40e4222427da1a619d51b/lib/Persistence/TrafficLimiter.php.
Also bots are tried to be prevented from destroying/reading a paste: https://github.com/PrivateBin/PrivateBin/blob/71797d1dd4af644d594110086ff1c02750aa0172/js/legacy.js#L146

**Comment by elrido** [comment]
I think this has been answered.
