### ISSUE TITLE
Burn after reading alert message apostrophes are escaped

### ISSUE THREAD

**Issue by calvinbui** [PrivateBin/PrivateBin#558]
## Steps to reproduce

1. Create a new Burn After Reading paste
2. Read the alert

### What happens

The apostrophes in `Don't` and `can't` appear as `&#x27;`

![image](https://user-images.githubusercontent.com/3604363/72208467-fc6fb580-34f6-11ea-98f8-ada327e72315.png)

### What should happen

The words `Don't` and `can't`

![image](https://user-images.githubusercontent.com/3604363/72208478-17dac080-34f7-11ea-8750-10ecf30a2bd5.png)

## Basic information

**Server address**:

**Server OS:**

**Webserver:**

**Browser:**
- Chromium 79
- Firefox 72

**PrivateBin version:** 1.3.2

I can reproduce this issue on <https://privatebin.net>: Yes

**Comment by elrido** [comment]
same issue as #557
