### ISSUE TITLE
Wrong encoding on "FOR YOUR EYES ONLY" message.

### ISSUE THREAD

**Issue by c0ncord2** [PrivateBin/PrivateBin#559]
## Steps to reproduce
1. Create a message with "Burn after reading" enabled.
2. Open the generated url on another tab.

### What happens
Text with wrong encoding is returned:
```
FOR YOUR EYES ONLY. Don&#x27;t close this window, this message can&#x27;t be displayed again.
```

### What should happen
Correct encoding, example:
```
FOR YOUR EYES ONLY. Don't close this window, this message can't be displayed again.
```

## Additional information

![image](https://user-images.githubusercontent.com/59669788/72278342-ba945b80-362b-11ea-9148-082f6631fcdb.png)

## Basic information

**Server address**: https://paste.fizi.ca/

**Browser:** firefox

**PrivateBin version:** 1.3.2

I can reproduce this issue on <https://privatebin.net>: Yes

**Comment by rugk** [comment]
Indeed likely a bug introduced by [the XSS fix](https://github.com/PrivateBin/PrivateBin/security/advisories/GHSA-8j72-p2wm-6738) in v1.3.2.

Technically internally thus a duplicate of https://github.com/PrivateBin/PrivateBin/issues/557?

**Comment by rugk** [comment]
Duplicate of https://github.com/PrivateBin/PrivateBin/issues/558 actually
