### ISSUE TITLE
GET Method Responce

### ISSUE THREAD

**Issue by danial1412** [PrivateBin/PrivateBin#561]
Hi, I'm trying to read an existing paste though a simple GET Method in Python. 

import requests

if __name__ == "__main__":
    url = "https://privatebin.net/?92c1e075b372eb42#BCJyXH74em4SWPHp5q9heNjWhiQgiXUAhRRGufS68SiH"
    headers = {'X-Requested-With': 'JSONHttpRequest'}
    r = requests.get(url, headers=headers)
    print(r.status_code)
    result = r.json()
    print(result)

What i get is:

{'status': 0, 'id': '92c1e075b372eb42', 'url': '/?92c1e075b372eb42', 'adata': [['Uv7QSzm03rnMISI6yFyZGg==', 'v33t4jVMsCw=', 100000, 256, 128, 'aes', 'gcm', 'zlib'], 'plaintext', 0, 0], 'meta': {'created': 1578999574, 'time_to_live': 604759}, 'v': 2, 'ct': 'l/Xnbiq7rKeg8VmmD4BC2009mja3/yh9GI50hiUPirdh9kuXMjE=', 'comments': [], 'comment_count': 0, 'comment_offset': 0, '@context': '?jsonld=paste'}

Am I able to decode the cyphertext without kdf key (since it is not passed as a json)? The replication of the kdf key is also not possible, since we don't have access to the kdf_key generation passphrase. 

Looking forward to any suggestions on how to retrieve the paste!

**Comment by r4sas** [comment]
See PBinCLI: https://github.com/r4sas/PBinCLI

**Comment by danial1412** [comment]
Thank you, PBinCLI implementation helped me a lot. Made the get method in the cpaste style

**Comment by r4sas** [comment]
Here cpaste project: https://git.cryptomilk.org/projects/cpaste.git/tree/cpaste
