### ISSUE TITLE
PrivateBin crashes when big files are decrypted

### ISSUE THREAD

**Issue by LizaChernysh** [PrivateBin/PrivateBin#562]
PrivatBin has problems with big files uploading. If file more than 20MB paste creating takes a long time and after ~5 min the app is crashed. 

## Steps to reproduce

1. Use the function "Attach file" and upload the file larger than 15 mb
2. create the paste 
3. try to decrypt the paste
### What happens
past decrypting takes a lot of time. after some minutes app crashes with error "AW! Snap. something went wrong when displaying this page"

### What should happen
past should be decrypted 

## Basic information

**Server address**:

**Server OS:**
Ubuntu 18

**Webserver:**
Apache 

**Browser:**
Chrome (latest version) 

**PrivateBin version:**
the latest 
I can reproduce this issue on <https://privatebin.net>: Yes / No
No, because for reproducing need function "Attach file" be enabled

**Comment by r4sas** [comment]
Telepaths on vacation. Please fill default issue report form.

**Comment by r4sas** [comment]
Ok, that's better. Can you find which version of PrivateBin your instance is using?

**Comment by LizaChernysh** [comment]
We use PrivatBin version 1.3.1 

Yes, it depends on computer.  But we tested large file downloading on different machines and in all cases decrypting of big files took a lot of time and in 90% returned an error message.

**Comment by elrido** [comment]
For these two processes, encryption and compression, we are relying on external libraries. It is faster now that we switched to the browser based webcrypto API and the WASM based zlib library then before with SJCL and the rawdeflate ones, but yes, on large files it's likely to slow to be useful. I newer experienced it crash as you describe, unfortunately. I, too, primarily use it on Ubuntu 18.04, but with Firefox, not Chrome.

On a constructive note: How about you try disabling the compression on your instance? That should reduce the amount of work your CPU has to do, both when creating and viewing the pastes. Maybe this would speed it up sufficiently to make it usable for your use case?

**Comment by silentshotghost** [comment]
crashes when you import large amount of text

**Comment by rugk** [comment]
We definitively need more details here:
* What is "large"? How many MB?
* At which step does it crash? Decrypting?
* Can you provide an example link to a paste?
* Which browser does it crash? + version number?
* Which OS does that browser run on? (on the client)
* Did you try it with another browser? Did it crash, too?
* Please check `about:performance` in Firefox or [Chrome/iums task manager](https://www.cnet.com/how-to/how-to-check-memory-usage-of-chrome-extensions/) if that happens and report what is shown for the tab there.
* …

**Comment by qol3m** [comment]
I have no issue even with 200MB files, which of course take a while to encrypt/decrypt (and a lot of server RAM), but in Firefox I can still use the other browser tabs while it is doing its work and close the tab if I need the process to stop.

Perhaps you have a very weak CPU?
