### ISSUE TITLE
PrivateBin doesn't support  Edge browser

### ISSUE THREAD

**Issue by LizaChernysh** [PrivateBin/PrivateBin#563]
an attempt to create a paste in Edge browser causes the error message. 

![image](https://user-images.githubusercontent.com/19654867/72348874-04407d00-36e4-11ea-83b6-a001746b7ba0.png)

**Comment by r4sas** [comment]
Is that issue related to #562 ?
About Edge, please read https://github.com/PrivateBin/PrivateBin/issues/468
