### ISSUE TITLE
No "burnafterreading" in the API v1.3

### ISSUE THREAD

**Issue by rylebrun** [PrivateBin/PrivateBin#566]
Hi,
I don't see the `burnafterreading` option in the[ v1.3 API documentation.](https://github.com/PrivateBin/PrivateBin/wiki/API)
Is it possible to use the *burn after reading* option when I create a paste through the API ? And how ?
Thanks,

**Comment by elrido** [comment]
Hi and thanks for checking the docs. The API is used by the webinterface itself, so it is definitely possible. The API document, that you link to, focuses on the API protocol, the exact properties and the format of the JSON transmitted over the API can be found in the JSON-LD files provided with each installation, which are also linked in the [encryption format documentation](https://github.com/PrivateBin/PrivateBin/wiki/Encryption-format#data-types).

Drilling down from paste, to paste meta properties to general types:
https://github.com/PrivateBin/PrivateBin/blob/5daba16333badd63ec44e68099865abff3ac285e/js/paste.jsonld#L25-L27
https://github.com/PrivateBin/PrivateBin/blob/5daba16333badd63ec44e68099865abff3ac285e/js/pastemeta.jsonld#L6-L22
https://github.com/PrivateBin/PrivateBin/blob/5daba16333badd63ec44e68099865abff3ac285e/js/types.jsonld#L84-L87

So its in the "adata" property of the paste and is enabled if the forth element of that list is set to 1.

Here some examples of the structure of the paste from our unit tests for php:
https://github.com/PrivateBin/PrivateBin/blob/5daba16333badd63ec44e68099865abff3ac285e/tst/Bootstrap.php#L54-L76
From one of the python clients:
https://github.com/r4sas/PBinCLI/blob/master/pbincli/format.py#L260-L275
And Groovy:
https://github.com/kkingsley-BF/PrivateBin-Groovy/blob/491a668665a51370b6767d2c14f8ee85e4a15c8b/Paste.groovy#L120

**Comment by rylebrun** [comment]
Thanks @elrido, I'm using this client : [amine7536/privatebin-cli](https://github.com/amine7536/privatebin-cli) and the build-in option seems broken.

So, I just need to change the 0 value to 1 in this line https://github.com/amine7536/privatebin-cli/blob/12871458cfacf2aef8c7f236856082168b0226f3/lib/crypto.js#L13
And all is fine now !

Thanks for your help, and good job!
