### ISSUE TITLE
Can't access PrivateBin 1.3.2 on FreeBSD via Chrome 

### ISSUE THREAD

**Issue by RogerAirgood** [PrivateBin/PrivateBin#567]
## Steps to reproduce

1. Install PrivateBin 1.3.2 with default config on FreeBSD 
2. Access PrivateBin via Chrome

### What happens
When accessing the site via Google Chrome (tested Windows 10 and Android) it fails to load and says "PrivateBin requires a modern browser to work.". It works fine with Firefox. 

### What should happen
Proper access

## Additional information
I've tried both nginx and lighttpd, same result

## Basic information

**Server address**: http://conorbeh.com:8991/

**Operating System**:
FreeBSD 12.1-RELEASE

**Web Server Version**:
nginx/1.16.1
lighttpd/1.4.54

**Browser version**:
Google Chrome Version 79.0.3945.117

**Privatebin Version**:
1.3.2

I can reproduce this issue on <https://privatebin.net>: No

**Comment by rugk** [comment]
Do you mind to explain what caused this issue? If I had to guess: webAssembly disabled?

**Comment by ConorBeh** [comment]
I learned that you needed to have HTTPS enabled to access PrivateBin via Chrome.

**Comment by elrido** [comment]
Thank you for confirming. So it was chrome disabling the webcrypto-API when accessing sites over an insecure transport #441.
