### ISSUE TITLE
Javascript required

### ISSUE THREAD

**Issue by sachaz** [PrivateBin/PrivateBin#57]
Hello,

When I'm launching a Privatebin page I got a very fast message saying the Javascript is required before disapearing
It's not only an issue for my installation, I can see this on other PrivateBin on the directory.

Regards,
Sacha

**Comment by elrido** [comment]
Up to and including version 0.22 this was an issue due to not using a `<noscript>` block. It was [fixed in late April](https://github.com/elrido/ZeroBin/issues/51) and will be part of the upcoming release.

**Comment by sachaz** [comment]
perfect, sorry for the noise.
When do you plan a upcoming release ?

**Comment by elrido** [comment]
No problem.
I hope it is done before the end of August.
