### ISSUE TITLE
"Expires: Month / Year / Never". Are these options coming back to PrivateBin?

### ISSUE THREAD

**Issue by ImSpecial** [PrivateBin/PrivateBin#594]
Hey sorry, if this is the wrong place to ask this, not sure where else this would go... I've noticed the recently that [these options are missing from the dropdown box](https://i.imgur.com/Jvx6PhU.png) on PrivateBin, I'm just wondering if they're coming back, if it's a bug or what.

**Comment by elrido** [comment]
Some people kept using the demo instance to publish sensitive personal information,  and other more nasty stuff. I kept spending more time dealing with (physical) letters, calls and emails from various data protection agencies, lawyers and law enforcement agencies, then actually coding on the project.

After the most recent round of abuse and publishing the 1.3.3 update, touching the container anyway, I changed the configuration of the demo site to exclude expiration options above 1 day. Any existing pastes already published with a larger expiration date remains unaffected, except if I get forced to take them down by one of the above conditions.

For your production needs, please either host your own instance or consider using one of the other sites from the [directory](https://github.com/PrivateBin/PrivateBin/wiki/PrivateBin-Instances-Directory).

**Comment by ImSpecial** [comment]
Alright, thanks for clarifying, it's unfortunate people need to abuse stuff like this. :/
