### ISSUE TITLE
Warning Message: "Cannot calculate expiration date"

### ISSUE THREAD

**Issue by utrenkner** [PrivateBin/PrivateBin#597]
## Steps to reproduce
Upgraded from 1.3 to 1.3.3
Create New PasteBin with standard settings (expiration date 3 days, one-time only)
Click "Send"

### What happens
Everything looks good, except for a red warning message " Cannot calculate expiration date."

### What should happen
The same but without that warning message. As it did until before the upgrade to 1.3.3.

## Additional information
Here is a screenshot of the Chrome dev console
![Screenshot-2020-03-17-11-21-15](https://user-images.githubusercontent.com/8254715/76848010-42bcfa00-6843-11ea-803d-042ac8b4634f.png)

Furthermore, I get a warning about a "[m]issing translation for: 'Cannot calculate expiration date.' in language de". The rest of the UI is correctly display in German.

## Basic information
**Server OS:** HardenedBSD 12.1 (essentially like FreeBSD 12.1)

**Webserver:** h2o/2.3.0-beta2

**Browser:** Chromium  79.0.3945.130 and Firefox 74.0;

**PrivateBin version:** 1.3.3

I can reproduce this issue on <https://privatebin.net>: No

**Comment by elrido** [comment]
The good news is that this has already been found and fixed in #586 - currently it is pending to get released with a 1.3.4 hotfix. It had gotten introduced with 1.3.2 as a new feature for emails.

**Comment by utrenkner** [comment]
Sorry, for the duplicate. I missed #586. 

And thanks for all the great work. I like PrivateBin a lot!
