### ISSUE TITLE
Implement Subresource integrity (SRI)

### ISSUE THREAD

**Issue by elrido** [PrivateBin/PrivateBin#6]
Some browsers (Chrome & Firefox) will soon add a new W3C specification called [subresource integrity](http://www.w3.org/TR/SRI/):

> This specification defines a mechanism by which user agents may verify that a fetched resource has been delivered without unexpected manipulation.

Here is an example from a [Firefox developer blog post](https://hacks.mozilla.org/2015/09/subresource-integrity-in-firefox-43/):

    <script src="https://code.jquery.com/jquery-2.1.4.min.js"
      integrity="sha384-R4/ztc4ZlRqWjqIuvf6RX5yb/v90qNGx6fS48N0tRxiGkqveZETq72KgDVJCp2TC"
    crossorigin="anonymous" />

Although so far I see no reason to switch zerobin to CDN usage, simply for the benefits federation offers, it might be worth to add such hashes for our JS libraries.

In a federated scenario, if an attacker can manipulate the JS to compromise the encryption (i.e. by injecting a "master key"), that attacker can also manipulate the integrity hash, so one would not notice this. On the other hand it gives the more security aware visitors some means to check if the library used by a specific zerobin instance matches those from a certain release or not.

Also to consider: Any development change to a JS library will invalidate its hash, so it would be very helpful to have some script to easily regenerate and update the hashes in all templates.

---

@rugk:

I don't really know how you imagine your "federated scenario"...

As long as the basic index file is always loaded from your own server you can use [SRI](https://scotthelme.co.uk/subresource-integrity/) to protect any other files loaded (from other servers). Currently all files are of course loaded from your own server, but with SRI could could easily change this without weaken security.

And you of course can still use SRI for your own server (in this case you also don't need the CORS header).
Combined with [a CSP](https://github.com/PrivateBin/PrivateBin/issues/10) this would also reduce the user trust to one single file: The index file. So security-minded users could check whether the served index file is correct (hash it with a hash you e.g. provide in the Readme here for all themes). Therefore this would mitigate https://github.com/PrivateBin/PrivateBin/issues/8 as users can easily check whether all served files are valid.

When all this is implemented we might of course use [this idea](https://github.com/sebsauvage/ZeroBin/issues/17#issue-4522658) and create a JS bookmarklet as it was already done previously. However in the current case we only would have to check the hash of the index file...

**Comment by elrido** [comment]
Now that we have SRI for all the javascript resources, they need to be regenerated whenever a JS file is changed. I added a mechanism for this into the phpunit bootstrap and described the procedure in the [wiki](https://github.com/PrivateBin/PrivateBin/wiki/Development#subresource-integrity-for-javascript-resources).

**Comment by rugk** [comment]
At first: Awesome of you to implement SRI. We could now host some static files on a CDN and provide an option to enable this in the config. Theoretically. Do you want to open an issue for this?

However as for the regeneration:
You don't want people to have to use composer, but to have them running the unit tests? Seriously, running unit tests is much more complicated then installing composer and running it.
Addition ally the unit tests require a composer installation (with dev modules AFAIK), which by themself require a more recent PHP version than what we support. (at least in my tests)

So maybe a simple bash script or something would be better? Or just explain [how users need to create the hash values](https://scotthelme.co.uk/subresource-integrity/) of the JS files and they can insert them - or just remove them.

BTW as we use CSP we could think about adding [`require-sri-for`](https://github.com/w3c/webappsec-subresource-integrity/pull/32) to the CSP.

**Comment by elrido** [comment]
Regarding CDN: I am strongly against. It is a privacy issue and makes your site depend on resources not under your control. Only resources frequently used many different sites even benefit of having a file already in cache compared to the additional connection(s) to the CDN that the browser has to open. Better to use a server with HTTP/2 and pipelining of requests in one connection. Also it is against the base principle of providing a self-contained tool that can be used in a federated fashion.

I do not expect regular server admins to ever have to regenerate the hashes, since they should not (have to) touch the javascript files. Theme designers can just reuse the already existing hashes. And both are free to add additional scripts (unfortunately Google Analytics is not that uncommon) without SRI hashes to the header.

Regarding `require-sri-for`: As far as I understand your link this is currently a proposal for an upcoming W3C standard of CSP and from what I have found there might be a by default disabled feature for it in the upcoming Chrome 54 and some not yet published development in Firefox. Hence there is currently no way to verify it is working as intended if we implement it now. Lets get back to it when it is actually in live and stable browsers.

**Comment by rugk** [comment]
> It is a privacy issue 

Yes, that's why I would only make it optional.

> makes your site depend on resources not under your control

Well... that issue if fixed with SRI.

> Hence there is currently no way to verify it is working as intended if we implement it now. Lets get back to it when it is actually in live and stable browsers.

Yeah, to prevent us forgetting this here is an issue: https://github.com/PrivateBin/PrivateBin/issues/82
