### ISSUE TITLE
Preview does not update when format is changed

### ISSUE THREAD

**Issue by rugk** [PrivateBin/PrivateBin#60]
## Steps to reproduce

1. Write some text.
2. Click on "preview".
3. Click on the button at the top to change the format.

### What happens
Nothing. To update the preview one has to switch to "edit" back and return to "preview".

### What should happen
Update the preview instantly.

## Basic information

**Browser:** Firefox 48

**PrivateBin version:** fc677b8e957c9c69c12af1fd5885a6e0361911f2

**Comment by elrido** [comment]
Thats absolutely correct, I did not implement that. Good idea!
