### ISSUE TITLE
Longer Pastes

### ISSUE THREAD

**Issue by silentshotghost** [PrivateBin/PrivateBin#600]
Longer pastes would be nice, at least a week should be the minimum

**Comment by elrido** [comment]
You can totally [enable such longer expirations in the configuration of your instance](https://github.com/PrivateBin/PrivateBin/wiki/Configuration#expiration) - by default even pastes that don't expire are possible.

If you refer to the recently restricted expirations on the demo website privatebin.net, please refer to #594 - You can find more instances in the [wiki](https://github.com/PrivateBin/PrivateBin/wiki/PrivateBin-Instances-Directory) or the [directory service](https://privatebin.info/directory/).

**Comment by silentshotghost** [comment]
@elrido https://github.com/PrivateBin/PrivateBin/wiki/PrivateBin-Instances-Directory is blank

**Comment by rugk** [comment]
So as it seems this question has been answered and I thus close this issue. If anyone has further questions on that topic, feel free to comment here, again.
