### ISSUE TITLE
YOURLS Shortend url does not appear in e-mail

### ISSUE THREAD

**Issue by sgrzy01** [PrivateBin/PrivateBin#606]
## Steps to reproduce

1. Add info
2. Hit Send
3. Hit Shorten URL Button
4. Hit Email Button

### What happens
The original long url appears in the e-mail

### What should happen
The shortened url should appear

## Additional information

using YOURLS integration

## Basic information

**Server address**:

**Server OS:**
Debian 9

**Webserver:**
Apache 

**Browser:**
Various

**PrivateBin version:**
1.3.4
I can reproduce this issue on <https://privatebin.net>: No
YOURLS not avail

**Comment by rugk** [comment]
Good idea. Though it is rather a feature and not a bug, but yeah… :smiley:

**Comment by Haocen** [comment]
When I implemented Email sending button I did think about this but I have a feeling if you're already sending the link over Email, would it be problematic if the URL is too long?

Shortened URL is useful when you pass the paste around vocally or via services that restrict number of characters allowed for its input(twitter, for example).

It would be very kind of you if you can let us know your use case so we can better understand how to solve this issue.

**Comment by rugk** [comment]
Fair point, indeed we don't need to decrease the security level if it is not needed.

@sgrzy01 as @Haocen said: Could you please describe the use case behind your issue? I.e. _why_ do you want a short URL in a mail instead of the long one?

---

Also, if one wants to create a PR: I think, what is always acceptable, is, if we would include both links. After all, users can (and likely will) anyway alter the mail template in their mail software. And if they don't, the receiver can choose which link they wanted to click.

**Comment by sgrzy01** [comment]
Thank you for your responses.. 
Really.. no technical reason at all... purely aesthetics.  

We deal with a user base that gets "nervous" seeing a long url... both in a normal mail client and especially mobile mail clients.  Plus, with all the phishing training we have been pushing a long-ish url sometimes prompts a call into support.

So, IMHO the shortened url where our domain is most of the url is a "friendlier" and is less "techy" to our user base.

Also, I'd absolutely prefer not to have both the long and short url in the e-mail, that would definitely confuse my users.

Thanks!.

**Comment by rugk** [comment]
> Plus, with all the phishing training we have been pushing a long-ish url sometimes prompts a call into support.

Well… as for short links people should be calling your support for a potential phishing attack even faster! A shortlink could point anywhere… :upside_down_face:
