### ISSUE TITLE
How can I remove the pastes

### ISSUE THREAD

**Issue by Skayserver** [PrivateBin/PrivateBin#607]
Hello, I have installed my paste 1 year ago and I have recently received a report from some copyrighted pasted and I want to remove but I cannot find how to remove these links from the created pastes.

I would appreciate it very much if you could give me an answer and a guide. thanks

**Comment by elrido** [comment]
Please see the [FAQ](https://github.com/PrivateBin/PrivateBin/wiki/FAQ#how-can-i-delete-a-paste). You can delete the whole paste but you can't modify the content of a paste.

**Comment by rugk** [comment]
So as it seems this question has been answered and I thus close this issue. If anyone has further questions on that topic, feel free to comment here, again.
