### ISSUE TITLE
Update DomPurify

### ISSUE THREAD

**Issue by rugk** [PrivateBin/PrivateBin#609]
https://github.com/cure53/DOMPurify/releases/tag/2.0.9

**not** security-relevant, just chore

**Comment by guzzisti** [comment]
DOMPurify is already on 2.0.14: https://github.com/PrivateBin/PrivateBin/commit/16143422484152bb0a809fc7998feb154540f8de

**Comment by rugk** [comment]
meanwhile [we have 2.0.15](https://github.com/cure53/DOMPurify/releases/tag/2.0.15) 🙈 

So still relevant. 🙂

**Comment by elrido** [comment]
I am not really sure why folks keep creating a ticket for the DOMpurify upgrade, but never for jQuery, base-x, kjua, prettify or showdown.

For public record: Before every release we have always updated the libraries, if it was possible to do so without side-effects. Bootstrap hasn't been upgraded in 1.3 for that reason - one of the last 3.x upgrades broke our JS and we had to revert it. Hope as part of our 1.4 release we can migrate the template to bootstrap 4 or 5 to address this.
