### ISSUE TITLE
Note not been burned after read on Chrome

### ISSUE THREAD

**Issue by matheusvasconcellos** [PrivateBin/PrivateBin#613]
## Steps to reproduce

1. Create a new note and choose the option to burn after reading (can use or not password);
2. Open the note on Chrome.

### What happens
Even after reading the note on Chrome, it is still possible to keep opening it, seems that Chrome is not burning the note.
If I open the same note on Firefox, the note is burned and is not possible to open anymore on Chrome nor Firefox.

### What should happen
The note should be burned on the first open on Chrome.

## Basic information

**Server address**: It's not a public server.

**Server OS:** Amazon Linux 2

**Webserver:** Nginx 1.16.1

**Browser:** Chrome and Firefox

**PrivateBin version:** 1.3.2

I can reproduce this issue on <https://privatebin.net>: No

**Comment by elrido** [comment]
This sounds like Chrome is caching the view or API requests (Chrome still showing it, but Firefox can't get it anymore). So the paste would be burned and not available any-more outside of the one browser that has it cached. Can you check on your server if that file got deleted (if the paste ID would be 123456, in the data folder, there would be a file 12/34/123456.php), to confirm or deny this interpretation?

**Comment by matheusvasconcellos** [comment]
Hi, thanks for the feedback.

The page was really been cached, but not by Chrome, I forgot to mention that we have a reverse proxy (also Nginx). After turning off the cache option on it, everything is working as should be.

Thanks for the light!
