### ISSUE TITLE
Add New options (Print, raw, download paste and embled)

### ISSUE THREAD

**Issue by wuniversales** [PrivateBin/PrivateBin#616]
I have already seen from other incidents that you have rejected all this, but what I say is different, since the user who publishes in privatebin, configures how he wants his content to be displayed.

I mean that the user who posts to privatebin can enable or disable all options (Print, raw, download paste and embled) for the end user (s).

I personally like to share code using "raw", this option is not given by privatebin.

Cheers

**Comment by rugk** [comment]
You can currently always paste the source code as "text only", i.e. raw and the receivers can also always click on the "raw text" button, though that may be obsolete/changed with https://github.com/PrivateBin/PrivateBin/issues/270.

Also the option to allow embedding is not easily possible, given that [we set](https://github.com/PrivateBin/PrivateBin/blob/9914c37683496d161d9f8c8355bc89c358b1b243/lib/Controller.php#L346) the ["X-Frame-Options"](https://developer.mozilla.org/docs/Web/HTTP/Headers/X-Frame-Options) for security reasons, so we cannot really conditionally allow it (at least as servers could also set it again). Generally, embedding is also not useful with burn-after-read etc.

And a printing button basically has been declined in https://github.com/PrivateBin/PrivateBin/issues/604. (Also, if you really wanted, just use the browser's print feature.)

As such, I'd say all listed buttons won't be added.
