### ISSUE TITLE
Unable to create directory data in /var/www/privatebin/lib/Persistence/AbstractPersistence.php:88

### ISSUE THREAD

**Issue by Mati20187** [PrivateBin/PrivateBin#617]
### What happens
When trying to send a paste, I get an error.

Information on the website:
`Could not create paste: server error or not responding`

Error log:
`[php7:error] [pid 5409] [client 83.145.151.199:33014] PHP Fatal error:  Uncaught Exception: unable to create directory data in /var/www/privatebin/lib/Persistence/AbstractPersistence.php:88\nStack trace:\n#0 /var/www/privatebin/lib/Persistence/AbstractPersistence.php(72): PrivateBin\\Persistence\\AbstractPersistence::_initialize()\n#1 /var/www/privatebin/lib/Persistence/TrafficLimiter.php(104): PrivateBin\\Persistence\\AbstractPersistence::_exists('traffic_limiter...')\n#2 /var/www/privatebin/lib/Controller.php(201): PrivateBin\\Persistence\\TrafficLimiter::canPass()\n#3 /var/www/privatebin/lib/Controller.php(125): PrivateBin\\Controller->_create()\n#4 /var/www/privatebin/index.php(18): PrivateBin\\Controller->__construct()\n#5 {main}\n  thrown in /var/www/privatebin/lib/Persistence/AbstractPersistence.php on line 88`

### What should happen
Paste should work

## Basic information

**Server OS:** Raspbian 10

**Webserver:** Apache 2.4.38

**Browser:** Firefox, qutebrowser

**PrivateBin version:** 1.3.4

I can reproduce this issue on <https://privatebin.net>: No

**Comment by rugk** [comment]
Looks like you have a permission error in your setup. See https://github.com/PrivateBin/PrivateBin/wiki/FAQ#what-are-the-recommended-file-and-folder-permissions-for-privatebin for more information.

**Comment by Mati20187** [comment]
After searching for a correct user which in my case was **www-data** I did `chown -R www-data:www-data privatebin/` which fixed the problem. Thanks @rugk !
