### ISSUE TITLE
Never Expire?

### ISSUE THREAD

**Issue by uascol** [PrivateBin/PrivateBin#621]
Hello, I am using PrivateBin for quite some time. I always used the browser version "Try it out!".
It had an expiry option "Forever" or "Never expire" something like that.
But now it's not there anymore, only 5 minutes, 10 minutes, 1 hour, 1 day.

How can I make a privatebin never expire?

**Comment by r4sas** [comment]
Run instance and configure it to your requirements. "Try it out!" instance provided as example of service, so here can be disabled "Never" expiring option.

**Comment by elrido** [comment]
Details on why this was disabled can be found in [#594](https://github.com/PrivateBin/PrivateBin/issues/594#issuecomment-595040259). There are [other instances](https://privatebin.info/directory/) that have that option still enabled, if you don't want to run your own instance.
