### ISSUE TITLE
PrivateBin stopped working on Firefox 68.8.0esr 

### ISSUE THREAD

**Issue by g0rbe** [PrivateBin/PrivateBin#623]
## Steps to reproduce

1. Go to [paste.danielgorbe.com](https://paste.danielgorbe.com)
2. Do anything

### What happens

Trying to create a ...

#### New plain text or markdown:

```
Could not create paste: server error or not responding
```

#### New source code:

Tab crashes
![Screenshot_20200516_195136](https://user-images.githubusercontent.com/36860942/82126720-f6882a80-979d-11ea-8883-a205ea04901a.png)

When somebody send a paste with no password, on Firefox i will be asked.

The site is working on Chromium and Firefox 74.

## Basic information

**Server address**: [paste.danielgorbe.com](https://paste.danielgorbe.com)

**Server OS:** Linux

**Webserver:** Nginx

**Browser:** Firefox 68.8.0esr 

**PrivateBin version:** 1.3.4

I can reproduce this issue on <https://privatebin.net>: **Yes**

**Comment by Haocen** [comment]
Would you please kindly show us the output from your Firefox console when the error happens?
You can find a guide on how to this [here](https://developer.mozilla.org/en-US/docs/Tools).

**Comment by elrido** [comment]
Since we have that sponsored browserstack account, I tried to reproduce it with Firefox 68 on Mac and Windows there, but it worked fine - creating, viewing and with the different formats. But it's not the ESR version, just the regular version 68.

As per the [68.8esr release notes](https://www.mozilla.org/en-US/firefox/68.8.0/releasenotes/), they [fixed a number of security issues](https://www.mozilla.org/en-US/security/advisories/mfsa2020-17/). Those regarding to sandbox security might somehow affect the webcrypto API or the use of webassembly? These issues also got addressed in version 76, but I can't reproduce it with that version either.

Any chance that you can test this with a 68.8esr from a different internet connection, to rule out proxy or packet filter or other network related issues, @g0rbe?

**Comment by g0rbe** [comment]
@Haocen 

```
parsererror SyntaxError: "JSON.parse: unexpected end of data at line 1 column 1 of the JSON data"
    jQuery 3
        s
        l
        o
privatebin.js:4422:25
    run https://paste.danielgorbe.com/js/privatebin.js?1.3.4:4422
    jQuery 4
        c
        fireWith
        l
        o
```

**Comment by g0rbe** [comment]
> Since we have that sponsored browserstack account, I tried to reproduce it with Firefox 68 on Mac and Windows there, but it worked fine - creating, viewing and with the different formats. But it's not the ESR version, just the regular version 68.

Im on Kali now, its default browser is Firefox 68 ESR.
Maybe you can reproduce with a live image.

> As per the [68.8esr release notes](https://www.mozilla.org/en-US/firefox/68.8.0/releasenotes/), they [fixed a number of security issues](https://www.mozilla.org/en-US/security/advisories/mfsa2020-17/). Those regarding to sandbox security might somehow affect the webcrypto API or the use of webassembly? These issues also got addressed in version 76, but I can't reproduce it with that version either.
> 

I updated my 74 to 76.0.1, and it works fine

> Any chance that you can test this with a 68.8esr from a different internet connection, to rule out proxy or packet filter or other network related issues, @g0rbe?

I tested with a system wide Tor with multiple exit node, but the issue is the same.
In my country, there is no sign of traffic filtering, so this probably not the problem.


I tought that maybe my modified user.js is the problem, but i tried with the default release profile and plain one (without any user.js change), but the issue is persist.

**Comment by Haocen** [comment]
> @Haocen
> 
> ```
> parsererror SyntaxError: "JSON.parse: unexpected end of data at line 1 column 1 of the JSON data"
>     jQuery 3
>         s
>         l
>         o
> privatebin.js:4422:25
>     run https://paste.danielgorbe.com/js/privatebin.js?1.3.4:4422
>     jQuery 4
>         c
>         fireWith
>         l
>         o
> ```

Hi, @g0rbe , this indicates the server returned error when submitting the paste.
Do you mind further copy paste the failed request from the [network monitor](https://developer.mozilla.org/en-US/docs/Tools/Network_Monitor) tab of your Firefox?

The request should be marked in red with an error code.

It will be very helpful if you can copy the content from the headers tab and response tab after selecting the failed request.

**Comment by g0rbe** [comment]
Response header:

```
HTTP/2.0 200 OK
server: nginx
date: Sun, 17 May 2020 17:35:37 GMT
content-type: application/json
set-cookie: lang=en
access-control-allow-origin: *
access-control-allow-methods: GET, POST, PUT, DELETE
access-control-allow-headers: X-Requested-With, Content-Type
strict-transport-security: max-age=63072000; includeSubdomains
X-Firefox-Spdy: h2
```

Request header:

```
Host: paste.danielgorbe.com
User-Agent: Mozilla/5.0 (Windows NT 10.0; rv:68.0) Gecko/20100101 Firefox/68.0
Accept: application/json, text/javascript, */*; q=0.01
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate, br
Content-Type: application/x-www-form-urlencoded; charset=UTF-8
X-Requested-With: JSONHttpRequest
Content-Length: 145
DNT: 1
Connection: keep-alive
Cookie: lang=en
TE: Trailers
```

Post param:

```
{"adata":[["jHsDX6n/ODd+fuqJRjt7Ag: ]
```
![Screenshot_20200517_194411](https://user-images.githubusercontent.com/36860942/82155656-0c612280-9866-11ea-92db-cd20e333e97d.png)



Response:
Nothing.
```
No response data available for this request
```

Edit and resend shows more data in the body:

```
{"adata":[["jHsDX6n/ODd+fuqJRjt7Ag==","MliW0Z3OyhE=",100000,256,128,"aes","gcm","zlib"],"plaintext",0,0],"meta":{"expire":"1week"},"v":2,"ct":""}
```

**Comment by g0rbe** [comment]
More error from the console log:

```
Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”). 2 paste.danielgorbe.com:1:1
```

```
Content Security Policy: The page’s settings blocked the loading of a resource at inline (“style-src”). paste.danielgorbe.com:1:1
```

**Comment by Haocen** [comment]
I think the problem is laying in the data being sent to server, the complete data should look like following:

```
{"adata":[["yd9z3 faMIny4SIqgCmy5w: =","pXLQRmHJ f0=",100000,256,128,"aes","gcm","zlib"],"plaintext",0,0],"meta":{"expire":"1week"},"v":2,"ct":"NiKsin8a2EeoVWluKF3hJObkG uFX/0BPBSj1iP/KMFPIKDBOwwg4qmzu2dP2IvzRIDQ vSty6tKvtNJhvAn/gPw3i5uVELohiov67G9sveDQf7NjfBvZMzxvRUs7RB4nn1HLNGAqgyoR4J6/5KnkE sfE0C5Qh1z6hgoRy rLaqhB21WO7osZXfdj8gNX9FT0Ep 1Is0qQjcrPWHmxmS7HRx0QlWXPjdb1yWvCANEwVxnzEE65COFMbc5dloLiEgGXfK9/nhfNb7apIc8ihVFOHEWcsle3idPSfNdWBEiv2n7eOGp2ilA=="}
```

If only
```
{"adata":[["jHsDX6n/ODd+fuqJRjt7Ag: ]
```
Was sent to server, then we need to look into what happened here, the server is not going to be able to understand this request. This is not even valid JSON, as far as I'm concerned.

**Comment by g0rbe** [comment]
Zaproxy and the *Edit and resend* shows the full data:

```
{"adata":[["xV9KV+3udX6ZaDQ4zsD2Zg==","viA5cYuhTZA=",100000,256,128,"aes","gcm","zlib"],"plaintext",0,0],"meta":{"expire":"1week"},"v":2,"ct":""}
```

**Comment by Haocen** [comment]
This seemed to be Firefox 68.8.0esr specific problem.
I was not able to reproduce the problem on Firefox 68.2.0esr.

The sympton seemed to be, after calling `JSON.stringify` and assigning the value to `ajaxParams.data`, looks like following:
```
"{\"adata\":[[\"McgdV+IQa4B5OpZh+BcCvw==\",\"C2nXb1Qxjmg=\",100000,256,128,\"aes\",\"gcm\",\"zlib\"],\"plaintext\",0,0],\"meta\":{\"expire\":\"1day\"},\"v\":2,\"ct\":\"\"}"
```
The value become truncated:
```
{"adata":[["McgdV+IQa4B5OpZh+BcCvw	
```
In the acutally sent request. Indicating Firefox is incapable of handling the formdata content it used to be able to handle?

**Comment by g0rbe** [comment]
@Haocen 

It a bug in 68.8.0esr only, PrivateBin works on FF 74 / 76 and on Chromium too.

**Comment by singlespeedfahrer** [comment]
Same here in Firefox 76 (Debian unstable). Chromium works.

**Comment by elrido** [comment]
Sorry, @singlespeedfahrer, I do not manage to reproduce the issue on Firefox 76. Are you sure that isn't an issue with the instance you use? Do you use any plugins or a proxy/VPN that might change any of the transmitted data? Same error in the console?

**Comment by singlespeedfahrer** [comment]
It happens in all instances I tried, for example https://privatebin.net. I have deactivated all extensions in firefox but this doesn' help. I don't use any kind of vpn or proxy. I'll try to find out more.

**Comment by g0rbe** [comment]
@singlespeedfahrer What system are you using?

**Comment by singlespeedfahrer** [comment]
I use debian wth a mix of testing and unstable. After an upgrade of firefox PrivateBin is working again! Thx!

**Comment by rugk** [comment]
Here is the Debian changelog for Firefox: https://metadata.ftp-master.debian.org/changelogs//main/f/firefox/firefox_76.0.1-2_changelog

Which does not list the ESR 86.8 version at all, but ah yes, it was still called iceweasel there: https://packages.debian.org/de/jessie/iceweasel

Only problem I cannot access the Changelog at https://metadata.ftp-master.debian.org/changelogs//main/f/firefox-esr/firefox-esr_68.8.0esr-1~deb8u1_changelog, because of a 404 error… :roll_eyes: 

Well… anyway, whatever caused the crash is likely fixed in the new Firefox.
As such, I guess we can close this issue.
If anyone has further questions/problems/information on that topic, feel free to comment here, again.
