### ISSUE TITLE
Feature Request - Provide an optional shorter IDs 

### ISSUE THREAD

**Issue by tantoinet** [PrivateBin/PrivateBin#626]
It would be great to allow generating shorter IDs for the pasted data.
This prevents dependency on URL shorteners and makes it simpler to access the pasted data quickly from non Copy/Paste enabled environments (eg. VMs without guest additions, ...)

**Comment by rugk** [comment]
The "ID" (i.e. actually the part after the hash sign `#`) does encode the encryption key, which is a fundamental part of the security model of PrivateBin.
As such, without changing what characters or compression/encoding we apply to the key, we cannot shorten it without decreasing the security of PrivateBin.

See also the FAQ: https://github.com/PrivateBin/PrivateBin/wiki/FAQ#if-i-use-privatebin-and-post-the-link-in-a-forum-in-social-media-etc-is-my-content-secure

As such, unless someone can propose a better encoding, we cannot fulfill this idea.
