### ISSUE TITLE
Browser Add-ons

### ISSUE THREAD

**Issue by JohnPlanetary** [PrivateBin/PrivateBin#627]
Since is so difficult/ impossible to guarantee the security of the server being used to deliver the service, it would be nice for a browser extension to be available to do all the sensitive part of the job, so that there is less opportunities for errors and backdoors on individual servers out there that are providing the service... even if compelled by law or server is attacked to change javascript and things like that, it won't affect the data security.

I'm not saying just be able to use with browser extension, just that it should also be possible with it.

**Comment by rugk** [comment]
Yeah, we had this idea already, and discussed and tested out different things. There is no thing (or result) we can recommend for now, unfortunately though.

Read up on https://github.com/PrivateBin/PrivateBin/issues/138 for the whole story.

As such, closing this, as a duplicate of https://github.com/PrivateBin/PrivateBin/issues/138
