### ISSUE TITLE
IIS on 2012 R2 cannot handle SHA512 js integrity hashes

### ISSUE THREAD

**Issue by iamdoubz** [PrivateBin/PrivateBin#636]
## Steps to reproduce

1. `git clone https://github.com/PrivateBin/PrivateBin.git&&cd PrivateBin`
2. `composer install`
3. Have an IIS server (yes I know how sad)

### What happens
Integrity could not be verified.

### What should happen
Integrity should be verified.

## Additional information
[Possible solution](https://support.microsoft.com/en-us/help/2973337/sha512-is-disabled-in-windows-when-you-use-tls-1-2) server side.

## Quick fix for this version only
1. Change all sha512 integrity's to sha256 ones by editing `$base\tpl\bootstrap.php` and this:

```php
		<script type="text/javascript" data-cfasync="false" src="js/jquery-3.4.1.js" integrity="sha256-QSuP+cWrMrkBn82EvNSlTA4mWhRShHT07kWyeiCr6us=" crossorigin="anonymous"></script>
<?php
if ($QRCODE):
?>
		<script async type="text/javascript" data-cfasync="false" src="js/kjua-0.6.0.js" integrity="sha256-tmijC9lmyE0VrPfHLD4C+LfSmVIfc+jC/oU6t+4g8uc=" crossorigin="anonymous"></script>
<?php
endif;
if ($ZEROBINCOMPATIBILITY):
?>
		<script type="text/javascript" data-cfasync="false" src="js/base64-1.7.js" integrity="sha512-JdwsSP3GyHR+jaCkns9CL9NTt4JUJqm/BsODGmYhBcj5EAPKcHYh+OiMfyHbcDLECe17TL0hjXADFkusAqiYgA==" crossorigin="anonymous"></script>
<?php
endif;
?>
		<script type="text/javascript" data-cfasync="false" src="js/zlib-1.2.11.js" integrity="sha256-IPq7GLhiYAUJQJegdeabYSryssoeBcrxhoDHm4VTcEE=" crossorigin="anonymous"></script>
		<script type="text/javascript" data-cfasync="false" src="js/base-x-3.0.7.js" integrity="sha256-tpgQLcCvQY9/1AOHujTEauD+RE4fvxH8PgapCK6h2Tc=" crossorigin="anonymous"></script>
		<script type="text/javascript" data-cfasync="false" src="js/rawinflate-0.3.js" integrity="sha256-4J7vrdkk8pPZUs1Y48MB5+j3fDhzTL6W+XcmZ707M1I=" crossorigin="anonymous"></script>
		<script type="text/javascript" data-cfasync="false" src="js/bootstrap-3.3.7.js" integrity="sha256-NkYOSU5MYoRDr97UCydDte3ppKdvtPe57yNFzH5Z/WQ=" crossorigin="anonymous"></script>
<?php
if ($SYNTAXHIGHLIGHTING):
?>
		<script type="text/javascript" data-cfasync="false" src="js/prettify.js?<?php echo rawurlencode($VERSION); ?>" integrity="sha256-2E2anSoKpf1gNFl7UZwikdBQ3tmR2ooe43i3Y9CyR2g=" crossorigin="anonymous"></script>
<?php
endif;
if ($MARKDOWN):
?>
		<script type="text/javascript" data-cfasync="false" src="js/showdown-1.9.1.js" integrity="sha256-1BV1EL2E7aSmOGJW4Gw3JFX5stUgle5KqFXj3Ojgid4=" crossorigin="anonymous"></script>
<?php
endif;
?>
		<script type="text/javascript" data-cfasync="false" src="js/purify-2.0.8.js" integrity="sha256-61pdKJePW1xGicFncRUp56h82pLoids1kfOjTif/HAU=" crossorigin="anonymous"></script>
		<script type="text/javascript" data-cfasync="false" src="js/legacy.js?<?php echo rawurlencode($VERSION); ?>" integrity="sha256-v4ynN5sCdjlEyChpzqzuNceM2cFb/Hmnw4weINCLghg=" crossorigin="anonymous"></script>
		<script type="text/javascript" data-cfasync="false" src="js/privatebin.js?<?php echo rawurlencode($VERSION); ?>" integrity="sha256-jnvQVsc24E3DF7C9ca8OkLfqKi/AnyMKHtiIAhsaugI=" crossorigin="anonymous"></script>
```

## Basic information

**Server address**:

**Server OS:** Windows Server 2012 R2

**Webserver:** IIS

**PHP:** 7.3.13

**Browser:** et al.

**PrivateBin version:** 1.3.4 (45a0535640fb066e28fdc7b31bd945dcef53e9ea)

I can reproduce this issue on <https://privatebin.net>: [ ] Yes / [x] No

**Comment by rugk** [comment]
You seem to be confusing something here.
The hashes in SRI have nothing to do with the hashes (actually HMACs AFAIK) in TLS.

As such, also the webserver should not have any influence on that.
The SRIs are verified _locally by the browser_.

Please recheck your STRs. There is likely something else that works/does not work and I'm not sure whether it is really related to these hashes.
I.e. What do you _actually_ see?

**Comment by iamdoubz** [comment]
I have setup two instances today: my own personal on Ubuntu 18 using apache and a work one for my team with IIS. I used the same browser between both. My personal one, works and no errors. The work one does not. Here is the actual error if I don't modify the `bootstrap.php` file:

![privatebin_iis_sha256](https://user-images.githubusercontent.com/4871781/84443714-c6e60a00-ac05-11ea-8e8d-bae07473fd7c.png)

It is trying to use SHA256 to verify the integrity of SHA512 hashes so it fails and I get the infinite loading message.

**Comment by elrido** [comment]
I suspect that the "sha256" in the error message might be a false lead (a bug in that browsers display of SRI errors) and that IIS is instead delivering the resources with an incorrect character encoding. You can verify that this is the case by checking in the network tab of your browsers dev console what character encoding was set in the header for one of the js files. It should be UTF-8, but if I remember correctly, IIS defaults to something like ISO-8859-1 instead. If this is indeed the problem, you should be able to configure this. I am not that familiar with IIS anymore, but this might be done using a [web.config file and settings similar to the below](https://docs.microsoft.com/en-us/previous-versions/dotnet/netframework-1.1/hy4kkhe0(v=vs.71)?redirectedfrom=MSDN), maybe?

```xml
<globalization 
    fileEncoding="utf-8" 
    requestEncoding="utf-8" 
    responseHeaderEncoding="utf-8" 
    responseEncoding="utf-8" 
    enableClientBasedCulture="false"
/>
```

Alternatively, maybe you need to [adjust the MIME type to be utf-8 as suggested in other examples](https://webhint.io/docs/user-guide/server-configurations/iis/).

Please let us know if the encoding is at fault here or you discover something else. If you can find a working configuration, we should [document that in the wiki page](https://github.com/PrivateBin/PrivateBin/wiki/IIS-Configuration-(Required)).

**Comment by iamdoubz** [comment]
Network headers before change (Firefox):
```
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:77.0) Gecko/20100101 Firefox/77.0
Accept: */*
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate, br
Referer: https://pb.dom.ain/
Connection: keep-alive
Cookie: lang=en; nc_sameSiteCookielax=true; nc_sameSiteCookiestrict=true; _pk_id.11.b47f=5b2294b41f03f7a5.1563308935.8.1563817215.1563817215.; _pk_id.7.b47f=d080f7529d3a485b.1563385511.6.1563903098.1563903098.; _pk_id.1.06c3=d0808bb819bf2839.1563385513.6.1563903250.1563903107.; _pk_id.9.b47f=860aab757b4530ec.1563484160.3.1571924698.1571924183.; _pk_id.8.06c3=06a270d9c4fde310.1563547499.5.1563827619.1563817454.; _pk_id.5.b47f=7a2c86e9674be608.1563826541.1.1563826541.1563826541.; _pk_id.12.06c3=10eef35297e52dfb.1563826803.1.1563827468.1563826803.
If-Modified-Since: Thu, 11 Jun 2020 19:00:16 GMT
If-None-Match: "0a0d8b2240d61:0"
Cache-Control: max-age=0
```
Then add this new web.config:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<configuration>
	<system.webServer>
        <staticContent>
            <clientCache cacheControlMode="DisableCache" />
            <!-- The brotli mime type is unknown to IIS, we need it or otherwise files will not be served correctly -->
            <remove fileExtension=".br" />
            <mimeMap fileExtension=".br" mimeType="application/brotli" />
            <!-- IIS doesn't set the right charset for text types -->
            <remove fileExtension=".css"/>
            <mimeMap fileExtension=".css" mimeType="text/css; charset=utf-8"/>
            <remove fileExtension=".html" />
            <mimeMap fileExtension=".html" mimeType="text/html; charset=utf-8" />
            <remove fileExtension=".js"/>
            <mimeMap fileExtension=".js" mimeType="text/javascript; charset=utf-8"/>
            <remove fileExtension=".json"/>
            <mimeMap fileExtension=".json" mimeType="application/json; charset=utf-8"/>
            <remove fileExtension=".svg"/>
            <mimeMap fileExtension=".svg" mimeType="image/svg+xml; charset=utf-8"/>
            <remove fileExtension=".txt" />
            <mimeMap fileExtension=".txt" mimeType="text/plain; charset=utf-8" />
            <remove fileExtension=".xml"/>
            <mimeMap fileExtension=".xml" mimeType="text/xml; charset=utf-8"/>
            <remove fileExtension=".webmanifest"/>
            <mimeMap fileExtension="webmanifest" mimeType="application/manifest+json; charset=utf-8"/>
            <!-- font types -->
            <remove fileExtension=".woff"/>
            <mimeMap fileExtension=".woff" mimeType="font/woff"/>
            <remove fileExtension=".woff2"/>
            <mimeMap fileExtension=".woff2" mimeType="font/woff2"/>
        </staticContent>
	</system.webServer>
	<system.web>
		<globalization fileEncoding="utf-8" requestEncoding="utf-8" responseHeaderEncoding="utf-8" responseEncoding="utf-8" enableClientBasedCulture="false" />
	</system.web>
</configuration>
```
Result after clearing cache and cookies (Firefox):

```
Host: mobile.loram.com
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:77.0) Gecko/20100101 Firefox/77.0
Accept: */*
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate, br
Referer: https://pb.dom.ain
Connection: keep-alive
Cookie: lang=en
If-Modified-Since: Thu, 11 Jun 2020 19:00:16 GMT
If-None-Match: "0a0d8b2240d61:0"
Cache-Control: max-age=0
```

AKA Nothing changed. Which super stinks.

**Comment by rugk** [comment]
…or maybe it mangles with the line endings somehow… (converts it to Windows-style CRLF??)

Are you sure you did not modify the JS files?

**Comment by iamdoubz** [comment]
Very sure. I do have another theory, but that will have to wait until Monday.

**Comment by Chris3773** [comment]
I ran into this same problem. It was caused during the upload to the windows server. Where files that had LF line breaks were converted to CRLF.

I got around the problem by uploading the files as a zip file and extracting it on the server.

**Comment by rugk** [comment]
Maybe someone can write an [FAQ entry](https://github.com/PrivateBin/PrivateBin/wiki/FAQ) for this problem? As it seems to be common one?
Maybe in a new question [below that generic question about the error message](https://github.com/PrivateBin/PrivateBin/wiki/FAQ#why-does-the-loading-message-not-go-away).

**Comment by iamdoubz** [comment]
I will verify @Chris3773 observation. Then I will write it up.

**Comment by elrido** [comment]
Git will automatically change the line ending characters on Windows. The SHA hashes get calculated on the files with UNIX line feeds, Windows uses carriage return + line feed characters. [You can change this behaviour.](https://docs.github.com/en/github/using-git/configuring-git-to-handle-line-endings)

Aside: If you do not develop the PHP side of things and want to change the libraries included via composer, there is no need for you to run composer, as we already include the production builds of the used libraries and you would replace them with the non-optimized development versions.

**Comment by rugk** [comment]
Additionally, [if you download the ZIP files](https://github.com/PrivateBin/PrivateBin/releases) instead of cloning the repository, you should also get the correct line-endings…

**Comment by elrido** [comment]
I think this question has been answered and I am closing the issue. Please feel free to reply if you have follow-up questions or create a separate issue for different topics.
