### ISSUE TITLE
Allow users to create accounts

### ISSUE THREAD

**Issue by learnedtocode** [PrivateBin/PrivateBin#637]
I'd like to request a new feature, **user account creation**. I didn't see any previous discussion on this but may have just missed it.

This would allow users to create an account with a password and then associate their username/account with a list of their pastes. This is like the existing IP hashes feature (if I understood it correctly) but this would work across changing IPs and different devices.

**Comment by r4sas** [comment]
Project is not targeted to use such things, so I think it is useless...

**Comment by rugk** [comment]
I think your use case might be solved by using #2 .

As such, I'd close this issue for now. Indeed, a login mechanism is too complicated IMHO.

**Comment by learnedtocode** [comment]
>I think your use case might be solved by using #2 .
>>I would also be in favour for such a "paste manager",. but don't store the pastes on the server. Just store them in the local storage on your own device.
not really, because the goal of this was to make a user's own paste history public.
I guess that is incompatible with the rest of the design goals of privatebin though, you can't really have both zero knowledge and a public history, so this should stay closed.

**Comment by rugk** [comment]
> I guess that is incompatible with the rest of the design goals of privatebin though, you can't really have both zero knowledge and a public history, so this should stay closed.

:+1:
