### ISSUE TITLE
Show warning when HTTPS is not used

### ISSUE THREAD

**Issue by rugk** [PrivateBin/PrivateBin#64]
In 2016 HTTPS should be used everywhere. As [explained in the Readme](https://github.com/PrivateBin/PrivateBin#what-it-doesnt-provide) without HTTPS PrivateBin is not secure, so that's why I propose to show a big (scary) warning message when HTTPS is not used.
### ideas for implementation
- show on home page for every user wanting to use PrivateBin
- big and red, stating that this PrivateBin instance is insecure as it does not use transport encryption
- the message should also be understood by non-techy users, but also server admins should know what it is about
- local IPs should be excluded (`127.0.0.1`, `::1`, `localhost`), so that PrivateBin does not show this message when running on your own computer
#### pro
- Without HTTPS PrivateBin does provide a false-sense of security.
- As a security-focused project PrivateBin should not allow insecure ways of transferring data.
- Server admins should get concerned when not using HTTPS. It is not clear whether the current notes in the Readme are clear enough. A big red warning message this may be 
- We could show some tips to server admins on how to switch to HTTPS, e.g. by using [Let's Encrypt](https://letsencrypt.org/).
- Users should get concerned about HTTPS and may be surprised to see that they used an insecure service for years, months, ...
#### contra
- Also the HTTP warning could be stripped by an attacker with a MITM attack. This means one cannot rely on this message.
- We should not act as a "moralizer" and let server admins decide things by themself.
- Users using PrivateBin should be clever enough to have a look into the URL bar and check whether the server uses HTTPS.
- We already have many notes in the Readme suggesting server admins to enable HTTPS.
- Also without HTTPS PrivateBin does protect against passive surveillance.
### things to decide on
- Exclude intranet IPs? (Yes/No)  
  **Pro:** The own LAN/WLAN is usually considered secure, so HTTPS is not necessary.  
  **Contra:** In large companies the LAN/WLAN is used by many, many people so it cannot be considered a "private LAN" and HTTPS should be used here too.
- Make it dismissible, so one can click on "close" to hide it? (Yes/No)  
  **Pro:** There may be situations where HTTPS does indeed not provide any additional security.  
  **Contra:** When users can hide this message it is not strong enough, only a persistent message may put enough pressure on webadmins to switch to HTTPS.
- Add a config value to let admins disable this warning? (Yes/No)  
  **Pro:** Admins should be able to control everything on their server. We should not be some kind of "moralizer" forcing them to show an annoying warning to all their users.  
  **Contra:** When web admins can hide this message it does not put enough pressure on webadmins to switch to HTTPS, because they can just toggle a switch in the config file to hide it instead of fixing the actual problem.

Related to https://github.com/elrido/ZeroBin/issues/8

**Comment by elrido** [comment]
I would not do this: The man-in-the-middle can be mitigated by using SRI (#6) and there are scenarios where it is still uncommon to use HTTPS on the application server side that are perfectly legitimate (reverse proxies for TLS-termination, Tor hidden services as Tor already provides an encrypted channel).

Also, as you might have already noticed, I hate to force people to do stuff. Provide a safe and working default, yes. Introduce new options that can't easily be disabled, no.

And however we do it, admins will always be able to easily disable it. Be it a simple message in the templates or one hidden and obfuscated in the JS.

**Comment by rugk** [comment]
>  The man-in-the-middle can be mitigated by using SRI

Well, no. :smile: If the PrivateBin source code (meaning index page and all things) is installed, anyone can of course MITM the first document including the SRI hashes, so that SRI can trivially be stripped.
Only HTTPS provides a protection against MITM attacks in this case.

> reverse proxies for TLS-termination

We could check `X-Forwarded-Proto`.

All other points of your explanation are indeed good arguments against such a message - at least against a message which cannot be hidden by admins.

**Comment by rugk** [comment]
Correction:
> reverse proxies for TLS-termination

Does not matter. I'd rather check it on the client-side and show an error there…

So with HTTPS becoming the default and in our case really requiring it, I'd say we can go this way.

To decide on the open questions (my suggestion):

> Make it dismissible, so one can click on "close" to hide it? (Yes/No)

No, IMHO. HTTPS is required for security reasons.

> Exclude intranet IPs? (Yes/No)

Technically hard, so no.

> Add a config value to let admins disable this warning? (Yes/No)

This is a thing I could live with a compromise: Introduce a config, but do not document it. So admins, who really ask, can ask us or look through the issues; but it's not too easy… This also prevents us from these admins, who would mangle with JS or the templates just to disable us. In such a case, they'd rather use a "clean, but bad" option than a "dirty and bad" solution. :wink: 
If you don't want this, I'd tend to "no" here. It's easier to implement without such an option.

**Comment by Arregi** [comment]
I would be glad to see this implemented, I think a config value (able/disable) will suffice calling to the honorability of the server admin. I would want the warning even if I know I am serving privatebin through http, just to remind anyone using it that the server is non secure. I think it is a great idea. About close/hide button, I don't think it is necessary, as long as doesn't prevent the user from pasting text.

**Comment by r4sas** [comment]
Same opinion to use config value. I'm use PBin in I2P, where HTTPS is not required itself cause of secured tunnels between clinet and server.

**Comment by rugk** [comment]
> I'm use PBin in I2P, where HTTPS is not required itself cause of secured tunnels between clinet and server.

Ah, yeah, that's the use case, where the config would really make sense.
Just now the question: Would it satisfy you if that config would not be documented? (just to make it a little harder for server admins to disable it – possibly even before even reading the message)
Or do you think that is an anti-pattern that should not be followed – even in this case?

>. I would want the warning even if I know I am serving privatebin through http, just to remind anyone using it that the server is non secure.

Yeah, possibly useful for "demo instances" or quickly setup test ones or whatever…
While we are at it: I guess it can properly determinate and ignore (dev instances) localhost. That's just a quick whitelist.

**Comment by manasb** [comment]
Came here to echo what R4SAS already commented in https://github.com/PrivateBin/PrivateBin/issues/64#issuecomment-448031983

I personally don't see the benefit of making things more difficult for people who are running PrivateBin over an already-encrypted network e.g. Tor/I2P to disable the HTTPS check/warning. I think that such a configuration option should be documented and the security-related warnings about not using HTTPS displayed prominently everywhere it is documented - there is an issue in that this would only be visible to the server administrators and doesn't account for someone using the service. 
For users, don't browsers already display a warning when data is transmitted over plain HTTP? Perhaps it would be better to take advantage of that to aid users when a PrivateBin instance doesn't use HTTPS.

**Comment by rugk** [comment]
> already-encrypted network e.g. Tor/I2P

Possibly we can approach it from another point-of-view: Instead of showing the error for all protocols rather than HTTPS, we can show it only for HTTP, i,e. _known_ insecure protocols.
This should mitigate the problem when using other secure protocols.

> For users, don't browsers already display a warning when data is transmitted over plain HTTP?

Modern ones, yes. But it also depends and not all indicators are string (big) enough or so to be shown/seen always by users.
We can display a much more prominent/big warning.

**Comment by r4sas** [comment]
> Possibly we can approach it from another point-of-view: Instead of showing the error for all protocols rather than HTTPS, we can show it only for HTTP, i,e. _known_ insecure protocols.
> This should mitigate the problem when using other secure protocols.

Neither web server, neither browser know that they use secure connection which incaplsulated with cryptography, because it established via proxy. So in that way enabling notification for HTTP also will be problem.

**Comment by rugk** [comment]
> Neither web server, neither browser know that they use secure connection which incaplsulated with cryptography, because it established via proxy.

Hu? Obviously the browser knows. Or, wait… yes, actually the protocol is the same. We could easily exclude `.onion` sites by their TLD, but don't know about i2p…

**Comment by r4sas** [comment]
I2P has `.i2p` TLD.
