### ISSUE TITLE
I have read #599 but i have another question : " System Purge "

### ISSUE THREAD

**Issue by ZerooCool** [PrivateBin/PrivateBin#640]
Hello, i have read #599 but i have another question : " System Purge "

I looked on my side, very interested to see the purge mechanism.
I don't know when it actually happened, but today, following my tests yesterday, I can see that the messages created are no longer present.

On the other hand, there are always the two subfolders !!!
So, we always have a trace, with two useless files, that one day we will have to save! I find it a bit annoying, right?

Example:

/ data / ef / a2 / message

purge ok

/ data **/ ef / a2**

But, 2 folder become useless !

Another question :
As administrator of the server, is it possible or not to consult the contents of the messages?
The mechanism would like me not to be able to, especially if these are private messages.
Unless I can see the messages, unless there is a password?

How to manage messages that would be checked as never to be deleted?
What happens if a user copies the Larousse encyclopedia several times in a message and asks to keep the message? So, the solicity storage space will increase, without knowing what is actually stored by the users, and, why !? Can you provide more information on the method of administration?
Should you ban storage for life, to ensure that the message can one day be purged?

**Comment by whalehub** [comment]
@ZerooCool I have a cron job running on my server that deletes those empty leftover folders periodically. It looks like this:

```
find /srv/www/privatebin/data -type d -empty -delete
```

All messages saved with PrivateBin are encrypted in the browser on the client side, so the server owner cannot decrypt them to view their contents.

If you're worried about running out of storage space, I would suggest either setting the `sizelimit` option in your `conf.php` file to a low value or disabling the "Never" expiry option by changing

```
never = 0
```

to

```
; never = 0
```

in your `conf.php` file.

**Comment by ZerooCool** [comment]
Thank you for your reply.
I had just discovered this option, and, I replaced the storage for life with storage over 2 and 5 years.

I can only appreciate this security mechanism which respects privacy, but, once again, my concern is elsewhere, how can we do to malicious use, if several messages are created to our well, regularly, which will cause some form of pollution.

The day when the hundreds of dead kittens start to smell bad, it will probably be a little too late to hope to clean up.

Anyway, great project, thank you for sharing.

**Comment by elrido** [comment]
I guess this has been answered, here above and also [in the other thread](https://github.com/PrivateBin/PrivateBin/issues/599#issuecomment-647672556).

Additional details:
- there is a [traffic limiter](https://github.com/PrivateBin/PrivateBin/wiki/Configuration#trafficlimit) option, by default only one paste/comment per IP can be created every 10 seconds
- The [purge cycle](https://github.com/PrivateBin/PrivateBin/wiki/Configuration#purge) is controlled via another option - check the docs on some of its intricacies and adjust the values depending on the traffic you get on your instance. The relatively large privatebin.net demo instance still uses these defaults and seems to remain at a near constant 1 GiB of disk space and around 30k of pastes.
