### ISSUE TITLE
Opengraph not work for me with discordapp

### ISSUE THREAD

**Issue by ZerooCool** [PrivateBin/PrivateBin#645]
Opengraph not work for me with discordapp

I have only a description, but, in english, not in french.
I want have my description in french.

I don't see the logo.

#593

My link : 
https://privatebin.visionduweb.fr

**Comment by elrido** [comment]
This feature got merged into the development branch, but isn't released yet in 1.3.4. It will be in the next release.

Given that this only requires a small extension of the template, you could just add it to your own bootstrap.php file until that next release comes out:
https://github.com/PrivateBin/PrivateBin/blob/7e77b941580236862b1d979ca322d5357495271e/tpl/bootstrap.php#L85-L96

**Comment by ZerooCool** [comment]
@elrido 
Sorry, I think you're wrong?
It seems to me that this code is present, already currently.
Just check my instance:
privatebin.visionduweb.fr

You closed the issue too quickly. You can reopen. Thank you.

**Comment by elrido** [comment]
Can someone with access to discord please investigate this, provide screenshots and find documentation on what exactly they support so that we can adjust the headers accordingly? Thank you

**Comment by ZerooCool** [comment]
Close with #651 and PR #668
