### ISSUE TITLE
 Opengraph not work for me with Facebook

### ISSUE THREAD

**Issue by ZerooCool** [PrivateBin/PrivateBin#646]
Opengraph not work for me with Facebook

#593

URL non valable !
L’URL img/apple-touch-icon.png?1.3.4 de l’élément og :image n’était pas valide.

og:url | https://privatebin.visionduweb.fr/
OK !

og:title | Visionduweb - PrivateBin
OK !

og:description | Visit this link to see the note. Giving the URL to anyone allows them to access the note, too.
NOT OK ! KO ! The description is in English, but, i have translate it in french, and, i can't have my french description !

If i open my website privatebin, it's the french description in the source code.
If i test with facebook, i have the english version and no picture.
If i test on discord, i have the english version and no picture.

https://developers.facebook.com/tools/debug/?q=https%3A%2F%2Fprivatebin.visionduweb.fr

**Comment by ZerooCool** [comment]
cd PrivateBin

`grep -r name=\"twitter:image\" ./`

```
./tpl/page.php:		<meta name="twitter:image" content="img/apple-touch-icon.png?<?php echo rawurlencode($VERSION); ?>" />
./tpl/bootstrap.php:		<meta name="twitter:image" content="img/apple-touch-icon.png?<?php echo rawurlencode($VERSION); ?>" />
```

`grep -r property=\"og:image\" ./`

```
./tpl/page.php:		<meta property="og:image" content="img/apple-touch-icon.png?<?php echo rawurlencode($VERSION); ?>" />
./tpl/bootstrap.php:		<meta property="og:image" content="img/apple-touch-icon.png?<?php echo rawurlencode($VERSION); ?>" />
```

I remove :
`?<?php echo rawurlencode($VERSION); ?>`

... Test ...

**Comment by ZerooCool** [comment]
I tested with the online version of https://cpaste.org and there, no image even on Facebook.
Well, we should be able to do better!

Regarding the deletion of PHP code, I do not think it is useful to add a parameter after the image, to indicate the version of the image, yes, no?

If really, as much to name the logo, with the version of the image:
logo-version.ext

Despite everything, that would mean that the logo could evolve, out, I don't think that is the priority, and, the logo looks very well as well.
I therefore obtain the withdrawal of the version, following the opengraph images.

**Comment by elrido** [comment]
cpaste runs an older release and doesn't include the recently added opengraph extensions.

The version number being added is exactly a little trick you can use to ensure caches refresh the image when you change it. We use this as a mechanism to ensure that some of our unversioned files do get refreshed when the version is upgraded. You can use it with a custom, hardcoded number to try and circumvent the facebook cache and force it to refresh - also send it a different paste for every test.

And yes, the logo is probably not optimal for this use case - we tried to make use of one of the [existing assets](https://github.com/PrivateBin/assets) we had at our disposal. :-)

**Comment by ZerooCool** [comment]
#644 #655

**Comment by ZerooCool** [comment]
Use the url with a? generates an error in the Facebook control tool. It does not seem to me that it is necessary to operate in this way.

Yes indeed, the images are just not the right size, to allow the opengraph to function properly.
It was my next test.

**Comment by ZerooCool** [comment]
Following my tests, I used the image that at home works on my main site, and, it did not work. I thought about rights, but, I did not try to make them more permissive.

I also tested the Twitter Card validation tool, which informs me that the robots.txt prohibits the functioning of Twitter Card.

I did not want to bother, and, I passed the links in absolute, rather than relative, and, in this case, the opengraph image is correctly displayed, on Facebook, Twitter, Discord, Linkedin, ok.ru ... ...

In this case, we would have to obtain the official address for PrivateBin images, and give them in absolute URLs, either from Github or from the official privatebin information site.

**Comment by ZerooCool** [comment]
With **relative URL**, and, this code for the robots.txt, the image is not displayed.
On the other hand, the twitter validator will work, without alert due to the configuration of the robots file.

```
# Autoriser le robot Twitter :
User-agent: Twitterbot
Disallow:

Allow: /img
```

**Comment by ZerooCool** [comment]
surprisingly, other images such as the favicon image respond perfectly to demand, if the url is relative.

Despite everything, I find that it does not make sense to mix the two.
Perhaps it would be better to place all the entries coming from the META tags, with an absolute URL.

Thus, it would be necessary to add a variable, from the configuration file, which would be used to enter the domain name, and, thus, write the absolute URL address, in the files called from the META tags (images, files, css, js , json ...)

**Comment by ZerooCool** [comment]
For Twitter : 144x144px < 4096x4096px
For Facebook : 200x200px <

**Comment by ZerooCool** [comment]
With that, we can close this issue, and, open a new issue : 

Perhaps it would be better to place all the entries coming from the META tags, with an absolute URL.

Thus, it would be necessary to add a variable, from the configuration file, which would be used to enter the domain name, and, thus, write the absolute URL address, in the files called from the META tags (images, files, css, js , json ...)
