### ISSUE TITLE
Email button not working?

### ISSUE THREAD

**Issue by bkhanale** [PrivateBin/PrivateBin#648]
## Steps to reproduce

1. Just create a new paste at https://privatebin.net or https://paste.bhushan.codes
2. Try clicking at email button

### What happens
Nothing happens

### What should happen
Something should happen, I'm not sure what email does. But some mail template should pop up.

## Additional information
Also the case with my hosted instance https://paste.bhushan.codes

## Basic information

**Server address**: https://paste.bhushan.codes

**Server OS:** Ubuntu 18.04

**Webserver:** Nginx reverse proxy + latest docker image

**Browser:** Chrome 83.0.4103.97 (Official Build) (64-bit)

**PrivateBin version:** 1.3.4

I can reproduce this issue on <https://privatebin.net>: Yes

**Comment by r4sas** [comment]
Telepaths on vacation.
Use issue template and fill it correctly.

**Comment by bkhanale** [comment]
@r4sas Updated the issue.

**Comment by elrido** [comment]
Hi Bhushan,

Your service works and I do get the email when creating a paste on it and clicking that button.

What is supposed to happen is that a mailto: link gets generated, which should open your email applications composite view, if you have an email application installed, and have that configured in your browser or operating system as the target for mailto: links.

If nothing happens for you after clicking the button, you have no email client available or it isn't registered properly.

Obviously, we can't implement this function on the server side, as the server is not supposed to learn the key that is part of the URL of your paste.

Maybe try your service with a different device that has an email client installed, to confirm that it is working?

**Comment by bkhanale** [comment]
@elrido Thanks, it works as expected. Closing this now.
