### ISSUE TITLE
Email option has wrong expiry time formatting and another expiry time quirk

### ISSUE THREAD

**Issue by groovybluedog** [PrivateBin/PrivateBin#652]
###  Steps to reproduce

1. Create a paste
2. Click on the email button
3. When the email opens, the notice with the expiry time is incorrectly formatted

### What happens
The notice says:
"This link will expire after 23&#x2F;06&#x2F;2020, 12:05:00."

### What should happen
The notice should correctly display the date when it expires.

## Additional information

I also noticed that when you make a new paste, if you click the email link on the success page where the delete link is, the email generated does not include the expiry time. When I visit the link and then use the email option, it does. 

## Basic information

**Server address**: It is on a private website

**Server OS:** CentOS 7, a cPanel server with Apache

**Webserver:** Not sure what other info to put here other than PHP 7.4.7 and Apache 2.4.43

**Browser:** Firefox however this happened with Edge InPrivate too

**PrivateBin version:** The latest 1.3.4

I can reproduce this issue on <https://privatebin.net>: Affirmative.

**Comment by elrido** [comment]
AFAIK this makes use of the [`Date.toLocaleString()`](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleString) method:
https://github.com/PrivateBin/PrivateBin/blob/e35a26c9166d85b615a9c696c028a5cde95481c3/js/privatebin.js#L3835

This means that the format used depends on the localization setting of your browser. Try changing your browsers locale to one that matches your expected date format.

**Comment by groovybluedog** [comment]
Interesting. I tried to replicate this within Microsoft Edge and I can confirm Outlook opened from both my website and demo website with the correct date format.

However Firefox is set to English United Kingdom (en-gb), and although Edge doesn't confirm it is en-gb, it is set to the language of English United Kingdom too. How would this happen when both browsers are set to the same locale? Odd.

**Comment by elrido** [comment]
Well, it is indeed odd, but the exact format to use for each locale [isn't really standardized in ECMA Script](http://www.ecma-international.org/ecma-262/10.0/#sec-date.prototype.tolocaletimestring), so different JavaScript engines used in different browsers certainly can return different strings for the same locale and time.

**Comment by groovybluedog** [comment]
Interesting, thanks. Is this something that can be fixed? Otherwise maybe an option to disable it?

**Comment by elrido** [comment]
Yes, this can be fixed - by the browser in question. Alternatively, we would have to maintain our own formatting library for all supported localizations. Since this is a "nice to have", affects only some browsers and locales, I would consider this as a "won't fix" on our side. We should not re-invent the wheel, just because some cars come with lumpy wheels...

**Comment by groovybluedog** [comment]
An option to disable it would be useful then, for those of us who don't want people to encounter the potential formatting issue.
