### ISSUE TITLE
Page text for "provide password" and "could not decrypt" messages doesn't pull from my language file when the retry button does

### ISSUE THREAD

**Issue by ghost** [PrivateBin/PrivateBin#653]
## Steps to reproduce

1. I set up a language file and configured it. It works correctly with everything else.
2. Oen the json language file, and find the "waiting on user to provide a password" and "Could not decrypt data. Did you enter a wrong password? Retry with the button at the top." lines
3. Alter the 2nd pair of quotes to the desired language data
4. Create a paste, copy link, and paste the URL, making a slight adjustment to any part of the URL past the #, which I assume is the key
5. Get asked for a password (is this the correct behaviour anyway?)
6. Enter any password as it won't matter, the paste didn't originally have one and the link is wrong

### What happens
The website, with the cache cleared and no CDN, will continue to show the old language text and not the new text I provided within the language file, for both the password incorrect warning, and the waiting on the user to provide password notice in the background when the popup to enter the password is displayed.

### What should happen
The page should be displaying my edits correctly.

## Additional information

When I change the "Retry" text, the retry button does change on the page I describe, confirming it isn't an issue with file uploads or caching. The format of the file is correct too and all other translation/language changes show across the site.

## Basic information

**Server address**: It is on a private website

**Server OS:** CentOS 7, a cPanel server with Apache

**Webserver:** Not sure what other info to put here other than PHP 7.4.7 and Apache 2.4.43

**Browser:** Firefox however this happened with Edge InPrivate too

**PrivateBin version:** The latest 1.3.4

I can reproduce this issue on <https://privatebin.net>: Not applicable as I would need file access

**Comment by elrido** [comment]
I don't think we ever managed to repro this - When I work on the translations or add new message IDs, I frequently change the i18n files and after restarting the webserver and force-reloading the page in the browser the new/changed messages always show up.
