### ISSUE TITLE
Note for mass spam - Create a script for identify all creation for a sender via IP then delete all

### ISSUE THREAD

**Issue by ZerooCool** [PrivateBin/PrivateBin#654]
Note for mass spam - Create a script for identify all creation for a sender via IP then delete all

You would have to find the IPs that send lots of POST requests in the webserver logs and then correlate their request times with the paste creation dates.
>> Yes, it"s my mean.

Actually in that scenario it might be easiest to just delete any pastes created in a certain time frame in bulk.
>> Hum, Yes but, No. This solution can delete a good message.

**Comment by elrido** [comment]
Such a script would be specific to the webserver log format. I think that is way out of scope for this project. Certainly this is a problem that other server operators have encountered and you will find an answer to that in the community around your specific webserver.

In the scope of this project, we will not add any additional information that makes it simpler to track the creator into the pastes meta-data. We want to protect the users and store as little information as possible in the paste on the server. We also recommend to disable the webserver logs, if possible, to increase their privacy. Unfortunately, the reality is that a) many countries have laws forcing you to collect these log and b) as a user you have no mechanism to detect if a server logs or not.

**Comment by ZerooCool** [comment]
Ok.
