### ISSUE TITLE
Attached file cannot be downloaded on Google Chrome >= 83

### ISSUE THREAD

**Issue by Berbe** [PrivateBin/PrivateBin#655]
## Steps to reproduce
1. Use Google Chrome 83 or later
2. Try to downloaded file attached to a paste

### What happens
No downloaded is triggered.
An error message in the console saying *Download is disallowed.*

### What should happen
Download should trigger

## Additional information
Error message provides the following link: [Download in Sandboxed Iframes](https://www.chromestatus.com/feature/5706745674465280)

## Basic information
**Browser:** Google Chrome 83

**PrivateBin version:** 1.3.4

I can reproduce this issue on <https://privatebin.net>: No; File sharing ability required

**Comment by elrido** [comment]
Over in #634 we found a [workaround for this, using CSP-headers](https://github.com/PrivateBin/PrivateBin/issues/634#issuecomment-642149280).
