### ISSUE TITLE
MySQL Unknown Error in Where Clause When Deleting Row

### ISSUE THREAD

**Issue by joshcsullivan** [PrivateBin/PrivateBin#656]
## Steps to reproduce

1. Open database and table in MySQL, view table to get a dataid if you don't have one already.
2. Type `DELETE FROM privatebin_paste WHERE dataid=e235451c143b7f58;`

### What happens
`ERROR 1054 (42S22): Unknown column 'e235451c143b7f58' in 'where clause'`

### What should happen
`Query OK, 1 row affected (0.00 sec)`

## Additional information
If you change the command to run against the postdate with the correct post date for that paste, it queries correctly and deletes the row. I tried running it from the root mysql user and got the same error, so not a permissions issue. I've confirmed dataid is the primary key. 

## Basic information

**Server address**: N/A

**Server OS:** Ubuntu 18.04 LTS

**Webserver:** Apache/2.4.29 (Ubuntu)

**Browser:** N/A

**PrivateBin version:** v1.3.4

I can reproduce this issue on <https://privatebin.net>: No, no access to server.

**Comment by elrido** [comment]
This is a string, not an integer, that is used as a primary key. You need to enclose the string in quotes:

```sql
DELETE FROM privatebin_paste WHERE dataid='e235451c143b7f58';
```

**Comment by joshcsullivan** [comment]
That would do it, thanks!
