### ISSUE TITLE
Do we have documentation for the markdown that can be used

### ISSUE THREAD

**Issue by ZerooCool** [PrivateBin/PrivateBin#659]
Do we have documentation for the markdown that can be used

Use generator stackedit for exemple work : 
https://privatebin.visionduweb.fr/?26eb5915be175b64#3HwJbXya8Tiay4Lj25LGv9Kww3eBExM5T5FVL6t9c5JA

During my tests, I realized that **the syntax used by Mediawiki is not accepted at all**, except for the quote and the bullet.

> quote ok
* chip ok

For titles it does not pass from mediawiki:
= title =

Nor for the fat of mediawiki:
'''bold'''

Nor for mediawiki tables:
{|

| -
| A
|
|

| -
|
| B
|

| -
|
|
| C

|}

Should you integrate a link to a markdown generator?
(This advertises one service rather than another)

Should we suggest configuring the addition of a custom markdown generator from the configuration?
(With the opening of a link in a new window)

Not everyone knows how to use Markdown, it's very technical, not for everyone, especially if not trained in it. A generator allows you to immediately understand and test markdown.

Finally, for the use of privatebin, the preview in reality is useless or not much, except in the case of the use of Markdown.
So, making it easier to use Markdown would make sense ...
It's easier to use markdown, it understands, and therefore, its use just as it makes the preview of privatebin more relevant to use.

**Comment by ZerooCool** [comment]
I read, with slackedit.io : 

UML diagrams
You can render UML diagrams using Mermaid. For example, this will produce a sequence diagram.

Then it's obscur for me.

1095/5000
If on their side, it seems obvious to set up, I suppose it is less obvious to set up on a wiki, since, surely, it will depend on the wiki tool used, but, that it is surely even less obvious to set up on privatebin (which is not the primary objective, I understood correctly, the objective being to make the reading of messages to server administrators.)

Nevertheless, I open this note, because, if the mardown of mediawiki does not work, and, that we use the syntax that we find partially in stackedit.io, then, the question arises.

Otherwise, we can still use, propose, a less complex tool!
https://markdownlivepreview.com

There, no questioning, with UML diagrams, easy to use, quick to use ...

It should still be able to easily inform the user:
- What type of MArkdown?
- How to quickly and nicely edit Markdown?
- Use an external generator, failing to integrate it directly?
- Enhance the preview tool, which loses its usefulness otherwise.

**Comment by elrido** [comment]
Well, we are ~~lazy~~ very efficient and haven't re-invented the wheel. We use the showdown library - Please check their [syntax documentation](https://github.com/showdownjs/showdown/wiki/Showdown's-Markdown-syntax) for more details.

[Mermaid](https://mermaid-js.github.io/mermaid/): Sure, this could be added as an additional format. A pull request for this feature would be welcome.

**Comment by ZerooCool** [comment]
Ok for Mermaid, it was a simple question. I don't need it personally. I use Mediawiki and YUML.

Thanks for the link to the syntax that I will add to my wiki.
In the example of the documentation of the wiki syntax, I see that the markdown editor put forward is "http://demo.showdownjs.com/"

Here, following my questions, I think that the user need which is currently not correctly supplied, is the proper use of markdown, without having to use the documentation, to facilitate use.

As mentioned, it seems to me that the preview tab doesn't really make sense, except, if you are able to edit in markdown.

It seems obvious that we are not going to delete the preview, it would be a step back.

On the other hand, I think it would be important to offer the possibility of editing quickly in markdown.

I would not do PR to modify the code, but, I propose to integrate a link to a markdown editor. (Which one? Well, either http://demo.showdownjs.com/ to stay in compliance with the documentation, or, another, simpler, as I proposed earlier: https://markdownlivepreview.com )

One could imagine a link which would only appear when the choice of markdown format is selected, thus, the user could open a markdown editor, in a new window.
It is a minimalist approach, but one that avoids having to deal with more complex integration issues.

The best, on this minimized approach, would be to leave the choice to the administrator, to propose the Markdown integrator which suits him best, from the configuration options of PrivateBin.

**Comment by ZerooCool** [comment]
Write text with a Markdown editor : https://simplemde.com

A Markdown editor could be integrated, it looks good, except that it automatically saves messages.

it can also be interesting, since, if the objective is above all not to allow the administrator of the privatebin server to have access, according to the needs, we may want to write, and, not to lose his work along the way, however, it becomes counterproductive for the privatebin project.

On the other hand, a possible future integration, without the backup option, could be interesting.

**Comment by rugk** [comment]
Next time, please open a new issue for *each* idea/issue/bug you have, so they can be tracked separately.
Also, please mind to search for existing issues before opening a new issue for a feature or bug.
E.g. for Mermaid support **if** you think this is a useful addition. (Personally I'd consider this going into a feature creep trisection as we cannot support any Markdown extensions one may have written, but well… if there is community demand.)

Also, please mind to use the bug issue template when reporting bugs.

As the original question has been answered for this question.
