### ISSUE TITLE
Unable to read attached files

### ISSUE THREAD

**Issue by frnode** [PrivateBin/PrivateBin#663]
## Steps to reproduce

1. Create a privatebin with file (test.txt without content)
2. Consult privatebin

### What happens
When I consult the page containing the secure file, I have the following error displayed
` Failed to execute 'atob' on 'Window': The string to be decoded is not correctly encoded.`

The error probably comes from the file `/js/privatebin.js`

After performing other tests, I noticed that the problem appeared in the ".txt" file. But there is also another problem it is that for example if I put a type of document ".docx" I cannot download.

### What should happen
I should access the file

## Additional information

![image](https://user-images.githubusercontent.com/17091613/86131499-022d7780-bae6-11ea-9e85-8657739e8b52.png)

## Basic information

**Browser:** Google Chrome 83.0.4103.116 (64 bits)

**PrivateBin version:** 1.3.4

I can reproduce this issue on <https://privatebin.net>: No (no file upload)

**Comment by elrido** [comment]
I can reproduce this issue, but only when uploading an empty file. It seems an empty string is not considered a valid base64 encoding. The error gets thrown at:
https://github.com/PrivateBin/PrivateBin/blob/9914c37683496d161d9f8c8355bc89c358b1b243/js/privatebin.js#L2753-L2754

In addition I tested several other attachments types on Chrome, including an odt document, a PDF, a zip archive, a PNG image and an XCF image. None of these produced any error and they all downloaded fine and with no difference to the original (verified using sha256sum).

Something that I did noticed for the first time in chrome is the following console message:
```
Refused to load the image 'data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='24' height='24' viewBox='0 0 24 24'%3E%3Cpath d='M0 0h24v24H0z' fill='none'/%3E%3Cpath d='M19.35 10.04C18.67 6.59 15.64 4 12 4 9.11 4 6.6 5.64 5.35 8.04 2.34 8.36 0 10.91 0 14c0 3.31 2.69 6 6 6h13c2.76 0 5-2.24 5-5 0-2.64-2.05-4.78-4.65-4.96zM14 13v4h-4v-4H7l5-5 5 5h-3z'/%3E%3C/svg%3E' because it violates the following Content Security Policy directive: "img-src 'self' blob:".
```
That SVG gets injected onto the page, but isn't from our app, as far as I can tell. It would display the following icon, if rendered:
![chrome-svg](https://user-images.githubusercontent.com/1017622/86160796-93174980-bb0c-11ea-9832-8b6cf35ff90c.png)

**Comment by elrido** [comment]
The issue with empty files should be addressed with 0673c1c. Any additional information you can provide us for those other file formats? Is it possible that those issues occur on servers that haven't yet [updated their CSP for the new 'allow-download' policy that Chrome introduced and enforces as of version 83](https://github.com/PrivateBin/PrivateBin/issues/634#issuecomment-642149280)?

**Comment by r4sas** [comment]
We just need to check for zero-length of file size. Empty pdf, zip, etc. have headers which adds size and can produce valid base64, isn't it?

**Comment by frnode** [comment]
Hi, I checked this is the problem (empty file), it does not occur if the file has content so the problem should be solved with the correction you made.
And actually I added the "cspheader" and the download works now.

Thank you

**Comment by elrido** [comment]
Ok, and then I can thank you for reporting this issue to us.
