### ISSUE TITLE
Can we only add one files per message?

### ISSUE THREAD

**Issue by ZerooCool** [PrivateBin/PrivateBin#665]
Can we only add one files per message?

**Comment by r4sas** [comment]
Send just file without any text? - Yes.

**Comment by rugk** [comment]
Yes, one text part + one file. Just create multiple files if you need or place them in a ZIP: (note server admins often have file upload restrictions)

**Comment by ZerooCool** [comment]
Hello,
Not sure to understand, in addition to the use of the translator.
So the answer is "yes" only one file!?

I tested it with text, or, without text, and, it’s only one file, with my configuration.

Is there an option to deposit more files?

It seemed like I could have put two in, but now I can’t, so I guess I never should have put two in?

To create a sharing of two files, I have to create two different messages?

privatebin.visionduweb.fr

**Comment by r4sas** [comment]
Only one file per paste.

**Comment by Haocen** [comment]
Checkout https://github.com/psi-4ward/psitransfer
A very nice project with resumable upload built in, the only trade off is you won't get as strong privacy and security protection as privatebin.
I think some day I'll look into how mega does their in browser encryption for large files, maybe slicing files into small pieces and encrypt each chunk? But I would assume this will require a lot of development resources, meanwhile it seemed for really huge files you'll still need browser extension or native client.

**Comment by ZerooCool** [comment]
Ok, thank you for your answers, therefore, I understand that only one file is currently possible per message, unless there is an error in understanding.

The previous project seems indeed interesting.

Perhaps it would be necessary to open an exit, on their project, to propose an integration in privatebin, or at least, a reflection in this direction, with regard in particular to the confidentiality of the content from end to end, encryption, deletion , different elements.

I think I can close this post soon.
I am still awaiting your opinions, concerning the need to open a possible outcome on their project.

**Comment by Haocen** [comment]
I don't think a direct integration with PrivateBin would fall into the author's understanding of the scope of his project.
At the meantime my current way of sending large files with security and privacy in mind is as following:
1. Encrypt and sign the file, ideally compress it as well.
2. Upload it to Psitransfer.
3. Paste the link to the uploaded file along with the decrypt key, hash value in PrivateBin.
4. Send the paste to recipient.

You may automate this process to a certain level if you're willing to invest some effort.

**Comment by rugk** [comment]
This is off-topic, but in addition to the tools recommended already, maybe have a look at https://github.com/warner/magic-wormhole for transfering files securely.

PrivateBin is not mainly a file transfer service. It's a pastebin.
Also, so far, most of the users were satisfied with being able to attach only one file.
If you think this should be changed, please open a new issue **and explain the use case** when you need this feature etc.

So as it seems this question has been answered and I thus close this issue. If anyone has further questions on that topic, feel free to comment here, again.
