### ISSUE TITLE
No avatars (VizHash/Identicons) shown

### ISSUE THREAD

**Issue by rugk** [PrivateBin/PrivateBin#67]
## Steps to reproduce

0. Enable vizhash in the config (usually not necessary as it is enabled by default)
1. Comment and some pads.

### What happens
No avatars or other images are shown,

### What should happen
I think it is supposed to show some avatars (with vizhash) here. Note I executed it on my local device, so my IP is just `127.0.0.1`.

## Additional information

![noimage](https://cloud.githubusercontent.com/assets/11966684/17572450/e1efeb4c-5f54-11e6-93bd-2079211d1da0.png)

This might of course be fixed with https://github.com/PrivateBin/PrivateBin/pull/59, but I also had issues with the Identicons version there, but I commented there.

## Basic information

**Browser:** Firefox 48

**PrivateBin version:** bea9a577a67087feb9ce40b55d80c315b08009b7

**Comment by elrido** [comment]
This will be fixed by merging 3988b86.

**Comment by rugk** [comment]
Why do you think so? i mean even when switching top identicons the old VizHash (which are still offered) should work.

And no it does not work:
![identicons](https://cloud.githubusercontent.com/assets/11966684/17592833/29daa8ae-5fe4-11e6-9d6c-75b13bab79ee.png)

ca66653d0cbd16d1724d560a2c9ec872abb13339

And BTW: I also realize that this feature never worked, also with older versions of ZeroBin. (tested with 0.22) That's also the reason why I was so surprised to see this feature being used as I have never seen it.
Is anyone else experiencing this issue?

@elrido Could you probably provide a screenshot to show it should look?

**Comment by elrido** [comment]
Just to clarify: This feature worked well but stopped working before the CSP header was introduced that did forbid the data URI as an image source. It is possible that it did not work for you due to the missing GD library which caused vizhash to silently drop the icon generation.

You can test it e.g. on one of my installs at https://snip.dssr.ch (release 0.22) or https://zerobin-test.dssr.ch (some version of yesterday).

**Comment by rugk** [comment]
Ah, you're right. It really was the CSP and I just had to update my config file with the recent version.
