### ISSUE TITLE
Print this paste

### ISSUE THREAD

**Issue by Verdem-crypto** [PrivateBin/PrivateBin#672]
You have to add a print this paste button!

**Comment by rugk** [comment]
Just use your browser's print feature, could not you? (<kbd>Ctrl</kbd>+<kbd>P</kbd>)

See also the related issue https://github.com/PrivateBin/PrivateBin/issues/616.

So I'd say, we don't really need a button that anyway only triggers what you could do with a browser, anyway. If anyone has further questions on that topic, feel free to comment here, again.
