### ISSUE TITLE
Issue about private information

### ISSUE THREAD

**Issue by misterJames22** [PrivateBin/PrivateBin#673]

**Comment by r4sas** [comment]
You must contact with https://nopaste.xyz/ owner, not us. WHOIS domain service will help you.

**Comment by misterJames22** [comment]
Sorry for the confusion, it's because they was a link toward your repo i though it was link sorry.

**Comment by rugk** [comment]
Moderation note: I've deleted the old edit from the GitHub history, because it includes the URL to sensitive content that should likely not be spread further.
Next time, don't post such URLs publicly.
