### ISSUE TITLE
Error - Can't open a privatebin with Edge

### ISSUE THREAD

**Issue by ZerooCool** [PrivateBin/PrivateBin#676]
Error with Edge:
Creation of a privatebin from Firefox
Request for deletion after reading.
Adding a file.
No password.

Opening from Edge requires entering a password.

If I put a password, 123, unable to valid the password from Edge.

The subsequent attempt to read from Firefox indicates that the message has been burned.

Information: This version of Windows 10 has not been up to date for a few weeks.

**Comment by r4sas** [comment]
https://github.com/PrivateBin/PrivateBin/issues/468
