### ISSUE TITLE
Illegal action using your technology

### ISSUE THREAD

**Issue by Spinoza142** [PrivateBin/PrivateBin#678]
Illegal action using your technology

https://nopaste.xyz/ [Link removed]

Are you aware that your technology is being used to make libelous statements about thousands of people? This is strictly prohibited by law and you could be held responsible for public disclosure of this list, just like Facebook and Wordpress which were charged in court. I preferred to let you know before legal recourse is taken.

Best regards,

**Comment by r4sas** [comment]
See #673.

And again: please contact nopaste.xyz owner.

**Comment by elrido** [comment]
For the public record: No, we are not running that website and are not responsible for it. We don't operate like Facebook - they keep their software under lock and key and if you want to use it, you do that on the facebook.com domain and therefore they become responsible for content hosted there. With Wordpress it is more complex. Wordpress is responsible for content published on their domain, but their software is public, like PrivateBin, and anyone can host a site using these pieces of software. When hosted on third party domain, the holders of those domains remain fully responsible for the content on their site, not the group that produced the open source software. Anyone can use our software under the [license agreement](https://github.com/PrivateBin/PrivateBin/blob/master/LICENSE.md#license) and it clearly states that "In no event will the authors be held liable for any damages arising from the use of this software."
