### ISSUE TITLE
Docker deployment through Caprover issue

### ISSUE THREAD

**Issue by monkeydust** [PrivateBin/PrivateBin#679]
## Steps to reproduce

1. Using Caprover
2. Docker image deployment

### What happens

1. Image starts
2. I go to my url for privatebin 
3. Get NGINX 502 error

### What should happen

1. Expected to go into application

## Basic information
Public URL - http://privatebin.server.sawhney.cloud/

Logs:
$ sudo docker service logs srv-captain--privatebin --since 10m --follow
srv-captain--privatebin.1.qe9a9mr7fkmr@ip-172-26-1-135    | /
srv-captain--privatebin.1.knglaqax2bfq@ip-172-26-1-135    | [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
srv-captain--privatebin.1.knglaqax2bfq@ip-172-26-1-135    | s6-chown: fatal: unable to chown /var/run/s6/etc/services.d/php-fpm7/run: Operation not permitted
srv-captain--privatebin.1.knglaqax2bfq@ip-172-26-1-135    | s6-chown: fatal: unable to chown /var/run/s6/etc/services.d/nginx/run: Operation not permitted
srv-captain--privatebin.1.knglaqax2bfq@ip-172-26-1-135    | [s6-init] ensuring user provided files have correct perms...exited 0.
srv-captain--privatebin.1.knglaqax2bfq@ip-172-26-1-135    | [fix-attrs.d] applying ownership & permissions fixes...
srv-captain--privatebin.1.knglaqax2bfq@ip-172-26-1-135    | [fix-attrs.d] done.
srv-captain--privatebin.1.knglaqax2bfq@ip-172-26-1-135    | [cont-init.d] executing container initialization scripts...
srv-captain--privatebin.1.knglaqax2bfq@ip-172-26-1-135    | [cont-init.d] done.
srv-captain--privatebin.1.knglaqax2bfq@ip-172-26-1-135    | [services.d] starting services
srv-captain--privatebin.1.knglaqax2bfq@ip-172-26-1-135    | 2020/08/13 16:21:08 [warn] 181#181: the "user" directive makes sense only if the master process runs with super-user privileges, ignored in /etc/nginx/nginx.conf:2
srv-captain--privatebin.1.knglaqax2bfq@ip-172-26-1-135    | nginx: [warn] the "user" directive makes sense only if the master process runs with super-user privileges, ignored in /etc/nginx/nginx.conf:2
srv-captain--privatebin.1.knglaqax2bfq@ip-172-26-1-135    | [services.d] done.
srv-captain--privatebin.1.knglaqax2bfq@ip-172-26-1-135    | [13-Aug-2020 16:21:08] NOTICE: [pool www] 'user' directive is ignored when FPM is not running as root
srv-captain--privatebin.1.knglaqax2bfq@ip-172-26-1-135    | [13-Aug-2020 16:21:08] NOTICE: [pool www] 'user' directive is ignored when FPM is not running as root
srv-captain--privatebin.1.knglaqax2bfq@ip-172-26-1-135    | [13-Aug-2020 16:21:08] NOTICE: [pool www] 'group' directive is ignored when FPM is not running as root
srv-captain--privatebin.1.knglaqax2bfq@ip-172-26-1-135    | [13-Aug-2020 16:21:08] NOTICE: [pool www] 'group' directive is ignored when FPM is not running as root
srv-captain--privatebin.1.knglaqax2bfq@ip-172-26-1-135    | [13-Aug-2020 16:21:08] NOTICE: fpm is running, pid 182
srv-captain--privatebin.1.knglaqax2bfq@ip-172-26-1-135    | [13-Aug-2020 16:21:08] NOTICE: ready to handle connections

Txs in advance

**Comment by elrido** [comment]
The log shows the normal startup messages, but no logged requests. The 502 error indicates a "Bad Gateway".

Very likely your stack includes an nginx acting as load balancer or such in front of the privatebin container(s) and it can't reach the backend. Check to ensure that you have it forwarding to the port 8080 of the privatebin container(s) FQDN or IP(s) and that said port is getting exposed in your configuration. Checking the logs of the reverse proxy nginx container in front of the privatebin one may reveal what it tries to reach and why that fails.

**Comment by monkeydust** [comment]
Thanks, that worked, redirect to 8080 had to be put in place.
