### ISSUE TITLE
extra minute in This document will expire in

### ISSUE THREAD

**Issue by jsarenik** [PrivateBin/PrivateBin#684]
## Steps to reproduce

1. Create a new paste with 5 minutes expiration.
2. Open the paste and refresh as suggested below:
 2.1. Right after it is created it says: **This document will expire in 4 minutes.** — this is wrong as it will actually expire in 5 minutes…
 2.2. A minute goes by. Refresh. Now it says **This document will expire in 3 minutes**.
 2.3. Another minute goes by. Refresh. Now it says **This document will expire in 3 minutes**
 2.4. Another minute goes by. Refresh. Now it says **This document will expire in 3 minutes**
 2.5. Another minute goes by. Refresh. Now it says something like **This document will expire in 59 seconds.**
 2.6. Another minute goes by. The paste gets deleted.

### What happens

It lasted really 5 minutes altogether (as was originally intended), but the "minute" messages were misleading (1 minute off).

### What should happen

It should say **This document will expire in 5 minutes.** right after the paste with 5 minute expiration is created. If there is any offset (which was probably thought to add-up for the last minute second counter) it should be removed (or added if it is missing; sorry I did not look into the source).

## Basic information

**Server address**: https://bin.bublina.eu.org

**Server OS:** Linux

**Webserver:** busybox httpd

**Browser:** Not related, but Google Chrome 85.0.4183.83 

**PrivateBin version:** 1.3.4

I can reproduce this issue on <https://privatebin.net>: **Yes**

**Comment by elrido** [comment]
The time gets always rounded down to a whole number and no fractions need to be calculated:
https://github.com/PrivateBin/PrivateBin/blob/633ec4b199896afb5f62f43db45e426c7bd3bae6/js/privatebin.js#L291-L325

Benefit: The time left feels more "urgent" and it won't tell you 1 hour left if it's 59 minutes.
Downside: For the 5 minute paste you never get to see 5 minutes, as after the paste is saved it's already slightly less then 5 minutes left.

Can you describe a use case where a higher precision is actually needed (say hours and minutes or minutes and seconds)? IMHO most users just need to know the paste expires and roughly when, but not down to seconds precision. Maybe the wording could to be changed, say "This document will expire in _about_ x minutes"?

**Comment by jsarenik** [comment]
@elrido Thank you for explanation! I appreciate it a lot.
