### ISSUE TITLE
Deny downloads?

### ISSUE THREAD

**Issue by StifflersMoM69** [PrivateBin/PrivateBin#685]
When attachment is added (jpg) the file can be downloaded. 

Isnt there a way to deny downloading files for a specific type?
Or at all only allow specific types to upload?

Sry for asking here, but i cant find any informations about it.

**Comment by rugk** [comment]
Preventing downloads is never 100%ly technically possible.
Especially if you want to display a preview…

As such, I'd say adding such a feature would at most give a false sense of security and I'd not do that.
You have to trust the receiver of the files not to mangle with them.
PrivateBin protects against intermediaries , not the receiver.
