### ISSUE TITLE
sorry for asking this in here...

### ISSUE THREAD

**Issue by Dhanamerdeka** [PrivateBin/PrivateBin#686]
sorry for asking this on here.... but i want to help translate this...
to indonesia... are u need indonesian translasion or not?
if yes i can translate it :) since i love this lol

**Comment by rugk** [comment]
For sure, we always appreciate translations. See https://github.com/PrivateBin/PrivateBin/wiki/Translation for a howto.

So as it seems this question has been answered and I thus close this issue. If anyone has further questions on that topic, feel free to comment here, again.

**Comment by Dhanamerdeka** [comment]
umm 1 again...
how can i change _self to _blank for opening new url from private bin?

**Comment by rugk** [comment]
This should already be done (see https://github.com/PrivateBin/PrivateBin/issues/61) altghough there was a bug recently (see https://github.com/PrivateBin/PrivateBin/issues/451).
