### ISSUE TITLE
Ask

### ISSUE THREAD

**Issue by Dhanamerdeka** [PrivateBin/PrivateBin#687]
does this private bin have discord? i want to ask a lot of things....

some my question
1. if this private bin have admin panel? like for ads etc...?

**Comment by rugk** [comment]
> does this private bin have discord

No, it does not.
Please ask questions on GitHub here and look at the [FAQ](https://github.com/PrivateBin/PrivateBin/wiki/FAQ) etc.

> if this private bin have admin panel? like for ads etc...?

No, see all issues attached to the milestone [basic admin interface](https://github.com/PrivateBin/PrivateBin/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22basic+administration+interface%22).

Also please give your issues meaningful titles.

**Comment by ZerooCool** [comment]
I have create a discord non official : https://discord.gg/Ebtphj

**Comment by Dhanamerdeka** [comment]
i see that even don't use english
