### ISSUE TITLE
Hide password when entered for decryption

### ISSUE THREAD

**Issue by rugk** [PrivateBin/PrivateBin#69]
When you enter the password when _encrypting_ a paste it is hidden, but when you - on the other hand - enter the password for _decrypting_ a paste, it is shown as plain text.

I think we should also hide the password in the decryption dialog. As this currently is just an JavaScript popup we might have to create our own UI for this.

**Comment by Wikinaut** [comment]
See discussion about the problem that the '*encrypting*-password is (may be) prefilled on https://github.com/PrivateBin/PrivateBin/issues/118

**Comment by Wikinaut** [comment]
Solution: use self-written (PB) input routines for entering encryption and decryption passwords.

**Comment by rugk** [comment]
@aldem commented about this issue from #134:

> By the way, coming back to "stupid, inresponsible way" - well, issue #69 clearly demonstrates what is really "irresponsible" - couple of my recipients already asked me "Are you sure this is secure?" when tried to access my links - not counting the fact that this makes impression that the whole thing is unprofessional (while this is not true).

**Comment by rugk** [comment]
@aldem Interesting experience. This pushes the importance of this issue a bit. However it is just technically difficult to do it right now. If you've any ideas or - even better - PRs, we would appreciate them very much.

**Comment by aldem** [comment]
Where exactly is the difficulty? Regular input field is used on encryption, what makes it more difficult on decryption?

**Comment by rugk** [comment]
The issue is we use a default JavaScript popup and this must appear before any JS can try and fire decryption. So basically we would have to implement an own "password UI", which is shown before the decryption is tried.
That's certainly possible, but harder than just using build-in Javascript functions.

**Comment by aldem** [comment]
OK, seems that I have the solution. Preliminary, but it works. I will prepare PR.
