### ISSUE TITLE
Plain-text: Return button & raw markdown

### ISSUE THREAD

**Issue by elrido** [PrivateBin/PrivateBin#7]
@rugk:

It would be nice to have a return button in plain-text view, so that you can get the "normal" view back after you clicked on "plain-text".
Alternatively you may also make it possible to use the back button of the browser - this would even be more intuitive.

---

@nitmir:

But if you add a button, it is no more plain-text. The plain-text view is handy because you can select all (ctrl-a) to get the content of the paste.
Using the back button of the browser would be nice though.

---

@rugk:

> But if you add a button, it is no more plain-text. The plain-text view is handy because you can select all (ctrl-a) to get the content of the paste.

Mhh that's true. But IMO it is not a "real" plain-text view anyway as it still renders markdown e.g. A real, plain-text view would be to show the raw markdown file.

---

@nitmir:

Ah I never noticed. I agree that plain-text should show the source markdown and not the rendered part.

---

@rugk:

So what about this issue?

Essentially it seems to be two issue now:
1) Do not render markdown when showing markdown source.
2) Allow browser back button (or a custom button) for switching back

**Comment by rugk** [comment]
As for this the History API:
> Alternatively you may also make it possible to use the back button of the browser - this would even be more intuitive.

Basically `history.pushState` can be used. If older browsers need to be supported [you may want to use this JS lib](https://github.com/browserstate/history.js).

**Comment by rugk** [comment]
I split the rendering issue into a new issue (https://github.com/PrivateBin/PrivateBin/issues/63), so taht this issue really only is about the back button now.

**Comment by elrido** [comment]
I noticed that `history.pushState` was already in use for the clone button to work. And I inserted a comment on why `text/html` is used instead of `text/plain` without `<pre>` tags. I had tried to change it and encountered the bug while testing.
