### ISSUE TITLE
Space-only passwords handled incorrectly

### ISSUE THREAD

**Issue by rugk** [PrivateBin/PrivateBin#71]
## Steps to reproduce

1. Put only spaces into the password box.
2. Click on Send and access the pad.

### What happens
Password is ignored and bin can be accessed without password.

I think the reason is just that the passwords are somehow trimmed. However ` x `, `   x` and `x   ` do work correctly. Note: Markdown trims this passwords mentioned here, so only `x` is show. Look into the source to see what I mean.

### What should happen
Encrypt bin with ` ` and request password.

## Basic information

**Browser:** Firefox 48

**PrivateBin version:** 6cb7454d07dc0f79c2861f8c762460132c7eb539

**Comment by elrido** [comment]
This is explicitly introduced behaviour to avoid the issues if somebody accidentally entered something in the password without realizing. Check the old issue for that at https://github.com/elrido/ZeroBin/issues/69.

Closing this as a "wont fix".

**Comment by rugk** [comment]
Okay, so it is okay if you want to disallow space-only passwords. However even in this case this is still an UX bug.

So let's make a new "expected behaviour":

### What happens
Password with only whitespace are ignored and bin can be accessed without password.

This is bas as users who really might to use only spaces as a password as they think the pad used a password, but *after* sending it to a friend, this person does not have to enter any password.

BTW: One cannot really put characters into the password box **accidentally** as they are shown as a big black circle.

### What should happen
Show an error message such as "You cannot use spaces only as a password. Please use another password." and do not upload the bin.

Therefore - with a different goal now - I am reopening this issue.
