### ISSUE TITLE
Generate paste url with different hostname

### ISSUE THREAD

**Issue by itz-sudo** [PrivateBin/PrivateBin#714]
Is there a way to define another host name in generated paste URL? Lets say I have two web server. Both are using same data file. But one is to generate url (read & write mode) and other one is to view generated url (view mode).

**Comment by rugk** [comment]
Hi,
so you want two PrivateBin instances where only one is writable(?).
Does this question from the FAQ help?
[How can I link to a read-only mode where users can't submit pastes?](https://github.com/PrivateBin/PrivateBin/wiki/FAQ#how-can-i-link-to-a-read-only-mode-where-users-cant-submit-pastes)

**Comment by itz-sudo** [comment]
Yes. this helps me. I have followed method 3 here. I want one instance as writable and other one as only readable. 
Assume,
**writable instance: privatebin1.example.com
readable instance: privatebin2.example.com**
Both instance having same data file. 
So when I create secrets in writable instance, I want paste url `hostname` generated as `Your paste is https://privatebin2.example.com/?34e690c06c32c67f#CFSuW9MkJeED7iYegz2Xm7m6XZqkygxw3EfnWm8e4pbP (Hit [Ctrl]+[c] to copy)`
Is it possible?

**Comment by itz-sudo** [comment]
waiting for the reply. Is this possible?

**Comment by rugk** [comment]
So what, you just want to change the hostname?
Well… you would need to adjust the JS for that, I guess.

Currently it is not.

**Comment by itz-sudo** [comment]
Alright, Thanks.
