### ISSUE TITLE
Remove because ignorance is bliss tagline

### ISSUE THREAD

**Issue by haynes11** [PrivateBin/PrivateBin#717]
## Steps to reproduce

1.  Hashed out "Because ignorance is bliss" motto line in PrivateBin/tpl/page.php 

### What happens

It still shows the motto

### What should happen

It should no longer show this. I want to keep this site very minimal (I've kept a "Powered by privatebin" credit) -  I want to remove the "Because Ignorance is bliss" tagine and the version number

Thanks,

**Comment by elrido** [comment]
In your `cfg/conf.php` (if you have one) did you set the [`template` configuration to `page`](https://github.com/PrivateBin/PrivateBin/wiki/Configuration#template)? If not set, it will use default on using the `bootstrap` template file.

**Comment by haynes11** [comment]
Hi elrido,

I set it to page but then that shows the old style blue type theme? How do I edit the bootstrap template so I can use that one with my modifications?

Thanks,

**Comment by elrido** [comment]
Sorry, I might be misunderstanding your question. If you want to preserve the original, for later upgrades, check the wiki for more details on [creating templates](https://github.com/PrivateBin/PrivateBin/wiki/Templates#creating-templates).

**Comment by rugk** [comment]
Indeed, `page` is the old style template and `bootstrap` the new one, so you may want to edit that…
So as it seems this question has been answered and I thus close this issue. If anyone has further questions on that topic, feel free to comment here, again.

**Comment by wivaku** [comment]
in general: is it possible to make the visibility of the tagline configurable?
The initial reaction from users has been that they don't trust the system because of the word _ignorance_.
I want to use the original template (don't want to make my own duplicate), and in the config specify if the tagline should be shown.

**Comment by rugk** [comment]
You need to edit the template for that other the translation file, though the latter only works for non-English translations. See #802 / #514

**Comment by wivaku** [comment]
Yes, can be edited in the template, but the request was to make it configurable so it's not necessary to create my own duplicate (and keep it up to date in case the template changes). 

BTW my attempts to duplicate + change the template have not been successful. I'll take another look at the links you shared.

**Comment by rugk** [comment]
> Yes, can be edited in the template, but the request was to make it configurable so it's not necessary to create my own duplicate (and keep it up to date in case the template changes).

This is a valid feature request and I can totally see how annoying it is to duplicate a template file just to change such a minor thing.
As such, I guess, however, this is covered by https://github.com/PrivateBin/PrivateBin/issues/514. If the (English) language file is editable and it is included there it should be adjustable.

This is also related to https://github.com/PrivateBin/PrivateBin/issues/540 and https://github.com/PrivateBin/PrivateBin/issues/639

**Comment by wrench12435678** [comment]
Having this configurable in the conf.php would be helpful
Personally on docker I still can't get a modified bootstrap php to load (infinite loading) or a modified language file (blank page)

**Comment by elrido** [comment]
Are you using the bootstrap.php as shipped in the [1.3.5 release](https://github.com/PrivateBin/PrivateBin/releases/tag/1.3.5) matching your container image? If you use the latest one, it won't have the matching hashes.

**Comment by wrench12435678** [comment]
> Are you using the bootstrap.php as shipped in the [1.3.5 release](https://github.com/PrivateBin/PrivateBin/releases/tag/1.3.5) matching your container image? If you use the latest one, it won't have the matching hashes.

I feel like an idiot, I was trying to find the last commit before the 1.3.5 release for the bootstrap.....when I could of just grabbed the source code zip from releases 🤦‍♂️
Now I have the correct one it all works
Thanks for the help :)
