### ISSUE TITLE
CSS tweaks needed: checkbox controls and labels misaligned on top line

### ISSUE THREAD

**Issue by DalekDave** [PrivateBin/PrivateBin#724]
Thank you for your work on Privatebin. :-)
Below is a *trivial* bug/suggestion. But perfection is perfection, right? ;-)

In the top line of my Privatebin instance, on the top line, the checkboxes, other controls and the labels are not properly aligned perfectly horizontally centered. 

You can see this in the screenshot below: 

![Screenshot_20201129_183132](https://user-images.githubusercontent.com/64964084/100547918-226a8980-3272-11eb-84bb-7a6cf2917243.png)

This stops me sleeping properly at night. Please could you fix it?
Thank you very much if so. :-D

**Comment by rugk** [comment]
I see no real issue in your screenshot. However, if you want to contribute a pixel-perfect fix, feel free to create a PR…
It should be just a small CSS patch.

**Comment by elrido** [comment]
Obsoleted by the bootstrap5 template, unfortunately.
