### ISSUE TITLE
Feature request: deminifier/unminifier to unminify uploaded/pasted file

### ISSUE THREAD

**Issue by DalekDave** [PrivateBin/PrivateBin#726]
This is a feature request for a deminifier/unminifier functionality to be built into Privatebin for unminifying (and reminifying?) files uploaded to or pasted into Privatebin.

What do you think?

**Comment by r4sas** [comment]
Out of project scope.

**Comment by rugk** [comment]
Indeed, just use our own web or local minifier for JSON or whatever file typo you want to minify.
Note it also does not save space, as the paste content is already compressed. As such, minifying just makes it less readable and when third-party clients read the paste they likely do not unminify it.
