### ISSUE TITLE
privatebin docker behind nginx reverse proxy does not load css and js

### ISSUE THREAD

**Issue by addy5001** [PrivateBin/PrivateBin#727]
## Steps to reproduce

1. Install nginx and use it as the reverse proxy for privatebin docker container to set up HTTPS
2. conf file for nginx: 
```
    location /private-bin/ {
        proxy_pass http://localhost:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
```
3. When I hit the link localhost/private-bin, plain HTML is loaded without CSS or JS. Buttons don't work and can't see any images.  

### What happens
When I hit the link localhost/private-bin, plain HTML is loaded without CSS or JS. Buttons don't work and can't see any images.  

### What should happen
Should load with JS and CSS like how its loaded if I hit the internal endpoint directly

## Basic information

**Server address**:

**Server OS:**

**Webserver:**

**Browser:**

**PrivateBin version:**

I can reproduce this issue on <https://privatebin.net>: Yes / No

**Comment by addy5001** [comment]
What is the configuration required for loading PrivateBin as it is through the nginx reverse proxy?

**Comment by rugk** [comment]
That seems to be an issue of your setup. Does it work without a reverse proxy? Here you can e.g. see the configuration used in our Docker image: 
https://github.com/PrivateBin/docker-nginx-fpm-alpine/blob/master/etc/nginx/sites-available/site.conf

Everything else should just be the standard setup. See the installation guide: https://github.com/PrivateBin/PrivateBin/blob/master/INSTALL.md

**Comment by elrido** [comment]
privatebin.net uses the container image with an nginx reverse proxy as well, but it doesn't use a subdirectory, so it's config looks similar to your example.
https://github.com/PrivateBin/privatebin.info-pelican/blob/d41baaa143bab6beae9978fd6d9bfa2b3b75fd2f/nginx.conf#L166-L175

If you want to map it to a subdirectory in the `location`, you probably have to normalize the path:
```
        proxy_pass http://localhost:8080/;
```
Note the slash at the end. It will replace your location `/private-bin/` with `/` in the requests sent to service behind the proxy. The container doesn't have anything to present when it gets asked for a CSS file at `/private-bin/css/` - with the mapping the path should get forwarded as `/css/`.

Quoting the [nginx docs](http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_pass) on the subject:
> If the proxy_pass directive is specified with a URI, then when a request is passed to the server, the part of a normalized request URI matching the location is replaced by a URI specified in the directive:
> 
> ```
>     location /name/ {
>         proxy_pass http://127.0.0.1/remote/;
>     }
> ```

This is an nginx specific behaviour and it will be the same with other applications that get mapped to paths on a virtual host. Other reverse proxies handle this in their own ways, so I would consider documenting all the possible reverse proxy configurations for the many different products as out of scope for the container image documentation.

**Comment by rugk** [comment]
So as it seems this question has been answered and I thus close this issue. If anyone has further questions on that topic, feel free to comment here, again.

**Comment by addy5001** [comment]
@elrido Thank you for the tip on the trailing slash "/". I had missed that on my proxy_pass directive. That worked 👍 
Thanks @rugk
