### ISSUE TITLE
Upgrade Bootstrap to v4 or higher

### ISSUE THREAD

**Issue by fynks** [PrivateBin/PrivateBin#728]
Bootstrap is going to release the version 5 while this app is still suing version 3.4.1.Since bootstrap is showing more performance gains by dropping jquery and other visual improvements.So why we are not embracing these improvements?

## Steps to reproduce
1.Go to css folder of project.
2.And see version number of bootsrap.

### What happens
Bootstrap 3.4.1 is being used

### What should happen
At least version 4.X should be used.

## Additional information
not applies here

## Basic information
not applies here

**PrivateBin version:** git-main-brnch

I can reproduce this issue on <https://privatebin.net>: Yes

**Comment by elrido** [comment]
When I last looked at upgrading to bootstrap 4, they advertised the imminent release of 5, so I held back on it, thinking to revisit the upgrade when they'd have released the new version - this was about a year ago and 5 is still in beta. Before the next release of PrivateBin I'll check again and if 5 isn't released, will consider upgrading the existing bootstrap template to 4 instead of 5. When I worked on the [PrivateBin directory](https://github.com/PrivateBin/Directory) app, I used bootstrap 4 on it and it seemed pretty close to version 3. We don't do anything complex, mainly use it for the top navigation bar and buttons with icons. It would be nice if we could avoid to have to upgrade the template twice.

**Comment by HenriGourgue** [comment]
I would like to work on this as my first contribution, is it open?

**Comment by elrido** [comment]
Absolutely, go for it! They now have a beta of bootstrap 5 published, so it might be worth to look at that instead of their version 4.

**Comment by elrido** [comment]
FYI, I've started work on this in a branch called `bootstrap5`.

current status (as of 7565be8ed5f7f4a19bd16a180f870ec05bd08163):
- renders without PHP errors & passes unit tests
- displays pastes
- responsive navbar
- right-to-left support
- auto dark mode with toggle

to be done:
- add "Dark Mode" to translation strings
- ensure that selecting dark mode also switches the prettify theme (source code formatter, the default one is unreadable in dark mode) - this may require a reload if we can't switch the `<link />` tags href-property on the fly from JS
- get expiration and format selections to work
- fix modals (password, QR-code, etc.)
- replace glyphicons with Bootstrap Icons (no longer included)
- test all the different settings and combinations
- check tab alignment in HTML source

My goal would be to add this as a new template option called `bootstrap5`, while for now `bootstrap` remains the default. This lets us add it into a point release without having to declare it a major or minor change. Also gives us time to prepare a matching pelican template for our project site and update the directory from bootstrap 5.2 to 5.3 as well, so they could all be switched at the same time.

I'm not sure if I'll add the variants (`-page` & `-compact`) and will want to drop the manual dark mode selection. This should be a user preference and in the above work it already automatically detects the browsers preference, but lets you change it with a toggle (same logic and looks as on the directory, though 5.3 now includes a dark theme).

Here below are some previews:

![bootstrap5 light-mode](https://github.com/PrivateBin/PrivateBin/assets/1017622/9bb9d8ec-b696-4167-b595-8d34d90030fa)

![bootstrap5 dark-mode](https://github.com/PrivateBin/PrivateBin/assets/1017622/dc44b8d3-54c9-42aa-a1a0-44a1c1eea239)

![bootstrap5 responsive](https://github.com/PrivateBin/PrivateBin/assets/1017622/e393b8a5-f6d0-462a-a463-0289ec53b0c0)

**Comment by elrido** [comment]
current status (as of 491ed9a52143b4d341882d1b4aa8446aec15d54a):
- got expiration and format selections to work
- fixed modals (password, QR-code, etc.)
- replaced glyphicons with Bootstrap icons (needs CSP relaxation to work, added a note to conf.sample.php on it, but left it as is for now - won't load the inline-SVG without it, but we seem to need that approach for the SVG fill color to be takenfrom CSS, for dark mode to work)
- tested the different settings and combinations
- got editor tabs to change active status

to be done:
- add "Dark Mode" to translation strings
- ensure that selecting dark mode also switches the prettify theme (source code formatter, the default one is unreadable in dark mode)
- check tab alignment in HTML source
