### ISSUE TITLE
Media-query width should depend on what site is shown

### ISSUE THREAD

**Issue by rugk** [PrivateBin/PrivateBin#73]
It is just silly to see two buttons here, when there is enough space to show them inline:

![widthdependent](https://cloud.githubusercontent.com/assets/11966684/17596390/72ed5e26-5ff1-11e6-9be3-22fca88f26c6.png)

For the "create page" site this may be okay, but when you only view a page there are fewer buttons, so you are able to show them inline.

**Comment by elrido** [comment]
This is an issue on intermediate screen sizes (tablets). We just use the bootstrap library, please notify them about it.
