### ISSUE TITLE
Version 1.2 supported Internet Explorer versions?

### ISSUE THREAD

**Issue by techboyg5** [PrivateBin/PrivateBin#734]
PrivateBin 1.3 uses the Web Crypto API which isn't supported in any version of Internet Explorer.

But what about PrivateBin 1.2? Which Internet Explorer versions does it support?

**Comment by elrido** [comment]
I assume only 10 and 11, as we used to have a dedicated error message just for IE < 10 in 1.2:

https://github.com/PrivateBin/PrivateBin/blob/91e50382421befb4734d5f209a0059c94657db04/tpl/bootstrap.php#L79-L81

**Comment by techboyg5** [comment]
> I assume only 10 and 11, as we used to have a dedicated error message just for IE < 10 in 1.2:
> 
> https://github.com/PrivateBin/PrivateBin/blob/91e50382421befb4734d5f209a0059c94657db04/tpl/bootstrap.php#L79-L81

What important browser features does 1.2 use?

**Comment by rugk** [comment]
Currently, we do not have a release plan. However, v1.3 e.g. also does not support the old Edge versions anymore, see #468.
We also have never committed to maintain v1.2, we just backported the security fix at that release time.

For now we do not have any plan to maintain and old version and personally I'd always recommend to use the latest version, also so you can use the latest features.
