### ISSUE TITLE
Protect paste creation ?

### ISSUE THREAD

**Issue by jpsarda** [PrivateBin/PrivateBin#736]
Is there an option to protect paste creation with a password ? Typically I would like to be the only one to be able to send pastes.

**Comment by rugk** [comment]
Does [this FAQ question](https://github.com/PrivateBin/PrivateBin/wiki/FAQ#how-can-i-link-to-a-read-only-mode-where-users-cant-submit-pastes) answer your question?
If not, please comment on why. If so, feel free to improve the FAQ and make it more clear, in case that was an issue.

I consider this question as answered and thus close this issue. If anyone has further questions on that topic, feel free to comment here, again.
