### ISSUE TITLE
How hide version? + little bug

### ISSUE THREAD

**Issue by Leproide** [PrivateBin/PrivateBin#738]
Hi!
How i can hide the PrivateBin Version from the footer? I hate tell to the users the version i run.
I can see a little bug, with nginx in the home i see `<i>in browser</i>` and not the cursive.

**Comment by elrido** [comment]
Feel free to remove it from and generally change the template to your hearts content:
https://github.com/PrivateBin/PrivateBin/blob/b38ebc503ea0843a5930b684eba5cbbdc057c90d/tpl/bootstrap.php#L579

**Comment by Leproide** [comment]
Tnx :)

**Comment by rugk** [comment]
So as it seems this question has been answered and I thus close this issue. If anyone has further questions on that topic, feel free to comment here, again.

As for the bug, please create a new issue and describe it in detail. A screenshot may help. Or, as it may be easy to fix if it is just an HTML tag missing, just submit a PR. :smiley:
