### ISSUE TITLE
SJCL use - scrutinization

### ISSUE THREAD

**Issue by rugk** [PrivateBin/PrivateBin#74]
Currently we [hash](https://github.com/PrivateBin/PrivateBin/blob/master/js/privatebin.js#L500) the user-provided password with SHA-256 and converts it to hex. This try to improve the strength of the password may be bad as it creates a new - untested - algorithm and may only make it worse. That's the reason why you should not [home-brew](https://security.stackexchange.com/questions/25585/is-my-developers-home-brew-password-security-right-or-wrong-and-why) algorithms by combining them which can lead to unespected results.
I always like [this example here](https://security.stackexchange.com/questions/33531/why-improvising-your-own-hash-function-out-of-existing-hash-functions-is-so-bad#answer-33550) where bcrypt and scrypt (two secure hash functions) are combined:

> Another potential issue with combining bcrypt and scrypt like this is that there has been very little study into how the two interact. As such, we don't know if there are any weird cases that can cause problems. As a more obvious example, take the one time pad. We compute c=m^k for some message m and some equally long perfectly random key k, and we get perfect security. So let's do it twice, for even more security! That gives us c=m^k^k... oh, wait, that just gives us m. So because we didn't take the time to properly understand how the internals of the system worked, we ended up with a real security vulnerability. Obviously it's more complicated in the case of KDFs, but the same principle applies.

So I wonder whether sjcl does not already stretch and/or hash the password internally, so that this hashing is actually insecure or at least useless.

**Comment by rugk** [comment]
I have asked the SJCL devs now about this: https://github.com/bitwiseshiftleft/sjcl/issues/313

**Comment by elrido** [comment]
The random unique key of the paste (the one in the URL is generated [like this](https://github.com/PrivateBin/PrivateBin/blob/addb666a235872cf11ebe0ade20d5dd48c6d5ec6/js/privatebin.js#L996):

    sjcl.codec.base64.fromBits(sjcl.random.randomWords(8, 0), 0)

While the plain text password is done like this:

   sjcl.codec.hex.fromBits(sjcl.hash.sha256.hash(password))

The [encrypt](http://bitwiseshiftleft.github.io/sjcl/doc/symbols/sjcl.json.html#.encrypt) method expects as the password parameter either a string, which is then internally generated into a 128 or 256 bit key (thats the bit part in the "256 bit AES" encryption) [using PBKDF2 key derivation](https://github.com/bitwiseshiftleft/sjcl/blob/master/core/convenience.js#L48).

To avoid any unexpected side effects, we could move towards a call like this (putting it all next to each other just to illustrate):

    var key = sjcl.random.randomWords(8, 0); // the random bytes without the base64 encoding
    var password = this.passwordInput.val(); // the non hashed string the user has typed in
    return = sjcl.encrypt(key + password, this.compress(message), options); // only concatenate them

I do not think the current implementation is a risk and changing it as illustrated above would be a very breaking change. All previously encrypted pastes could no longer be decrypted. To avoid this we would need to introduce a version marker into the pastes and then decrypt them accordingly. That would increase the code complexity quite significantly and would therefore introduce quite some risks on its own.

**Comment by rugk** [comment]
See the answer by @Nilos from SJCL:
> If you call sjcl.encrypt, it will use pbkdf2 to generate a key out of the password provided (in your case key + hex(sha256(password)). You could thus simply concat the key and the password.

So he suggested the same as you said. Now we just have to evaluate whether it is worth to do so and I certainly thing yes. Some reasons:

* Yes the act of introducing a version number in the saved JSON increases code complexity, but I think this is something, which is long overdue. One could expect that the en/decryption algorithm may change in the future and could have built-in this from the beginning. So as the stuff was not designed like this, we may have to do it now. At least it is a change, which might be required in the future anyway, so whether we implement it now or later does not matter.
* The act of changing the encryption and decryption algorithm itself should actually decrease the code complexity and as this is the riskiest part of all that JS, I am quite certain the risk would be lowered.
* I think we should let as much things as we can be handled by trusted third-party libraries as self-baking cryptographic things can only be bad.

**Comment by rugk** [comment]
The final statement from Nilos is:
> Both ways should be equally fine as far as I can see it.

So, @elrido, you can decide whether you want to change this. You know my arguments.

**Comment by elrido** [comment]
Ok, so as far as we and experts on the library can tell, there is no know risk in the way we do it now. There is a possibility for a risk of unknown proportion (could also be non-existent) in how we do it and this could be mitigated with a major change.

Since this involves a major breaking change in the paste format I would rather like to combine this with a general rethinking of the paste format. If we want to change it, this might be the opportunity to check for other parts that could be improved as well. I'll create a separate milestone for this, but it will certainly not be part of this release.

**Comment by rugk** [comment]
Would it help for a future re-design if we at least introduce the version number right now (without reading this number, just saving it)?

However this issue may of course soon become obsolete if we switch to WebCrypto APIs of browsers (https://github.com/PrivateBin/PrivateBin/issues/28).

**Comment by elrido** [comment]
If we don't use the number, no. Also we might later reconsider the way we implemented the version and then we remove it again and add it properly.

First we should have a proper design of the paste format in mind. For this it probably is helpful to first do a prototype with the webcrypto stuff and then compare the needed data we want to store in the three cases and can then standardize on one solid format including version.
