### ISSUE TITLE
Need Help to recover text after Burn

### ISSUE THREAD

**Issue by OusamaK** [PrivateBin/PrivateBin#740]
I got my account password in the link from PrivateBin. The settings were set on Burn After Read. I accidently refreshed the page by hitting F5. Now I can't reach the IT Admin as he is on vacation and have no way to contact him. Is it possible to still get my password? I read that it can be recovered as the "key" is in URL. 

Any Suggestion would be very helpful.

**Comment by elrido** [comment]
The point of the burn-after-reading-function is to delete the document after displaying it exactly once - it would be a bug if this were not the case. So the key is of course in the URL you got, but the document you try to decrypt with it does no longer exist. There is nothing you or anyone else can do and a new link needs to be created. Surely the IT department in question has a backup for the admin?

**Comment by rugk** [comment]
Yeah, it needs to be sent to you again.
So as it seems this question has been answered and I thus close this issue. If anyone has further questions on that topic, feel free to comment here, again.
