### ISSUE TITLE
(SRI Error) None of the "sha512" hashes in the integrity attribute match the content of the subresource.

### ISSUE THREAD

**Issue by saqeria** [PrivateBin/PrivateBin#745]
## Steps to reproduce

1. Install all required dependencies.
2. Git clone https://github.com/PrivateBin/PrivateBin.git (In webroot directory and rename to paste)
3. Go to domain.ltd/paste

### What happens
Javascript and CSS is not being loaded. When opening console in firefox I can see the following errors:
```
GEThttps://xcherry.tech/paste/css/bootstrap/bootstrap-3.4.1.css
[HTTP/2 403 Forbidden 7ms]

GEThttps://xcherry.tech/paste/css/bootstrap/bootstrap-theme-3.4.1.css
[HTTP/2 403 Forbidden 7ms]

GEThttps://xcherry.tech/paste/css/bootstrap/privatebin.css?1.3.4
[HTTP/2 403 Forbidden 10ms]

GEThttps://xcherry.tech/paste/css/prettify/prettify.css?1.3.4
[HTTP/2 403 Forbidden 12ms]

GEThttps://xcherry.tech/paste/js/jquery-3.4.1.js
[HTTP/2 403 Forbidden 12ms]

GEThttps://xcherry.tech/paste/js/zlib-1.2.11.js
[HTTP/2 403 Forbidden 13ms]

GEThttps://xcherry.tech/paste/js/base-x-3.0.7.js
[HTTP/2 403 Forbidden 14ms]

GEThttps://xcherry.tech/paste/js/rawinflate-0.3.js
[HTTP/2 403 Forbidden 14ms]

GEThttps://xcherry.tech/paste/js/bootstrap-3.3.7.js
[HTTP/2 403 Forbidden 14ms]

GEThttps://xcherry.tech/paste/js/prettify.js?1.3.4
[HTTP/2 403 Forbidden 13ms]

GEThttps://xcherry.tech/paste/js/purify-2.0.14.js
[HTTP/2 403 Forbidden 14ms]

GEThttps://xcherry.tech/paste/js/showdown-1.9.1.js
[HTTP/2 403 Forbidden 13ms]

GEThttps://xcherry.tech/paste/js/legacy.js?1.3.4
[HTTP/2 403 Forbidden 13ms]

GEThttps://xcherry.tech/paste/js/kjua-0.6.0.js
[HTTP/2 403 Forbidden 15ms]

GEThttps://xcherry.tech/paste/js/privatebin.js?1.3.4
[HTTP/2 403 Forbidden 15ms]

GEThttps://xcherry.tech/paste/img/icon.svg
[HTTP/2 403 Forbidden 16ms]

None of the "sha512" hashes in the integrity attribute match the content of the subresource.
```

### What should happen
Privatebin should load correctly with the default files and SRI hashes.

### What have I tried
I haven't changed any files or the config yet. I tried to regenerate SRI tokens (Even though I haven't changed any file for this to be needed). The phpunit command in privatebin directory gives the following output:
```
phpunit
PHP Fatal error:  Uncaught Error: Class 'PHPUnit_Framework_TestCase' not found in /var/www/html/xcherry/paste/tst/ConfigurationCombinationsTest.php:12
Stack trace:
#0 /usr/share/php/PHPUnit/Util/FileLoader.php(59): include_once()
#1 /usr/share/php/PHPUnit/Util/FileLoader.php(47): PHPUnit\Util\FileLoader::load()
#2 /usr/share/php/PHPUnit/Framework/TestSuite.php(354): PHPUnit\Util\FileLoader::checkAndLoad()
#3 /usr/share/php/PHPUnit/Framework/TestSuite.php(452): PHPUnit\Framework\TestSuite->addTestFile()
#4 /usr/share/php/PHPUnit/Util/Configuration.php(1005): PHPUnit\Framework\TestSuite->addTestFiles()
#5 /usr/share/php/PHPUnit/Util/Configuration.php(874): PHPUnit\Util\Configuration->getTestSuite()
#6 /usr/share/php/PHPUnit/TextUI/Command.php(929): PHPUnit\Util\Configuration->getTestSuiteConfiguration()
#7 /usr/share/php/PHPUnit/TextUI/Command.php(171): PHPUnit\TextUI\Command->handleArguments()
#8 /usr/share/php/PHPUnit/TextUI/Command.php(163): PHPUnit\TextUI\Command->run()
#9 /usr/bin/phpunit(42): PHPUnit\TextUI\Command::main() in /var/www/html/xcherry/paste/tst/ConfigurationCombinationsTest.php on line 12
root@Cherry:/var/www/html/xcherry/paste/tst# ls
Bootstrap.php                      FilterTest.php    phpunit.xml
ConfigurationCombinationsTest.php  FormatV2Test.php  README.md
ConfigurationTestGenerator.php     I18nTest.php      RequestTest.php
ConfigurationTest.php              IconTest          ViewTest.php
ControllerTest.php                 JsonApiTest.php   Vizhash16x16Test.php
ControllerWithDbTest.php           ModelTest.php
Data                               Persistence

```

## Additional information
A screenshot of the privatebin instance with the errors can be found here: https://prnt.sc/yjxi5v

**Comment by rugk** [comment]
Did you check our FAQ entries on this topic? See https://github.com/PrivateBin/PrivateBin/wiki/FAQ#why-does-the-loading-message-not-go-away and others linked there.
Do you use Cloudflare or a similar service?

Also, please mind to fill out the issue template completely. E.g. server information can be quite important here (Windows server? etc.).

You seem to get 403 errors, so maybe the requested URL is wrong?
So check that the loaded files actually are correct.

**Comment by saqeria** [comment]
> 
> 
> Did you check our FAQ entries on this topic? See https://github.com/PrivateBin/PrivateBin/wiki/FAQ#why-does-the-loading-message-not-go-away and others linked there.
> Do you use Cloudflare or a similar service?
> 
> Also, please mind to fill out the issue template completely. E.g. server information can be quite important here (Windows server? etc.).
> 
> You seem to get 403 errors, so maybe the requested URL is wrong?
> So check that the loaded files actually are correct.
@rugk 

1. Yes I've checked the FAQ and couldn't solve the issue.
2. I don't use cloudflare or a similar service.
3. The requested url is correct, but the files can't be loaded because of the "None of the "sha512" hashes in the integrity attribute match the content of the subresource."
4. The loaded files are correct and also the correct permissions are applied.

I use Ubuntu 20.12 on a raspberry pi 4 with nginx and php-fpm enabled and configured.

**Comment by saqeria** [comment]
@rugk 
It almost seems like the standard SRI hashes from this repo are incorrect and therefor the content gets blocked.

**Comment by elrido** [comment]
A first issue is the [403 forbidden](https://en.wikipedia.org/wiki/HTTP_403) status code that your webserver returns instead of the requested resources (CSS, images & JS files). From your log:

```
[HTTP/2 403 Forbidden 14ms]
```

These should give you a status 200 and the requested file instead. Check your webserver configuration. Since you do mention nginx, you can find an [example configuration snippet for that server over in our docker image](https://github.com/PrivateBin/docker-nginx-fpm-alpine/blob/7e968c9b82739a60d844d453e3b3567f818e6264/etc/nginx/http.d/site.conf#L8-L11), which uses a similar sounding setup (nginx + php-fpm).

> It almost seems like the standard SRI hashes from this repo are incorrect and therefor the content gets blocked.

The SRI-hashes get refreshed by running phpunit on the repo, which I expect every developer does before they commit changes to JS or php files.

Just to rule this out for master, I did pull the latest master and ran phpunit on it and the SRI hashes remain the same, so they are correct. Reg. the hashes of the releases, you can yourself go to the [demo instance](https://privatebin.net/) and check that those hashes works for you.

**Comment by saqeria** [comment]
> A first issue is the [403 forbidden](https://en.wikipedia.org/wiki/HTTP_403) status code that your webserver returns instead of the requested resources (CSS, images & JS files). From your log:
> 
> ```
> [HTTP/2 403 Forbidden 14ms]
> ```
> 
> These should give you a status 200 and the requested file instead. Check your webserver configuration. Since you do mention nginx, you can find an [example configuration snippet for that server over in our docker image](https://github.com/PrivateBin/docker-nginx-fpm-alpine/blob/7e968c9b82739a60d844d453e3b3567f818e6264/etc/nginx/http.d/site.conf#L8-L11), which uses a similar sounding setup (nginx + php-fpm).
> 
> > It almost seems like the standard SRI hashes from this repo are incorrect and therefor the content gets blocked.
> 
> The SRI-hashes get refreshed by running phpunit on the repo, which I expect every developer does before they commit changes to JS or php files.
> 
> Just to rule this out for master, I did pull the latest master and ran phpunit on it and the SRI hashes remain the same, so they are correct. Reg. the hashes of the releases, you can yourself go to the [demo instance](https://privatebin.net/) and check that those hashes works for you.

**I honestly don't know where the 403 forbidden error comes from.. I've applied the same config options as the example snippet that you've mentioned. See my virtual host config below:**

```
server {
    listen 80; 
    listen 443 http2 ssl;
    server_name  domain.ltd;

    ssl_certificate /path/to/fullchain.pem;
    ssl_certificate_key /path/to/privkey.pem;

    location / {
        root   /var/www/html/xcherry/;
         index  index.html index.htm;
    }
    location /paste {
        root   /var/www/html/xcherry/;
        include snippets/fastcgi-php.conf;
        fastcgi_pass unix:/var/run/php/php7.4-fpm.sock;
        index  index.php;
    }
    location ~ \.php$ {
        fastcgi_pass unix:/var/run/php/php7.4-fpm.sock;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;

        # Prevent exposing nginx + version to $_SERVER
        fastcgi_param SERVER_SOFTWARE "";
    }
```

**If i try to regenerate new SRI hashes using phpunit command I get the following error:**
```
root@Cherry:/var/www/html/xcherry/paste/tst# phpunit
PHP Fatal error:  Uncaught Error: Class 'PHPUnit_Framework_TestCase' not found in /var/www/html/xcherry/paste/tst/ConfigurationTest.php:5
Stack trace:
#0 /usr/share/php/PHPUnit/Util/FileLoader.php(59): include_once()
#1 /usr/share/php/PHPUnit/Util/FileLoader.php(47): PHPUnit\Util\FileLoader::load()
#2 /usr/share/php/PHPUnit/Framework/TestSuite.php(354): PHPUnit\Util\FileLoader::checkAndLoad()
#3 /usr/share/php/PHPUnit/Framework/TestSuite.php(452): PHPUnit\Framework\TestSuite->addTestFile()
#4 /usr/share/php/PHPUnit/Util/Configuration.php(1005): PHPUnit\Framework\TestSuite->addTestFiles()
#5 /usr/share/php/PHPUnit/Util/Configuration.php(874): PHPUnit\Util\Configuration->getTestSuite()
#6 /usr/share/php/PHPUnit/TextUI/Command.php(929): PHPUnit\Util\Configuration->getTestSuiteConfiguration()
#7 /usr/share/php/PHPUnit/TextUI/Command.php(171): PHPUnit\TextUI\Command->handleArguments()
#8 /usr/share/php/PHPUnit/TextUI/Command.php(163): PHPUnit\TextUI\Command->run()
#9 /usr/bin/phpunit(42): PHPUnit\TextUI\Command::main()
#10 {main}
  in /var/www/html/xcherry/paste/tst/ConfigurationTest.php on line 5
```

The user that handles php and nginx is the same: www-data. When checking files owned by .. in the paste directory using command: "ls -l". I get the following output:

```
root@Cherry:/var/www/html/xcherry/paste# ls -l
total 220
-rw-r--r-- 1 www-data www-data  1532 feb  7 15:48 BADGES.md
-rw-r--r-- 1 www-data www-data   335 feb  7 15:48 browserconfig.xml
drwxr-xr-x 2 www-data www-data  4096 feb  7 15:48 cfg
-rw-r--r-- 1 www-data www-data 19262 feb  7 15:48 CHANGELOG.md
-rw-r--r-- 1 www-data www-data   394 feb  7 15:48 CODE_OF_CONDUCT.md
-rw-r--r-- 1 www-data www-data  1075 feb  7 15:48 composer.json
-rw-r--r-- 1 www-data www-data 53127 feb  7 15:48 composer.lock
-rw-r--r-- 1 www-data www-data  1558 feb  7 15:48 CREDITS.md
-rw-r--r-- 1 www-data www-data    80 feb  7 15:48 crowdin.yml
drwxr-xr-x 4 www-data www-data  4096 feb  7 15:48 css
drwxr-xr-x 2 www-data www-data  4096 feb  7 15:48 doc
drwxr-xr-x 2 www-data www-data  4096 feb  7 15:48 i18n
drwxr-xr-x 2 www-data www-data  4096 feb  7 15:48 img
-rw-r--r-- 1 www-data www-data   517 feb  7 15:48 index.php
-rw-r--r-- 1 www-data www-data  9024 feb  7 15:48 INSTALL.md
drwxr-xr-x 3 www-data www-data  4096 feb  7 15:48 js
drwxr-xr-x 5 www-data www-data  4096 feb  7 15:48 lib
-rw-r--r-- 1 www-data www-data 42883 feb  7 15:48 LICENSE.md
-rw-r--r-- 1 www-data www-data  1974 feb  7 15:48 Makefile
-rw-r--r-- 1 www-data www-data   294 feb  7 15:48 manifest.json
-rw-r--r-- 1 www-data www-data  4957 feb  7 15:48 README.md
-rw-r--r-- 1 www-data www-data   376 feb  7 15:48 robots.txt
-rw-r--r-- 1 www-data www-data   666 feb  7 15:48 SECURITY.md
drwxr-xr-x 2 www-data www-data  4096 feb  7 15:48 tpl
drwxr-xr-x 4 www-data www-data  4096 feb  7 15:48 tst
drwxr-xr-x 5 www-data www-data  4096 feb  7 15:48 vendor
```
This same permission are also applied for the "paste/js/" directory:

```
root@Cherry:/var/www/html/xcherry/paste/js# ls -l
total 584
-rw-r--r-- 1 www-data www-data   7364 feb  7 15:48 base64-1.7.js
-rw-r--r-- 1 www-data www-data   3980 feb  7 15:48 base-x-3.0.7.js
-rw-r--r-- 1 www-data www-data  37045 feb  7 15:48 bootstrap-3.3.7.js
-rw-r--r-- 1 www-data www-data    505 feb  7 15:48 comment.jsonld
-rw-r--r-- 1 www-data www-data    180 feb  7 15:48 commentmeta.jsonld
-rw-r--r-- 1 www-data www-data   4010 feb  7 15:48 common.js
-rw-r--r-- 1 www-data www-data  88145 feb  7 15:48 jquery-3.4.1.js
-rw-r--r-- 1 www-data www-data  25372 feb  7 15:48 kjua-0.6.0.js
-rw-r--r-- 1 www-data www-data   8608 feb  7 15:48 legacy.js
-rw-r--r-- 1 www-data www-data   1045 feb  7 15:48 package.json
-rw-r--r-- 1 www-data www-data    645 feb  7 15:48 paste.jsonld
-rw-r--r-- 1 www-data www-data    446 feb  7 15:48 pastemeta.jsonld
-rw-r--r-- 1 www-data www-data  15081 feb  7 15:48 prettify.js
-rw-r--r-- 1 www-data www-data 174251 feb  7 15:48 privatebin.js
-rw-r--r-- 1 www-data www-data  16990 feb  7 15:48 purify-2.0.14.js
-rw-r--r-- 1 www-data www-data  19782 feb  7 15:48 rawinflate-0.3.js
-rw-r--r-- 1 www-data www-data  75632 feb  7 15:48 showdown-1.9.1.js
drwxr-xr-x 2 www-data www-data   4096 feb  7 15:48 test
-rw-r--r-- 1 www-data www-data   2067 feb  7 15:48 types.jsonld
-rw-r--r-- 1 www-data www-data   5194 feb  7 15:48 zlib-1.2.11.js
-rw-r--r-- 1 www-data www-data  61388 feb  7 15:48 zlib-1.2.11.wasm
```
Please let me know what else I can try as I would really love to get PrivateBin working.

**Comment by elrido** [comment]
No need to re-generate the SRI hashes at this point - if your server doesn't serve the files they hashes don't matter. Fix the permission issue first, if you then still have SRI warnings, lets re-evaluate that part.

I see that you have a single rule for the location `/paste`, which is to send it all to PHP:

```
    location /paste {
        include /etc/nginx/mime.types;
        include snippets/fastcgi-php.conf;
        include fastcgi_params;
        fastcgi_pass unix:/var/run/php/php7.4-fpm.sock;
        index index.php;
    }
```

But PHP only handles the requests for the web UI and the API, it doesn't care about the static files and the index.php will just always send you the web UI, regardless of the path. You need to tell nginx that it should first check if the path resolves to a static file, and if so, serve that and only as a last resort serve index.php via php-fpm. You probably need at least a try_files directive in that block, maybe a separate block before that using a regex match (the below is from our docker image config, yours may need to be different, check the nginx docs if it doesn't work):

```
try_files $uri $uri/ /index.php$is_args$args;
```
This rule first checks if a file exists matching the path and serve it, or try if there is a directory of that name, of falls back to the index.php, appending any GET arguments (for static files, GET arguments get ignored).

**Comment by saqeria** [comment]
@elrido Hi, thank you for your help and effort. I fixed the issue by adding this line to the nginx config:     
```
location ~* ^.+\.(?:jpg|svg|jpeg|gif|bmp|ico|png|css|js|woff|woff2|ttf|wasm)$ {
}
```
This seemed to fix all the errors,
