### ISSUE TITLE
Conf.php doesn't get applied

### ISSUE THREAD

**Issue by saqeria** [PrivateBin/PrivateBin#746]
I've first installed privatebin with all the default files including the default conf.sample.php. After I saw that everything was working correctly like supposed to. I defined a different PATH by following this documentation (https://github.com/PrivateBin/PrivateBin/blob/master/INSTALL.md#installation). The PATH that is defined in the index.php contains the cfg, doc, data, lib, tpl, tst and vendor directories. After that I applied the corresponding user to access the directories and files. I restarted my host machine and everything was still working fine. After this I tried changing the conf.php to my liking but the changes doesn't get applied. When I go to my privatebin's url I can still see the default configuration getting applied. I also tried adding the following line in my php-fpm pool.d config but that didn't work out either.
`In a php-fpm pool config: env[CONFIG_PATH] = /path/to/privatebin/conf.php`

I looked through the issues but couldn't find anything similar. Help is very much appreciated ♥.

**Comment by rugk** [comment]
As notes, please double-check that the path to your config file is correct: https://github.com/PrivateBin/PrivateBin/blob/master/INSTALL.md#changing-the-config-path-only

**Comment by saqeria** [comment]
> As noted, please double-check that the path to your config file is correct: https://github.com/PrivateBin/PrivateBin/blob/master/INSTALL.md#changing-the-config-path-only

I checked the config path it is correct and accessible.

**Comment by saqeria** [comment]
I was just thinking about it. It might has something to do with nginx/php cache but I'm not sure. I restarted nginx, php and php7.4-fpm but this didn't fix the issue.

**Comment by rugk** [comment]
May be a permission problem. Notice that in most PHP configurations likely `php` is the correct user. See also: https://github.com/PrivateBin/PrivateBin/wiki/FAQ#what-are-the-recommended-file-and-folder-permissions-for-privatebin

**Comment by saqeria** [comment]
> May be a permission problem. Notice that in most PHP configurations likely `php` is the correct user. See also: https://github.com/PrivateBin/PrivateBin/wiki/FAQ#what-are-the-recommended-file-and-folder-permissions-for-privatebin

I don't think that is the issue. As you can see in my /etc/php/7.4/fpm/pool.d/www.conf:
```

; Start a new pool named 'www'.
; the variable $pool can be used in any directive and will be replaced by the
; pool name ('www' here)
[www]

; Per pool prefix
; It only applies on the following directives:
; - 'access.log'
; - 'slowlog'
; - 'listen' (unixsocket)
; - 'chroot'
; - 'chdir'
; - 'php_values'
; - 'php_admin_values'
; When not set, the global prefix (or /usr) applies instead.
; Note: This directive can also be relative to the global prefix.
; Default Value: none
;prefix = /path/to/pools/$pool

; Unix user/group of processes
; Note: The user is mandatory. If the group is not set, the default user's group
;       will be used.
**user = www-data
group = www-data**
```

**Comment by saqeria** [comment]
@elrido Do you have a clue on what might be the issue?

**Comment by saqeria** [comment]
I fixed the issue. For anyone else facing the same problem. php-fpm or nginx was serving the old cached files like I suspected. These were the changes that I made.

**Add these lines to the http block in /etc/nginx/nginx.conf:**

```
open_file_cache          max=10000 inactive=5m;
open_file_cache_valid    2m;
open_file_cache_min_uses 1;
open_file_cache_errors   on 
```

**And added these lines to the server block in /etc/nginx/conf.d/domain.ltd.config:**

```
#######  Disables cache  #######
        sendfile off;
        add_header Last-Modified $date_gmt;
        add_header Cache-Control 'no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0';
        if_modified_since off;
        expires off;
        etag off;
        proxy_no_cache 1;
        proxy_cache_bypass 1;
```

I also turned off 'opcache' in the php7.4-fpm config file.

**Comment by SoulofSorrow** [comment]
Hello, I have the same problem my docker container does not load the config. Unfortunately I do not understand why. I have checked the mount path, the env variable and the config file. Do I have to pay attention to anything with docker?
