### ISSUE TITLE
Ability to create new custom themes

### ISSUE THREAD

**Issue by Thatkookooguy** [PrivateBin/PrivateBin#748]
## Steps to reproduce

1. Deployed privatebin inside a docker container using:
   ```
    docker run -d --name=privatebin --restart="always" --read-only -p 8080:8080 -v $PWD/privatebin/data:/srv/data -v $PWD/privatebin/tpl:/srv/tpl -v $PWD/privatebin/cfg:/srv/cfg:ro privatebin/nginx-fpm-alpine
   ```
   I attached the tpl folder in order to add a custom `my-theme.php` file to the templates folder.
2. Copy all the files from the `/tpl` folder that exists in the repo to `$PWD/privatebin/tpl`
   > Everything should work as intended since all the files are there (bootstrap.php & page.php)
3. For some reason, the UI is stuck at loading forever.

### What happens
The UI is not loaded if I'm trying to override the `tpl` folder, even if the folder's content is identical (+my file)

### What should happen
Either the site should work if all the original files in `tpl` exists, or some step in missing in the [docs](https://github.com/PrivateBin/PrivateBin/wiki/Templates#creating-templates)?

## Additional information

![image](https://user-images.githubusercontent.com/10427304/108610102-ae0c3600-73db-11eb-9ba4-53e1a7d289dc.png)
You probably already know how this looks like but this is what I see for the 1st attempt.

## Basic information

**Server OS:** Windows 10 with Docker (wsl2), running `privatebin/nginx-fpm-alpine`

**PrivateBin version:** Docker image release 1.3.4

I can reproduce this issue on <https://privatebin.net>: No :-)

**Comment by Thatkookooguy** [comment]
Btw, I don't mind sharing the theme with a PR so it will be available from the original folder. But I still think this is a good feature to have (loading a theme.php or theme.css) file from outside this project (but maybe a local file).

Also, if you want me to try and implement this, I don't mind trying while I'm writing my theme :-)

**Comment by Thatkookooguy** [comment]
is it related to the integrity of the files? How can I make privatebin trust the new files?
```
Failed to find a valid digest in the 'integrity' attribute for resource 'http://localhost:10198/js/purify-2.0.14.js' with computed SHA-256 integrity '<string>'. The resource has been blocked.
```

**Comment by elrido** [comment]
It should totally be possible to add a theme like you describe and in the cfg/conf.php you'd choose your own theme name. Could you check the logs for your container (`docker logs privatebin`, since you named it privatebin) to ensure there are no php errors thrown?

The message above looks less like an issue loading the theme, more like an issue with the javascript loading. Did you maybe copy a template from the master branch here on gitlab and attach that to the 1.3.4 release? If so, it will have differing SRI hashes for the javascript files. You can either: a) replace the SRI hashes in your theme with [those from the release version](https://github.com/PrivateBin/PrivateBin/blob/9914c37683496d161d9f8c8355bc89c358b1b243/tpl/bootstrap.php#L44-L75) or b) during development, remove the SRI hashes from the javascript includes.

And yes, we would certainly be interested in a PR for your theme when it is ready.

**Comment by Thatkookooguy** [comment]
There are some PHP errors thrown. I'm not sure which one is causing the other. I attached the logs with the error I got from loading my `kibibit.php` theme (which is a copy of `boostrap.php`). I replaced the host string there just so that it won't be public right now. Sorry for that :-)
```
2021/02/21 11:56:46 [error] 73#73: *303 FastCGI sent in stderr: "PHP message: PHP Warning: Undefined variable $BASEPATH in /srv/tpl/kibibit.php on line 77" while reading response header from upstream, client: 172.17.0.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/run/php-fpm.sock:", host: "<SOME HOST>"

2021/02/21 11:56:46 [error] 73#73: *303 FastCGI sent in stderr: "PHP message: PHP Warning: Undefined variable $BASEPATH in /srv/tpl/kibibit.php on line 89PHP message: PHP Warning: Undefined variable $BASEPATH in /srv/tpl/kibibit.php on line 93" while reading upstream, client: 172.17.0.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/run/php-fpm.sock:", host: "<SOME HOST>"

2021/02/21 11:56:46 [error] 73#73: *303 FastCGI sent in stderr: "PHP message: PHP Warning: Undefined variable $INFO in /srv/tpl/kibibit.php on line 581" while reading upstream, client: 172.17.0.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/run/php-fpm.sock:", host: "<SOME HOST>"
```

**Comment by Thatkookooguy** [comment]
I tried using the files of version 1.3.4 (like the one installed inside the docker. As you recommended), but it acts the same as before.

**Comment by elrido** [comment]
The above are warnings from PHP and won't break the site.

For the SRI hashes, if that is the problem, then your browser console will contain SRI errors and tell you it prevented the JS in question to load. Press [F12] in Chrome or Firefox to open the console, reload the page and it should show errors/warnings if there are any. If these are the problem, you can temporarily remove the hashes from the template (the integrity properties of the script tags).

**Comment by Thatkookooguy** [comment]
ok so removing the integrity attributes worked so I'm closing this issue.

But if I want to send a pull request with a new theme, shouldn't I add it back? how do I do that? just copy the integrity attributes from the boostrap file? what if I added new style tags? how should I generate integrity attributes for new assets?

thanks!

**Comment by rugk** [comment]
> just copy the integrity attributes from the boostrap file?

correct, as long as they refer to the same file, that should work.

> what if I added new style tags? how should I generate integrity attributes for new assets?

Have a look at the development guides: https://github.com/PrivateBin/PrivateBin/wiki/Development#subresource-integrity-for-javascript-resources
