### ISSUE TITLE
Render avatars (Identicons) on client side (JS)

### ISSUE THREAD

**Issue by rugk** [PrivateBin/PrivateBin#75]
Continuing https://github.com/PrivateBin/PrivateBin/issues/52.

So should we render the Identicons on the client-side?

## Pro
* reduces the things the server has to do (as they are regenerated for each page request?)
* we could use new technologies such as Canvas or SVGs

## Contra
* needs whole new implementation
* current icons would have to change (as we switched to Identicons recently anyway, they already changed and as no new version has been released

**Comment by elrido** [comment]
As already discussed, this would be pointless, because then you could easily fake them or have clients that use different libraries, hence the whole point of the icons falls flat.

**Comment by rugk** [comment]
Anyone who can run JS code on the client side can fake them - or can extract the secret data entered into the bin and so on...
But of course that's nothing special and could already happen now (a JS which changes the PNG `data:` image)

As for what the implementation does is:
* Server returns the hash as it is currently used (or embeds it in the Pad via a "data-" attribute)
* All the JS does it rendering and displaying this data

**Comment by elrido** [comment]
I don't think the tiny performance gain on the server (icon rendered once when a comment is created) compared to the performance loss client side (all icons of all comments with icons have to be rendered on every page load by every visitor) is worth the effort of introducing more JS (which we still don't unit test).

Also, less attack surface if images have to be rendered for a rainbow-table compared to hashes (in the "attacker wants to figure out an IP of a comment poster" scenario).

**Comment by rugk** [comment]
> (icon rendered once when a comment is created) 

Okay, is the icon really saved on the server? For each user?

If this is true I'd also say we can close this issue with "wontfix" for now.

> Also, less attack surface if images have to be rendered for a rainbow-table compared to hashes

Arrr, it's not really less attack surface. It's just another call (passing it to the Identicon lib) and probably there might even be a way to get the input string from such a Identicon. As said Identicons are not one-way.
So attack surface does hardly matter.

**Comment by elrido** [comment]
> Okay, is the icon really saved on the server? For each user?

Actually its per comment, as there is no concept of user (and the icon is just an indication that two comments _might_ be by the same person). You can see [here the nickname being set](https://github.com/PrivateBin/PrivateBin/blob/master/lib/PrivateBin.php#L260) in the comment object which then [triggers the icon generation](https://github.com/PrivateBin/PrivateBin/blob/master/lib/Model/Comment.php#L189).

**Comment by rugk** [comment]
Okay.
