### ISSUE TITLE
conf.php with new setup "basepath"

### ISSUE THREAD

**Issue by hikerus** [PrivateBin/PrivateBin#753]
I found a new setup in conf.php but no further description.

; The full URL, with the domain name and directories that point to the PrivateBin files
; This URL is essential to allow Opengraph images to be displayed on social networks
; basepath = ""

"with the domain name and directories that point to the PrivateBin files" seems not to be very clear to me. My Privatebin URL is eg "https://bin.domain.tld".

**Comment by rugk** [comment]
Without looking it up again [it's likely the base of HTML](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/base).
But it's [indeed not mentioned in out wiki](https://github.com/PrivateBin/PrivateBin/wiki/Configuration), so one should probably add it.

**Comment by elrido** [comment]
I've added it to the wiki (thanks for the hint) and tried to expand the explanation from the conf.sample.php a bit with two examples and what this is used for. Your instance will work just fine without it, but it is required if you want to Twitter and co. to display your shared PrivateBin link a bit nicer.

Note to self: I think I never set this up on the demo site, either.

**Comment by elrido** [comment]
I think this question has been answered and I am closing the issue. Please feel free to reply if you have follow-up questions or create a separate issue for different topics.
