### ISSUE TITLE
New security headers

### ISSUE THREAD

**Issue by rugk** [PrivateBin/PrivateBin#765]
We could consider adding 

https://securityheaders.com/?q=privatebin.net&followRedirects=on
* permissions-policy

https://www.golem.de/news/http-header-webseiten-vor-spectre-schuetzen-2103-155142.html

```
    Cross-Origin-Resource-Policy: same-origin
    Cross-Origin-Embedder-Policy: require-corp
    Cross-Origin-Opener-Policy: same-origin
    X-Content-Type-Options: nosniff
    X-Frame-Options: deny
 ```

AFAIK as we do not embed third-party stuff and do not want to be embedded by them, it should be easy to just statically set the most strict configuration.

**Comment by elrido** [comment]
The golem article seems to be behind a paywall or cookiewall and I can't access it. Do you have any other sources for the benefits of this?

**Comment by rugk** [comment]
`X-Content-Type-Options` is missing also according to our ZAP security scan (https://github.com/PrivateBin/docker-nginx-fpm-alpine/issues/29).

**Comment by rugk** [comment]
> The golem article seems to be behind a paywall or cookiewall and I can't access it. 

No paywall here. The article explains it quite easy, so it's a good read, actually.

> Do you have any other sources for the benefits of this? 

Well… the TL;DR is just it's Spectre/Meltdown mitigation stuff that makes sure the content runs in it's own process AFAIK.
See also:
https://developer.mozilla.org/en-US/docs/Web/HTTP/Cross-Origin_Resource_Policy_(CORP)

**Comment by elrido** [comment]
If I understand correctly, you propose to set these headers for all requests to static or dynamic resources?
```
Cross-Origin-Resource-Policy: same-origin
Cross-Origin-Embedder-Policy: require-corp
Cross-Origin-Opener-Policy: same-origin
X-Content-Type-Options: nosniff
X-Frame-Options: deny
```
We could add them to the nginx configuration via the `add_header` directive in the main `server` block, for example around here:
https://github.com/PrivateBin/docker-nginx-fpm-alpine/blob/master/etc/nginx/http.d/site.conf#L7

**Comment by rugk** [comment]
Yeah, AFAIK it's fine to send these headers for each request.

We could send them as part of the PHP code or in nginx in the Docker. Yeah, I basically don't care. :smile:

**Comment by elrido** [comment]
I would do it in the webserver, not in php logic, as php changes don't affect sending the static resources.
