### ISSUE TITLE
"Loading…" message not go away?

### ISSUE THREAD

**Issue by Tealk** [PrivateBin/PrivateBin#768]
## Steps to reproduce

1. Update from 1.3.4 to 1.3.5

### What happens
I only get the Loading message

### What should happen
That I see the input field for code

## Basic information

**Server address**: https://paste.anzah.network

**Server OS:** Debian 10

**Webserver:** Nginx

**Browser:** Firefox

**PrivateBin version:** 1.3.5

I can reproduce this issue on <https://privatebin.net>: Yes / No

**Comment by elrido** [comment]
It seems to be either a caching problem or you are using a different template file that needs to be updated. All js resources point to the old versions of the 1.3.4 release.

**Comment by Tealk** [comment]
I have replaced all filesah many thanks, I have no longer thought of the templates

**Comment by elrido** [comment]
Thank you for updating! You sure are quicker then we are with our demo website ;-)

**Comment by Tealk** [comment]
The last version is already a few days ago, I have totally forgotten about the template.
I actually follow all projects which I offer so I'm always up to date and if I can I like to help with feedback.

so thank you for your work :)
