### ISSUE TITLE
Bootstrap Page on Mobile

### ISSUE THREAD

**Issue by cryptoseb** [PrivateBin/PrivateBin#770]
This is a bit of a tall-order suggestion, but I'll drop it here anyways. 

Currently using Bootstrap Page template as I feel that on Desktop, it's where the send button is the most natural.
On mobile, it then hides the send button in the hamburger menu, which isn't natural.

Curious is if there has been any discussion on having bootstrap-page keep the Send button in the normal position on Mobile, but drop it beside the options on the left side on Desktop?

**Comment by rugk** [comment]
As far as I understand, this should be fixed with https://github.com/PrivateBin/PrivateBin/pull/478.

Which PrivateBin version do you use?
The just released 1.3.5 should include this.

**Comment by cryptoseb** [comment]
I'm also running 1.3.5. Send button is pulled down on top of the editor on the default style, but not on bootstrap-page. It's fine. I've just gone back to using the default styling.

**Comment by elrido** [comment]
I think this question has been answered and I am closing the issue. Please feel free to reply if you have follow-up questions or create a separate issue for different topics.
