### ISSUE TITLE
Small issues after upgrade to 1.3.5, probably templating issue but ...

### ISSUE THREAD

**Issue by DFF-fred** [PrivateBin/PrivateBin#772]
## Steps to reproduce

1. Add a secret message and click send

### What happens
1. I am getting a "Cannot calculate expiration date."

### What should happen
Well.. no error message in red? ;-)

 A refresh makes it disappear though

## Additional information
Firefox console gives me all this:
This page uses the non standard property “zoom”. Consider using calc() in the relevant property values, or using “transform” along with “transform-origin: 0 0”. pass.dao2.com
Some cookies are misusing the recommended “SameSite“ attribute 5
Cookie “lang” will be soon rejected because it has the “SameSite” attribute set to “None” or an invalid value, without the “secure” attribute. To know more about the “SameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite pass.dao2.com
Cookie “lang” will be soon rejected because it has the “SameSite” attribute set to “None” or an invalid value, without the “secure” attribute. To know more about the “SameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite pass.dao2.com
Cookie “lang” will be soon rejected because it has the “SameSite” attribute set to “None” or an invalid value, without the “secure” attribute. To know more about the “SameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite pass.dao2.com
Cookie “lang” will be soon rejected because it has the “SameSite” attribute set to “None” or an invalid value, without the “secure” attribute. To know more about the “SameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite pass.dao2.com
Cookie “lang” will be soon rejected because it has the “SameSite” attribute set to “None” or an invalid value, without the “secure” attribute. To know more about the “SameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite pass.dao2.com
Error: Cannot calculate expiration date.
    calculateExpirationDate https://pass.dao2.com/js/privatebin.js?1.3.5:553
    showEmailButton https://pass.dao2.com/js/privatebin.js?1.3.5:4025
    showCreatedPaste https://pass.dao2.com/js/privatebin.js?1.3.5:4689
    success https://pass.dao2.com/js/privatebin.js?1.3.5:4432
    success https://pass.dao2.com/js/privatebin.js?1.3.5:4468
    jQuery 6
    run https://pass.dao2.com/js/privatebin.js?1.3.5:4479
    sendPaste https://pass.dao2.com/js/privatebin.js?1.3.5:4916
    jQuery 9
    init https://pass.dao2.com/js/privatebin.js?1.3.5:4351
    init https://pass.dao2.com/js/privatebin.js?1.3.5:5392
    <anonymous> https://pass.dao2.com/js/privatebin.js?1.3.5:42
    jQuery 13

## Basic information
https://pass.dao2.com

Linux + Cpanel

Apache 2.4

Firefox 87.0 (64-bit) on Linux

1.3.5

I can reproduce this issue on <https://privatebin.net>: Yes / No
No

**Comment by rugk** [comment]
> I am getting a "Cannot calculate expiration date."

How exactly do you get that? In the browser console, as an error message in red (feel free to attach a screenshot)?

And what are your expiration time settings in your server configuration?

**Comment by DFF-fred** [comment]
Hi! Sorry for lacking clarity. Please find further explanation and answers to your questions below:
1. Error message is both on the web interface and the console:
![Screenshot from 2021-04-15 13-24-10](https://user-images.githubusercontent.com/5652441/114823778-2b599300-9dee-11eb-8bc9-35f58ef123c5.png)
![Screenshot from 2021-04-15 13-24-33](https://user-images.githubusercontent.com/5652441/114823792-2f85b080-9dee-11eb-948a-fad0101d6ae7.png)

2. I didn't change the expiration settings from last version. Those are:
.. and this was it! I somehow had an invalid character in my conf file (which was there before but somehow didn't disturb the app) and everything is working once I removed it.

So alll fixed now.

Thank you.

**Comment by rugk** [comment]
Okay, that's great to hear. As that is apparently then something out of our influence, I'll close this issue. :smile:  
But it's great to hear we could help.
