### ISSUE TITLE
Restrict form content via CSP

### ISSUE THREAD

**Issue by rugk** [PrivateBin/PrivateBin#778]
I've found the following (i.e. another CSP recommendation, see #777) in a HTTP Observatory scan:

> Restricts where \<form\> contents may be submitted by using form-action 'none', form-action 'self', or specific URIs

Now I was reluctant to change that as currently (speaking of 8232dce as I'm writing this) we explicitly allow forms as a sandbox whitelisted:
https://github.com/PrivateBin/PrivateBin/blob/8232dce395e421450779bd710e5872399f792085/cfg/conf.sample.php#L90

As such, we maybe use that somewhere or it was a workaround.

Searching the git history (after finally finding the appropriate/best command for that: `git log -S "allow-forms" --source --all`), I find two commits (order chronologically):
* https://github.com/PrivateBin/PrivateBin/commit/e9b10f9e2daa2c0e69f39ca5af8ebf4585337dbb - introduced the CSP sandbox, instantly with `allow-forms`
* https://github.com/PrivateBin/PrivateBin/commit/faf596aeb75605d99a12b93a1d66fad0e300301f - removed the whole sandbox while implementing some features… uhm I guess we can ignore that,. it was apparently re-added later.

hmm…

----

Okay, found it in https://github.com/PrivateBin/PrivateBin/issues/168#issuecomment-276725743:
> and forms are required for the password entry in the bootstrap theme.

I'm unsure if that is even correct. As `allow-forms` says:
> allow-forms This value allows the page to submit forms.

We don't actually submit them – at least not to a server/URL, just read it via JS… :thinking: 
It's a thing to try out.

---

Anyway, but given this is the only use-case `form-action 'self'` seems to be safe to add, is not it?

ref #108

**Comment by elrido** [comment]
I just tested it with the CSP that had `allow-forms` removed from sandbox and indeed, at least on Firefox, clicking the button in the password dialog doesn't trigger the event anymore. If I re-add the policy and reload my paste I can submit the password form.

I'm fine with adding `form-action 'self'`.

**Comment by rugk** [comment]
Okay, so maybe we should test it on Browserstacks, but I'll submit it for now.
