### ISSUE TITLE
Allow disabling CSP header

### ISSUE THREAD

**Issue by rugk** [PrivateBin/PrivateBin#78]
For testing or other reasons it might be useful to disable the CSP header completely. Currently you can only do this by adding some invalid values there as neither `cspheader = false` nor `cspheader = ""` disable it, but just use the default CSP header in this case.

**Comment by elrido** [comment]
Simply set it to:

    default-src *;

**Comment by rugk** [comment]
Well.. yeah that's possible, but don't you think a way, which prevents the header to be send at all would be better?

**Comment by elrido** [comment]
If this is only for development, that should be enough. Or do you see a risk that it interrupts a test you do? Then simply uncomment the line in [PrivateBin::_view()](https://github.com/PrivateBin/PrivateBin/blob/master/lib/PrivateBin.php#L405).

**Comment by rugk** [comment]
No, it is all right. I just though such a thing would be nice to have.
