### ISSUE TITLE
POST url loging

### ISSUE THREAD

**Issue by sachaz** [PrivateBin/PrivateBin#781]
Hi,

French law forces us  to have in logs for POST link by ip.
Due to this our public instance is illegal.
Can we activate this info (without the secret key) ?

**Comment by r4sas** [comment]
You can do that in your webserver software. How to do it - read docs regarding to your software.

**Comment by rugk** [comment]
And if you are asking whether that could be implemented in PrivateBin, I’m strictly against that.
It’s fundamentally against the “privacy by default” approach taken by PrivateBin, and – as already said – also just not necessary.

Also you should check whether your instance is really “illegal” then if you don't do this, but this totally depends on your jurisdiction and we cannot offer legal advise here. 

So as it seems this question has been answered and I thus close this issue. If anyone has further questions on that topic, feel free to comment here, again.

**Comment by rugk** [comment]
> Can we activate this info (without the secret key) ?

An addendum: The secret key is never send to the server. That is the whole concept of PrivateBin, so you can claim “zero knowledge” as a server operator as you don’t have the keys and are not able to decrypt the content unless provided an URL that includes the key. See our Readme for example that also explains that: https://github.com/PrivateBin/PrivateBin#what-privatebin-provides

**Comment by sachaz** [comment]
> And if you are asking whether that could be implemented in PrivateBin, I’m strictly against that.
I stricky understand your position.
Laws on privacy are moving and it's a everyday fight here in France.
One part police is arguing we have to provide IP logs for all the services we have, in another part the lay is saying to provide what we can. ;)
