### ISSUE TITLE
Checkbox issues when set in config

### ISSUE THREAD

**Issue by rugk** [PrivateBin/PrivateBin#79]
https://github.com/PrivateBin/PrivateBin/issues/11 happens again, when you set `opendiscussion` or `burnafterreadingselected` to `true`. The other item is not disabled in this case.

And when you set both values to true both are enabled. I don't know if we should do something about this or just believe no server admin will be so stupid to do this.

**Comment by elrido** [comment]
Note: The current behaviour if both `opendiscussion` and `burnafterreadingselected` are set to `true` is that the `burnafterreadingselected` wins out, as its check is called first and then disables the discussion before the check on the discussion is run. In such a scenario the admin would probably prefer that the burn-after-reading is the default to lower the amount of time the pastes need to be stored.
