### ISSUE TITLE
Use vanilla javascript and not jquery

### ISSUE THREAD

**Issue by 9mido** [PrivateBin/PrivateBin#791]
Most of what jquery was capable of in the past can now be done with newer versions of vanilla javascript. It would be nice to have everything written in pure vanilla javascript without relying on jqeury. 

Bootstrap v5 no longer uses jquery and would make sense to follow in that direction. 

Related: #728

**Comment by 9mido** [comment]
I see an existing issue for this is currently open. Sorry.

**Comment by rugk** [comment]
Duplicate of #198
