### ISSUE TITLE
identicon library is abandoned - find and switch to a replacement

### ISSUE THREAD

**Issue by elrido** [PrivateBin/PrivateBin#793]
As I was running composer to install a new library into our repo, it warned me that:
```
Package yzalis/identicon is abandoned, you should avoid using it. No replacement was suggested.
```

I'm not familiar on what packagist.org's process is to declare a package abandoned. I see that the last commit in their repo is from 2019 and there are a number of unanswered issues and pull requests.

I would suggest that we go looking for a replacement library before our next major release. I looked at some of the libraries with similar names (identicon, gravatar), but while not abandoned, many have not received updates since 2015 or 2019 either. This may not necessarily be bad, they might just be feature complete and stable, but I'd prefer to use a library that at least has some active maintainer handling issues, should they occur, or we are back at having to maintain it ourselves, like with the vizhash one (last commit in 2013).

We could also keep the identicons library, but switch to a new, maintained one by default, like we did with vizhashes. Admins could choose to remain on the older ones via the configuration option.

Impact: The already generated identicons and vizhashes remain unchanged in the existing comments. Newly generated icons from a new library likely will look different. Upon upgrade to the new library, any newly generated comments get a different icon. In an ongoing discussion, after the change one could no longer be sure that the commenters are still the same as the icon will look different for the same IP. That might be a reason an admin might want to choose to stick to an older library.

Security considerations: At this point we have no evidence or suspicions of issues in any of the used libraries. We do feed them the SHA512 HMAC of the users IP and the server unique salt, so even if the generated image leaks information, it should not be possible to use this to correlate unique users across different instances or their IP addresses.

Please let me know if you have any suggestions on replacement libraries, have concerns beyond what I could come up with above or would like to pick this issue up.

I think it is a relatively simple one in terms of actual work. The new library would be added to composer.json, downloaded using `composer update --no-dev --optimize-autoloader` and added in this area of the code:
https://github.com/PrivateBin/PrivateBin/blob/e32e3979a8e4abbd81ae95229d83c916a32e2e14/lib/Model/Comment.php#L167-L175

**Comment by rugk** [comment]
Having a quick look for alternatives I found https://jdenticon.com/. It has a nice and profesional website, and seems to be quite popular. The [PHP implementation got it's latest update in 2019 though](https://github.com/dmester/jdenticon-php/), but it's from the same dev as the JS version, which looks quite maintained. (Maybe there was indeed no reason to update the PHP implementation.)
It also supports SVG generation, which is nice IMHO.

Also the generated images look quite nice and you can even adjust the style. So we can use this chance to switch to such a nice library.

Alternatively, we could of course also switch to generating the images via JS on the client. This would expose the "SHA512 HMAC of the users IP and the server unique salt" as you said, though, so well… maybe… not.
Or we would want to switch to a password-hash that is stronger (i.e. slower) than SHA512, but maybe that's not really necessary.

**Comment by elrido** [comment]
Note to self: When testing new icon libraries, use the script for size and speed comparisons from https://github.com/PrivateBin/PrivateBin/issues/148#issuecomment-502426961
