### ISSUE TITLE
Unable to create directory data

### ISSUE THREAD

**Issue by facade1337** [PrivateBin/PrivateBin#798]
## Steps to reproduce

1. Basic Fresh Ubuntu 20.10 on RaspberryPi
2. Installed nginx.
3. Setup Virtual Hosts
4. Cloned into privatebin
5. Created user "www" and set this user as the owner of the entire privatebin directory as this is the user Nginx runs as.
6. Tried to create a paste.
**Pretty aware that this is a permissions issue -- couldn't find any information on it in the FAQ or install guide.
### What happens
 "Could not create paste: unable to create directory data"

### What should happen
The paste should be created.

## Basic information

**Server address**: paste.facade.cf

**Server OS:** Ubuntu 20.10

**Webserver:** nginx/1.18.0 (Ubuntu)

I can reproduce this issue on <https://privatebin.net>: No

**Comment by elrido** [comment]
If your using nginx, your probably using php-fpm or -fcgi to execute the application. The user account of the php daemon is the one that needs to have write access. nginx only needs to read the static files. Installation of webserver and php is outside of the scope of this project, you'll find tons of guides on how to set this up on the distro of your choice.
