### ISSUE TITLE
Postgres support

### ISSUE THREAD

**Issue by elrido** [PrivateBin/PrivateBin#8]
@mathroc:

I tried ZeroBin with Postgres but it's not working because Postgres does not have a `blob` type. It could work with a `bytea` column but its usage is a bit different than a blob in mysql (it require serializing and unserializing the data)

---

@elrido:

Thanks for bringing this up!

I mainly used to BLOB type to circumvent issues with length limitations when using MySQL and storing larger attachments. The actual contents are always gzipped, encrypted and base64 encoded JSONs as you can see i.e. when looking a paste stored using the flat file model.

I will check what type is better suited for this in PostgreSQL.

**Comment by mathroc** [comment]
thank you, this is working nicely !
