### ISSUE TITLE
Access counter for pastes

### ISSUE THREAD

**Issue by FlightMS** [PrivateBin/PrivateBin#800]
As a creator of a paste i like to know if all people I‘ve shared the link for the paste saw it (or even more than I planned).

For this scenario, an access counter would be very useful, which will show how often the paste was opened.

**Comment by r4sas** [comment]
Because project is against of recording service usage, I think that won't be added.
Anyway, if it will be added, you'll never know if paste seen amount of times by every user itself, because someone can open your paste 5, 10, 100 times, so your counter would report incorrect data.

**Comment by rugk** [comment]
Yeah, I see it similarly…

Also technically it's again hard given the whole data handling is not intended on adding data after the paste has been created…

**Comment by elrido** [comment]
I think this request has been answered and as I agree with the above concerns, I'll close this with status "won't fix".
