### ISSUE TITLE
[question] get privatebin version programmaticaly

### ISSUE THREAD

**Issue by mhow2** [PrivateBin/PrivateBin#801]
Currently, privatebin version is publicly available at the bottom of the page when browsing the web content.

I'm looking for a way to retrieve several web services version remotely. In the case of PrivateBin I thought of we scrapping the version from HTML. Unfortunately, the div's class looks like `col-md-1 col-xs-4 text-center` which is not that handy for scrapping :D 

Of course the best would be to have a dedicated endpoint/page to retrieve the version.

**Comment by elrido** [comment]
Both, the PrivateBin fork, as well as the original ZeroBin, append the version as a GET-parameter to the main javascript's URL. We use it in the [PrivateBin directory](https://privatebin.info/directory/) to detect the version of an instance. You can find the relevant piece of code at, the third match will contain the version number:
https://github.com/PrivateBin/Directory/blob/48b29e490ad039d61576b7b9044954fabc9edf91/src/models.rs#L369-L370

Apart from the WebUI version, there is also a version in each paste. Details on those and how they differ can be found in the [wiki](https://github.com/PrivateBin/PrivateBin/wiki/Encryption-format#format-version-2-privatebin--13).

**Comment by mhow2** [comment]
Thanks ! That would be enough for me to scrap the version.

**Comment by rugk** [comment]
As I'm curious though, I'd like to ask for what reason do you want to scrape those, @mhow2? What do you want to make with these version numbers?
