### ISSUE TITLE
AbstractPersistence _store fails in a race condition

### ISSUE THREAD

**Issue by mvanholsteijn** [PrivateBin/PrivateBin#803]
## Steps to reproduce

1.  Run an intense load test  with 50 concurrent users
```shell-session
$ go install github.com/k6io/xk6/cmd/xk6@latest
$ xk6 build --with github.com/binxio/xk6-privatebin@v0.1.0
$ cat > test.js <<!
import http from 'k6/http';
import {
    sleep,
    check
} from 'k6
import privatebin from 'k6/x/privatebin';


export default function() {
    var params = {
        headers: {
            'X-Requested-With': 'JSONHttpRequest',
        },
    };
    var paste = privatebin.encrypt("hello world!");

    var result = http.post('https://privatebin.net', paste.body, params);
    if (check(result, {
            'post status 200': (r) => r.status === 200,
            'post ok': (r) => r.headers['Content-Type'].startsWith('application/json') && r.json().status === 0,
        })) {
        var url = `${result.url}?${result.json().id}`;
        var result = http.get(url, params);
        if (!check(result, {
                'get status 200': (r) => r.status === 200,
                'get data equal': (r) => r.headers['Content-Type'].startsWith('application/json') && JSON.stringify(r.json().adata) === JSON.stringify(JSON.parse(paste.body).adata)
            })) {
            console.log(result.url);
            console.log(result.body);
        }
    } else {
        console.log(JSON.stringify(result));
    }
    sleep(0.5);
}
!
$ ./k6  run -u 50 -i 1000 test.js
```

### What happens
Some requests throw the following exception:

```
PHP message: PHP Fatal error:  Uncaught Exception: unable to write to file /srv/data/purge_limiter.php in /srv/lib/Persistence/AbstractPersistence.php:121
Stack trace:
#0 /srv/lib/Persistence/PurgeLimiter.php(84): PrivateBin\Persistence\AbstractPersistence::_store()
#1 /srv/lib/Model.php(70): PrivateBin\Persistence\PurgeLimiter::canPurge()
#2 /srv/lib/Controller.php(257): PrivateBin\Model->purge()
#3 /srv/lib/Controller.php(125): PrivateBin\Controller->_create()
#4 /var/www/index.php(18): PrivateBin\Controller->__construct()
#5 {main}
```
By adding the following statement at that point:

```php
error_log(json_encode(error_get_last()));
```
I got the following message:

```json
{
  "type": 2,
  "message": "file_put_contents(/srv/data/purge_limiter.php): Failed to open stream: File exists",
  "file": "/srv/lib/Persistence/AbstractPersistence.php",
  "line": 118
}
```
This indicates that there we a race condition where two process wanted to write the file purge_limiter.php, when it did not yet exist. 

### What should happen
- no error in creating the file in race conditions.

## Additional information

The problem was solved by adding the following code to the `_store()` function:
```php
        // make sure the file exists before writing to it
        $handle = @fopen($file, 'x');
        if ($handle) {
            fclose($handle);
        }
```

## Basic information

**Server OS:** alpine:3

**Webserver:** nginx

**Browser:** N/A
 

**PrivateBin version:** 1.3.5

I *cannot* reproduce this issue on <https://privatebin.net> as there is a rate limiter active.
As it is a race condition, it is hard to reproduce. But I can get it to consistently occur when running privatebin on Cloud Run.

**Comment by elrido** [comment]
I can totally see this race condition occurring, but it should only occur during the initial creation. Afterwards these files are all present. Could you reproduce the error after the file got created?

It should be possible to reproduce this in the unit testing, maybe using child processes and loops to do lots of store() calls close together. I'll take a stab at it.

Also, I need to find a way to suppress the error_log() output in the unit tests, somehow.

**Comment by rugk** [comment]
THanks a lot for the report @mvanholsteijn. You seem to have comitted sth. which references this issue. So do you plan creating a PR?

If so, thanks a lot already! :smiley: 
(Also great of you finding this issue. :slightly_smiling_face:)

**Comment by mvanholsteijn** [comment]
@rugk I will create a PR. 

@elrido The error is very easily reproducible on Google Cloud Run, as it continuously spins containers up and down.

**Comment by elrido** [comment]
I need to be able to reproduce it locally, otherwise I can't debug it.

Reg. Google Cloud Run: Does that mean it doesn't persist the purge_limiter.php and or the server_salt.php between runs? Without this neither the automatic purging nor deleting pastes with a delete token will work. Surely Google, as the main K8s backer, has a persistent volume solution with accessType ReadWriteMany for backing the data directory of your containers?

**Comment by mvanholsteijn** [comment]
@elrido good point: more work to do then! The container spins up and down to 0 depending upon the load. For Cloud Run there is no persistent volume available. 

Sounds like I need to provide an alternative implementation for these functionalities too.

**Comment by mvanholsteijn** [comment]
As it is a race condition it is hard to reproduce.  I could not even reproduce it with the same container locally, probably because my machine is too fast: The configured Cloud Run container instance only has  a single vcpu and 512mb to do all the work.

**Comment by elrido** [comment]
I think this had been brought up with the database as well, that it was expected that those items would be stored in there as well. We could split the work up, I'd do the DB side and you the GCS one? Would we merge some methods from AbstractPersistence into the AbstractData class, so any persistence implementation can use it in any data storage?

The filename could be the key to store and retrieve these values, the server salt stores be a string, the purge limiter a unix timestamp and the traffic limiter an array of string keys (sha256 hashes) and unix timestamp.

**Comment by mvanholsteijn** [comment]
I will be glad to help and I can do the GCS support.

**Comment by elrido** [comment]
I'll create a ticket and a branch to collaborate on that.

The traffic limiter only gets updated for paste creation, we allow unlimited reads (except for the burn-after-reading pastes, but that is handled by deleting the paste on the first API view request).

The traffic limiter indeed is more of a separate key/value store. If the data storage abstraction would offer a get and put method for storing strings or ints, the implementation could decide how to handle it internally and filestorage may be the exception that stores the traffic in a single file. I don't intend to change that part, otherwise we would have to include upgrade mechanisms from the old file formats, etc.

**Comment by rugk** [comment]
Just as a brainstorming idea: If you rewrote it to be generic, one could use Redis instead of a SQL db or so for the traffic limiter then. Redis is much simpler and faster as far as I heart and it's actually built for what exactly you'd want to do here, i.e. store key/values and quick access them.
