### ISSUE TITLE
Each request generates a warning when the CONFIG_PATH points to a secret directory mount in Cloud Run

### ISSUE THREAD

**Issue by mvanholsteijn** [PrivateBin/PrivateBin#808]
When I deploy PrivateBin in Cloud Run, I am (mis)using the Google Secret Manager mount to the configuration without requiring to copy it into the container image. However, privatebin tests on every requests whether the file $CONFIG_PATH/conf.ini exists. This cause an warning message in the log on every request:

```
Could not open file at path /cloudcfg/conf.ini. The path is in a mounted secrets volume, but the exact path does not correspond to any secret specified in the mount configuration.
```

## Steps to reproduce
2. copy the following terraform template and run `terraform apply`
3. use pbincli to send a paste to the server.
4. check the Cloud Run log

```hcl
variable "region" {
  type    = string
  default = "europe-west4"
}

variable "project" {
  type    = string
}

variable "image" {
  type    = string
  default = "eu.gcr.io/binx-io-public/privatebin:v46"
}

provider "google" {
  project = var.project
  region  = var.region
}

provider "google-beta" {
  project = var.project
  region  = var.region
}

resource "google_cloud_run_service" "privatebin" {
  name     = "privatebin"
  location = var.region
  provider = google-beta

  template {
    spec {
      service_account_name  = google_service_account.privatebin.email
      container_concurrency = 5
      containers {
        image = var.image
        volume_mounts {
          name       = "config"
          mount_path = "/cloudcfg"
        }
        env {
          name       = "CONFIG_PATH"
          value      = "/cloudcfg"
        }
      }
      volumes {
        name = "config"
        secret {
          secret_name = element(reverse(split("/", google_secret_manager_secret.privatebin.name)), 0)
          items {
            key  = element(reverse(split("/", google_secret_manager_secret_version.privatebin.name)), 0)
            path = "conf.php"
          }
        }
      }
    }
  }

  metadata {
    annotations = {
      "run.googleapis.com/launch-stage" = "BETA"
    }
  }

  traffic {
    percent         = 100
    latest_revision = true
  }

  autogenerate_revision_name = true
}

resource "google_storage_bucket" "privatebin" {
  name          = format("private-bin-%s", var.project)
  location      = var.region
  force_destroy = true

  lifecycle_rule {
    condition {
      age = 30
    }
    action {
      type = "Delete"
    }
  }
}

resource "google_service_account" "privatebin" {
  account_id   = "privatebin"
  display_name = "PrivateBin"
}


resource "google_storage_bucket_iam_binding" "privatebin_object_admin" {
  bucket = google_storage_bucket.privatebin.name
  role   = "roles/storage.objectAdmin"
  members = [
    format("serviceAccount:%s", google_service_account.privatebin.email)
  ]
}

resource "google_cloud_run_service_iam_binding" "run_invoker" {
  location = google_cloud_run_service.privatebin.location
  project  = google_cloud_run_service.privatebin.project
  service  = google_cloud_run_service.privatebin.name
  role     = "roles/run.invoker"
  members = [
    "allUsers",
  ]
}

resource "google_secret_manager_secret" "privatebin" {
  secret_id = "privatebin-configuration"

  replication {
    automatic = true
  }
}


resource "google_secret_manager_secret_iam_binding" "privatebin_accessor" {
  project   = google_secret_manager_secret.privatebin.project
  secret_id = google_secret_manager_secret.privatebin.id
  role      = "roles/secretmanager.secretAccessor"
  members = [
    format("serviceAccount:%s", google_service_account.privatebin.email)
  ]
}

resource "google_secret_manager_secret_version" "privatebin" {
  secret      = google_secret_manager_secret.privatebin.id
  secret_data = <<EOF
[main]
name = "My Serverless PrivateBin"
discussion = true
opendiscussion = false
password = true
fileupload = false
burnafterreadingselected = false
defaultformatter = "plaintext"
sizelimit = 10485760
template = "bootstrap"
languageselection = false

[expire]
default = "1day"

[expire_options]
5min = 300
10min = 600
1hour = 3600
1day = 86400
1week = 604800
1month = 2592000
1year = 31536000
never = 0

[formatter_options]
plaintext = "Plain Text"
syntaxhighlighting = "Source Code"
markdown = "Markdown"

[traffic]
limit = 0

[purge]
limit = 300
batchsize = 10

[model]
class = GoogleCloudStorage

[model_options]
bucket = "${google_storage_bucket.privatebin.name}"
EOF 
}

output "privatebin_url" {
  description = "url of the privatebin service"
  value       = google_cloud_run_service.privatebin.status[0].url
}
```

### What happens
On every request, the following log message appears:
```
Could not open file at path /cloudcfg/conf.ini. The path is in a mounted secrets volume, but the exact path does not correspond to any secret specified in the mount configuration
```

### What should happen
Preferably I do not do get this message.

## Additional information

The log message is caused by the following code. As I do not have an .ini file, everything works normally.

https://github.com/PrivateBin/PrivateBin/blob/9b19a88bb9d4a3d4acc2258d30ba8cf8ea03b863/lib/Configuration.php#L113-L121

It would be nice if I could disable this check.

## Basic information

**Server address**: N/A

**Server OS:** N/A

**Webserver:** N/A

**Browser:** N/A

**PrivateBin version:** 1.3.5

I can reproduce this issue on <https://privatebin.net>:  No

**Comment by elrido** [comment]
Without access to the google cloud, I can't replicate this. Disabling or removing this would break the automatic migration of the ini into the PHP file - it was regarded as a security issue to keep those ini files, at the time, so removing it would re-introduce that issue. You could just create an empty ini file that isn't readable (restrictive permissions) to avoid the warning, if it bothers you? Maybe they have a flag to set to disable that log message, different log level or such?

**Comment by mvanholsteijn** [comment]
If i would add the file, privatebin would then try to rename it and attempt to delete the sample config file. Which would generate more errors. 

Perhaps by setting an environment variable  we can skip this test. Or alternatively, skip it if config_path does not point to a web or php source directory.

**Comment by elrido** [comment]
It checks if the file is readable, so a non-readable file shouldn't trigger any warnings.

Sorry, this is a corner case in a security sensitive area, introducing a way to disable it is not worth the risk to all the other users, IMO. You could always bake a custom image with your configuration already deployed, so there is no mount that catches this error. Or switch to the more powerful k8s - PrivateBin isn't designed as a FaaS, it requires a full stack.

**Comment by mvanholsteijn** [comment]
I understand that it is an edge case and that the log message a bit of an annoyance.  The odds that I can get Google to suppress this warning, are small :-) The reason that I thought I might have a change of getting a fix in the PrivateBin source is that CONFIG_PATH was designed for this type of deployment. 

_[situations where you want to keep the PrivateBin static files separate from the rest of your data, or you want to reuse the installation files on multiple vhosts, you may only want to change the conf.php. In this instance, you can set the CONFIG_PATH environment variable to the absolute path to the conf.php file. This can be done in your web server's virtual host config, the PHP config, or in the index.php if you choose to customize it.](https://github.com/PrivateBin/PrivateBin/blob/d355bb87e361787beb3258c9da5bc906ebc774db/INSTALL.md#changing-the-config-path-only)_ 

So if you have CONFIG_PATH specified *and* it does not point to a directory under /srv or /var/www, I would say it is acceptable to just read the config.php from the specified directory without changing it. 

On Google Cloud Run: Google Cloud Run is an implementation of Knative which is the specification to run serverless workloads on Kubernetes. You will only pay for the requests that are processed and it will scale from 0 to 1000 instances in the blink of an eye, allowing PrivateBin to handle 5000 requests simultaneously per region (With the 5 php handlers per container).  When the pastes are on Google Cloud Storage, PrivateBin can be provided with cross-region high availability and unlimited storage against very low cost.  GKE cannot scale that fast and the cost of running a cluster 24x7 are orders of magnitude higher.

**Comment by elrido** [comment]
@rugk, what is your handle on this? You may remember, we had introduced this change and the unusual feature of rewriting the configuration file in software as part of the mitigations for the [file leak vulnerability](https://privatebin.info/reports/vulnerability-2017-09-29.html) in version 1.1.1. Specifically, it is this section:
https://github.com/PrivateBin/PrivateBin/blob/9b19a88bb9d4a3d4acc2258d30ba8cf8ea03b863/lib/Configuration.php#L112-L121

If we tamper with this or remove it (I prefer the latter), installations older then 1.1.1 would (potentially) require a manual step to upgrade - rename the ini file and manually add the php-comment-header to mitigate the leak, if they use an insecure setup. On the other hand side, removing it will not affect any installations already on 1.1.1 or higher or those that don't use any configuration file and run on defaults. At least in the [directory](https://privatebin.info/directory/), only one instance of PrivateBin older than 1.1.1 is listed (the other is one that I use for testing, including in the unit tests for the directory).

I'd be fine with removing this section, but we should point this out in the next releases' upgrade notes - something like: "if you upgrade from < 1.1.1, please first upgrade to 1.3.5, then to this release, to ensure your configuration file gets migrated".

**Comment by rugk** [comment]
I'm also fine with removing it. There was plenty of time to upgrade.
Ideally, we would have marked it properly as deprecated before (the .ini file) and could then remove it. But well… just point it out as in the release notes that you would have to upgrade to 1.3.5, as you said, and I'm fine with it.
Actually, removing such unused code and stuff is always a good idea. Some cleanup here…

**Comment by mvanholsteijn** [comment]
Thank you, guys!
