### ISSUE TITLE
Make WebAssembly loading (for zlib) possible to use in Chrome/ium with a stronger CSP

### ISSUE THREAD

**Issue by rugk** [PrivateBin/PrivateBin#814]
The goal is to remove `unsafe-eval` from the CSP of PrivateBin.

## Reason it is included

> The `unsafe-eval` is required in Chrome and Safari for WASM loading. If not set, calling WebAssembly.instantiate will trigger an error in those browsers.
>https://github.com/PrivateBin/PrivateBin/blob/8232dce395e421450779bd710e5872399f792085/js/zlib-1.2.11.js#L34-L35
>
>- [Technical background](https://github.com/WebAssembly/content-security-policy/blob/master/proposals/CSP.md#summary-of-webassembly-apis-and-their-risks)
>- [Browser comparison matrix](https://github.com/WebAssembly/content-security-policy/blob/master/proposals/CSP.md#behavior-of-current-implementations)
>- [Proposal to W3C to standardize `wasm-eval` directive](https://github.com/w3c/webappsec-csp/pull/293), that Chrome has implemented for web apps, but not web sites, that would allow to restrict eval while allowing wasm. It hasn't been accepted and even if it will, it will take years for browsers with support for it to be rolled out for a majority of users. :-(

https://github.com/PrivateBin/PrivateBin/issues/108#issuecomment-821773679

**Edit:** As it turns out, [the change cannot actually fix the CSP problem](https://github.com/PrivateBin/PrivateBin/issues/814#issuecomment-864543105).

## Potential solution

> Regarding [`unsafe-eval` the Matrix Element client has the same issue and someone suggested](https://github.com/vector-im/element-web/issues/12262#issuecomment-864274860) this:
> > Using `WebAssembly.instantiateStreaming` would avoid this problem.
> 
> ---
> 
> Also [the docs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WebAssembly/instantiateStreaming) for this say:
> > This is the most efficient, optimized way to load wasm code.
>
> So would likely not be a bad idea to use this altogether…

https://github.com/PrivateBin/PrivateBin/issues/108#issuecomment-864372271

**Comment by elrido** [comment]
I did a quick experiment of changing it, and it does simplify the code a lot, but ran into several compatibility issues:
- fetch is not supported in some older browsers that otherwise do support WASM - that one is minor and we can choose to ignore it
- more problematic is need for delivering wasm files with a specific mime-type - as the linked doc states:
 > Note: For this to work, .wasm files should be returned with an application/wasm MIME type by the server.
 Even the current stable versions of [nginx](https://trac.nginx.org/nginx/ticket/1606) and [apache](https://bz.apache.org/bugzilla/show_bug.cgi?id=63162) this still isn't in the default MIME type lists for .wasm files, so it requires the server admin to manually add this to their configurations - we can do so in our docker image, but it may not be so easy for everyone.

I suggest we keep the known working and robust mechanism using the buffer, until this change landed in at least the two major web servers in stable releases and gets widely adopted.

Pushed my experimental change to the branch [wasm-streaming](https://github.com/PrivateBin/PrivateBin/tree/wasm-streaming) for future pick-up.

**Comment by rugk** [comment]
> we can do so in our docker image, but it may not be so easy for everyone.

Could we server different JS for our Docker image vs “standard installations”? Or somehow else do a feature detection?

BTW /cc’ing @DemiMarie in case you are interested.

**Comment by rugk** [comment]
So sad, [this issue is well-lnown](https://stackoverflow.com/a/52732080/5008962)…

So blocked by:
* nginx https://trac.nginx.org/nginx/ticket/1606, fixed 2021-08, don’t know in which release this will go though
* as for Apache it’s https://issues.apache.org/jira/browse/TIKA-2894, fixed in v1.23 (resolved in 2019-08)

I see [that the Raffle project](https://github.com/ruffle-rs/ruffle/wiki/Using-Ruffle#configure-webassembly-mime-type) apparently has a fallback implementation as it only “suggests” to add that MIME type.

**Comment by rugk** [comment]
Ah okay, of course the fallback is trivial: Just catch the error and go on…
The issue is, that we of course cannot tighten the CSP unless we can remove that fallback.

So I have an idea:
* Can we have a FAQ or Config doc for the CSP and that `unsafe-eval`?
* \+ The installation guide should mention that…
* Then in our PrivateBIn Docker image, we configure everything as we suggest and in addition do a `sed` on our config sample file to remove `unsafe-eval`?
* All other users are encouraged in the config file to remove `unsafe-eval` if they (can) add the mime-type they need.

**Comment by elrido** [comment]
Adding a fallback and a customization only supported in our docker image sounds incredibly fragile, to me and increases maintenance for us and our user base. I'm well motivated to switch to the streaming implementation, if it means reducing the amount of code (in the zlib loader and the CSP policy length).

But what exactly is the problem with `unsafe-eval` in your view? Can you please provide a scenario that can be mitigated by removing the `unsafe-eval` from the CSP? (a point by point description adapted for our product, not a link to some general description, please)

I did try to come up with attacks that are enabled by it, but the usual digs are around enabling crypto-miners or XSS through third-party libraries - we don't ship random third party libraries, we use SRI hashes so they can't be easily manipulated, we don't allow third-party domains to load JS in our CSP, so AFAIK the only things that can use eval and WASM are our own libraries that (I hope) we can/do trust in.

**Comment by elrido** [comment]
>     * as for Apache it’s https://issues.apache.org/jira/browse/TIKA-2894, fixed in v1.23 (resolved in 2019-08)

That is the Apache Tika project, not the Apache httpd webserver. AFAIK the ticket for httpd is at https://bz.apache.org/bugzilla/show_bug.cgi?id=63162 - last update on 2021-04-22, still unresolved.

**Comment by rugk** [comment]
I don’t see an immediate attack vector and if I would well… it would be a vulnerability. The thing about CSP is always defense-in-depth, so arguing like this brings us nowhere.

But it’s good to get a grasp of what usual bypasses are, that always assume an XSS vulnerability (e.g. in DOMPurify or when we – as with that [filename thing](https://github.com/PrivateBin/PrivateBin/security/advisories/GHSA-8j72-p2wm-6738) – miss to properly sanitize user input data).
[Here is a usual bypass that uses `unsafe-eval`](https://book.hacktricks.xyz/pentesting-web/content-security-policy-csp-bypass#unsafe-eval) (note combining it with `unsafe-inline` or more let’s it get more critical, i.e. weakens the protection provided by the CSP.)
It especially gets critical if one hosts PrivateBin in a subdirectory and [hosts other libraries like Angular](https://book.hacktricks.xyz/pentesting-web/content-security-policy-csp-bypass#third-party-endpoints-unsafe-eval) on the same domain.

---

That all said, I also like that it’s more performant of course and the way to load the WebAssembly directly while streaming is clever…

So let’s talk about how to tackle it again:

> Adding a fallback and a customization only supported in our docker image sounds incredibly fragile, to me and increases maintenance for us and our user base.

Not really. The fallback is just always there in the JS.

The only difference is the CSP, which is configurable anyway already – and well… the required webserver configuration, which we can only suggest…, but which is either supported or not. (and I guess if we want to support these LTS distros that will take some time anyway, so let’s rather have a fallback solution now. The other things are just a proper documentation – and the Docker image of course automates that documentation.)

**Comment by rugk** [comment]
Waait…
@DemiMarie are you sure about your inital statement?

Because that test page fails in Chromium and it uses `instantiateStreaming`: https://s3.amazonaws.com/webassembly-chrome-csp/csp_test.html

That is actually also already linked in https://github.com/WebAssembly/content-security-policy/issues/7.

So it does not fix our CSP problem. It’s “just” a performance and code optimisation then…

**Comment by DemiMarie** [comment]
> @DemiMarie are you sure about your inital statement?

Nope!  I thought that `instantiateStreaming` from a `Response` object would work, but apparently it does not.

**Comment by rugk** [comment]
Okay given the initial approach does not wwork for the given reasons, I see news on the Chrome/ium side though. Apprently you can now use `wasm-eval` instead of `unsafe-inline`…

ref https://github.com/w3c/webappsec-csp/pull/293#issuecomment-1011536030

**Comment by elrido** [comment]
Can you try that and if it works in modern chrome(ium, Edge, ...) and Safari, raise an PR to get this merged, please?

**Comment by rugk** [comment]
already got a reply that it does not work, and even if it would likely be too recent now (and Safari is a thing not even considered/tested yet): https://github.com/w3c/webappsec-csp/pull/293#issuecomment-1014726154

So let's have a look at this later…

**Comment by elrido** [comment]
We could now finally pick this one back up:

> Even the current stable versions of [nginx](https://trac.nginx.org/nginx/ticket/1606) and [apache](https://bz.apache.org/bugzilla/show_bug.cgi?id=63162) this still isn't in the default MIME type lists for .wasm files, so it requires the server admin to manually add this to their configurations - we can do so in our docker image, but it may not be so easy for everyone.
> [...]
> Pushed my experimental change to the branch [wasm-streaming](https://github.com/PrivateBin/PrivateBin/tree/wasm-streaming) for future pick-up.

Both of these now have added wasm to their default mime-type lists:
- https://trac.nginx.org/nginx/browser/nginx/conf/mime.types#L55
- https://github.com/apache/httpd/blob/trunk/docs/conf/mime.types#L1216

I'll update my branch, retest and see if we can resurrect this.
