### ISSUE TITLE
Update privatebin with composer

### ISSUE THREAD

**Issue by janstieler** [PrivateBin/PrivateBin#819]
Hi,
why is composer not updating privatebin itself?
I have installed privatebin using composer  but if i use composer update/upgrade depencies will update but not privatebin himself. Also how ca I update privatebin if I have installed it with composer and don't want to extract the zipfile from hand?

Cheers

**Comment by elrido** [comment]
I don't think this is an installation mechanism that we support. As far as I know we use composer only to maintain dependencies of the project, not to ship privatebin itself. The recommended installation method is to download and extract the archive file (tar or zip) or to use the container image.

**Comment by janstieler** [comment]
HI,
I thought I installed it through Composer but it's been a while so I could be wrong.
Okay second question. Would it not be a good idea to serve Privatebin through Composer?
It would make the update-process easier.

**Comment by rugk** [comment]
At least we did once publish it at Packagist (Composer): https://github.com/PrivateBin/PrivateBin/issues/55#issuecomment-234704829

**Comment by elrido** [comment]
I'm not sure if it got automated or not, but as of this writing an up to date version (1.4.0) seems published on there.
