### ISSUE TITLE
Use require-sri-for in CSP

### ISSUE THREAD

**Issue by rugk** [PrivateBin/PrivateBin#82]
Force browsers to check our [SRI](https://github.com/PrivateBin/PrivateBin/issues/6) by using [`require-sri-for`](https://github.com/w3c/webappsec-subresource-integrity/pull/32) in our [CSP](https://github.com/PrivateBin/PrivateBin/issues/10).

**Comment by elrido** [comment]
(partial copy of statement in #6) This is currently a proposal for an upcoming W3C standard of CSP and from what I have found there might be a by default disabled feature for it in the upcoming Chrome 54 and some not yet published development in Firefox. Hence there is currently no way to verify it is working as intended if we implement it now. We'll get back to it when it appears in the wild in stable browser versions.

**Comment by rugk** [comment]
See also https://scotthelme.co.uk/enforcing-the-use-of-sri/

This feature will be supported in Chrome 55 and as Scott says:
> Much like other CSP directives though, you can enable the new directive now and browsers will simply start to enforce it once support is added.

**Comment by elrido** [comment]
Whut? [Seems like Firefox supported this, but pulled the feature again.](https://caniuse.com/#search=require-sri-for) The only statement reg. why I found was on [MDN web docs](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/require-sri-for):

> This feature is obsolete. Although it may still work in some browsers, its use is discouraged since it could be removed at any time. Try to avoid using it.

So now Chrome is the only browser to have this. *scratches-head*

**Comment by rugk** [comment]
Still deprecated, so not really a good candidate to implement, unfortunately…
