### ISSUE TITLE
I have 2 issues!

### ISSUE THREAD

**Issue by Duke4125** [PrivateBin/PrivateBin#820]
I have 2 isseus. << URL(S) >> main domain https://duke.ml/
paste domain > https://paste.duke.ml/

1) When i goto the mian url for my website it come's up with **Forbidden
You don't have permission to access this resource.**

2)  I make changes to the config / language files and nothing changes on the live website... 

Discord: Dukx#6969

**Comment by rugk** [comment]
We cannot fix or provide help with unrelated issues of your website.

In general please just follow our official docs, depending hwo you've installed it: https://github.com/PrivateBin/PrivateBin/blob/master/INSTALL.md

> I make changes to the config / language files and nothing changes on the live website...

If you mean the English language, that is not used by PrivateBin actually, see #514.
As for all other languages it should work.

**Comment by rugk** [comment]
So as it seems this question has been answered and I thus close this issue. If anyone has further questions on that topic, feel free to comment here, again.
