### ISSUE TITLE
Problem with installation

### ISSUE THREAD

**Issue by sushinger** [PrivateBin/PrivateBin#822]
Hello

I have difficulties understanding the installation and upgrade process. I'm not a developer, but would love to use PrivateBin on my webserver.

Google search for has brought me here:

https://github.com/PrivateBin/PrivateBin/blob/master/INSTALL.md#installation

from I was asked to visit the "latest release" page. There I found 4 assets at the bottom.

So I have downloaded the first one "PrivateBin-1.3.5.tar.gz.asc" and tried to extract that on my webserver, but couldn't extract the file, not even after renaming it to "PrivateBin-1.3.5.tar.gz" or "PrivateBin-1.3.5.tar".

Is there anyone here who can explain the installation and upgrading process for non-developers and provide a file that I can simply upload and extract?

Thanks
Sushi

**Comment by r4sas** [comment]
`PrivateBin-1.3.5.tar.gz.asc` is digital signature of release file. Use item `Source code (tar.gz)` for downloading release.

**Comment by rugk** [comment]
@sushinger Created a PR at https://github.com/PrivateBin/PrivateBin/pull/823 to clarify the instructions. Please let us know (e.g. just by reviewing there/using the GitHub review tools), whether that is sufficient.
