### ISSUE TITLE
Docker Conf.php doesn't get applied

### ISSUE THREAD

**Issue by SoulofSorrow** [PrivateBin/PrivateBin#826]
Hello, I have the same problem my docker container does not load the config. Unfortunately I do not understand why. I have checked the mount path, the env variable and the config file. Do I have to pay attention to anything with docker?

**Comment by rugk** [comment]
Wrong repository, but apparently you already found the correct one.

**Comment by rugk** [comment]
Duplicate of https://github.com/PrivateBin/docker-nginx-fpm-alpine/issues/60
