### ISSUE TITLE
Powershell Integration

### ISSUE THREAD

**Issue by f22l2** [PrivateBin/PrivateBin#827]
as I don't see any working powershell integration anywhere (to allow invoke-webrequest with post to get the url), I'd like to contribute with such, but got an issue with understanding this part of documentation:

`cipher_text = cipher(AES(kdf_key), GCM(iv, paste_meta), paste_blob)`

by my understanding would be to use AES with GCM mode using kdf_key generated by Rfc2898DeriveBytes on the paste_blob

`$keygen   = [System.Security.Cryptography.Rfc2898DeriveBytes]::new($paste_password, $kdf_salt_size, $kdf_iterations, "SHA256");`

and then 

    $aesGcm = [Security.Cryptography.AesGcm]::new($kdf_key)`
    $messageBytes = $paste_blob;
    $nonce = $keygen.GetBytes(12)
    $tag = [byte[]]::new(16);
    $assocData = [byte[]]::new(12)
    $cipherText = [byte[]]::new($messageBytes.Length)
  
    $aesGcm.Encrypt($nonce, $messageBytes, $cipherText, $tag, $assocData)`

so that $paste_blob would be encypted, and IV would be our nonce as we are using GCM in AES, but this logic put me into 
`"Cannot decrypt paste: Decryption key missing in URL (Did you use a redirector or an URL shortener which strips part of the URL?)". ` 

as basically paste_meta was not used, but actually not sure where to put it...

so if that might be more described in the https://github.com/PrivateBin/PrivateBin/wiki/Encryption-format would be more then welcome.

Thanks in advance

**Comment by elrido** [comment]
The paste_meta is used as the associated data for message authentication (it needs to be unencrypted for the client to parse the message correctly, but if manipulated by a third party after encryption, the message fails to decrypt - if the message decrypts, the associated data is authentic) and the [paste ID has to be 32 bytes long](https://github.com/PrivateBin/PrivateBin/blob/d65bf02d7819a530c3c2a88f6f9947651fe5258d/js/privatebin.js#L1415), so my guess is:

```
$aesGcm = [Security.Cryptography.AesGcm]::new($kdf_key)`
$messageBytes = $paste_blob;
$nonce = $keygen.GetBytes(32) // the paste ID is 32 bytes long - shorter IDs won't be accepted
$tag = [byte[]]::new(16);
$assocData = Encoding.UTF8.GetBytes($pasteMeta) // a raw UTF-8 string, containing compacted JSON, i.e. [["oXNJqsy23JuvJ8lSnCzANw==","nNliDGmH8zQ=",100000,256,128,"aes","gcm","zlib"],"plaintext",0,0]
$cipherText = [byte[]]::new($messageBytes.Length) // the encrypted data is usually somewhat longer than the plain text, due to AES being a block cipher - the last block gets padded with zero bytes after the end of the message

$aesGcm.Encrypt($nonce, $messageBytes, $cipherText, $tag, $assocData)
```

It's not explicitly mentioned in the doc, since it seems to be a common practice in many crypto libraries, but since the .NET one seems to return `$cipherText` and `$tag` separately, they do need to be concatenated to form the full message. See for example this python implementation:
https://github.com/r4sas/PBinCLI/blob/0.3.1/pbincli/format.py#L295

**Comment by rugk** [comment]
SIde-note: @f22l2 if you are developing a PowerShell client/library and it is finished, it would be [great if you could publish/link that on our third-party clients wiki page](https://github.com/PrivateBin/PrivateBin/wiki/Third-party-clients).

**Comment by f22l2** [comment]
thanks a lot @rugk & @elrido. Overall I've changed most of the code yesterday night. One thing that might be problematic is that nonce size supported in MS (I'm using PowerShell 7.1.3) can be 12 bytes (96 bits) as you can see:

![image](https://user-images.githubusercontent.com/89009922/129687006-2c9c0627-3932-455f-b9e1-ade3a4909601.png)

whenever using >96 `MethodInvocationException: Exception calling "Encrypt" with "5" argument(s): "The specified nonce is not a valid size for this algorithm. (Parameter 'nonce')"`

Overall code that I've changed:

```

  function Get-SymmetricKey
   {
      
       param([parameter(mandatory=$true)][int]$bytes)

       $randomizer       =  New-Object System.Security.Cryptography.RNGCryptoServiceProvider;
       $random           =  [System.Byte[]]::new($bytes) #256bits
       $randomizer.GetBytes($random);
       return $random

       
    }

    $paste_password       = "password";    #for test only 
    $UTF8_paste_password  = [System.Text.Encoding]::UTF8.GetBytes($paste_password);

    $key     = Get-SymmetricKey -bytes 32;
    $en_key  = [convert]::ToBase64String($key);
    
    $iv      = Get-SymmetricKey -bytes 12 #96bits
    $salt    = Get-SymmetricKey -bytes 8  #64bits

    $keygen   = [System.Security.Cryptography.Rfc2898DeriveBytes]::new(($key + $UTF8_paste_password), $salt, 100000, "SHA256") 
    $kdf_key  = $keygen.GetBytes(32);


    $base64salt = [convert]::ToBase64String($salt);
    $base64iv   = [convert]::ToBase64String($iv);

    #$adata is paste_meta;
    $adata    =  @{ adata = @(@("$base64iv","$base64salt",100000,256,128,"aes","gcm","none"),"plaintext",0,0) } | ConvertTo-Json -Compress;
   #example of adata {"adata":[["gVfFthU01nLleOCk","smjAdttr/WY=",100000,256,128,"aes","gcm","none"],"plaintext",0,0]}

    $paste_data = @{ paste = "text"
                     attachment =  "filename"
                     attachment_name = "filename.ext" 
                     children = @( "paste_id#$($en_key)", "https://privatebin.xyz" )} |  ConvertTo-Json -Compress;
    #example {"attachment_name":"filename.ext","children":["paste_id#PilNZVvCjj50sNYi8CGhVuKGiF+Z6zTJORETYpSxcq0=","https://privatebin.xyz"],"paste":"text","attachment":"filename"}                   

    $aesGcm = [Security.Cryptography.AesGcm]::new($kdf_key)
    $messageBytes = [System.Text.Encoding]::UTF8.GetBytes($paste_data);
    $tag = [byte[]]::new(16);
    $assocData = [System.Text.Encoding]::UTF8.GetBytes($adata);
    $cipherText = [byte[]]::new($messageBytes.Length)
  
 
    #void Encrypt(byte[] nonce, byte[] plaintext, byte[] ciphertext, byte[] tag, byte[] associatedData)
    $aesGcm.Encrypt($iv, $messagebytes, $cipherText, $tag, $assocData)

    $base64ct =   ([convert]::ToBase64String($cipherText + $tag));


    $postbody = @{
                   v= "2"
                   adata = @(@("$base64iv","$base64salt",100000,256,128,"aes","gcm","none"),"plaintext",0,0)
                   ct = "$($base64ct)"      
                   meta = @{
                       expire = "5min"
           }
   }

   $body = $postbody | convertto-json | out-string;
   $URI =  "https://privatebin.xyz"
   $header = @{"X-Requested-With" = "JSONHttpRequest"}
   Invoke-RestMethod -Method POST -Uri "$($uri)" -Headers $header -Body $body -Credential $cred

```
where:

![image](https://user-images.githubusercontent.com/89009922/129711454-8c89fdbd-4336-41d4-b6fe-5538a41c7c20.png)

but still results are the same, receiving the url 

![image](https://user-images.githubusercontent.com/89009922/129711617-535ee6e7-e2be-4811-b2d3-a4ede632b7d0.png)

but even if I will combine it with paste_id to following format:  
[/admin.php?5b80afdeaaef110e#PilNZVvCjj50sNYi8CGhVuKGiF+Z6zTJORETYpSxcq0=](url)

I'm being asked for  $paste_password  for decryption, but it doesn't work. So I'm thinking to rewrite it once again using bouncycastle where I would be able to use different nounce size, but if you'd be so kind to confirm if there is no issue with the logic, I will be very grateful.

**Comment by elrido** [comment]
I am unsure about the initialization of `$cipherText` as a byte array of a fixed length. AFAIK AES will pad the last block with zero bytes, so it can be longer than the plain text message, presumably it gets rounded up to the next 16 byte / 128 bit block offset. But that is implementation dependent, so you'd need to check the docs of your language/library to learn what to provide here to be safe that no part of the last block gets cut off.

**Comment by xXBuilderBXx** [comment]
The code above seems to be asking for a password even if none is specified for some reason

**Comment by xXBuilderBXx** [comment]
The code above seems to be asking for a password even if none is specified for some reason @lyra-edmundson

**Comment by rugk** [comment]
@lyra-edmundson did you ever put that into a proper repo or published it, BTW? If so, you could add it to our list of third-party clients: https://github.com/PrivateBin/PrivateBin/wiki/Third-party-clients

**Comment by AlastorVance** [comment]
Thank's for your work @lyra-edmundson 
Do you have a licence on it ?

**Comment by AlastorVance** [comment]
Hello,

Actually, I had a use for it and didn't wait for the reply.
You'll find a script at the following link: https://github.com/AlastorVance/Send-ToPrivateBin
Thank you very much @lyra-edmundson for the original code.

**Comment by lyra-edmundson** [comment]
That's great @AlastorVance, no problem. :)
