### ISSUE TITLE
Coding restrictions: Require review for everything going into the main branch

### ISSUE THREAD

**Issue by rugk** [PrivateBin/PrivateBin#830]
I would propose to let all things be reviewed and tested by our CI before it is merged. This is a proper coding standard of course, and one only needs to adjust some settings to make it happen. I'd propose this:

![image](https://user-images.githubusercontent.com/11966684/130865671-ea18c410-0898-462d-a645-2d6c0b105a77.png)

Is everything fine with that, @PrivateBin/maintainers?

**Comment by elrido** [comment]
FYI, I had to relax the settings of these two projects to get the 1.4 release done, as no one had time to review my branches. I suggest we keep it that way until we have more maintainers or more activity. I'll still try and work in branches and with PRs for review, to see if the situation changes.
