### ISSUE TITLE
footer removal

### ISSUE THREAD

**Issue by RedBull17-code** [PrivateBin/PrivateBin#831]
is it possible to remove the footer where the description and how can i do it without breaking the code
![footer for PrivateBin](https://user-images.githubusercontent.com/84050344/131655637-c70bd767-750f-48dc-b71c-ebbd20a71199.jpg)

**Comment by RedBull17-code** [comment]
also remove/hide editor and preview option

**Comment by elrido** [comment]
> is it possible to remove the footer where the description and how can i do it without breaking the code

Yes, small design changes like these are exactly the purpose of our simple to use template system. Have a look at: https://github.com/PrivateBin/PrivateBin/wiki/Templates#creating-templates

> also remove/hide editor and preview option

You could hide it with CSS rules in your template, but it is a pretty integral feature of this tool, so it will likely have unintended consequences if you do so.

**Comment by rugk** [comment]
So as it seems this question has been answered and I thus close this issue. If anyone has further questions on that topic, feel free to comment here, again.
