### ISSUE TITLE
Disable CSP

### ISSUE THREAD

**Issue by pebu1337** [PrivateBin/PrivateBin#837]
What files would need to be changed to disable CSP? CSP currently breaks my site as for some reason it prevents the js files in /lib from loading. They have not been modified and I have tried both the current repo and the last stable release with the same issue.
All javascript optimizations are disabled on cloudflare.
[paste.pebu.xyz](url)

**Comment by pebu1337** [comment]
Or alternatively, how would I modify the integrity attributes to the SHA-256 that the console spits out at me?

**Comment by elrido** [comment]
For future reference, the CSP header is a [configuration item and is documented in the wiki](https://github.com/PrivateBin/PrivateBin/wiki/Configuration#cspheader). The integrity attributes can be changed or removed in the used template.

**Comment by rugk** [comment]
Please note that doing anything of these two steps **heavily weaken the security of your PrivateBIn instance** and it is **not recommend to do so**.

The SRI may not be the biggest problem as long as it is hosted on your own server, but CSP removes a whole layer of defense against probably _the_ biggest . Please inform yourself about the used technologies before mangling with them.

From your description, it sounds as if you have **SRI** errors, not CSP ones. As such, please read the corresponding FAQ questions: https://github.com/PrivateBin/PrivateBin/wiki/FAQ#why-does-the-loading-message-not-go-away
We have a lot of them covering many error cases, where that issue may happen, the biggest potentially being that you use Cloudflare, with a configuration that modifies the JS files.
