### ISSUE TITLE
Sign git commits

### ISSUE THREAD

**Issue by rugk** [PrivateBin/PrivateBin#85]
We should consider signing git commits.

* https://github.com/micahflee/onionshare/issues/221#issuecomment-220317661
* It is also displayed on GitHub: https://github.com/blog/2144-gpg-signature-verification
* Here is GitHub's help for this: https://help.github.com/articles/generating-a-gpg-key/

So if we decide to do this, there are some questions:
* Only, @elrido, you sign it with your key?
* Or we could use one master key and (if that is possible with git - I have not looked into it) use subkeys for contributors in PrivateBin organisation. Might be less secure if we get evil devs (:laughing:)... But you, @elrido, could maybe revoke the subkey in this case.

**Comment by rugk** [comment]
Of course, we should also sign tags (releases) in this case.

**Comment by elrido** [comment]
I would consider signing the tags of the releases. What would be the benefit of signing the commits? Protection against intruders cracking our github accounts and committing in our names?

**Comment by rugk** [comment]
Well... at least I can say I have 2FA enabled, so breaking in may not be easy. :smiley: 

But signing commits is good for these reasons:
* Users may - as you know and propose - want to use nightly versions of PrivateBin and for users that care this provides the possibility to not only verify releases, but also commits.
* It does not hurt, it can be done automatically.
* One can verify that the person who committed this is - really - me. This would likely be the "break in into GitHub accounts" scenario.
* One can see if a commit is not signed that there is something wrong. Did the account got compromised? Had the author need to implement a backddor*?
* When commits are signed all of the commits can be verified.

However as I am keen to more reasons for this, I missed here, [I've asked a question](https://security.stackexchange.com/questions/134164/why-should-i-sign-git-commits-tags-should-i-sign-both-commits-and-tags).

* To prevent this - we could include "I did not implemented a backdoor with this commit." in each commit we push and as the commit is signed, not even a National Security Letter. This is how these warrants work, but yeah... I am not really serious about this. Actually we both cannot get NSLs...

**Comment by rugk** [comment]
I began to sign commits. The public key for verification can for now be found [here](https://raw.githubusercontent.com/rugk/test/master/RugkGitSoftwareSignKey.txt).

Now just waiting for @elrido to sign commits too.

**Comment by elrido** [comment]
I did set up a key and I published our keys on [PrivateBin.info/credits.html](https://privatebin.info/credits.html). The last release is now also signed.
