### ISSUE TITLE
PHP Fatal Error JSON character encoding issue on file uploads 

### ISSUE THREAD

**Issue by jimbyau** [PrivateBin/PrivateBin#853]
I am unable to get file attachments to upload/paste above a few hundred KB.  Very small files work. Browser just sits there thinking.  This error below appears in the PHPerror.log.  I wasn't been able to reproduce this error on a couple of other public instances, the same 1MB upload test file works fine.  I have tried PHP 7.4 and 7.3.   Project version is 1.3.5.

you eventually get an error in the browser:
Could not create paste: server error or not responding.

[27-Oct-2021 11:19:41 UTC] PHP Fatal error:  Uncaught Exception: A JSON error occurred: Control character error, possibly incorrectly encoded (3) in /home/securedropcloud/privatebin/lib/Json.php:76
Stack trace:
#0 /home/securedropcloud/privatebin/lib/Json.php(52): PrivateBin\Json::_detectError()
#1 /home/securedropcloud/privatebin/lib/Request.php(112): PrivateBin\Json::decode('{"adata":[["g3U...')
#2 /home/securedropcloud/privatebin/lib/Controller.php(163): PrivateBin\Request->__construct()
#3 /home/securedropcloud/privatebin/lib/Controller.php(121): PrivateBin\Controller->_init()
#4 /home/securedropcloud/public_html/index.php(18): PrivateBin\Controller->__construct()
#5 {main}
  thrown in /home/securedropcloud/privatebin/lib/Json.php on line 76

Couldn't find anything on this issue.  Ideas?

**Comment by r4sas** [comment]
Anyway I think there promblem in webserver (apache?), because cutted request provided to php from it.
