### ISSUE TITLE
 Could not create paste: Error saving paste. Sorry.

### ISSUE THREAD

**Issue by zzb16888** [PrivateBin/PrivateBin#857]
## Steps to reproduce

1.
2.

### What happens
 Could not create paste: Error saving paste. Sorry.

## Basic information

**Server address**:

**Server OS:**

**Webserver:**

**Browser:**

**PrivateBin version:**

I can reproduce this issue on <https://privatebin.net>: Yes / No

**Comment by r4sas** [comment]
Please fill issue template.

**Comment by rugk** [comment]
We miss information here and no reply was provided, so I'll close this issue.
