### ISSUE TITLE
PrivateBin API Wiki for "create comment" POST request contains an error

### ISSUE THREAD

**Issue by shivanandvp** [PrivateBin/PrivateBin#861]
## Steps to reproduce

1. Open https://github.com/PrivateBin/PrivateBin/wiki/API
2. Check https://github.com/PrivateBin/PrivateBin/wiki/API#as-of-version-13 for the POST request of the "create comment" action 

### What happens
The POST request for "create comment" _currently_(as of Dec 4, 2021) shows the "data to send" as `{"v":2,"adata":["base64 encoded iv","base64 encoded salt",100000,256,128,"aes","gcm","zlib"],"ct":"base64 of cipher text"}`

### What should happen
1. The `data to send` should contain `pasteid` and `parentid`. I obtained these from my Browser console.
2. Also, the source data for cipher text should be added to the encryption format page: https://github.com/PrivateBin/PrivateBin/wiki/Encryption-format

## Basic information

**Server address**:

**Server OS:**

**Webserver:**

**Browser:**

**PrivateBin version:**

I can reproduce this issue on <https://privatebin.net>: Yes / No

**Comment by rugk** [comment]
Thanks a lot for this report. @elrido can you confirm these findings?

Please also note the wiki is publicly editable, but if you are not sure about a value, it's actually good to open an issue as you did.

**Comment by elrido** [comment]
From the description in the top of the linked section:
> The full PUT and POST data now is expected to be sent as a JSON string instead of URL-encoded form data. Please see the [encryption format](https://github.com/PrivateBin/PrivateBin/wiki/Encryption-format) page for details on the JSON string format.

So it probably would be less confusing if we removed the "Data to send" column or linked the relevant JSON-LD schemas that describe the full formats. Objections?

**Comment by rugk** [comment]
No, IMHO a link to a canonical reference is a good idea.

**Comment by elrido** [comment]
Done

**Comment by shivanandvp** [comment]
The earlier format was less confusing, in my opinion
