### ISSUE TITLE
PrivateBin API Wiki on encryption format does not specify comment data json

### ISSUE THREAD

**Issue by shivanandvp** [PrivateBin/PrivateBin#862]
## Steps to reproduce

1. Visit https://github.com/PrivateBin/PrivateBin/wiki/Encryption-format
2. In https://github.com/PrivateBin/PrivateBin/wiki/Encryption-format#preparation, look for `comment_data_json`

### What happens
As of Dec 5, 2021, 
1. Only `paste_data_json` is found, not `comment_data_json`. 
2. There is no information about the requirements that the password for the PBKDF2 key generation for comment data should be the same as the random password for the paste (which can be obtained by bs58 decode of the decryption key from the URL)

### What should happen
1. There should be information about the structure of `comment_data_json`. I see from https://github.com/PrivateBin/PrivateBin/blob/5a9bcea3a919af84e275dc77c80ea270272a4663/js/types.jsonld#L24 that it should be something like
```
        {
		"comment": "comment text"
		"nickname": "nickname text"
	}
```
2. Also to be mentioned is that the *random password* for the key generation for the comment should be the **same** as the *random password* for the key generation for the paste. The *random password* for the PBKDF2 key can be obtained by base58 decode of the decryption key from the URL which appears after the # sign. I found this by trial and error over days, trying to figure out why there was always a JSON error while decrypting a newly commented paste. I compared the POST requests generated through code vs that done by the browser.

## Basic information

**Server address**:

**Server OS:**

**Webserver:**

**Browser:**

**PrivateBin version:**

I can reproduce this issue on <https://privatebin.net>: Yes / No

**Comment by elrido** [comment]
The encryption mechanism is the exact same, so only the one form is documented. You have correctly identified the [JSON-LD](https://json-ld.org/) schema that are referenced in every response, as to make them self-documenting. The reply for fetching a comment will refer to this document:
https://github.com/PrivateBin/PrivateBin/blob/e36a94cfdda5205920f4c58fdf05ea29d0bae507/js/comment.jsonld#L25-L27
The pb prefix is documented in the types, as seen further up in the same document:
https://github.com/PrivateBin/PrivateBin/blob/e36a94cfdda5205920f4c58fdf05ea29d0bae507/js/comment.jsonld#L4
And as you found, the types schema explains the structure of the `CommentCipherMessage`:
https://github.com/PrivateBin/PrivateBin/blob/e36a94cfdda5205920f4c58fdf05ea29d0bae507/js/types.jsonld#L24-L31
and that it expects text as defined by schema.org:
https://github.com/PrivateBin/PrivateBin/blob/e36a94cfdda5205920f4c58fdf05ea29d0bae507/js/types.jsonld#L3
