### ISSUE TITLE
Simple REST examples in Wiki

### ISSUE THREAD

**Issue by Samuel-Dittmann** [PrivateBin/PrivateBin#865]
Hey there,

Im just looking for a simple example of a REST POST request for creating a paste. Im using Postman and it just returns errors or a blank response. The wiki contains a sample JSON body with unlabeled variables so Im not even sure what needs to be replaced. Can anybody provide an example REST body for me to work on?

**Comment by r4sas** [comment]
I don't think that PrivateBin paste can be queried with REST.
Everything can be found [here](https://github.com/PrivateBin/PrivateBin/wiki/API#as-of-version-13) and [here](https://github.com/PrivateBin/PrivateBin/wiki/Encryption-format).

Examples can be found in [third-party clients](https://github.com/PrivateBin/PrivateBin/wiki/Third-party-clients).

**Comment by rugk** [comment]
So as it seems this question has been answered and I thus close this issue. If anyone has further questions on that topic, feel free to comment here, again.
