### ISSUE TITLE
Self-hosted kutt.it URL shortener integration

### ISSUE THREAD

**Issue by fsociety3765** [PrivateBin/PrivateBin#866]
Hi,

I have a self-hosted PrivateBin instance up a running. All is working as expected.

I am trying to get the URL shortener integration working. I am using a self-hosted URL shortener called Kutt [(https://kutt.it)](https://kutt.it) which is not mentioned in the docs. Kutt requires the API key to be set within the header of the API request prefixed with X-API-KEY [(https://docs.kutt.it)](https://docs.kutt.it).

Is this possible to achieve this with PrivateBin? I can't see any options in the config for adding headers to the API calls.

Thanks,

FS

**Comment by rugk** [comment]
Did you have a look at the [this FAQ question](https://github.com/PrivateBin/PrivateBin/wiki/FAQ#the-url-is-so-long-cant-i-just-use-an-url-shortener)? I don't recall the exact implementation currently, but AFAIK it cannot send any header. (Also you of course would need proper CORS headers to allow JS calls from a different domain etc.)

**Comment by fsociety3765** [comment]
Thank you. Yes, I did see that FAQ. 

Doesn't look like it is possible then with the Kutt API. 

Yes the CORS issue is a separate issue that I was hoping I could solve in the Nginx config for Kutt.
