### ISSUE TITLE
Running PrivateBin on Oracle database

### ISSUE THREAD

**Issue by austinhuang0131** [PrivateBin/PrivateBin#868]
Quote INSTALL.md:

> The `Database` model has only been tested with SQLite, MySQL and PostgreSQL, although it would not be recommended to use SQLite in a production environment. If you gain any experience running PrivateBin on other RDBMS, please let us know.

Hereby I am informing you that I have successfully adapted PrivateBin to an Oracle database (OCI). The source code is available [here](https://codeberg.org/austinhuang.me/privatebin-oci). There is an online demo on my server, ~~but I don't think it's production-ready~~.

**Comment by rugk** [comment]
Awesome and thanks for letting us know. As you see in the issue tracker, there was no real demand to be compatible with Oracle DBs, so it is not implemented yet.

As you write by yourself:
> If you're running a database locally, why even bother with Oracle?)

…so well, I guess most instances are quite small and use it like this.

But well… your reasoning is not a bad one… :upside_down_face: 

----

So after all, do you plan to submit these changes upstream i.e. here?
If they stay compatible to the current used DB options and are well-tested, I – theoretically – for now see nothing wrong with supporting another DB type?

**Comment by austinhuang0131** [comment]
Each Oracle Cloud VM only has 45 GB of space, so for someone who's planning on hosting multiple services *for fun*, it's an unnecessary strain. Though, since I'm a beginner, I may have not properly gauged how much space PrivateBin would take lol

---

> So after all, do you plan to submit these changes upstream i.e. here?

You can take any changes as needed, but because I have no formal knowledge of PHP, the implementation as of now is practically a hack and is probably *very dirty*. Some review/advice would be appreciated.

> If they stay compatible to the current used DB options

Yes.

> and are well-tested

I have tested create/read pastes/comments/attachments, as well as deleting pastes (manually or by expiry), so *it should be fine*.
