### ISSUE TITLE
How to integrate with Analytics (e.g. Google Analytics)?

### ISSUE THREAD

**Issue by okainov** [PrivateBin/PrivateBin#874]
Is there a simple/recommended way to add some script/JS/analytics to my instance of Privatebin? I'd like to add Google Analytics, but I don't really want to modify main source code too much, would be great if there is some easy solution here...

**Comment by elrido** [comment]
I'd recommend having a look at the [template system](https://github.com/PrivateBin/PrivateBin/wiki/Templates). You can just copy an existing template and add your additional script tags into the HTML.

I do personally think that adding tracking to tool designed to collect as little information on visitors as possible (for a web application) seems to undermine part of it's appeal, but this is free software after all.
