### ISSUE TITLE
php warning in bootstrap template

### ISSUE THREAD

**Issue by reneluria** [PrivateBin/PrivateBin#875]
## Steps to reproduce
1. run PrivateBin in recent PHP versions (like 8.1.*)

### What happens
This error is displayed:

Deprecated: strlen(): Passing null to parameter #1 ($string) of type string is deprecated in /var/www/html/PrivateBin/tpl/bootstrap.php on line 36

## Additional information

![Capture d’écran 2022-02-03 à 13 31 21](https://user-images.githubusercontent.com/1652160/152343320-718fbef8-ea02-4bba-981e-6b45a9a1398c.png)

## Basic information

**Webserver:**

php-fpm 8.1

**PrivateBin version:**

1f872167c181931f866e4902d91b23888b220ad6

**Comment by elrido** [comment]
Did you by any chance set the `syntaxhighlightingtheme` to an empty string in your configuration file, that might have gotten cast to `null`? I failed to reproduce this so far, as it normally is a non-empty string.

**Comment by elrido** [comment]
I have now had the time to test this using our alpine:edge based container and I don't get any such warnings on php81. I'll therefore close this report as not reproducible. @reneluria, if you would like, please share your (redacted) conf.php file or at least all the `syntaxhighlightingtheme` related settings of it, I can help you set these correctly, so you don't get any such warning about empty keys.

**Comment by reneluria** [comment]
Hello @elrido here you have the material to reproduce

https://github.com/reneluria/PrivateBin/blob/kube/deploy/README.md

It's basicaly two docker images and manifests to run them on kubernetes

I've put all together to be able to test with [kind](https://kind.sigs.k8s.io/)

**Comment by elrido** [comment]
If I understand correctly, you are building a custom image in that setup - I haven't found your custom configuration, that could explain why you get these warnings, while we don't in our image - it's not a PHP 8.1 issue per se, even older PHP 7.x versions could get such an error, if you'd manage to set these configuration values to `null`.

Have you tried the projects [tailor-made image](https://hub.docker.com/r/privatebin/nginx-fpm-alpine/), which includes an nginx web server or the [example kubernetes deployment](https://github.com/PrivateBin/docker-nginx-fpm-alpine#kubernetes-deployment), or the [helm chart](https://github.com/PrivateBin/helm-chart#privatebin-helm-chart)? Is there anything we can improve about these?

**Comment by reneluria** [comment]
Well, the documentation says you can use the default configuration, this is what I did,
and by default, the value of `syntaxhighlightingtheme` is `null`:

https://github.com/PrivateBin/PrivateBin/blob/master/lib/Configuration.php#L47

regarding the "tailer-made image", I hadn't notice there was a wiki mentioning it, sorry

**Comment by elrido** [comment]
Thank you for that pointer, that certainly can be improved.
