### ISSUE TITLE
lojban translation

### ISSUE THREAD

**Issue by foxsouns** [PrivateBin/PrivateBin#876]
I was considering working on a translation of PrivateBin into lojban (mainly for fun), but lojban does not have an ISO 639-1 code; however, it has an ISO 639-2/639-3 code (`jbo`). What should I do?

**Comment by rugk** [comment]
I guess you read [the wiki page](https://github.com/PrivateBin/PrivateBin/wiki/Translation) in that topic. But generally de are in Crowdin and you can translate it there: https://crowdin.com/project/privatebin

However, they also does not Seen to support your language, so hmm…

**Comment by elrido** [comment]
Have a look at the [Gotchas section of the translation wiki page](https://github.com/PrivateBin/PrivateBin/wiki/Translation#gotchas). It explains how to extend the language labels with a (not yet existing) ISO code and then you can create a translation file for this. As I can see in the document, I had envisaged someone wanting to translate tlhIngan Hol or 1337 5934|<, but why not start with Lojban instead. :-) You will probably not be able to use the Crowdin web interface, but we can still incorporate it, they ignore languages we haven't selected in there.

PS: Sorry, for the duplicate post.

**Comment by r4sas** [comment]
@elrido you're wrong. See at Home -> Languages -> Custom Languages

**Comment by foxsouns** [comment]
> Have a look at the [Gotchas section of the translation wiki page](https://github.com/PrivateBin/PrivateBin/wiki/Translation#gotchas). It explains how to extend the language labels with a (not yet existing) ISO code and then you can create a translation file for this. As I can see in the document, I had envisaged someone wanting to translate tlhIngan Hol or 1337 5934|<, but why not start with Lojban instead. :-) You will probably not be able to use the Crowdin web interface, but we can still incorporate it, they ignore languages we haven't selected in there.
> 
> PS: Sorry, for the duplicate post.

cool, guess ill get started! i think ill use `jb`, as thats the closest i think im going to get to `jbobau`, which the three letter code is based off of, and it's unique. think ill turn this issue into the target for my (soon to be) pull request.

**Comment by foxsouns** [comment]
> @elrido you're wrong. See at Home -> Languages -> Custom Languages

in where would i find this? i was assuming the wiki, but there is no `Languages` section there.

**Comment by elrido** [comment]
> @elrido you're wrong. See at Home -> Languages -> Custom Languages

Gee, @r4sas, thanks for the "Wink mit dem Zaunpfahl". ;-) Indeed, and it's not even a custom language, they support Lojban (and LOLCAT and Klingon) in their default list!

So I apologize, @foxsouns, you can now also translate it using the crowdin web frontend, if you prefer. Either way works.

**Comment by foxsouns** [comment]
nice! i think ill close my pr after moving all my current data to there.

**Comment by foxsouns** [comment]
pr moved.

**Comment by elrido** [comment]
We still need some of the changes in the PR - I'll comment over there. Also, I see that Crowdin created the new translation as a three letter json file - I have to check if we can make this work somehow (may require code changes), can fix this in the settings in Crowdin or need to create a custom language so we get a two letter code, instead.
