### ISSUE TITLE
Dark Mode Code looks odd

### ISSUE THREAD

**Issue by MrDrache333** [PrivateBin/PrivateBin#877]
## Steps to reproduce
1. Set the Theme to DarkMode
2. Create a new Paste with Type "Code" and ad some lines
3. Click o Preview

### What happens
The even lines are white in dark mode and the Text is dark. Very bad to read.

### What should happen
The Theme is still dark mode, the even lines are not white and the Text is not Black to see the text

## Additional information
<img width="703" alt="Bildschirmfoto 2022-02-09 um 23 11 52" src="https://user-images.githubusercontent.com/22854641/153298850-20782e03-2303-464d-9a86-ed25dcb9005e.png">

## Basic information

**Server address**: https://paste.oelrichsgarcia.de

**Server OS:** Latest Docker Image

**Webserver:**Latest Docker Image

**Browser:**Safari 15.4 and Safari 15.3

**PrivateBin version:**1.3.5

I can reproduce this issue on <https://privatebin.net>: Yes / No
No, because there is no Dark Mode

**Comment by r4sas** [comment]
Try to use other highlight theme:
`syntaxhighlightingtheme = "sons-of-obsidian"`

**Comment by rugk** [comment]
Duplicate of https://github.com/PrivateBin/PrivateBin/issues/439

**Comment by rugk** [comment]
Due to the repeated problems with that, [I have added a short FAQ question](https://github.com/PrivateBin/PrivateBin/wiki/FAQ#the-dark-syntax-highlighting-looks-broken-how-can-i-fix-that).
