### ISSUE TITLE
Usage Control

### ISSUE THREAD

**Issue by bc-bjoern** [PrivateBin/PrivateBin#883]
It would be a interesting function to allow the secret creation just for several ip adresses.
And on the other side, allow the retrieving for everyone with a valid link. 

I didn't found a solution for that one. 
Thanks!

**Comment by r4sas** [comment]
That is out of project scope.

**Comment by elrido** [comment]
Hm, there was actually a PR that implemented such a feature and it seems to have dropped off our radar and not gotten merged 😳. Have a look at the discussion starting around https://github.com/PrivateBin/PrivateBin/pull/622#issuecomment-626282713 - Haocen provided an example on how to set this up using nginx on the webserver side, there will be similar mechanisms to do the same in other webservers.

**Comment by elrido** [comment]
@r4sas, could you comment in the MR #622 on how you'd feel about adding that feature? I'll consider investing some hours into it on the weekend to get conflicts resolved and get an updated MR in.

**Comment by bc-bjoern** [comment]
Just in case this feature is not out of project scope, I submited another PR #895 
It's supporting subnet whitelisting as well. For me it would be very useful.

**Comment by r4sas** [comment]
See #890

**Comment by bc-bjoern** [comment]
Yes, sorry. Didn't saw it before. #890 is even better. I closed my PR now. 
Thanks!
