### ISSUE TITLE
Cross origin requests being rejected because cors-preflight `Not Allowed`.

### ISSUE THREAD

**Issue by ennec-e** [PrivateBin/PrivateBin#889]
## Description
Before sending the actual cross origin requests, browsers seem to require
successful response to an OPTIONS method preflight request. [[ref:cors-preflight]]  
Currently _privatebin.net_ et al. respond to OPTIONS request with `405 Method Not Allowed`  
So cross origin requests are effectively not possible.

This is a bug because privatebin api is designed to be open to cross origin requests. [[cite]]

Possible resolution:  
This is sample configuration for enabling cors in nginx. [[sample:allow-cors]]  
Similarly, explicitly enable successful response for OPTIONS request method to support CORS.

[ref:cors-preflight]: https://fetch.spec.whatwg.org/#cors-preflight-fetch  
[cite]: https://github.com/PrivateBin/PrivateBin/issues/39#issuecomment-234532730  
[sample:allow-cors]: https://enable-cors.org/server_nginx.html  

## Steps to reproduce
1. Open browser JavaScript console
2. Use [Fetch API] (or XMLHttpRequest API) to get/post paste data from privatebin api endpoint. 
```
resource =  "https://privatebin.net/?pasteID=foo"
headers = new Headers({'X-Requested-With': 'JSONHttpRequest'})
init = {method: "GET", headers: headers}

responsePromise = fetch(resource, init)
responsePromise.then( function (r) {console.log(r)} )
```

[Fetch API]: https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API

### What happens
3. Browser makes 2 sequential requests to server
  3.1. a preflight OPTIONS method call to privatebin server expecting CORS directives; gets 405 Method Not Allowed.
  3.2. an actual GET method request for the resource
4. The response of GET request is automatically denied to JS because of failure in 3.1 (even when the get response itself has CORS allow)
5. Fetch resource fails.

### What should happen
Privatebin should respond with valid response to options call as described in [ref:cors-preflight]
So that subsequent cross origin resource request succeeds. 

[ref:cors-preflight]: https://fetch.spec.whatwg.org/#cors-preflight-fetch 

### Screenshots
[Console]

[Network - preflight request]

[Network - resource request]

[Console]: https://paste.tildeverse.org/?ffeaed5663ac172b#7zGskZWNi7wLec4GjWAqQbH9jhYiy7ypoRRTFMVMgF1t
[Network - preflight request]: https://paste.tildeverse.org/?a928e76224c21a48#AaDo8g5JvZynfHihizrazQHbojHfYdR36Doe32wfg3Uj
[Network - resource request]: https://paste.tildeverse.org/?7fb2765468f3e9f1#4r3mZ9FT7yrstyGDvrx6XFmPwwxudtMq51qnqyiPWLr9

## Basic information

**Server address**: https://privatebin.net

**Server OS:** ?

**Webserver:** Nginx

**PrivateBin version:**

I can reproduce this issue on <https://privatebin.net>: Yes

**Comment by elrido** [comment]
This is not a bug in our code, but a [(missing) configuration in our nginx server](https://github.com/PrivateBin/privatebin.info-pelican/blob/master/nginx.conf). Our sites config simply doesn't support OPTION requests, so the request never reaches the app (and it shouldn't, IMHO, that is more efficiently handled on the web server side). I encountered this exact issue while implementing #2 and on my nginx-based test instance had to add this to the nginx configuration for that subdomains location-/-block, to to enable it:
```
	    if ($request_method = OPTIONS ) {
			add_header Content-Length 0;
			add_header Content-Type text/plain;
			add_header Access-Control-Allow-Origin *;
			add_header Access-Control-Allow-Methods "GET, POST, PUT, DELETE";
			add_header Access-Control-Allow-Headers "X-Requested-With, Content-Type";
			return 200;
		}
```
With the above, the preflight is handled efficiently in nginx and never reaches the apps PHP logic. If you like to test this in your use case, you can point your cross-site request at the test instance on https://zerobin-test.dssr.ch/ which has this enabled. Normal requests aren't affected by this pre-flight check, since they won't cross the site boundaries (i.e. requests from privatebin.net stay on privatebin.net).

The paste manager feature aims to change that, at which point this setting will become the mechanism by which server admins can allow or deny the paste manager on other instances to be used with their instance. Third party CLI client implementations, on the other hand, simply never implemented this preflight check and already can interact with any compatible PrivateBin version without any option for the admins to disable this.

**Comment by ennec-e** [comment]
> Third party CLI client implementations, on the other hand, simply never implemented this preflight check and already can interact with any compatible PrivateBin version without any option for the admins to disable this.

Yes. I was implementing a simple static web page client so was forced to deal with the browser's preflight checks.  
An example use case would be to host a thin static client site on say github-pages, so that the JS delivered is always in user control or ***easily*** verifiable. (as long as you trust static host not to meddle). Or even have an "offline" web-extension based client. So any updates go through the browser extension stores and _individual_ users can't be targeted with malicious JS by rogue servers.

Noticed the lack of any 3rd party _web_ clients so figured the CORS issue I was facing might be a common limiting factor worth tackling one way or another. 

I did also take a look at the [docker image nginx conf] earlier but thought Privatebin may perhaps want to allow/disallow 
checks individually after them passing through nginx depending on the exact resource requested. Or depending on the requesting third party site (origin). Of course if that is too far fetched or a non-goal then having preflight handling code in the app feels less desirable. But otherwise, perhaps it could have some utility?

The link I mentioned above did suggest the ability to short circuit response to preflight with nginx. But I wasn't aware that the app isn't even get passed such requests. I thought they were being rejected at the app as the default behavior. Thanks for clarifying.

Do you think the nginx configuration above would be a good addition to the [docker image] then?  
It would be nice to have CORS support on the primary demo instance and other default config instances.

[docker image]: https://github.com/PrivateBin/docker-nginx-fpm-alpine  
[docker image nginx conf]: https://github.com/PrivateBin/docker-nginx-fpm-alpine/blob/master/etc/nginx/http.d/site.conf

**Comment by ennec-e** [comment]
Paste manager sounds like an interesting feature. I'll take a look :)

**Comment by elrido** [comment]
Once I (finally) get around to conclude the paste manage and get it into a release, I'll definitely will want to add it to that images configuration - since we will want it to be an option, I'll need to do so in a way that makes it easy to toggle off for the images users.

For the main demo site, it runs behind the nginx that serves the static info page as well, so we can add it right in there. PR for that raised in https://github.com/PrivateBin/privatebin.info-pelican/pull/25

**Comment by ennec-e** [comment]
Thanks! Looks good :)

**Comment by elrido** [comment]
Deployed, but my testing shows it to only work with HTTP 1.1, not HTTP/2? Can you let me know what behaviour you get in the browser with your static page, please? It might just be curl not liking the `content-length` in it's HTTP/2 library, but they usually are pretty standards compliant.

```
$ curl -v -X OPTIONS --http1.1 https://privatebin.net/
[...]
*  SSL certificate verify ok.
> OPTIONS / HTTP/1.1
> Host: privatebin.net
> User-Agent: curl/7.68.0
> Accept: */*
> 
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* old SSL session ID is stale, removing
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Server: nginx/1.20.2
< Date: Sun, 20 Feb 2022 15:37:47 GMT
< Content-Type: application/octet-stream
< Content-Length: 0
< Connection: keep-alive
< Content-Length: 0
< Content-Type: text/plain
< Access-Control-Allow-Origin: *
< Access-Control-Allow-Methods: GET, POST, PUT, DELETE
< Access-Control-Allow-Headers: X-Requested-With, Content-Type
[...]
$ curl -v -X OPTIONS https://privatebin.net/
[...]
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x55d9c33bbe30)
> OPTIONS / HTTP/2
> Host: privatebin.net
> user-agent: curl/7.68.0
> accept: */*
> 
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* old SSL session ID is stale, removing
* Connection state changed (MAX_CONCURRENT_STREAMS == 128)!
* http2 error: Invalid HTTP header field was received: frame type: 1, stream: 1, name: [content-length], value: [0]
* HTTP/2 stream 0 was not closed cleanly: PROTOCOL_ERROR (err 1)
* stopped the pause stream!
```

**Comment by ennec-e** [comment]
Hi. Tried it. It works. 

**Testing with** 
```
resource =  "https://privatebin.net/?pasteID=foo"
headers = new Headers({'X-Requested-With': 'JSONHttpRequest'})
init = {method: "GET", headers: headers}
fetch(resource, init)
  .then( (response) => { return response.text() } )
  .then( (text) => { console.log(text) } )
```

**Screenshot** [Console](https://paste.tildeverse.org/?b08e20e487e81b46#5jPk9EyZWxChDhemb4dFHV6btRXzhKLqnLJ9oQbBhUzG)


Firefox req-res:

**Request**

```
OPTIONS /?pasteID=foo HTTP/2
Host: privatebin.net
User-Agent: Firefox/95.0
Accept: */*
Accept-Language: en-GB,en;q=0.5
Accept-Encoding: gzip, deflate, br
Access-Control-Request-Method: GET
Access-Control-Request-Headers: x-requested-with
Origin: https://start.fedoraproject.org
DNT: 1
Connection: keep-alive
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: cross-site
TE: trailers

```
**Response**

```
HTTP/2 200 OK
server: nginx/1.20.2
date: <date>
content-type: application/octet-stream
content-length: 0
content-length: 0
content-type: text/plain
access-control-allow-origin: *
access-control-allow-methods: GET, POST, PUT, DELETE
access-control-allow-headers: X-Requested-With, Content-Type
X-Firefox-Spdy: h2

```

Content length looks duplicated for some reason. Perhaps curl is tripping on that?
Firefox does indicate the connection is happening over HTTP/2

**Comment by elrido** [comment]
Agreed and with the latest update and the switch to a 204 code I think we got this settled for the HTTP/2 case as well:

```
$ curl -v -X OPTIONS https://privatebin.net/
[...]
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x5574346e6e30)
> OPTIONS / HTTP/2
> Host: privatebin.net
> user-agent: curl/7.68.0
> accept: */*
> 
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* old SSL session ID is stale, removing
* Connection state changed (MAX_CONCURRENT_STREAMS == 128)!
< HTTP/2 204 
< server: nginx/1.20.2
< date: Fri, 25 Feb 2022 05:54:27 GMT
< access-control-allow-origin: *
< access-control-allow-methods: GET, POST, PUT, DELETE
< access-control-allow-headers: X-Requested-With, Content-Type
```

And just to keep all the information as part of one thread and for future reference, I currently recommend the use of the following nginx configuration to be added into the location-block of the PrivateBin instance in question:
```
        if ($request_method = OPTIONS) {
            add_header Access-Control-Allow-Origin *;
            add_header Access-Control-Allow-Methods "GET, POST, PUT, DELETE";
            add_header Access-Control-Allow-Headers "X-Requested-With, Content-Type";
            return 204;
        }
```
