### ISSUE TITLE
Enhancement: Line Numbers

### ISSUE THREAD

**Issue by stalks** [PrivateBin/PrivateBin#89]
Unless I've completely missed it (in which case please enlighten me). **An option to show line numbers would be useful.**

**Comment by soakes** [comment]
Ive been using this for a while now and I agree, its a missing feature unless I also missed how to enable it.  

Would love to see this implemented, soon.

**Comment by elrido** [comment]
There is the "Format" drop down menu and the option called "Source Code" will provide you line numbers (and syntax highlighting).

**Comment by soakes** [comment]
Thanks for the reply.  I usually use source code option as I typically send bash snipits to a friend but somehow never noticed the line numbers being there.  Might be a template issue or I'm missing some package as Im sure I've not seen it.

Thanks again for pointing this out, will take a look again when I get home and will update later.

**Comment by soakes** [comment]
Apologises, I can confirm its all fine.  It seems one of my plugins in my browser was messing around with part of the site and somehow hiding the numbers.  After using no-plugins, the sites working correctly.  Just figuring out which ones messing.  Sorry for the noise.

**Comment by elrido** [comment]
No problem at all, glad it is working for you.
