### ISSUE TITLE
Client Certificate authentication - MySQL

### ISSUE THREAD

**Issue by git-noise** [PrivateBin/PrivateBin#894]
Hello,

I had a question regarding client certificate authentication for Databases. It is not a bug per se, but I believe I did not see any reference in the documentation.
What would be the recommended way of doing that?
If we take MySQL as an example, should that be part of the dsn or should that be passed as an array in opt[12] - which is the usual way things are done with PDO I believe?

Many thanks for your insight.

Best,

**Comment by elrido** [comment]
As you correctly assume, it works similarly to other PDO implementations. You need to be aware of the following options that get injected automatically:
https://github.com/PrivateBin/PrivateBin/blob/c8c6a6753007f40c851d6a643567908943bf7b72/lib/Data/Database.php#L90-L111
In your configuration file, you can therefore extend the `opt` setting with additional keys to point to your client certificates:
https://github.com/PrivateBin/PrivateBin/blob/c8c6a6753007f40c851d6a643567908943bf7b72/cfg/conf.sample.php#L171-L179

If I read the [php.net docs](https://www.php.net/manual/en/ref.pdo-mysql.php) correctly, you will need to lookup the integers behind the two flags `PDO::MYSQL_ATTR_SSL_CERT` and `PDO::MYSQL_ATTR_SSL_KEY` - ini files can't reference those constants, AFAIK, hence we also turn the `PDO::ATTR_PERSISTENT` into the integer `12`:
```
$ php -r 'var_dump(PDO::ATTR_PERSISTENT);'
Command line code:1:
int(12)
```

**Comment by git-noise** [comment]
Hello,

Many  thanks for the detailed answer! I'll look into it and report back.

Best,
