### ISSUE TITLE
How to know when the next version will be released

### ISSUE THREAD

**Issue by Patriccollu** [PrivateBin/PrivateBin#897]
Hello,

I would like to know when the next version of PrivateBin - which should include the new Corsican locale - will be released.

If you don't have the answer by now, is there a place (forum, blog, ...) where I can monitor the project's evolution?

Best regards,
Patriccollu.

**Comment by rugk** [comment]
Hi and thanks for your question.

You can just use [GitHub notifications and configure them to only watch releases](https://docs.github.com/en/account-and-profile/managing-subscriptions-and-notifications-on-github/setting-up-notifications/configuring-notifications#configuring-your-watch-settings-for-an-individual-repository). In addition to that, each release will [be announced on PrivateBin.info](https://privatebin.info/category/news.html), which [also has an RSS/Atom feed you can subscribe to with your preferred RSS reader](https://privatebin.info/feeds/all.atom.xml).

I hope this answers the question.

Best regards
rugk

**Comment by Patriccollu** [comment]
Hi @rugk ,

Thank you for these interesting pieces of information which allow me to be informed **_when_** the new release is issued.

In the present case, I would like to know **_before_** when the **_next version_** will be released. Do you know that?

Best regards,
Patriccollu.

**Comment by rugk** [comment]
> In the present case, I would like to know before when the next version will be released. Do you know that? Or do you have an estimated date?

Generally, we have no regular release schedule and no process of notifying users before a new release happens.

However, as fur the next release right now, I can say we are currently preparing a new release, which should be released in the near future. Stay tuned!

**Comment by Patriccollu** [comment]
@rugk Thank you for your answer.

**Comment by elrido** [comment]
ping -> https://github.com/PrivateBin/PrivateBin/releases/tag/1.4.0
