### ISSUE TITLE
[Question] URL shortener

### ISSUE THREAD

**Issue by 0xspade** [PrivateBin/PrivateBin#904]
Any suggested self-hosted URL shortener which is perfect to partner with privatebin?

**Comment by 0xspade** [comment]
Closing this one, found out that YOURLS works perfectly fine with PB.

**Comment by rugk** [comment]
Good you found it. For future reference, see https://github.com/PrivateBin/PrivateBin/wiki/FAQ#the-url-is-so-long-cant-i-just-use-an-url-shortener
