### ISSUE TITLE
Feature request: Disclaimer

### ISSUE THREAD

**Issue by pojlFDlxCOvZ4Kg8y1l4** [PrivateBin/PrivateBin#908]
Hello,

after some digging in the source zip and github repo, I've found that there's no option to add a proper disclaimer. 
I've abused the "kittens will die" note for now, but it's rather full in the upper part now. 
I would like to use a part of the bottom for a disclaimer part, which allows for multiple lines and spaces in between lines.

Sadly, I am not a good programmer, so I can't add a pull request.

Would this be possible to add to privatebin, and if so, what would be the expected ETA?

**Comment by elrido** [comment]
I think this question has been answered and I thus close this issue. If anyone has further questions on that topic, feel free to comment here, again.

**Comment by rugk** [comment]
Okay, I understood the issue as being a feature request for having a more easily configurable footer or disclaimer line at the bottom…

**Comment by pojlFDlxCOvZ4Kg8y1l4** [comment]
> Okay, I understood the issue as being a feature request for having a more easily configurable footer or disclaimer line at the bottom…

That is accurate, I just didn't know what to say😅
The kittens will die message is pretty easy to change, a template takes more time and a better understanding of how things work behind the curtain. 
It does seem like a good idea to me to have a easy to configure disclaimer similar to the kitten feature in the config file.

**Comment by elrido** [comment]
The template system is very simple as doesn't require programming skills. You just copy/paste it and change the HTML document in your copy as you like. I don't see why we should turn every single visible area, especially the ones that are template specific, into configuration options when the template system is so simple to use.
