### ISSUE TITLE
Additional headers for XSS mitigation

### ISSUE THREAD

**Issue by elrido** [PrivateBin/PrivateBin#91]
As per [securityheaders.io](https://securityheaders.io/?q=privatebin.net&hide=on&followRedirects=on) advice, we could add the three headers [X-Xss-Protection](https://scotthelme.co.uk/hardening-your-http-response-headers/#x-xss-protection), [X-Frame-Options](https://scotthelme.co.uk/hardening-your-http-response-headers/#x-frame-options) and [X-Content-Type-Options](https://scotthelme.co.uk/hardening-your-http-response-headers/#x-content-type-options) to complement our CSP one. This would help protect agains (i)frame based XSS.

**Comment by rugk** [comment]
Yes, but would not this be headers, which should rather be set by the webserver in the webserver configuration?

In any case we should make sure no double-headers are send when they are set in the webserver configuration already.

**Comment by elrido** [comment]
You can set headers wherever you want. The webserver headers should override those of the application. We can't check on the PHP side if the webserver will send additional headers afterwards.

These three headers are ones that we as developers of the applications can better implement then require the server admins to look into how our application is behaving. Also on cheap shared hosters they might not even be able to change these.

**Comment by rugk** [comment]
> Also on cheap shared hosters they might not even be able to change these.

This is a good argument, so I am in favour of adding these.
