### ISSUE TITLE
Trouble upgrading to new version

### ISSUE THREAD

**Issue by un99known99** [PrivateBin/PrivateBin#917]
Hi, I am currently running 1.3.5 on up-to-date debian bullseye.
I tried to follow the instructions to upgrade (extract and copy over the packed content).

Either I am doing that wrong, but changed files are not going to be updated.

May you could share the commands you used to upgrade (I am not an expert) to 1.4.0. 

Would be also help to add some more technical infos about how to upgrade in the release notes.
Looking forward to you answer.
Many thanks,
Mike

**Comment by elrido** [comment]
On the demo site we use the docker container, so the upgrade was just deploying the 1.4.0 image over the 1.3.5 one. If you still see the old version in the browser, after replacing the files on disk, I suggest checking your webserver and/or CDN configuration for any cache related settings that may cause the old version to still get used.
