### ISSUE TITLE
MariaDB x PDO::MYSQL_ATTR_INIT_COMMAND (1.4.0)

### ISSUE THREAD

**Issue by devnull-hub-lab** [PrivateBin/PrivateBin#919]
Hello all,

After update PrivateBin to 1.4.0, I got some errors.
The error is related to commit 0be55e05bf45c5761360e8f6bd1c224ba1b9fbac (use quoted identifiers, tell MySQL to expect ANSI SQL).

PDO is loaded and active, but MariaDB cannot set sql_mode. When not set, double quotes result in error.

AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught PDOException: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '"privatebin_config" SET "value" = ? WHERE "id" = ?' at line 1 in Database.php:550...

Double quotes should only be applied if sql_mode has set true.

## Basic information

**Server OS: FreeBSD 13.0 p10
**Webserver: Apache 2.4 / PHP 8.0 / MariaDB 105
**Browser: Safari / Chrome
**PrivateBin version: 1.4

**Comment by elrido** [comment]
Is this a restriction of your MariaDB instance, i.e. a permission issue, not letting your user set the `sql_mode`? This setting is documented in https://mariadb.com/kb/en/sql-mode/#ansi_quotes and I had tested it successfully even in an ancient MySQL 5.5 installation, so that setting should be present.

https://mariadb.com/docs/reference/mdb/system-variables/sql_mode/#privileges states that:
> The `sql_mode` system variable requires the SUPER privilege to dynamically set its global value at runtime.
> 
> The `sql_mode` system variable does not require any special privilege to dynamically set its session value at runtime.

Maybe we should change the statement to `SET SESSION sql_mode='ANSI_QUOTES'`, so we don't require the `SUPER` privilege? Could you test if adding the `SESSION` keyword lets you use the double quotes without `SUPER`? Or `GRANT` the user `SUPER`, if you prefer not to touch the code.

**Comment by devnull-hub-lab** [comment]
elrido,

Thanks for your reply!

It's a little weird.
I think the user defined in conf.php has the SUPER privilege, as you can be seen here: https://envs.sh/ENx.png
Directly from the mysql terminal, works.

But it seems to me that in execution, I can't get these same permissions, because I did the other test, changing the directive to "SET SESSION" in the source code, and it worked!

**Comment by dausruddin** [comment]
Hi. I have applied  this changes but I'm still having the same issue. 
I'm trying to upgrade from **1.3.4** to **1.4.0**.

![image](https://user-images.githubusercontent.com/5763466/183252708-aa19b641-0215-4113-a751-b565212bbc77.png)

**Error on webpage**:
```
 Could not get paste data: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '"privatebin_config" SET "value" = ? WHERE "id" = ?' at line 1
```

**Error in server log**:
```
2022/08/06 20:20:49 [error] 3349#3349: *1700 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught PDOException: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '"privatebin_config" SET "value" = ? WHERE "id" = ?' at line 1 in /home/user/PrivateBin-1.4.0/lib/Data/Database.php:550
Stack trace:
#0 /home/user/PrivateBin-1.4.0/lib/Data/Database.php(550): PDO->prepare()
#1 /home/user/PrivateBin-1.4.0/lib/Data/Database.php(972): PrivateBin\Data\Database::_exec()
#2 /home/user/PrivateBin-1.4.0/lib/Data/Database.php(142): PrivateBin\Data\Database::_upgradeDatabase()
#3 [internal function]: PrivateBin\Data\Database::getInstance()
#4 /home/user/PrivateBin-1.4.0/lib/Model.php(86): forward_static_call()
#5 /home/user/PrivateBin-1.4.0/lib/Controller.php(199): PrivateBin\Model->getStore()
#6 /home/user/PrivateBin-1.4.0/lib/Controller.php(125): PrivateBin" while reading response header from upstream, client: xxx.xxx.xxx.xxx, server: domain.tld, request: "POST / HTTP/2.0", upstream: "fastcgi://unix:/run/php/php7.4-fpm.sock:", host: "domain.tld"
```

_OS_: Ubuntu 18.04
_MySQL_: 8.0.30

**Comment by elrido** [comment]
Sorry for staying quiet - I tried to reproduce this, yesterday, using our docker container and a mysql one, but failed to do so. The error does indeed look like it is ignoring your session setting for the ANSI quotes. Does your `dsn`, as configured in the conf.php, indeed start with `mysql:` and is `PDO::MYSQL_ATTR_INIT_COMMAND` supported in your php environment? Is there maybe some other setting on the MySQL server, that would prevent you from using the ANSI quotes?

**Comment by dausruddin** [comment]
Hi. Sorry for super long delay in replying. I'm currently in an area with limited connection.

My database configuration in `conf.php` is something like this:
```
[model]
; example of DB configuration for MySQL
class = Database
[model_options]
dsn = "mysql:host=localhost;dbname=privatebin;charset=UTF8"
tbl = "privatebin_"     ; table prefix
usr = "privatebin"
pwd = "xxxxxxx"
opt[12] = true    ; PDO::ATTR_PERSISTENT
```

> is PDO::MYSQL_ATTR_INIT_COMMAND supported in your php environment? 

How do I check? I have been Googling and questions asked are always about errors. But I don't have any `MYSQL_ATTR_INIT_COMMAND` errors.

> Is there maybe some other setting on the MySQL server, that would prevent you from using the ANSI quotes?

I installed MySQL from Official repo. I didn't modify any specific settings after that.


I am not sure what is happening, but I am planning to migrate to a new smaller server soon. Probably this will fix whatever is broken since I did an OS upgrade from 16.04 to 18.04 a while ago. I'll inform the result later.

I think this issue can be closed for now as my issue might be an isolated one.
Thanks for the reply.

**Comment by devnull-hub-lab** [comment]
Hi dausruddin,

To test ANSI quotes, I suggest you do the same test I did:
https://envs.sh/ENx.png

If your mysql server or users permission is preventing using ANSI quotes, you will know. The results will be different from mine.

About PDO, check your phpinfo(). You need to have PDO Driver for MySql:
https://envs.sh/Qnv.png

You need to build PHP with PDO support:
https://www.php.net/manual/pt_BR/ref.pdo-mysql.php

I don't use GNU/Linux, but I think Ubuntu/Debian have php-pdo package extension (from apt).

If you already have this package installed and active (phpinfo()), alternatively I suggest you use the php debugger.
I don't believe your ubuntu is broken. It seems to be a package missing or missconfiguration.

**Comment by dausruddin** [comment]
Sorry for another delay.

Did the test and result is fine
![image](https://user-images.githubusercontent.com/5763466/185634677-eda164f1-b6af-4774-bd7a-5247bdfc5cc0.png)

This is from my phpinfo
![image](https://user-images.githubusercontent.com/5763466/185635263-b515d0f5-752b-487b-9377-32b0d25fc0be.png)

I am using [ppa:ondrej/php](https://launchpad.net/~ondrej/+archive/ubuntu/php) and already installed related packages from there.

I will proceed with my plan to migrate server. I don't think I can debug the problem by myself.

**Comment by dausruddin** [comment]
Weird. I moved my privatebin onto another server but still having the same issue.

Is this because my current Privatebin version is 1.3.4, trying to upgrade to 1.4.0?

**OS**: Ubuntu 20.04
**MySQL**: 10.5.16-MariaDB
**PHP**: 7.4

**Comment by devnull-hub-lab** [comment]
@dausruddin,

The quoted identifiers was implemented on 1.4.0 version.

But I already suspected that migrating to another server would not solve the problem.

In your sql test above, did you try with your privatebin username?
The test must be done with the same user that was inserted in privatebin/cfg/conf.php in "usr = ..." directive.

Second, execute and pastebin the result:
php -i | grep -i pdo

Third, I don't know if @elrido would agree with me, but ONLY for TESTING purpose, I suggest you change LogLevel directive in your httpd.conf.
Default is "LogLevel warn"
Change to "LogLevel trace8"

Restart apache. Test again with privatebin page.
After, check your apache error.log. Maybe there are some additional errors about PDOException that may help you/us in a solution.

After test, Rollback your Apache LogLevel to original value.

**Comment by dausruddin** [comment]
> In your sql test above, did you try with your privatebin username?

Yes I did.

> php -i | grep -i pdo

![Screenshot_20220820-073553_Termux](https://user-images.githubusercontent.com/5763466/185719704-b4392300-9fbf-472d-b296-7ee263a09038.png)

> I  suggest you change LogLevel directive in your httpd.conf.
Default is "LogLevel warn"
Change to "LogLevel trace8"

I am using nginx. Do I need to use [debug](http://nginx.org/en/docs/debugging_log.html)  for the log instead?

**Comment by dausruddin** [comment]
I decided to reinstall everything and restore my database. Currently I am using latest git commit, PHP 8.1, MariaDB, and Nginx. I am happy to say that I cannot reproduce the bug anymore.

 I am not sure which side the issue is from, but I think this issue can be closed for now.
Thank you!
