### ISSUE TITLE
Feature Request - Proceed to show secret?

### ISSUE THREAD

**Issue by Rand72889** [PrivateBin/PrivateBin#921]
It would be nice to have a option that can be enabled to have a landingpage shown with a customizable text for elements that have the option "Burn after reading" enabled.

"Please click here to open the secret - you can only view it once - after that it is permanently deleted. Proceed?"

People tend to test the link and burn it that was and as everything seems to be working for them they sent the link afterwards.

Also this would prevent apps like messengers to accidentally burn the note by generating a preview.

**Comment by elrido** [comment]
Personally, I consider such "are you sure?" dialogs bad UX, and they tend to train users to just click them, without reading them.

Regarding the messengers: Just accessing the URL isn't enough to trigger the download of the paste, it is only sent upon request by the JS logic in the browser, so the messenger or bot would need to open these in a full browser or with a DOM emulation and JS enabled. If you do have evidence of such an issue, please do share the user agent header sent to your webserver of these, so we can add them to our block list:
https://github.com/PrivateBin/PrivateBin/blob/d0142c31ccc663cc371fddc806f090b57a53482c/js/legacy.js#L55-L65

**Comment by elrido** [comment]
@Rand72889 - if you can provide us some user agent strings to block from triggering the paste deletion, please do share them with us here. I'm closing the request for the UX change, due to the above noted concerns.
