### ISSUE TITLE
privatebin error

### ISSUE THREAD

**Issue by Blisk** [PrivateBin/PrivateBin#930]
## Steps to reproduce

1. moved privatebin on new server
2. blank page

### What happens
blank page

## Additional information

error in php
Warning: require(/var/www/html/privatebin/vendor/composer/../paragonie/random_compat/lib/random.php): failed to open stream: No such file or directory in /var/www/html/privatebin/vendor/composer/autoload_real.php on line 66

Fatal error: require(): Failed opening required '/var/www/html/privatebin/vendor/composer/../paragonie/random_compat/lib/random.php' (include_path='.:/usr/share/pear:/usr/share/php') in /var/www/html/privatebin/vendor/composer/autoload_real.php on line 66

## Basic information

**Server address**:

**Server OS:** centos 8 stream

**Webserver:** apache 2.4.5
php 7.4

**Browser:** all browsers

**PrivateBin version:**

I can reproduce this issue on <https://privatebin.net>: Yes / No

**Comment by elrido** [comment]
Check that all of the files got transferred and are readable (ownership, mode bits) by the php / apache process(es). Given the error, look first in the vendor directory. Less likely is an issue with the PATH setting in index.php:
https://github.com/PrivateBin/PrivateBin/blob/4487171263f6e60a7731abca6857dc255e061da0/index.php#L14

**Comment by Blisk** [comment]
thank you
