### ISSUE TITLE
Can't make PostgreSQL work

### ISSUE THREAD

**Issue by PeGaSuS-Coder** [PrivateBin/PrivateBin#934]
Since there's no PostgreSQL example in the config, I've tried to duplicate the one used for MySQL, without success.

Here's my attempt:
```
[model]
; example of DB configuration for PostgreSQL
class = Database
[model_options]
dsn = "pgsql:host=localhost;dbname=pastebin;charset=UTF8"
tbl = "pastebin_"     ; table prefix
usr = "pastebin"
pwd = "<redacted>"
opt[12] = true    ; PDO::ATTR_PERSISTENT
```

Whenever I try to create a paste, I get a:
:warning:  `Could not create paste: server error or not responding`

Could someone point me in the right direction, please?

Thanks in advance.

**Comment by r4sas** [comment]
Look for PHP logs...

**Comment by PeGaSuS-Coder** [comment]
Apparently, `charset=UTF8` isn't valid on PostgreSQL.

Working `[model]` below, if anyone wants to add it to the default config:
```
[model]
; example of DB configuration for PostgreSQL
class = Database
[model_options]
dsn = "pgsql:host=localhost;dbname=pastebin"
tbl = "pastebin_"     ; table prefix
usr = "pastebin"
pwd = "password"
opt[12] = true    ; PDO::ATTR_PERSISTENT
```

Cheers!
