### ISSUE TITLE
MySQL doesn't support `CREATE INDEX IF NOT EXISTS`

### ISSUE THREAD

**Issue by elrido** [PrivateBin/PrivateBin#943]
I hadn't caught this in testing, since I've switched to MariaDB when Linux distros started shipping it as the default over MySQL, many years ago. But it seems that [MySQL still doesn't support](https://dev.mysql.com/doc/refman/8.0/en/create-index.html) `CREATE INDEX IF NOT EXISTS`, where as [MariaDB does](https://mariadb.com/kb/en/create-index/) (as well as PostgreSQL and SQLite, but not OCI). 

This got introduced in [2182cdd](https://github.com/PrivateBin/PrivateBin/commit/2182cdd44f092277ce829cb9effd861ceb415c06#diff-c4661c92ca75850dcd481b990c4a8c40b5203ad07a25f128f709101aefec6216R796) and was originally reported over in [the docker container project](https://github.com/PrivateBin/docker-nginx-fpm-alpine/issues/103). We do have some other locations with those `IF NOT EXISTS` guards in the auto upgrade to 0.21, which got introduced in [b53efda](https://github.com/PrivateBin/PrivateBin/commit/b53efda6352f487ff6ae45a6055f413d9d668629#diff-d5e56553cf29390f9223e5cb7ebbd4051f3f434d2dee9257678146c666730d18R610) and should be reviewed as well.

We could simply revert to the statement without `IF NOT EXISTS`, since it is only run when the table is created and therefore the index can't exist. That should also be safe for the 0.21 upgrade as well, though we only have 2 instances in the directory with that age (one is mine, doesn't use the DB and is used for testing old version features, both of the paste format and in unit tests of the directory itself) - my bad for being overly cautious and consistent with these clauses. Or we could even consider dropping the 0.21 DB upgrade code.

Any opinions and feedback is welcome, I'll try to get a PR for this done by next weekend.

**Comment by rugk** [comment]
> We could simply revert to the statement without IF NOT EXISTS, since it is only run when the table is created and therefore the index can't exist. 

Sounds like the simplest and most pragmatic option, so sure… go for it.
