### ISSUE TITLE
add more options for timeout

### ISSUE THREAD

**Issue by dpalic** [PrivateBin/PrivateBin#944]
on https://paste.aes.pm/

it would be great to have more options between
1h and 1d
e.g.
2h, 4h, 8h

or even better user can enter a value

**Comment by r4sas** [comment]
Duplicate of https://github.com/PrivateBin/PrivateBin/issues/524

**Comment by rugk** [comment]
Please also note server admins can already offer and configure more values. See https://github.com/PrivateBin/PrivateBin/wiki/Configuration#expiration for details.
