### ISSUE TITLE
<>4<> password not working 

### ISSUE THREAD

**Issue by poll1213** [PrivateBin/PrivateBin#950]
## Steps to reproduce

1.
2.

## Basic information

**Server address**:

**Server OS:**

**Webserver:**

**Browser:**

**PrivateBin version:**

I can reproduce this issue on <https://privatebin.net>: Yes / No

**Comment by elrido** [comment]
Please fill out the details of your issue - with just such a bare bones subject there isn't much to go on to help you, sorry.

**Comment by rugk** [comment]
We miss information here and no reply was provided, so I'll close this issue.
