### ISSUE TITLE
Add HTML encoding to prevent HTML injection

### ISSUE THREAD

**Issue by GoldHatSecurity** [PrivateBin/PrivateBin#952]
## Steps to reproduce
1. Enter the attack payload into privatebin, such as `'">a/href=http://evil.comClick Here</a>`
2. Press Send
3. View the resulting link which will have rendered the HTML

### What happens
This could be used to trick a user into clicking on something malicious.

### What should happen
The application should HTML encode all output to the browser, which would prevent this from rendering as HTML. In this case, the output would be `'"&gt;a/href=http://evil.comClick Here&lt;/a&gt;` which would display the original text rather than a link.

## Additional information
Current output:
<img width="623" alt="Screen Shot 2022-07-07 at 8 25 17 AM" src="https://user-images.githubusercontent.com/52438121/177811488-fc8fa06f-25e8-4011-bbf2-a1ad019e9e99.png">

## Basic information

1.4.0

I can reproduce this issue on <https://privatebin.net>: Yes

**Comment by elrido** [comment]
I can't reproduce this either and the screenshot is of a dark theme, so not taken on privatebin.net. It may be an older release of the software? @GoldHatSecurity, can you please send us more details, incl.:
- link to the actual instance where this occurs and can be reproduced.
- browser and operating system you observed this on.

**Comment by elrido** [comment]
Please re-open when anyone can provide more information on how to reproduce this.
