### ISSUE TITLE
Let's add a package-lock.json to our js directory so automated tools can better work/upgrade it

### ISSUE THREAD

**Issue by rugk** [PrivateBin/PrivateBin#953]
## Steps to reproduce
Dependabot showed the following error:
> 
![grafik](https://user-images.githubusercontent.com/11966684/177881404-cc70a282-35a4-4316-8ab2-169df8231173.png)
>  Dependabot can't update vulnerable dependencies without a lockfile
>
>The currently installed version can't be determined.
> To resolve the issue add a supported lockfile (package-lock.json or yarn.lock).

### What happens
In this case it was just a [kinda disputed CVE](https://github.com/jsdom/jsdom/issues/3124). We [also only use that lib in tests](https://github.com/PrivateBin/PrivateBin/search?q=jsdom), so I've dismissed this advisory.

### What should happen
Anyway, what is correct is the principle error it shows is correct. [Npm's and most people agree that the `package-lock.json` should be committed](https://stackoverflow.com/a/56254478/5008962) to the repository.
Also `npm ci` should then be used for installing the required software dependencies in a CI.

Given [the work that has been done there](https://github.com/jsdom/jsdom/releases) refreshing/updating these libs too may not be bad idea, however, in any case.

**Comment by elrido** [comment]
I don't mind adding one, although our versions are already pinned precisely, so it seems pretty redundant:

https://github.com/PrivateBin/PrivateBin/blob/f9d78d62a00ce3985b817b129c8e86d185d85275/js/package.json#L9-L16

I did check if one is already generated locally and just .gitignored but it isn't. Neither did I find one in the unit-testing container. In the github actions we do install the modules as you describe. So how can we generate that lock file? If you could create it and commit it in a PR, that would be great!

**Comment by rugk** [comment]
> So how can we generate that lock file?

Just run `npm install`.

> although our versions are already pinned precisely

They are not. The `^` means it follows semantic versioning, i.e. bumps minor etc. Which is alos the suggested and **correct** behavior, just to be sure.

**Comment by rugk** [comment]
BTW got the same vulnerability warning offline:
```
$ npm update                                

up to date, audited 99 packages in 6s

2 packages are looking for funding
  run `npm fund` for details

1 moderate severity vulnerability

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
$ npm audit
# npm audit report

jsdom  <=16.4.0
Severity: moderate
Insufficient Granularity of Access Control in JSDom - https://github.com/advisories/GHSA-f4c9-cqv8-9v98
fix available via `npm audit fix --force`
Will install jsdom@20.0.0, which is a breaking change
node_modules/jsdom

1 moderate severity vulnerability

To address all issues (including breaking changes), run:
  npm audit fix --force
```

**Comment by rugk** [comment]
I assume when it's merged dependabot will create a PR, so I'll let that be up to the bot then… :upside_down_face:
