### ISSUE TITLE
Could not create paste: Error saving paste. Sorry.

### ISSUE THREAD

**Issue by jude1337** [PrivateBin/PrivateBin#961]
## Steps to reproduce

1. Type text
2. Click save

### What happens
Could not create paste: Error saving paste. Sorry. 

### What should happen
Create paste

## Basic information

**Server address**: https://bin.judas1337.xyz/

**Server OS:** Ubuntu 20.04

**Webserver:** Apache2 2.4.41

**Browser:** Brave v1.41.100

**PrivateBin version:** Latest 1.4.0

I can reproduce this issue on <https://privatebin.net>: No

**Comment by r4sas** [comment]
PHP logs?

**Comment by jude1337** [comment]
php7.4-fpm:
[24-Jul-2022 00:00:01] NOTICE: error log file re-opened

Apache:
[Sat Jul 23 00:00:00.996273 2022] [mpm_prefork:notice] [pid 11811] AH00163: Apache/2.4.41 (Ubuntu) configured -- resuming normal operations
[Sat Jul 23 00:00:00.996295 2022] [core:notice] [pid 11811] AH00094: Command line: '/usr/sbin/apache2'
[Sat Jul 23 00:33:10.966261 2022] [core:error] [pid 306500] [client 185.7.214.104:43788] AH00126: Invalid URI in request POST /cgi-bin/.%2e/.%2e/.%2e/.%2e/bin/sh HTTP/1.1
[Sat Jul 23 13:09:00.327643 2022] [php7:error] [pid 306505] [client 141.101.84.14:13824] script '/var/www/html/xmlrpc.php' not found or unable to stat
[Sat Jul 23 13:56:17.769220 2022] [php7:error] [pid 306505] [client 172.70.93.24:48880] script '/var/www/html/xmlrpc.php' not found or unable to stat
[Sat Jul 23 18:48:22.659684 2022] [php7:error] [pid 312071] [client 185.7.214.104:44392] script '/var/www/html/index.php' not found or unable to stat
[Sun Jul 24 00:00:01.005472 2022] [mpm_prefork:notice] [pid 11811] AH00171: Graceful restart requested, doing restart


Also what permissions should i give the data folder, cant find it on the install link.

**Comment by r4sas** [comment]
Without write permission you can't save paste. What you mean with "public write"?

**Comment by elrido** [comment]
> What permissions do i exactly give it though because if i give it public write isnt that dangerous?

Please have a look at the [FAQ entry "What are the recommended file and folder permissions for Privatebin?"](https://github.com/PrivateBin/PrivateBin/wiki/FAQ#user-content-what-are-the-recommended-file-and-folder-permissions-for-privatebin).

**Comment by r4sas** [comment]
Closing as answered.
