### ISSUE TITLE
Remove URL shortener link once read, deleted or burnt

### ISSUE THREAD

**Issue by ilium007** [PrivateBin/PrivateBin#962]
I have been through the config docs but can't see any reference to this. Will PrivateBin remove a link from the Shrink (or others) database once the PrivateBin message has been deleted or burnt? I can see the DB being filled with irrelevant URL's for content that no longer exists.

**Comment by rugk** [comment]
> Will PrivateBin remove a link from the Shrink (or others) database once the PrivateBin message has been deleted or burnt?

No. Nothing like this is implemented.

As you [can see in the config (guide)](https://github.com/PrivateBin/PrivateBin/wiki/Configuration#urlshortener) only one URL can be configured for creating a short url.
If we would want a delete feature, one would likely have to configure a second delete URL.

As such, feel free to propose a feature request.
However, I would question what you'd archive then. I mean, the pastes are deleted anyway and the URL contains no information at all, so why would you want to delete the short URL? (Feel free to either open a new issue or explain it here.)

**Comment by r4sas** [comment]
1. I think there is no possibility to delete short link because PBin is not saving shortener response.
2. Most of services do not supports deletion without needed rights (like administrator) or requires specific API option (like [delete for YOURLS API](https://github.com/claytondaley/yourls-api-delete)), which again requires ID of shorted link.

**Comment by elrido** [comment]
I think the question has been answered and I therefore close this issue.

**Comment by ilium007** [comment]
In just figured that over time the Shlink database would get full of old links.
