### ISSUE TITLE
Loading forever no nginx access

### ISSUE THREAD

**Issue by TechXero** [PrivateBin/PrivateBin#965]
## Steps to reproduce

1. Load the page

### What happens
Having the loading forever issue due to cloudflare and I have no access to nginx as am on a shared host...

### What should happen
Page should load

## Basic information

**Server address**: https://notes.xerolinux.xyz

**Server OS:** Linux ?

**PrivateBin version:** 1.4.0

I can reproduce this issue on <https://privatebin.net>: No

**Comment by r4sas** [comment]
Please read this FAQ section: https://github.com/PrivateBin/PrivateBin/wiki/FAQ#how-to-make-privatebin-work-when-using-cloudflare-for-ddos-protection

**Comment by TechXero** [comment]
I did requires nginx which I do not have access to !!!!!

**Comment by r4sas** [comment]
In that case please write to your hosting provided support.

**Comment by TechXero** [comment]
I did they said to contact you !!!!!

**Comment by r4sas** [comment]
Can you send a technical support response? And your message to them, if you can.
Please don't forget to remove any confidential data from messages.

**Comment by TechXero** [comment]
That's what they said

```
Hello,

Since you've cpanel hosting. nginx doesn't support on this,

I would suggest to upgrade vps for root level access.. You can see our vps plans here https://www.interserver.net/vps/ . A single slice vps comes with 2G memory, 30G storage, 1TB transfer and the price is $6. We can now offer a free personal directadmin license, on a vps or server. 1 user 10 domains, as an alternative to cPanel.

Unfortunately no way to enable nginx on shared servers. Please contact a developer for further assistance.


Regards,
InterServer, Inc
```

**Comment by r4sas** [comment]
Can you try to change caching option on CF side to 'bypass' for this domain?

**Comment by TechXero** [comment]
Don't think so I looked can't find anything

**Comment by r4sas** [comment]
https://developers.cloudflare.com/cache/best-practices/customize-cache/
I think this is what you need.

**Comment by TechXero** [comment]
can you check if it's working now ?

https://notes.xerolinux.xyz/

**Comment by r4sas** [comment]
Yes, now it works as intended.

**Comment by TechXero** [comment]
Thanks for the heads up finally .. Been battling with it all day..

**Comment by r4sas** [comment]
If it is not hard for you, can you add that information to wiki? This will help others if they run into this problem.

**Comment by TechXero** [comment]
added 
https://github.com/PrivateBin/PrivateBin/wiki

**Comment by r4sas** [comment]
Moved that information to FAQ. Thank. you.
