### ISSUE TITLE
Help with subresource integrity

### ISSUE THREAD

**Issue by jangel97** [PrivateBin/PrivateBin#966]
Hi,

The error is in the latest release 1.4.0.

I am hitting following error `Failed to find a valid digest in the 'integrity' attribute for resource 'https://privatebin/js/privatebin.js?1.4.0' with computed SHA-512 integrity '/F0+9bIbFUC8mKQzrcAjIs2Jg92w1DMcczT2Y/KqHVkFEXH1ZSrqtUX7QjLH6RgVR0YhTxhmWkZ2c8scGCwpkQ=='. The resource has been blocked.`
![image](https://user-images.githubusercontent.com/38217290/185173320-ffbd1217-e163-4ddf-89d4-af99fc015752.png)

The tab is stuck here:
![image](https://user-images.githubusercontent.com/38217290/185173678-df44514d-b54e-4187-b2ce-31bed60c481b.png)

Running this ```fetch('/js/privatebin.js').then(r => r.blob()).then(b => b.arrayBuffer()).then(t => crypto.subtle.digest('SHA-512', t)).then(hab => console.log(btoa(String.fromCharCode(...new Uint8Array(hab)))))``` returns different hash than this one https://github.com/PrivateBin/PrivateBin/blob/master/tpl/page.php#L54

I think I could overwrite hash in this file during my build process or restore the file somehow. What is the recommendation to fix a subresource Integrity issue for JS resources?

This privatebin instance is deployed in a Kubernetes environment, it goes through a reverse proxy.

Thanks!

**Comment by jangel97** [comment]
Providing my own bootstrap in /var/www/html/tpl/bootstrap.php and overriding the hash there, helped me solve the issue. 

Sorry for any annoyance. 

Thanks,

**Comment by rugk** [comment]
For future reference, see https://github.com/PrivateBin/PrivateBin/wiki/FAQ#how-to-make-privatebin-work-when-i-have-changed-some-javascript-files
