### ISSUE TITLE
Access Conf File on Docker Deployment

### ISSUE THREAD

**Issue by vladimirpradilla** [PrivateBin/PrivateBin#978]
I use dockerhub version 1.4.0 and deployed it with Rancher and I need to make a setting in the config file to enable file upload but I couldn't find the path to access the file.

Can you tell me how to get it?

**Comment by elrido** [comment]
Yes, the configuration file in the container image lives in `/srv/cfg`, as can be [seen in the Dockerfile](https://github.com/PrivateBin/docker-nginx-fpm-alpine/blob/master/Dockerfile#L68).
