### ISSUE TITLE
Content Secure Policy is broken, "None of the “sha512” hashes in the integrity attribute match the content of the subresource." error

### ISSUE THREAD

**Issue by nolsen42** [PrivateBin/PrivateBin#98]
Installed the latest PrivateBin on my webserver, and the textbox does not open, Inspect element throws two errors.

``None of the “sha512” hashes in the integrity attribute match the content of the subresource.``
``Content Security Policy: The page’s settings blocked the loading of a resource at self (“script-src https://nolsen.xyz”).``

You can see for yourself at https://nolsen.xyz/PrivateBin

**Comment by rugk** [comment]
It seems you modified the JS files.
In this case you need to regenerate the file hashes. Here is one method how you can do it: https://github.com/PrivateBin/PrivateBin/wiki/Development#subresource-integrity-for-javascript-resources

Otherwise you can do it manually. See https://scotthelme.co.uk/subresource-integrity/ for more information.

BTW this is not CSP, but SRI.

**Comment by nolsen42** [comment]
@rugk Modified? Not sure how they got modified, but I'll try this.

**Comment by nolsen42** [comment]
It might have something to do with cloudflare modifying the files for
optimization, will check soon.

**Comment by rugk** [comment]
Indeed, Cloudflare may cause issues.

**Comment by nolsen42** [comment]
@rugk It was indeed Cloudflare that was causing the problem.

**Comment by rugk** [comment]
BTW as for Cloudflare you should be aware that they are basically [MITM all your traffic](https://scotthelme.co.uk/cloudflares-great-new-features-and-why-i-wont-use-them/). So i hope you have at least set Cloudflare to "Full SSL (Strict)" as Cloudflare has already been used for MITM traffic [e.g. in India](https://medium.com/@karthikb351/airtel-is-sniffing-and-censoring-cloudflares-traffic-in-india-and-they-don-t-even-know-it-90935f7f6d98#.3ie9791kb).
