### ISSUE TITLE
Chat client preview burns Privatebin message

### ISSUE THREAD

**Issue by bberndt** [PrivateBin/PrivateBin#982]
## Steps to reproduce

1.Make a Privatebin message.  Set it to burn / expire after 1 read.  
2. Paste the URL into a chat client that hits the web site as its preview, such as iMessage. 

### What happens
The message is burned/ expired when the user clicks the link. 

### What should happen
The message should still be there for an actual human to hit it once. 

## Additional information
Am I missing a config value?  Or is the even preventable? 

## Basic information

**Server address**: privatebin.edulog.com

**Server OS:** Rocky OS 8

**Webserver:**  Apache

**Browser:**

**PrivateBin version:** 1.4.0

I can reproduce this issue on <https://privatebin.net>: Yes / No
Yes.

**Comment by elrido** [comment]
If you could collect and share the user agent string of that messenger from your apache access logs, we can add it to the bot list:
https://github.com/PrivateBin/PrivateBin/blob/afd84da6b2a35ce779be9a5ebd51d2e2ff0a54cb/js/legacy.js#L55-L65

**Comment by bberndt** [comment]
I tested this again in iMessage, and it seemed to work fine, I think.  I will do some more testing and keep you posted.

**Comment by elrido** [comment]
Please re-open if you can reproduce it and can share a user agent string that we can block.
