### ISSUE TITLE
Cannot decrypt files larger than 10M! A JSON error occurred!

### ISSUE THREAD

**Issue by iemobiu** [PrivateBin/PrivateBin#990]
**Basic Environment:**

Ubuntu20.04, Apache2, php8.0, mysql8

**The php.ini configuration file (/ etc/PHP / 8.0 / apache2 / PHP ini)**

upload_max_filesize = 350M

post_max_size = 350M

memory_limit = 256M

**PrivateBin is configured as follows:**

sizelimit = 31457280

**The problem**

When a file of more than 10 M is uploaded and sent, the following error is displayed when it is opened by copying the link address:

A JSON error occurred: Control character error, possibly incorrectly encoded (3)

PS: Can you suggest a progress bar showing a percentage or speed when uploading attachments and decrypting them? It makes for a friendlier experience.

**Comment by elrido** [comment]
It sounds like it is the response (GET request) that is being mangled, not the upload of the paste (POST request). You can check if the uploaded paste looks complete on disk (and is larger then 10 megs). In PHP there is also the output_buffering limit, which might be restricting the response size and you would have to check if there are any such settings in apache.

**Comment by rugk** [comment]
> PS: Can you suggest a progress bar showing a percentage or speed when uploading attachments and decrypting them? It makes for a friendlier experience.

See https://github.com/PrivateBin/PrivateBin/issues/9

**Comment by iemobiu** [comment]
> 听起来像是被破坏的是响应（GET请求），而不是粘贴的上传（POST请求）。您可以检查上传的粘贴在磁盘上是否完整（并且大于 10 兆）。在 PHP 中还有 output_buffering 限制，这可能会限制响应大小，您必须检查 apache 中是否有任何此类设置。



> output_buffering

Thank you very much. I'll find a time to configure output_buffering and test it. 
BTW：what are the apache Settings for such restrictions?
