### ISSUE TITLE
Add expiration time more than a month for `privatebin.net`

### ISSUE THREAD

**Issue by Benjamin-Loison** [PrivateBin/PrivateBin#991]
The default configuration seems to support `1 year` and `never` expiration times:

https://github.com/PrivateBin/PrivateBin/blob/2e2c70ed15fee78842b104b43ce97e436ac8bcb4/cfg/conf.sample.php#L114-L125

However the _example_ instance https://privatebin.net doesn't support these options:

![Screenshot from 2022-10-14 17-04-38](https://user-images.githubusercontent.com/12752145/195880359-36c5032e-7914-49a2-9f11-fff454b21d8b.png)

In my case `1 month` isn't enough while `1 year` would match my expectations. If the reason is to avoid having too much data on the _example_ instance because the expiration times are too far away, maybe adding some countermeasures such as CAPTCHAs etc would make sense.

What is the _example_ instance stance about expiration time greater than `1 month`?

Maybe I am just not aware that the instance https://privatebin.net shouldn't be used for *production* pastes.

**Comment by elrido** [comment]
Details on why this was disabled can be found in [#594](https://github.com/PrivateBin/PrivateBin/issues/594#issuecomment-595040259). There are [other instances](https://privatebin.info/directory/) that have that option still enabled, if you don't want to run your own instance.
