### ISSUE TITLE
[Request] Return text editor size to the old size

### ISSUE THREAD

**Issue by dausruddin** [PrivateBin/PrivateBin#993]
Hi.

Due to [this commit](https://github.com/PrivateBin/PrivateBin/commit/649c7aaa78c7cbb4a6aefec2038488eadeeb714e), the text box editor in newer versions has 100% width bigger screen.

```
/* address 2K or 4K monitors when using bootstrap 3 */
@media (min-width: 1280px) {
	.container {
		width: 100%;
		padding-left: 4ch;
		padding-right: 4ch;
	}
}
```
Version 1.3
![image](https://user-images.githubusercontent.com/5763466/196156869-ce425940-6964-4188-b501-dd5c5eff60c4.png)

Version 1.4.0
![image](https://user-images.githubusercontent.com/5763466/196157045-4c544415-9bb0-4935-81ee-3f9d684412e9.png)

From my understanding, it apply 100% width when a 720p screen size detected (because 720p has 1280x720p screen size).
But strangely enough the note says 
```
/* address 2K or 4K monitors when using bootstrap 3 */
```

From Googling, I found that 2K screen is 2560x1440 in size. Shouldn't the minimum width set to 1440, and not 1280?

Honestly I think having the editor a bit centered like the old design is better looking. But that is just me. 

Thank you!

**Comment by elrido** [comment]
Resolved for the bootstrap5 template in #1341.
